### ISSUE TITLE
Version 4.0 will no longer support existing extensions...

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1009]
I came across this problem recently because I have started to use the 4.0 API assembly dev build in the TestCentric GUI. Once I switched to the 4.0 API, I was no longer able to load an NUnit project using the project loader extension.

In this case, the problem came down to the fact that the project loader creates a test package using the `TestPackage(string)` constructor, which is no longer available in 4.0. However, there could be other problems I haven't  yet reached and more than just the project loader extension could be affected.

In more general terms:
1. The dev-4.0 branch contains some breaking changes to the API assembly - and to other assemblies as well.
2. Extensions always reference the API assembly and may reference other assemblies as well.

By definition, 4.0 has to contain breaking changes - that's why it's a major release - so keeping it compatible isn't an option. I propose that we simply state that all extensions built against the 4.0 engine will no longer load. Existing extensions will need to be re-issued, at the 4.0 level, if they are to continue being used.

I'm making this a feature request and asking for discussion by the team in case I missed some alternative. If everyone agrees, no code needs to be changed in the engine but the documentation should reflect it and we'll need to do new releases of those extensions we want to continue to support.

**Comment by mikkelbu** [comment]
I agree with documenting this breaking change.

**Comment by CharliePoole** [comment]
I'm taking this as agreed upon at this point.

**Comment by CharliePoole** [comment]
Even though this is basically a decision to not support old extension versions and therefore doesn't require coding, I'm keeping it here so it will make it into the release notes for 4.0 when the time comes.

**Comment by CharliePoole** [comment]
@nunit/engine-team @nunit/team-city-team 

This was decided four years ago, primarily because of lack of objection, or even comment.

However, as I have been working on V4, I have been bothered by the fact that we can't use extensions which implement unchanged interfaces between NUnit 3 and NUnit 4. Working with a single extension, the NUnit V2 ResultWriter, I created a wrapper, which calls the old extension using reflection. Attributes are already recognized by their names, regardless of version or which assembly defines them.

I'm considering re-opening this and making the effort to create wrapppers this for each of our V3 extension points. Now that I've done one, the others ought to be relatively easy.

Reflection isn't a terrible choice in the case of the result writer extension, since there are only two methods called one time per run to create the XML result. That may not be true for other methods, in particular for test event listeners, which end up being called at least twice per test executed, and more if there is text output. Fortunately, JetBrains is converting the TeamCity event listener, so this isn't as big an issue. And users can decide to rewrite any in-house extensions if they see poor performance. Anyway, poor performance may be preferable to not working at all.

Note that we can't use a config file, because the API assembly contains a number of interfaces, many of which have breaking changes.

I'd appreciate your input on this before I go any further. Wrap? Force upgrading (and rewriting)?

**Comment by manfred-brands** [comment]
@CharliePoole Can you keep the V3 version of the interface in a separate compatibility bridging project and use that to call the V3 extensions instead of using reflection?

If you need reflection and as the method signatures are known at compile time, you can speed this up significantly using [CreateDelegate](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-delegate-createdelegate)

As explained by [Nick Chapsas[(https://www.youtube.com/watch?v=er9nD-usM1A).

Note as the engine driver use reflection to call into the framework it also could use created delegates instead of method.Invoke.
But that is not relevant if the methods are only called once for a run as the setup time for create delegate is not cheap.

**Comment by stevenaw** [comment]
I like enabling compatibility and easing upgrades where we can. This seems like a good low hanging fruit for reducing that friction.

@manfred-brands Would a bridging project require an extra dependency we'd need others to explicitly install? Is it something that could also be used for third party extensions? It sounds like it could be a workable solution, I'm just trying to understand the big picture.

On the reflection side I also support `CreateDelegate` where it makes sense in heavily used paths. We've used it selectively in the framework, but one place that comes to mind is the async adapters I think.

**Comment by manfred-brands** [comment]
> Would a bridging project require an extra dependency we'd need others to explicitly install? Is it something that could also be used for third party extensions? It sounds like it could be a workable solution, I'm just trying to understand the big picture.

The bridging project would be part of the console install and it would allow calling existing V3 extensions as if they were V4.
It purely allows calling existing extensions that implement still compatible interfaces.
Note that I don't know if this is feasible, I would have to look at @CharliePoole wrapper he already made.

@CharliePoole Can you push your reflection calling code into a branch so we can see what is actually needed?

**Comment by CharliePoole** [comment]
What I have is mixed in with some other stuff, so I'll extract it before
pushing a branch.

Meanwhile, I'm thinking that a bridging project is an interesting idea.

Charlie

**Comment by CharliePoole** [comment]
See branch port-1634, NUnitV3InterfaceWrappers.cs.

**Comment by CharliePoole** [comment]
I think it's worth doing this for any extensions where we are not changing the extension points they support. So far, there have not been any such changes. I'm removing this breaking change from v4.

I'll create a separate issue for supporting the old extensions. The code I currently have can serve as a model but I don't like the way it is currently used, so more work is needed.

FYI the current implementation requires code changes in each place where an extension is used, i.e. one per extension point. Also, avoiding creating the wrapper on each execution requires a cache, which I have implemented. A better approach will be to wrap the old interfaces at the moment the extension service creates a new `ExtensionNode`. This will give a central place where the old interfaces are wrapped as well as a single cache for the wrapped methods.
