### ISSUE TITLE
method NUnit.Options.OptionSet.Unprocessed always returns "false"

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit-console#101]
method NUnit.Options.OptionSet.Unprocessed always returns "false" and event the "false" is not used

```c#
        private static bool Unprocessed (ICollection<string> extra, Option def, OptionContext c, string argument)
        {
            if (def == null) {
                extra.Add (argument);
                return false;
            }
            c.OptionValues.Add (argument);
            c.Option = def;
            c.Option.Invoke (c);
            return false;
        }
```

**Comment by CharliePoole** [comment]
It seems like some left-over from an older version, but since Options.cs is not our code, I don't think we want to do anything about it. I have a side project to create our own option-handling code based on this, but it's not a high priority for us.
