### ISSUE TITLE
Can't make extension event listener to work.

### ISSUE THREAD

**Issue by dors001** [nunit/nunit-console#1010]
Hello,

I've read the documentation for NUnit3 and tried to implement NUnit.Engine + EventListener extension but i can't make it to work.

**Scenario nunit/nunit#1:**
1) My test project is done with framework 4.7.2 - according to the documentation (if i understood it correctly) i've opened a new project and through Nuget i installed NUnit.Engine + NUnit.Engine.API
2) In the new project i implemented Event Listener Extension
```
using NUnit.Engine.Extensibility;
using System;

namespace NUnit.Engine.Framework472
{
    [Extension(Description = "Event Listener Extension")]
    public class EventListenerWorker : ITestEventListener
    {
        public EventListenerWorker()
        {

        }

        public void OnTestEvent(string report)
        {
            Console.WriteLine($"Test Report Data OnTestEvent: ");
            Console.WriteLine(report);
        }
    }
}


```

* Now i have 2 projects - one for writing tests and one for writing extensions.

3) I've configured the absolute path for the extension project in the .addins file in the NUnit.Engine folder
..\nunit.engine\3.12.0\contentFiles\any\lib\net20\nunit.engine.nuget.addins
My DLL is this **NUnit.Engine.Framework472.dll**

The .addins file now looks like this:
```

../../../NUnit.Extension.*/**/tools/     # nuget v2 layout
../../../../NUnit.Extension.*/**/tools/  # nuget v3 layout
../../../nunit.extension.*/**/tools/     # nuget v2 layout
../../../../nunit.extension.*/**/tools/  # nuget v3 layout
../nunit.extension.nunit3extensions/some version/tools
```
4) I've installed the NUnit.ConsoleRunner in order to manually run the tests.

5) I've set a breakpoint in the EventListener and run the tests.

6) Results:

6.1) When running the test through the Console Runner the application does not break in Even listener even though the tests are running.

![image](https://user-images.githubusercontent.com/36482953/130420359-70e2f460-3d29-4852-b523-a5255445d029.png)

6.2) When running the test through Visual Studio the application does not break at EventListener.OnTestEvent()

**Scenario nunit/nunit#2:**
1) I've tried installing the extensions through Nugets - I've created a nuget of EventListener extension through Microsoft Nuget Manager and tried installing it in the extensions project (Not in the project that i use to write tests).

2) Results > same results as in Scenario nunit/nunit#1.

I've read the documentation a few times and tried redoing the whole process several time.
i don't understand what am i doing wrong.
please advise.

Thank you and have a pleasant week.

**Comment by mikkelbu** [comment]
Hi @dors001

I've transferred this issue to the nunit-console project, as this is the place for extensions. I've not written an extension myself, but I think you need to adjust the *.addin file in the NUnit.ConsoleRunner you installed, so that it references your extension.

**Comment by CharliePoole** [comment]
@dors001 It's best to work with the console runner first. If you once have it working under the console runner, then getting it working under Visual Studio is only a matter of getting the settings right. But if it isn't working at all under the console, then it will never work under Visual Studio.

Normally, an extension only needs to reference the nunit.engine.api assembly. Avoid referencing the engine if possible.

Tests _of the extension_ will frequently need to reference the engine, however.

To help you install your extension, we would need to have a lot more information, especially about where everything is located. Extensions are located relative to the copy of the engine being used, which is normally part of the runner. So, if you install the console runner into your project using NuGet, that's one thing. If you install it globally using Chocolatey or through the msi, that's entirely different. If you can add as much info as possible, we can try to help you.

**Comment by dors001** [comment]
@mikkelbu, @CharliePoole  - Thank you for your response.

I've started from scratch and went with the installation through NuGet, it works now, i manage to get to the extension but i do reference the extension in my test, is it good practice?

```
        [OneTimeSetUp]
        public void InitNunitTestEngine()
        {
            ResultWriter resultWriter = new ResultWriter();
            ITestEngine engine = TestEngineActivator.CreateInstance();
            _workDirectory = engine.WorkDirectory;
            _internalTraceLevel = engine.InternalTraceLevel;
            TestPackage package = new TestPackage("../Tests.dll");
            _runner = engine.GetRunner(package);
            _testResult = _runner.Run(listener: null, TestFilter.Empty);
            resultWriter.WriteResultFile(_testResult, myPath);
        }
```

One more question please, 
Because i'm working with TeamCity i'm bound to use the installation with Chocolatey, in light of this, should i install the NUnit.Engine.Api in my project's assembly? 
Should i install additional packages?

Thank you and have a pleasant day.

**Comment by CharliePoole** [comment]
Once you have tested your extension, I suggest you create a chocolatey package and install it in the same way you install the console runner. The runner will then find it automatically. But while you are developing the runner, that's not possible.

Could you add a bit of info about exactly what you are trying to test? If you are simply writing unit tests of the listener, then you shouldn't need the engine at all, but you will need the api assembly in the project. If you are writing tests of how it it is actually called by the engine (functional tests) then you may need to do something a bit more complex.

**Comment by dors001** [comment]
The goal is to write to a txt file a log of any failed test.
That's why i want to use the EventListener extension to catch the failed tests.

**Comment by CharliePoole** [comment]
But what is the goal of the test? What is it testing? What causes you to create such a complicated OneTimeSetUp? (I assume you have a pretty good reason, but I don't know what it is, so I can't really answer yet.)

**Comment by dors001** [comment]
I want to test integrations with various APIs.
My tests sends parameters that i generate to a mock API, i get an expected response in the form of a json, after that i'm asserting the json.

because i have more than a thousand tests, going through the logs is a hassle and i wish to improve the process to just log failed tests.

**Comment by CharliePoole** [comment]
Sorry, I still don't get it. Why are you actually __running__ tests from inside a test? What is the purpose of the OneTimeSetUp you show? That is, why not just run your tests directly under NUnit3 Console?

**Comment by dors001** [comment]
I'm not running tests from a test...
I have a test project and i run all the tests that i have in this project each merge i do using a pipeline - the pipline build, run tests and eventually merge the branch.
Now i have TeamCity that render logs for me, but TeamCity shows all the logs of all the tests, meaning i see lots of line of logs that i don't use.

**My goal is:**

When i merge a branch and my tests are running one by one, if one of them fail i want to log it and everything else can be ignored.

The Scenario should be as follows:
1) merge process
2) Tests are running
3) Test fails
4) EventListener identifies failed test.
5) Parse the xml result file that is created by nunit.engine.
6) Save the parsed xml on my local machine.

**Explanation on the OneTimeSetup:**
I've used it because i wanted to debug it so i can understand what am i missing, so if i run a test and add those lines to a OneTimeSetup i can debug the process.
I've used this method to debug because i didn't find a better way debug the extension.


I hope that made things a bit clearer.

**Comment by CharliePoole** [comment]
This is the line that made me say "running tests from a test"... since OneTimeSetUp is part of your tests...

```
_runner = engine.GetRunner(package);
```

Yes, debugging _in situ_ is hard and what you are doing is a clever way around it.

The reason that your not breaking in the listener is that it is being created as part of the tests, in a separate process. If you are running a version of NUnit3 Console that supports running in process (--inprocess option) you can try using that. Otherwise, see below.

### My Approach to Extensions

Here's a summary of how I do it...

I have both unit tests and functional tests for my extensions. The functional tests run under nunit3-console with a faked installation of the extension I'm building. The unit tests are completely stand-alone and don't use the console at all.

#### Unit Tests

For those I use NUnitLite. The test is an exe and I can debug directly in it quite easily. For a listener extension, these are very simple... I send events directly to the extension class and examine the results.

#### Functional Tests

I install the ConsoleRunner in my tools directory. (Actually, I sometimes install multiple versions and run tests under all of them)

To execute the tests, I simply use the path to the runner to start a process.

In order for the runner to find the extension, I "install" it in the same place. I do that in a script. My extensions are packages and I am able to simply unzip them into the correct location.

If I get an error in the functional test, which I don't understand, I try to write a unit test to capture the problem. That avoids the need to debug the functional tests themselves.

#### Example

See the tests for the NUnit Project Loader Extension: https://github.com/nunit/nunit-project-loader/

**Comment by CharliePoole** [comment]
Since there has not been any further discussion of this for a few months, I'm closing the issue. However, if you have further  questions, feel free to add them here as we will continue to see them and respond.
