### ISSUE TITLE
upgrading from 3.8 to 3.12: --explore results in System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by soraphis** [nunit/nunit-console#1016]
executing from powershell:
```
ps> & "path_to_nunit_console\\nunit3-console.exe" "--explore=testlist_2.txt" "MySolution.sln"
NUnit Console Runner 3.12.0 (.NET 2.0)
Copyright (c) 2021 Charlie Poole, Rob Prouse
Dienstag, 7. September 2021 15:31:25

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    MySolution.sln

Results (nunit3) saved as testlist_2.txt
```

which results in:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="0" runstate="Runnable" testcasecount="15" result="Failed" label="Error" total="15" passed="0" failed="15" inconclusive="0" skipped="0" asserts="0">
  <test-suite type="Project" id="1" name="MySolution.sln" fullname=".....MySolution.sln" runstate="Runnable" testcasecount="15" result="Failed" label="Error" site="Child" total="15" passed="0" failed="15" inconclusive="0" skipped="0" asserts="0">
    <test-suite type="Assembly" id="167" name="MyProject.Test.dll" fullname=".....MyProject.Test\bin\Debug\MyProject.Test.dll" runstate="NotRunnable" testcasecount="1" result="Failed" label="Error" start-time="2021-09-07 13:31:25Z" end-time="2021-09-07 13:31:25Z" duration="0.001" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
      <failure>
        <message><![CDATA[System.ComponentModel.Win32Exception : The system cannot find the file specified]]></message>
        <stack-trace><![CDATA[--Win32Exception
The system cannot find the file specified
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Services\TestAgency.cs:Line 95.
   bei NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner() in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:Line 272.
   bei NUnit.Engine.Runners.ProcessRunner.Explore(TestFilter filter) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:Line 70.
]]></stack-trace>
...
...
...
```

this repeats for all projects in the solution.
the same command works just fine when using nunit3.8. I've downloaded the zip file for 3.12 and extracted the 'net35' folder.

and the error does not really help me to know whats wrong.

Start of the solution file:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.27130.2024
MinimumVisualStudioVersion = 10.0.40219.1
...
```

assemblies are .net-framework 4.7 and use the old .csproj format (not the sdk format)

nuget packages are updated to 
nunit: version 3.12.0
nunit.ConsoleRunner: version 3.12
nunit3TestAdapter: version 3.16.1

**Comment by CharliePoole** [comment]
The VS Project Loader extension may not work correctly in all cases with the 3.12 console. What happens if you run the assemblies either separately or together from the command-line?

**Comment by soraphis** [comment]
nunit 3.8 and nunit 3.11 find the same TestCases if i Run

    PS> & "nunit3-console.exe" "--explore=testlist_2.txt" ".\MyProject.Test\MyProject.Test.csproj"

but nunit 3.12 shows the same error as above ( System.ComponentModel.Win32Exception : The system cannot find the file specified )

**Comment by CharliePoole** [comment]
Running the csproj file invokes the same VS Project loader extension as running the solution. Try running the assembly itself...

```
PS> & "nunit3-console.exe" "--explore=testlist_2.txt" "PATH TO THE TEST ASSEMBLY"
```

**Comment by soraphis** [comment]
PS> & "nunit3-console.exe" "--explore=testlist_2.txt" ".\MyProject.Test\bin\Debug\MyProject.Test.dll"

results in (basically the same):

```
<test-run id="0" runstate="Runnable" testcasecount="1" result="Failed" label="Error" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
  <test-suite type="Assembly" id="0" name="" fullname="" runstate="NotRunnable" testcasecount="1" result="Failed" label="Error" start-time="2021-09-07 15:50:16Z" end-time="2021-09-07 15:50:16Z" duration="0.001" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
    <failure>
        <message><![CDATA[System.ComponentModel.Win32Exception : The system cannot find the file specified]]></message>
        <stack-trace><![CDATA[--Win32Exception   ... // same error 
```

**Comment by CharliePoole** [comment]
OK... I was asking because I'm responsible for that extension and I thought it might be my bug. So, that was helpful to me but not to you. :-(

To focus on the problem, I'd stick with running a single assembly for the moment. Since you're targeting the .NET Framework, you should be able to run in process. Try adding "--inprocess" to see if you get a better error message. In fact, it would be even better to run it under the debugger, which may show you some internal exceptions, which are not being reported.

Also... I just noticed your message under 3.11 regarding NUnit framework 3.13.2. You can use different versions of the framework, of course, but only if the test assemblies are in different directories.

**Comment by mikkelbu** [comment]
@soraphis You wrote
> the same command works just fine when using nunit3.8. I've downloaded the zip file for 3.12 and extracted the 'net35' folder.

Did you also extract the agents, because the code is failing as it cannot find the agent process. Can you try to extract all the content of the zip file and then see if that works

**Comment by soraphis** [comment]
Thank you very much! 
Sorry for bothering you all :/

**Comment by eyep-incomm** [comment]
@soraphis Hi! did you extract the following folders from the .zip 

- \bin\NET20 
- \bin\NET35
- \bin\NET20\Addins
- \bin\NET35\Addins
- \bin\Agent

To a single folder? Did you also extract all netstandard and netcoreapp folders too? I'm having the same exact issues as you and can't seem to figure it out for the life of me. I have documented them in [1020](https://github.com/nunit/nunit-console/issues/1020)

**Comment by cameracode** [comment]
@soraphis Hi! did you extract the following folders from NUnit.Console-3.120.0.zip

\bin\NET20
\bin\NET35
\bin\NET20\Addins
\bin\NET35\Addins
\bin\Agent
To a single folder? Did you also extract all netstandard and netcoreapp folders too? I'm having the same exact issues as you and can't seem to figure it out for the life of me. I have documented them in [1020](https://github.com/nunit/nunit-console/issues/1020)

**Comment by CharliePoole** [comment]
The console packages are intended to be installed as a unit. You can't just pick certain directories within the package to install, at least not without detailed, low-level knowledge of how NUnit works.

**Comment by cameracode** [comment]
@CharliePoole Thanks for replying. Just so I can understand,if I am using .NET Framework 4.7.2 then if I extract from NUnit.3.12.0.zip 

- \bin\NET35 (all of the dlls and configs to like my own folder)
- \bin\NET35\addins (the whole folder into c:\nunit)
- \bin\agents (the whole folder into c:\nunit)

Then I should be good? I was extracting the contents of those 3 folders into a single one and not maintaining the hierarchy. So I think that's where I messed up.

Then I should be able to invoke like - 
'''
& "c:\SomeFolder\nunit-console.exe" "SomeDLL.dll" 
'''

Correct?
