### ISSUE TITLE
Should we change 'master' to 'main'?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1017]
I think we all understand the reasons. I'm in favor and have changed all the extensions to use main. The process is easiest if there aren't any outstanding pull requests, so we would want to pick the right time to do it.

**Comment by mikkelbu** [comment]
I'm also in favor (even if I haven't done it for the analyzers yet).

**Comment by CharliePoole** [comment]
@ChrisMaddock What do you think?

**Comment by rprouse** [comment]
I am in favor and would like to do this for all our repos.

**Comment by CharliePoole** [comment]
The change from master to main is done on GitHub. I'll finish up this issue with updates to CI.

**Comment by CharliePoole** [comment]
@nunit/engine-team @nunit/core-team @k15tfu 

Assuming you are not making changes in your local master branch, it's probably simplest to delete it and then pull to get the new main.

**Comment by CharliePoole** [comment]
CI appears to work without change! Closing this.
