### ISSUE TITLE
Define Extension Points to be supported in V4.0

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1019]
We have several issues addressing individual extension points but we really need a full list of what will be supported in V4... or at least we need to know which of the existing extension points will be retired and which will continue to be supported. Otherwise, it's not possible to know which ones to work on!

**Comment by CharliePoole** [comment]
I wrote this issue wearing my hat as maintainer of our extensions. Now that I'm getting more involved in V4.0 of the engine, I'm adding my proposal for what I'd like to see...

1. Continue to maintain all the existing extension points, which are...
    * Event Listeners
    * Result Writers
    * Project Loaders
    * Framework Drivers

2. Add extension point for pluggable agents

3. Add others as we see the need

__Note: __ This issue is about Extension _points_, not about which Extensions we deliver...

@nunit/engine-team What do you think?

**Comment by jnm2** [comment]
Sounds good to me.

**Comment by CharliePoole** [comment]
Added a new label for things that are design decisions. I'm thinking of using this primarily for v4.0 planning. The issue will stay in the 4.0 milestone as a reminder until we actually implement it.

In this case, the decision has been discussed and we will maintain existing extension points plus the new pluggable agent extension point.
