### ISSUE TITLE
Installers Cause a SmartScreen warning

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#1021]
1. Download installers from the web
2. Attempt to install
3. A Windows SmartScreen warning pops up preventing you from installing
4. You must click the small `More info` link to get the following screen that allows you to install.

![image](https://cloud.githubusercontent.com/assets/493828/6836469/aae81d6e-d318-11e4-85fb-7bc4def53190.png)

I think that we need to purchase a signing certificate to get around this. Maybe we just document it? I believe it will also be flagged as safe once enough people install it.

There is more information here, http://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application

Other opensource projects have had this problem. Apparently there are signing authorities that will give out certs for opensource projects. See, mono/MonoGame#3189

**Comment by mikkelbu** [comment]
Moving this to the nunit-console projects, as this project is the only one containing an installer.

**Comment by CharliePoole** [comment]
No action here since 2016. (The 2019 comment isn't about the msi at all.) I'm assuming it's no longer relevant and closing.
