### ISSUE TITLE
Nunit handle is not releasing after aborting jenkins job 

### ISSUE THREAD

**Issue by irfanjs** [nunit/nunit-console#1034]
**<< what is the issue >>**

we have jenkins job which builds the unit test cases. Often we have to abort the jenkins job due to some reason, the moment we abort the job, Nunit handle gets locked and then we can not run further tests using Jenkins . 

in the resource manager, we see associated handles to nunit. 

**<< what is expected>>**

we need some better solution on how Nunit can release the lock even after aborting jenkins .  please suggest 

**<< environment >>**
OS : windows 
Jenkins version : 2.222.4
Nunit : 3.5.0

**Comment by mikkelbu** [comment]
@irfanjs Exactly which kinds of handles/locks are being held? Can you provide some more information.

Please note that NUnit 3.5 is 5 years old, so a lot can have happened since this version.

**Comment by irfanjs** [comment]
![image](https://user-images.githubusercontent.com/4394061/141120616-25b1c59a-978e-482c-a8e3-3c3bc69e13e2.png)

@mikkelbu : Please refer above screenshot 

can you tell me how to check exact version of `nunit3-console.exe` and `nunit-agent.exe `

all handles are related to PDB and DLL files . please suggest

**Comment by CharliePoole** [comment]
The version of nunit3-console.exe is displayed when it runs.
The version of the agent started by nunit3-console.exe is the same as the console runner itself.
Do you have output from nunit3-console?

**Comment by irfanjs** [comment]
@CharliePoole : following is the version 

> 14:46:39      [exec] NUnit Console Runner 3.8.0 
> 14:46:39      [exec] Copyright (c) 2018 Charlie Poole, Rob Prouse
> 14:46:39      [exec] Runtime Environment
> 14:46:39      [exec]    OS Version: Microsoft Windows NT 6.3.9600.0
> 14:46:39      [exec]   CLR Version: 4.0.30319.42000

please suggest

**Comment by CharliePoole** [comment]
@irfanjs We need more info as both @mikkelbu and I have requested...

* Console output from your console runner run, up to the point where your error occurs.
* Some info on what is being locked, in case it's not in that output. (The image you posted shows that the agent process is locking something, but it doesn't show what is actually locked. Is it cut off in the image?)

Other desirable info:

* Does this happen with all your runs or just a particular project?
* Does it happen if you run the console runner outside of Jenkins for the same project?

If the full info doesn't show up easily in the console output, then try using `--trace:Debug` on the command-line. There will be several different trace files created. Post anything from the trace related to the failure.

**Comment by mikkelbu** [comment]
Closing this as we have not heard back from the reporter. Please note that we will still get notifications on new comments in this issue.
