### ISSUE TITLE
Type of variable enumerated in 'foreach' is not guaranteed to be castable

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit-console#104]
V3087 Type of variable enumerated in 'foreach' is not guaranteed to be castable to the type of collection's elements. ExtensionServiceTests.cs 141

```c#
foreach (ExtensionNode node in _serviceClass.Extensions)
```
more correct
```c#
foreach (IExtensionNode node in _serviceClass.Extensions)
```

**Comment by CharliePoole** [comment]
Probably goes back to before the interface was introduced. Since we only put ExtensionNodes into the collection, it doesn't cause a problem. Have you verified that the test only uses properties and methods of the interface?

**Comment by constructor-igor** [comment]
I checked compilation: no problems.
So, I don't see other possible problems with the change.

**Comment by rprouse** [comment]
I am for fixing this. I am removing the is:question tag.
