### ISSUE TITLE
Produce dev builds from the dev-4.0 branch

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1042]
@nunit/engine-team. We discussed having some way, as a team, to resolve issues of overall direction for development of the next major release. Here's a relatively small one. :-)

Work towards the 4.0 release is not currently merged into master, but kept in a dev-4.0 branch. The project doesn't publish any builds from that branch, although I published one privately a while back for use by the TestCentric GUI. It would be useful for folks working with the nunit.framework master branch, like members of the framework team and contributors, to be able to use the 4.0 console dev releases to run tests.

I propose we publish merges to dev-4.0 in our myget feed just as we do merges to master. They would be versioned as 4.0.0-devxxxxx. People using the myget feed would need to select the release they wanted unless they were happy with the latest 4.0 dev build, but I think that's how the myget feed is generally used anyway.

I'll leave  this up for discussion for at least 72 hours (probably longer because... Thanksgiving) before doing a PR. :-)

**Comment by CharliePoole** [comment]
@manfred-brands This relates to your recent PR.

**Comment by CharliePoole** [comment]
@rprouse For general, future support of NUnit 4, are there API changes you are making? We'll need to decide if a separate driver factory is needed in the engine or if we can just rename the NUnit3 factory.

**Comment by jnm2** [comment]
Another option could be a new feed for v4, if MyGet provides that capability. But it's already a well-understood problem with release feeds, too, that you might not be able/ready to update to v4 but you need to pull in new v3 patches.

I'm in favor of making the existing feed more useful. If it causes great hardship, packages can also be unlisted and a different approach tried.

**Comment by mikkelbu** [comment]
I'm also in favor.

I think very few people access our MyGet feeds - https://www.myget.org/feed/nunit/package/nuget/NUnit.ConsoleRunner shows 10 downloads - so I cannot see a problem in the user having to specify the release they want.

**Comment by CharliePoole** [comment]
Done... first 4.0 build on myget is 4.0.0-dev05363.

**Comment by CharliePoole** [comment]
This was done for dev-4.0 but is no longer relevant for the actual 4.0 work.
