### ISSUE TITLE
Do we need a new label for "dev" builds?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1043]
In our myget feed or in any combined set of feeds which includes it, "dev" builds sometimes appear alongside "alpha" or "beta" builds. Because "dev" > either of the other two, it appears to be a better selection to nuget and possibly to some users. In fact, depending on when the dev build was created, it may actually be either > or < than the others.

Ways we can fix this...

1. Delete dev builds from myget whenever an alpha or beta is produced. This is what I have been doing. If this is done consistently, then any dev builds present are guaranteed to be later builds than an alpha or beta.

2. Find some other label alphabetically less than "alpha", like "adv" or "adev" or "aaa". My preference would be for something meaningful. Any ideas?

3. Find some other label fors alpha and beta builds alphabetically greater than "dev" and less than "rc".

Note that even if we do 2 or 3, we still need to do 1.

Of course, another option is to ignore the problem, since we have lived with it already for a long time.

Ideas?

**Comment by rprouse** [comment]
Can we automate the first option? It could be a build step for alpha and beta releases.

**Comment by CharliePoole** [comment]
@rprouse Seems feasible. Could be an independent local task run by someone who has the proper authority.

**Comment by CharliePoole** [comment]
Closing this... we no longer have anything except `dev` labels on myget.
