### ISSUE TITLE
Agent for .NET 6.0

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1044]
@nunit/engine-team 

It's certain we will want one eventually. Do we want one for the 3.13 release? 

I think it's easy to add ... pretty much a copy of the 5.0 launcher code. Drawback is everyone who works on the engine needs to have it.

One way to lessen the developer impact would be to include it conditionally and only define the condition in our CI build.

Thoughts?

**Comment by PatrickLeGarrec** [comment]
We use the engine and we are migrating all our tests to .Net 6. 
Need that agent.

**Comment by mikkelbu** [comment]
I don't mind having a .NET 6.0 agent, and I think we already used this conditional approach when we added .NET 5 - see https://github.com/nunit/nunit-console/pull/835.

**Comment by rprouse** [comment]
Installing .NET 6.0 on developer machines is easy these days so I have no issue with it.

**Comment by CharliePoole** [comment]
Great. I'll add and test the agent first, then look at the approach used in the PR, which @mikkelbu referenced. I wasn't aware of that behavior because I have all the SDKs we use installed.

**Comment by CharliePoole** [comment]
Whoops! I misunderstood. PR #835 conditionally runs netcoreapp3.1 tests under .NET 5.0 if it is installed. It doesn't provide a .NET 5.0 agent so it's of no use to someone with .NET 5.0 tests, perhaps because they reference a .NET 5.0 application.

WRT .NET 6.0, we already support it in the sense that you can run .NET Core 3.1 tests under .NET 6.0. But that isn't what was being requested, if I understood correctly.

**Comment by mikkelbu** [comment]
Then it was I who misunderstood the change in #835 (so much for working after midnight)

**Comment by CharliePoole** [comment]
So we don't have a .NET 5.0 agent either. See #858.

I imagine that being able to write and run .NET Core 3.1 tests under 5.0 or 5.6 is sufficient for a majority of users. It may not be a __large__ majority, however. Any thoughts on that @nunit/engine-team ?

Adding a new agent is pretty easy in principle, but it involves a lot of steps. We need to build the agent, test it, package it and test the package. They are all doable steps, however. Unfortunately, I'm currently having a problem building the agent for .NET 6.0, which could just be an issue with my own configuration. Can someone else try that please?

If somebody else runs into the same problem, then I think we might need to leave this out of the release. I don't have any problems adding 5.0, however, so we could do that much. Alternatively, either of them could be postponed to the next release. The cadence of releases is a general issue I want to discuss in the @nunit/engine-team in any case.

**Comment by CharliePoole** [comment]
I'm taking this out of the 3.13 release. See my comment on #858, which applies here as well.

**Comment by mikkelbu** [comment]
I think it is fine to leave the new agents out of the release.
