### ISSUE TITLE
Agent for Net 5.0

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1048]
This is a lack that has been referred to in many issues, most notably #858. I'm creating this as a separate issue in order to spell out clearly that we intend to have a .NET 5.0 agent.

I'm pretty sure that this will require some preliminary steps, which I'll add to this issue as they come up.

**Comment by mikkelbu** [comment]
Shouldn't this be closed as a duplicate of #1044? It makes better sense to have a .NET 6 agent, as .NET 6 is LTS and the support of .NET 5 runs out in May.

**Comment by CharliePoole** [comment]
While it's not duplicate exactly, I agree that there's a slight doubt about needing both 5.0 and 6.0. Let's keep it for now... one reason... I already have code for a 5.0 agent. in the TC agent, so I can just start by copying it.

Biggest reason however, I'd like to have a discussion with the team about what agents we ultimately need, as soon as possible after the the Core Team (hopefully) approves me as the lead. I'm getting a little impatient, of course. :-)
