### ISSUE TITLE
What Runtime Should the netfx Console Runner target?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1058]
The .NET Framework build of the Console Runner, `nunit3-console.exe` has targeted .NET 2.0 for many years. Of course, nowadays, most users probably run it under 4.6.2 or higher.

It seems to me that upgrading it to 4.6.2, 4.7.2 or 4.8 would make sense and would not cause any serious problems for users.

@nunit/core-team What do you think? If make the change, which version is best? I'd target this for the 3.14 release and we could do it pretty quickly if you agree.

**Comment by jnm2** [comment]
Whatever you pick forces the .NET Framework quirking behavior associated with that version of .NET Framework. Here's a huge list of such runtime switches that turn off and on depending on the target framework version of the entry assembly: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/application-compatibility#runtime-changes

This choice of quirk level will only affect user code (in-process tests, addins) which runs in a process that has nunit3-console.exe as the entry assembly.

**Comment by CharliePoole** [comment]
@jnm2 Yes, at least in the short term, till we get rid of in-process execution. I once had code that forced the correct level of quirking behavior depending on what framework the user chose but I don't think that's worth the effort any longer.

**Comment by CharliePoole** [comment]
Another way to look at this... is there any reason __not__ to target 4.8?

**Comment by jnm2** [comment]
The only issue I can think of is if someone wants to run the console runner without installing 4.8. I'm not sure if this is likely to happen or not. All Windows 10 and 11 machines that are running a supported update of Windows come with 4.8 preinstalled. Windows 8 or Windows Server machines may not have it, but they can install it, and I'm not aware of a real reason to avoid installing 4.8 given Microsoft's intense focus on backwards compatibility with it.

**Comment by CharliePoole** [comment]
I still do some work on a Windows 7 VM myself, using VS2017. I have 4.8 on it as well.

That said... another way to go we might consider would be to target 4.0, allowing it to run on any machine with 4.5, 4.6, etc 

I don't see much point in targeting 2.0 for the runner or engine although we can keep supporting it with an agent for running tests.

**Comment by CharliePoole** [comment]
OK... How about this for a plan...

1. Convert to 4.0 for now. We can consider higher releases as needed.
2. Continue to supply a built-in 2.0 agent until we have a 2.0 pluggable agent, then drop the built-in agent.

**Comment by jnm2** [comment]
What benefits come with 4.0? E.g., you can start using `async`/await` at 4.5.

**Comment by CharliePoole** [comment]
There's no benefit to us. The main benefit to users over higher level is that they can run it on their machines. WRT features available in 4.5, etc. I'd say that depends on whether we need them for some new functionality. Do you have some ideas in that direction?

**Comment by jnm2** [comment]
I don't have ideas currently. I'm wondering what motivates moving forward from 2.0. If it has to do with Microsoft support lifecycles, it might be worth noticing that the only version of .NET Framework older than 4.5.2 that is in support is 3.5. In four months, 4.5.2–4.6.1 will also be out of support.

**Comment by CharliePoole** [comment]
At one point, I was wanting to share a net standard engine among the netfx and netcore runners. But since you convinced me we really don't want to have a net standard engine it's slightly moot. :-)

At this point, I'm happy to leave it alone. We don't need extra work! At some future point, we may want to come back to this.

**Comment by CharliePoole** [comment]
As indicated in the discussion, I don't think this is something we want to change in the short to medium term. We can revisit it in the future - assuming we don't stop having a netfx runner entirely.

**Comment by jnm2** [comment]
And it sounds like, if someone wanted to use `Task<T>` framework APIs or tuple syntax, we have no reason identified that would keep us from pushing it to 4.8 at that point when this question is revisited.

**Comment by CharliePoole** [comment]
Yup! And thanks for helping me think this through!
