### ISSUE TITLE
Do we really need Closed Without Action milestone?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1081]
@nunit/engine-team This milestone currently has 258 issues we closed without making any change. Often, they have labels as well, which indicate why they were closed. 

I think this was something we once wanted to track but I no longer see it as useful. I'd like to both stop using it and delete the milestone. 

What do you think?

**Comment by jnm2** [comment]
I have no objections.

**Comment by CharliePoole** [comment]
Moving ahead then

**Comment by mikkelbu** [comment]
I didn't have any free time yesterday, so didn't have time to answer. Personally I like - and use - this milestone to make sure that all closed items are assigned a milestone. We have had a couple of issues in the framework that were solved, but were we forgot the milestone, so.that the resulting release notes didn't mention these issues. Does the release manager tooling solve this?

**Comment by CharliePoole** [comment]
@mikkelbu The tooling relies on the milestone mapping to the release and on each issue you want to show in the notes being given a label. We decide in advance which labels are shown and which are ignored. I'll put up a doc with the specifics of which labels, etc. and I'll try to include your concern in it.

Let me make sure I understand the problem... I think you are saying that somebody could merge a PR to fix an issue, causing the issue to close but then didn't put the issue into a milestone. Is that it?

**Comment by mikkelbu** [comment]
Yes. I think I've added a milestone to closed issue at least a couple of times the last year. I just took a look now and found two more :). But this is not a major issue for me (I just like things to be (very) neat and tidy).
![image](https://user-images.githubusercontent.com/1007631/148660159-89b883dd-30c6-44e9-9de6-d9a017309596.png)

**Comment by CharliePoole** [comment]
I was hoping to make the milestone decision* up front for issues which are code-related. Let's see how it works out and please let me know if you catch anything you feel is missing as we do releases and we can change process if we need to.

(*) A "decision" because we decide when to release a feature and also whether a particular change is big enough or important enough for a milestone. Generally, I think non-code stuff (like the Code of Conduct, ironically)  doesn't really have to be in a milestone. The repo history is there for anyone who wants the lowest level of detail.
