### ISSUE TITLE
Should we create releases locally?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1085]
@nunit/engine-team I'd like your comments on this before doing it!

We now have an automated script that covers doing releases with the process described at https://github.com/nunit/nunit-console/wiki/Creating-a-New-Release. That's actually a pretty standard way to use GitReleaseManager and I even had help from Gary Ewan Park when I first did it for TestCentric. But I think we can improve on it.

A major problem is that it requires a lot of builds. Even if nothing goes wrong and requires a rerun it still takes four complete builds before the release is created. And yet the final build, triggered when you click "Publish", is the one actually used for the release.

The biggest culprit is in the creation of the Draft Release. We end up doing a CI build of the release branch, then a PR build and finally another build after it's merged. However, we don't actually use any of those releases. What gets used to create the Draft Release is the _name_ of the release branch, not it's content. It wasn't always this way. At one time we had to modify things like CHANGES.txt in the release process as well as change version numbers. But no more.

We can already create a draft release on GitHub without doing a build or making any use of the CI servers. This command

    `build --target=CreateDraftRelease --productVersion=x.x.x`

Creates a draft release of the appropriate version on GitHub, based on the milestone of the same name.

This seems like a better approach to me. We can even run this command multiple times, modifying the milestone if necessary, until we are satisfied with the result.

If we did it this way, we would resume the process described on the wiki at step 7, by clicking the Publish Button and everything would proceed from there.

The main "drawback" I can see is that anyone running the command needs to have an environment variable set with a valid GitHub access token. However, everyone should be using access tokens already anyway.

What do you think?

**Comment by CharliePoole** [comment]
I have another small release to do, so I think I'll try it as suggested above and report here.

**Comment by CharliePoole** [comment]
Here's a running log of release 3.13.2...

1. I moved all remaining open issues out of the 3.13.2 milestone.
2. I checked out my local master branch and made sure it was up to date.
3. I tried the command `build --target=CreateDraftRelease --productVersion=3.13.2` and got an error because the existing script only allows you to create a draft release on a release branch. That makes sense when running on AppVeyor but not in the local context where I have specified the version in the command. That can be fixed.
4. I created branch `release-3.13.2` from master and did `build --target=CreateDraftRelease`. The draft was created on GitHub at https://github.com/nunit/nunit-console/releases
5. I edited the draft release and clicked on "Publish Release", which published the release and tagged the master as 3.13.2. The AppVeyor build started automatically and ran to completion, publishing packages to NuGet and Chocolatey, uploading them to GitHub as assets in the release, adding comments to the closed issues and closing the milestone.

Compared to all the steps I took for 3.13.1, this seems like the way to go. The glitch at step 3 needs to be fixed and then no release branch will be needed. If we need to go back to a release, the tag will be there to branch from.

**Comment by mikkelbu** [comment]
One danger of running it locally is forgetting step 2, so the packages will contain something different that we are tagging in the repository.

* Can we make it so that the script will fail if one has local changes ?
* When running `build --target=CreateDraftRelease` locally does the script then create a draft release on the current commit in the local repository or is in on the newest master ?

**Comment by CharliePoole** [comment]
I'll have to check about the possibility of giving an error. It may not make sense. I might have changes, which I don't intend to push before the release.

CreateDraftRelease doesn't look at _either_ the local repo or the newest master. It looks at the milestone and creates a draft release based on the closed issues in the milestone. You can run the command repeatedly. Each time, it updates the  draft based on the state of the milestone.

When you publish the release in the browser, a build is triggered on main, which includes target CreateProductionRelease. Theoretically, that could go wrong in two ways...

1. We reversed a merged feature, so the release would say we had fixed something that wasn't fixed. I'm not worried about that because it's extremely unlikely.
2. We completed a new issue and forgot to rerun CreateDraftRelease. That seems possible, although not highly probable. Maybe we could fix that by calling CreateDraftRelease before CreateProductionRelease, but I would have to think about it a bit.

If I had a slightly bigger team, say 10 people with 3 of them doing releases at different times, I'd be more worried about these things. Currently, we have three people and I'll probably be doing the releases, so I'm being a bit more casual.

However, there is one way we could prevent conflicts entirely: Run both CreateDraftRelease and CreateProductionRelease locally. Then everything would use the latest master downloaded to the local machine. That would be doing releases pretty much as Chris did them but assisted by scripts rather than through the UI.

As it stands, I am slightly more in favor of running CreateDraftRelease locally as often as needed (and by as many people as may need to) and then doing a careful check before clicking the Publish button in the browser. :-)

**Comment by CharliePoole** [comment]
@mikkelbu I missed part of your comment... "So the packages will contain something different..." That part is not possible. When you click publish, GitHub tags your master and a build is triggered of that tag.

**Comment by CharliePoole** [comment]
I'm going with the "local approach" i.e. create the draft release locally and let GitHub trigger the final release.

Further work, inclucing updating the script as well as the instructions on the wiki, will fall under issue  #1057.
