### ISSUE TITLE
2 warnings 

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit-console#109]
Compilation of nunit-console shows 2 warnings.

```
Warning 1   The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'd:\My\MyProjects\@NUnit\nunit-console\src\NUnitEngine\nunit.engine\XmlHelper.cs' D:\My\MyProjects\@NUnit\nunit-console\src\NUnitEngine\nunit.engine\CSC  nunit.engine
Warning 2   The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'd:\My\MyProjects\@NUnit\nunit-console\packages\Mono.Cecil.0.9.6.1\lib\net20\Mono.Cecil.dll'  D:\My\MyProjects\@NUnit\nunit-console\src\NUnitEngine\nunit.engine.tests\CSC    nunit.engine.tests
```

![image](https://cloud.githubusercontent.com/assets/1849690/19589816/2cbf7ea8-9777-11e6-8b0b-2d54e978226e.png)

**Comment by rprouse** [comment]
What version of Visual Studio are you using? Do you have latest from master? I just got latest and did a clean then rebuild and it builds without warnings in VS 2015 Update 3.

**Comment by constructor-igor** [comment]
I use VS2013.
Sources of nunit-console was downloaded from master.

**Comment by rprouse** [comment]
@constructor-igor are you still seeing these warnings? Nobody else is seeing them.

**Comment by mikkelbu** [comment]
Closing this, as we now use VS 2017 to compile the code. The issue can be reopened if the problem also exists in VS 2017.
