### ISSUE TITLE
Symbol package validation failing for NUnit.ConsoleRunner.NetCore

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1096]
"The uploaded symbols package contains pdb(s) for a corresponding dll(s) not found in the nuget package."

**Comment by CharliePoole** [comment]
I examined the packages and I do not find any extra pdb files in the `.snupkg`.

Based on research, this appears to be a spurious error message due to multiple duplicate uploads. The needed confirmation will involve setting up a project with a package reference to NUnit.ConsoleRunner.NetCore and checking that the source __is__ available from the nuget.org source server. If it is, this can be closed.

**Comment by mikkelbu** [comment]
I tried to do this, but one cannot have package references to `NUnit.ConsoleRunner.NetCore`. This gives the warning `Error	NU1212	Invalid project-package combination for NUnit.ConsoleRunner.NetCore 3.14.0. DotnetToolReference project style can only contain references of the DotnetTool type`.

Then I followed https://blog.maartenballiauw.be/post/2020/04/22/referencing-specific-assembly-nuget-package.html and was able via 

```
  <ItemGroup>
    <PackageReference Include="NUnit.ConsoleRunner.NetCore" Version="3.14.0" IncludeAssets="None" ExcludeAssets="All" PrivateAssets="None" GeneratePathProperty="true"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="nunit.engine.core, Version=3.14.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb">
      <HintPath>$(PkgNunit_consolerunner_netcore)\tools\netcoreapp3.1\any\nunit.engine.core.dll</HintPath>
    </Reference>
  </ItemGroup>
```

to get a reference to nunit.engine.core.dll. But looking into the global nuget cache on my machine `......\.nuget\packages\nunit.consolerunner.netcore\` I could not see any pdb files in the folders.

I also tried to create a dummy program that referred to an interface within nunit.engine.core, but I could only access the decompiled source and not the original source code.

```csharp
    public class Class1
    {
        public static void Main(string[] args) {
            ITestRunnerFactory factory;
        }
    }
```

and when I made a test inside the project I was still not able to step into the source. So I'm not sure how to test this.

**Comment by CharliePoole** [comment]
Do you think we should just drop the source package for this package so we stop getting the warning from nuget.org?

**Comment by mikkelbu** [comment]
I haven't seen the warning, but I think it is fine to drop it, given that it is very hard to use the package as a NuGet dependency. So I doubt that anyone are going to miss the symbols.

**Comment by CharliePoole** [comment]
This is due to the fact that the package is created from the same binaries as are used for the NUnit.ConsoleRunner package, resulting in duplicate assembly errors on nuget.org. Removed creation of source package for this package.
