### ISSUE TITLE
insufficient info on driver reflection exception

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#11]
@CharliePoole commented on [Thu May 19 2016](https://github.com/nunit/nunit/issues/1506)

When the nunit3 driver gets an exception in its calls to CreateObject it doesn't show the nested exception that actually caused the problem.

---

@CharliePoole commented on [Tue May 24 2016](https://github.com/nunit/nunit/issues/1506#issuecomment-221247325)

I created this issue based on an nunit-discuss post showing a TargetInvocationException with no info about the inner exception that actually caused the problem. However, I haven't been able to duplicate the problem. Somewhere in the code, I suspect, is a catch that rethrows in a way that loses the information. We just don't know where it is, so I'm marking this as needing confirmation with a specific example that causes the problem.

---

@CharliePoole commented on [Tue May 24 2016](https://github.com/nunit/nunit/issues/1506#issuecomment-221273114)

See #1509 for an example of stack trace with insufficient information.

**Comment by tom-dudley** [comment]
I believe the changes made in https://github.com/nunit/nunit-console/pull/165 will fix this

**Comment by ChrisMaddock** [comment]
Looks like it to me. @CharliePoole - will you confirm you think everything is covered?

**Comment by CharliePoole** [comment]
I agree. Closing this through #165.
