### ISSUE TITLE
Writability check could give a friendlier message.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#110]
@CharliePoole commented on [Fri Oct 16 2015](https://github.com/nunit/nunit/issues/901)

We introduced a writability check for result files, which simply tries to write an abbreviated file to the directory, throwing an exception and aborting the runner if it is unable.

We should see if we can give a better message that explains the directory is not writable.

When the directory used was chosen by default (i.e. the current directory is not writable), we should consider having a backup location instead.

---

@rvignesh89 commented on [Fri Oct 21 2016](https://github.com/nunit/nunit/issues/901#issuecomment-255506467)

@CharliePoole could you give a little more details about this enhancement?

---

@CharliePoole commented on [Fri Oct 21 2016](https://github.com/nunit/nunit/issues/901#issuecomment-255507631)

The console runner calls CheckWritability on each output path specified for saving results, e.g.: TestResult.xml. That method is implemented by various result writer extensions and generally throws some System.IO type of exception. The user has to interpret the exception to figure out what is wrong.

We should catch the exception and make it the inner exception of an NUnitEngineException that has a message saying specifically that the output path specified is not writable. If you want to do it, get that part working and we can consider a backup location after that.

Since this is related to the console runner, it's in the wrong repo. I will move it.

**Comment by octoberclub** [comment]
What is the intention of implementing CheckWritability in each of the implementations? They all seem to do the same - open a StreamWriter to check the file path is writable.

**Comment by CharliePoole** [comment]
The implementation may choose to create an output file at this point, which is later overwritten. That leaves some info behind in the case where the run terminates prematurely. The nunit 3 writer does this.

**Comment by octoberclub** [comment]
Thanks, so I guess it needs to catch SystemException here https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L172 and rethrow a NUnitEngineException with the system exception set as the inner exception ?

**Comment by CharliePoole** [comment]
Yes, I think that will do the job.

**Comment by rvignesh89** [comment]
@CharliePoole I couldn't find any type of tests for ConsoleRunner. Could you lead me to the direction if I've missed it?

**Comment by CharliePoole** [comment]
It's a good point. We have unit tests for various parts of the runner, such as the reports and the command-line options, but we really don't do an overall test. That could be done as a unit test if we used NSubstitute to replace the engine runner. My thinking is that we can do this particular change without an automated test but should come back at some point and add those sorts of overall tests.

**Comment by CharliePoole** [comment]
Closed by #119
