### ISSUE TITLE
Provide better info when AppDomain won't unload

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#111]
We fixed the problem of the agent failing to terminate when this happens but the user is not getting much information to allow debugging the reason the AppDomain failed to close. We should deal with this to the extent possible either in a console message or in the log.

**Comment by octoberclub** [comment]
Not sure if there's any way of detecting or diagnosing why an Appdomain has failed to close - likely it's a native call originating from the test case that has locked some resource?  If anyone has any ideas, I'm happy to add something later.

In the meantime, which of these would be useful additions to the exception messages? 

- The full message from System.CannotUnloadAppDomainException (or other such exception)
- Information on the timeout that occured when attempting to unload. e.g. Unloading Appdomain xxx did not respond in xxx secs
- AppDomain friendly name 
- ApplicationBase
- A list of loaded assembly modules for the Appdomain (Using ReflectionOnlyGetAssemblies)

**Comment by CharliePoole** [comment]
Sorry, I thought I had already added this to our Backlog. Hopefully somebody will pick it up now. Good suggestions @octoberclub - any chance you want to do a PR?

**Comment by octoberclub** [comment]
Yes please. Will do.

**Comment by ChrisMaddock** [comment]
@octoberclub - I've removed you assignment to open this issue up to others - if you're able to come back to it, the contribution would still be welcome! 😄
