### ISSUE TITLE
Reorganize build output (bin) directories

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1118]
Currently we build into a set of bin directories according to the target runtime... net20, netcoreapp3.1, etc. Then we Publish the projects into the _same directories_. This can be very confusing to debug because it's not always obvious whether a problem has arisen in the build step or the publish step.

Since we do now publish all the binaries to BIN_DIR, I'm proposing that we go back to the naive build approach of having a bin directory under each project. We can then continue to publish them to the main bin directory (BIN_DIR) and that published structure does not have to match the existing one. Rather it can be made to look pretty much like the structure we want in our packages allowing further simplification.

@rprouse @mikkelbu @jnm2 
I'd appreciate comments on this idea before I do it.

**Comment by mikkelbu** [comment]
Given the confusion in #1044 I think it is fine to separate them

**Comment by CharliePoole** [comment]
Changes in the 3.15.0 release have simplified the publishing step substantially. I'm moving this to 4.0 for further investigation.
