### ISSUE TITLE
Add a package test that uses nunit framework 4.0

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1139]
That way we'll know when and if the api changes!

**Comment by manfred-brands** [comment]
I don't mind trying. I have to make myself familiar with your tests first.

**Comment by CharliePoole** [comment]
OK, you've got it... here's an outline of where I think you would need to start.

1. Create a target Assembly. I suggest copying the mock-assembly project, making some name adjustment and using the latest NUnit 4 as the framework.
2. Create some new tests. The tests are defined in package-tests.cake. We should have at least one targeting .net fx and one core or more... up to whatever targets nunit4 supports.
3. There are lists of tests in package-definitiions.cake. You'll want to add them to the standard runner tests and the net core ones to the netcore tests as well.
4. Run them using `build -t Package` or `./build.sh -t Package` on linux.

Hope that helps.
