### ISSUE TITLE
nunit3-console.exe does not have a manifest

### ISSUE THREAD

**Issue by johannes-schmitt** [nunit/nunit-console#1166]
### Steps to reproduce:
1. Download the NUnit Console Runner executable (e.g. Download NuGet package and extract it)
2. Open a Visual Studio Developer Command Prompt
3. Extract the app manifest by running the following command: `mt.exe -inputresource:"C:\path\to\nunit3-console.exe";#1 -out:;#1 -out:"C:\path\to\extracted.manifest"`
4. Inspect the extracted manifest

Expected: manifest is identical to https://github.com/nunit/nunit-console/blob/main/src/NUnitConsole/nunit-console/app.manifest
Actual: manifest is a default manifest

### Implications: 
* test code that uses `Environment.OSVersion.Version` (and friends) is not working as expected
* message on application start is misleading:
```
NUnit Console 3.15.0 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Montag, 28. Februar 2022 15:13:16

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0 ********** this is printed when running on Windows 10
   Runtime: .NET Framework CLR v4.0.30319.42000
```

**Comment by CharliePoole** [comment]
Can you please indicate which package you used? (I assume it's NUnit.ConsoleRunner... but what version?)

**Comment by CharliePoole** [comment]
Your PR will, of course, only fix the 4.0 release when it comes, which won't be for months. How critical do you feel this error is?

**Comment by CharliePoole** [comment]
@johannes-schmitt Is there some reason you don't run your nunitv2 tests under nunit3-console?

**Comment by johannes-schmitt** [comment]
> How critical do you feel this error is?
It's nothing critical and I think getting this into the 4.0 release is fine. I guess we should reevaluate in case this bug gets more traction.
