### ISSUE TITLE
Trouble upgrading from 3.8 > 3.15  'The system cannot find the file specified'

### ISSUE THREAD

**Issue by peepomint** [nunit/nunit-console#1188]
Good afternoon y'all. 

I've recently been tasked with updating a large projects CI setup, which includes a gitlab-runner which includes the nunit3-console application and a test agent.  It should be noted I have inherited this situation; so I am trying to provide as much detail as possible but if I'm a little short please just ask and I will provide additional detail.

I am almost certain that this is an issue with what I'm doing, as opposed to nUnit, as such, I'd very much like to know if there is any documentation surrounding the requirements for nunit3-console, I am a little confused as to _exactly_ which components I require?

For a .net 4.7.2 project
Do I need the console runner AND agent binaries? 
Where does nunit3-console look for the agent binaries? 
Are there any logs I can look at surrounding the error below?

I noticed that the zip for the console runner contains many different console binaries split across many versions of .net AND agents also spread across many .net versions. 

If there is any documentation surrounding any of the above I'd be extremely interested in reading it, but I've not _yet_ found anything. 

Running : 

`c:\path\to\nunit3-console.exe <testassembly>.dll`

Returns 'The system cannot find the file specified', full output: 

```
NUnit Console 3.15.0 (Release)
 Copyright (c) 2022 Charlie Poole, Rob Prouse
 Tuesday, June 21, 2022 1:23:15 PM
 Runtime Environment
    OS Version: Microsoft Windows NT 6.2.9200.0
    Runtime: .NET Framework CLR v4.0.30319.42000
 Test Files
     <testassembly>.dll
 Errors, Failures and Warnings
 1) Error : 
 System.ComponentModel.Win32Exception : The system cannot find the file specified
 --Win32Exception
 The system cannot find the file specified
    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
    at NUnit.Engine.Services.TestAgency.GetAgent(TestPackage package) in C:\projects\nunit-console\src\NUnitEngine\nunit.engine\Services\TestAgency.cs:line 76
    at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunnerIfNeeded() in C:\projects\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 250
    at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\projects\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 138
 Test Run Summary
   Overall result: Failed
   Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
   Start time: 2022-06-21 03:23:16Z
     End time: 2022-06-21 03:23:16Z
     Duration: 0.050 seconds
 Results (nunit3) saved as TestResult.xml
```

I have tried the following : 
`nunit3-console.exe <testassembly>.dll  --inprocess `
Which results in the tests running correctly. 

Any help _greatly_ appreciated, thanks :)

**Comment by kasperSiteimprove** [comment]
I've seen this exact error because I didn't specify the correct runtime framework string. When I upgraded to 3.15 my scripts used `--framework=v4.0`. That needed to be `--framework=net-4.0` for my .net 4.5 project. Hope it provides a clue :)

**Comment by peepomint** [comment]
Turns out whoever built the original runner image was just doing a copy of the binaries, I've moved to using the installer and this has resolved, thank you everyone for your input :)
