### ISSUE TITLE
.NETStandard test assemblies are not supported by this version of the engine

### ISSUE THREAD

**Issue by rcocks-hl** [nunit/nunit-console#1195]
Hi,

I'm having an issue where trying to running nunit3-console is failing with the error `.NETStandard test assemblies are not supported by this version of the engine`.

    command "".\..\NuGet.packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" --skipnontestassemblies --noresult  --config=Debug --where "cat == Unit" "<solution>.sln""

However the tests themselves are all framework, and the .net standard assembly it complains about isn't a test assembly, but merely referenced from the (.net Framework) test assembly.

It is my understanding that .net framework should be able to reference .net standard, and I expected nunit3-console to support tests which are written in framework test project referencing a .net standard assembly.

The unit tests run fine from visual studio and it is only the console runner that is having an issue.

**Comment by CharliePoole** [comment]
Does your .NET Standard assembly reference the NUnit framework? NUnit's definition of a "test assembly" is any assembly, which references the framework. If such an assembly is under your control, you can make it into a non-test assembly by use of the `NonTestAssembly` attribute.

**Comment by CharliePoole** [comment]
I notice you are using 3.10, which is quite old. Can you use a newer version? Preferably 3.15.0?

**Comment by CharliePoole** [comment]
OK. I'll look at the code. It may be that the check is in the wrong place, since __every__ assembly has to be examined in order to determine if it's a test assembly. Meanwhile, I suggest defining and adding your own attribute with the full name `NUnit.Framework.NonTestAssemblyAttribute` and applying it. The runner checks for the attribute by name. :-) Of course, this won't work if the check is made before the attribute is looked for. :-(

**Comment by CharliePoole** [comment]
@rcocks-hl If you are building from current source, rather than the 3.15 source, then the project loader extension won't work. It has not yet been updated to use the 4.0 interface. If you're using the 3.15 source, it ought to work.

**Comment by CharliePoole** [comment]
@rcocks-hl It sounds as if this is still an issue in  3.15.2 then. I'll try to confirm it with an example.

Meanwhile, if you want to run using the solution file, I suggest using the workaround of defining your own NonTestAssembly attribute in the assembly, which is causing a problem.

**Comment by CharliePoole** [comment]
@rcocks-hl Seems that I lost track of this issue but fixed another one, which describes the same problem, #1182. It's in the 3.16 release, which just came out a few hours ago. Give that a try and let me know if it works and if so I'll close this one as well.
