### ISSUE TITLE
Upgrade Cake build to latest version

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#12]
@CharliePoole commented on [Thu Jun 23 2016](https://github.com/nunit/nunit/issues/1609)

Currently seems to be 0.13

---

@ChrisMaddock commented on [Thu Jun 23 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-228115200)

When this get's done, it might be nice to also make use of cake-build/cake#908. :-)

---

@CharliePoole commented on [Thu Jun 23 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-228143600)

@ChrisMaddock I agree!

---

@ChrisMaddock commented on [Fri Jun 24 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-228314373)
#1615 should probably be investigated before this. :-)

---

@ChrisMaddock commented on [Tue Jul 26 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-235201399)

It's probably worth now waiting for Cake v15, which is coming soon. It will have required fixes for  cake-build/cake#908, and also full error messages from the NUnit3 tool, which might make it a preferable alternative. 

This might even be better done with a bit of a refresh, post-split.

---

@CharliePoole commented on [Tue Jul 26 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-235287528)

Seems fair. BTW, I'm using Cake 0.14 for the teamcity extension and having some issues with mono 3.2.8. So we'll need to see if that gets fixed.

---

@ChrisMaddock commented on [Tue Jul 26 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-235290230)

Good to know.

Reopening this issue as I presume closing it was accidental?

---

@CharliePoole commented on [Tue Jul 26 2016](https://github.com/nunit/nunit/issues/1609#issuecomment-235307985)

Yes... I keep doing that! Button should say Close Issue!

Fix for my problem is supposed to come in Cake 0.15 in a few days.

**Comment by mikkelbu** [comment]
The current version of Cake in this repository is 0.19.1. Should we close this issue or change the issue into make use of cake-build/cake#908? As far as I can tell we will need to something like the following (and run the tests using `appveyor.yml`).

```
if(BuildSystem.IsRunningOnAppVeyor)
{
    // Upload artifact to AppVeyor.
    BuildSystem.AppVeyor.UploadTestResults("./tests.xml", AppVeyorTestResultsType.XUnit);
}
```

**Comment by CharliePoole** [comment]
This is an old issue, written when we were using 0.6.4 and should have been closed long ago. Re-directing an issue to be about something entirely different doesn't seem like a good idea to me.

**Comment by ChrisMaddock** [comment]
@mikkelbu - if you fancied doing a PR on its own for the UploadTestResults however, I think that would be nice to have. :-) 

You'll have to look at how the results come out of the .NET Standard version of the engine - I think this issue pre-dates that. I started adding UploadTestResults to the framework CI a long time ago - but stopped as not all frameworks produced a results XML file, and I decided it was better to have no results uploaded than 'some but not all' results - that felt like it could be misleading.

**Comment by CharliePoole** [comment]
I agree. It's enough of a no-brainer that a PR without an issue is probably sufficient, so long as we give it the usual issue-style labels and it explains what it is doing - we need that for the release notes.

@ChrisMaddock What do you mean by not all frameworks producing a result file? Strictly speaking __no__ framework build produces a result file - it sends the results to the runner, which produces the file.

**Comment by ChrisMaddock** [comment]
'framework test assemblies' sorry.

Did the old PCL build of NUnitLite not create a results file, or am I mis-remembering? It was a while ago.

**Comment by CharliePoole** [comment]
Ah yes, NUnitLite is the runner of course. In our PCL you couldn't write files, so we didn't. 😄
