### ISSUE TITLE
Explicit test isn't run when condition is --where "cat=XXXX"

### ISSUE THREAD

**Issue by meanthadar-p** [nunit/nunit-console#1201]
NUnit Console: 3.15.2

Hi, as I try follow nunit docs https://docs.nunit.org/articles/nunit/writing-tests/attributes/explicit.html
I run below command and expected to include **[Explicit]** tests with cat = XXXX

`> nunit3-console SeleniumTests.dll --noheader --where "cat==XXXX" --workers 6 --result TestResults.xml`

but for actual, the test summary is showing that they're skipped all explicit test
```
Test Run Summary
  Overall result: Passed
  Test Count: 37, Passed: 32, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 5
    Failed Tests - Failures: 0, Errors: 0, Invalid: 0
    Skipped Tests - Ignored: 0, Explicit: 5, Other: 0
```

Could you please help advise how I can run tests include [Explicit] tests???

**Comment by CharliePoole** [comment]
@meanthadar-p Could you add some code showing the header of the test with the category applied to it? Also, the actual category name may be important and make sure your casing is correct.

**Comment by CharliePoole** [comment]
I'm closing this as not reproducible without more info. We can reopen it if @meanthadar-p provides some details.
