### ISSUE TITLE
Logging output no longer captured

### ISSUE THREAD

**Issue by msscribner** [nunit/nunit-console#1211]
The XML file specified by the --result argument of the Console Command Line no longer appears to capture data using the TestContext.Progress.WriteLine() API.

Data is still posted to the Console Window... but not to the Log file.

I'm expecting to see something along the lines of:

              <test-case id="0-2899" name="Case_Management_Hide_Pencil_Icon_For_Case_Offenses_483323(Chrome)" fullname="AutomationTests.TestSuite.CaseManagement.CaseManagementTests.Case_Management_Hide_Pencil_Icon_For_Case_Offenses_483323(Chrome)" methodname="Case_Management_Hide_Pencil_Icon_For_Case_Offenses_483323" classname="AutomationTests.TestSuite.CaseManagement.CaseManagementTests" runstate="Runnable" seed="915489632" result="Passed" start-time="2022-01-09 06:47:52Z" end-time="2022-01-09 06:58:14Z" duration="622.047676" asserts="12">
                <properties />
                **<output><![CDATA[OpenQueueItemByNumberOnTab() Report-Case Number:[2019-000002]
]]></output>**
              </test-case>

But the **<output>** tag is not getting posted to the file.

**Example of Command Line being used:**
"C:\CTS\AutomationTests.dll" --where "method == Demo_01" --labels=After --workers=2 --work="C:\temp\P1" --result="AutomationTestResults_P1.XML" --dispose-runners --trace=Verbose

**Source Code example call:**
    var message = "OpenQueueItemByNumberOnTab() Report-Case Number:[2019-000002]";
    TestContext.Progress.WriteLine($"{DateTime.Now} - {message}");

**Nunit Versions:**
Nunit: 3.12.0
Nunit.Console 3.10.0
Nunit.ConsoleRunner 3.10.0
Nunit.Engine 3.11.1
NUnit.Engine.Api 3.10.0
Nunit.Extension.UUnitProjectLoader 3.6.0
Nunit3TestAdapter 3.15.1

**Comment by CharliePoole** [comment]
The purpose of `TestContext.Progress` is to provide a way to bypass the capture of output, allowing you to display messages on the console, as described in the <a href="https://docs.nunit.org/articles/nunit/writing-tests/TestContext.html">documentation</a>.
