### ISSUE TITLE
Nunit Agent does not terminate properly after Environment.FailFast is invoked

### ISSUE THREAD

**Issue by gbiellem** [nunit/nunit-console#122]
We've been struggling with NUnit ConsoleRunner 3.4.1 terminating with a return code of -100 on our TeamCity Build Agents (TC 10.0.2) .  After this happens the test assembly files remain locked which prevents a new build of that project from being kicked off on that machine
Looking at the running processes we discovered that nunit-agent is still present in the process list even after the build was complete with the -100 failure. Killing that process fixes the issue.

When this happens there is a corresponding entry in the eventlog with a stack trace showing 
that nunit-agent terminated after a call to Environment.FailFast was made by one of the frameworks our code uses.

**Comment by CharliePoole** [comment]
The problem with hanging agent processes is fixed in the 3.5 release. However, that release has a critical error and will be superseded by 3.5.1 tomorrow, so you should probably wait or that to upgrade.

If that doesn't solve your problem, we can reopen this.

**Comment by gbiellem** [comment]
@CharliePoole Re  the above you mentioned an imminent release of 3.5.1.  - I saw the NUnit 3.5.1 Test Adapter was released.  Is that what you meant?

**Comment by CharliePoole** [comment]
It's been a busy week! Yes, I meant that there was an adapter release coming out, which made no sense in the context of this issue. Please try the 3.5 console release and let me know if it solves your problem.

**Comment by gbiellem** [comment]
Thanks @CharliePoole - Will do

**Comment by gbiellem** [comment]
Hi @CharliePoole - I can report we are seeing the same behavior after the updating 3.5 of the console release.
