### ISSUE TITLE
Change name of NUnit Net Core Runner executable

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1224]
@rprouse @mikkelbu @jnm2 @nunit/engine-team @nunit/framework-team

Strictly speaking, this would be a breaking change and should not be done in 3.16.

However, I have had so much confusion in issues between people using the two different runners, with entirely different feature sets, both called `nunit3-console.exe`. That it's tempting to do it without waiting for 4.0. I'm thinking of calling it `nunit-netcore-console.exe`.

This would break interactive usage as well as use of the runner in scripts... i.e. `.\net6.0\nunit3-console.exe` would need changing.

Since I'm proposing this primarily for my own convenience in handling bug reports, I'll accept the result of a vote. :-)

**Comment by rprouse** [comment]
I don't have a strong opinion on this. Do you know of any tools like Cake that would need to be updated to work with the new name?

**Comment by CharliePoole** [comment]
@rprouse Only that the scripts will need to be updated. I think most links get forwarded but I'll do more research.

**Comment by mikkelbu** [comment]
@CharliePoole I think the name is fine, and I think it makes sense to change the name even if it is a breaking change. If it is mentioned explicitly in the release notes, then I think people can adapt to it.

**Comment by CharliePoole** [comment]
@mikkelbu @rprouse In that case, I think I'll go ahead and do it.

@rprouse Thinking more about your question, I realized that the cake extensions similar to the one you maintain would need to be updated, but only if they use the .NET Core runner. I don't know of any that do that. Also, we can keep the dotnet CLI command the same.
