### ISSUE TITLE
Test names not printed to stdout except when test writes to stderr

### ISSUE THREAD

**Issue by realityexists** [nunit/nunit-console#123]
nunit3-console.exe 3.5.0 doesn't seem to show any progress at all when I run it on one assembly containing many NUnit 3.5.0 tests, unless the tests print something. I'd expect it to at least print out the names of the tests it's running to stdout, but it only seems to do that for tests that write something to stderr (via NLog), which seems weird. Other tests are not written to stdout at all. (I know they're running, though, because I have NLog configured to also log to a file.)

The command line I'm using is simply `nunit3-console.exe --noresult --shadowcopy path\to\MyTests.dll` I've tried removing the `--noresult` and even adding `--verbose`, but that didn't make any difference.

This is related to #25, but much simpler (and I'm pretty sure it used to print out the names of the tests before).

**Comment by CharliePoole** [comment]
There are various options for printing test names, controlled by `--labels`. The default setting is `--labels:On`, which does exactly what you describe. If you want to see the names of all tests, specify `--labels:All`.

**Comment by realityexists** [comment]
Oh, thanks! Sorry, don't know how I missed that.
