### ISSUE TITLE
Reduce build targets for nunit.engine.core assembly

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1246]
@rprouse @mikkelbu @jnm2 I'd particularly like your thoughts on this one including on the timing (i.e. 3.16 vs 4.0).

It seems as if the .Net 5.0 and 6.0 builds of nunit.engine.core are not needed. If we remove them, .Net Core 3.1 will be used and that seems sufficient. Eliminating those builds would simplify the project a bit. 

I anticipated this idea when I created the .Net 7.0 agent - it doesn't have its own engine core build, but uses the 6.0 version.

I'd appreciate hearing about anything I'm missing in thinking about this! Do you think it's suitable for 3.16 or should it wait for 4.0, whenever that comes?

**Comment by jnm2** [comment]
I agree. 3.16 sounds good.

**Comment by rprouse** [comment]
I also agree that reducing the build targets makes sense and I don't see it as a breaking change so 3.16 is fine.
