### ISSUE TITLE
Install dotnet tool failed

### ISSUE THREAD

**Issue by genusP** [nunit/nunit-console#1271]
I installing latest version (3.16.0) and get error
`The settings file in the tool's NuGet package is invalid: 
Entry point file 'nunit3-console.dll' for command nunit was not found in the package. Tool 'nunit.consolerunner.netcore' failed to install. Contact the tool author for assistance.`
File DotnetToolSettings.xml contains invalid definition EntryPoint!

**Comment by ma-hag** [comment]
> I installing latest version (3.16.0) and get error `The settings file in the tool's NuGet package is invalid: Entry point file 'nunit3-console.dll' for command nunit was not found in the package. Tool 'nunit.consolerunner.netcore' failed to install. Contact the tool author for assistance.` File DotnetToolSettings.xml contains invalid definition EntryPoint!

Same problem.

**Comment by CharliePoole** [comment]
How embarassing! This unfortunately demonstrates that none of our acceptance tests actually run the package via the dotnet command! I'll add that as well as fixing the XML file.

Version 3.16.1 is already planned to come out before the end of the month. There will be a dev build on myget containing this fix by the end of today.

**Comment by CharliePoole** [comment]
A fix is availble from our myget feed as version 3.16.1-dev00002. See https://www.myget.org/feed/nunit/package/nuget/NUnit.ConsoleRunner.NetCore/3.16.1-dev00002

Please confirm if this works for you and I'll keep it in the 3.16.1 release.

**Comment by genusP** [comment]
Installer success

**Comment by CharliePoole** [comment]
Great... I'll keep this open until I add a regression test.

**Comment by worldofprasanna** [comment]
Thanks this fix worked for us.
