### ISSUE TITLE
When running under teamcity, agent processes are sometimes left running after nunit-console has exited

### ISSUE THREAD

**Issue by davidjward30** [nunit/nunit-console#128]
We are finding that nunit agent processes are sometimes left running forever after a CI build has completed. This is serious issue for a CI server as once an agent is in such a state, build after build can fail and manual intervention is required to recover. 

When logging into the build machine, I typically observe several agent processes consuming 0 CPU and they appear to have unloaded all tests assemblies, leaving the directory and nunit assemblies locked. In this state, the CI system is then blocked from cleaning up the working directory.

This seemed to start happening in nunit 3.4 and is still an issue with nunit 3.5.0

Our initial investigation suggests that the user-invoked cancellation of CI builds might be the source of the issue.  Cancellation will appear to be successful and the error will typically manifest later when the agent picks up another build.

**Comment by davidjward30** [comment]
Hello,

Are there any plans to address this? It causes frequent false-alarm test failures that are only resolves by killing old agent processes.

Regards,

David.

**Comment by CharliePoole** [comment]
@davidjward30 I'm afraid there has been a lot going on and nobody picked this one up. I've marked it confirm so that somebody can try to reproduce it, ideally without TC being involved, because that will allow others who don't use TC (actually, almost all of us) to work on it.

**Comment by davidjward30** [comment]
If it helps I can contact TC support and ask how it cancels a build. I suspect it simply kills the main process.

**Comment by CharliePoole** [comment]
It's easy enough to simulate that. 😄 

Mainly, this is not being worked on because I triaged it and marked it confirm. Nobody has confirmed it yet. We rely on "pull" rather than "push" to get people working on things. 😉 

@nunit/engine-team Doesn't anybody want to give this a shot?

@davidjward30 I imagine somebody will grab this and run with it once the release is out next week.

**Comment by chris-smith-zocdoc** [comment]
In our environment we've worked around this issue by killing any orphaned processes both before and after nunit steps. We set the execution behavior to `Always, even if build stop command was issued` which ensures it always runs. 

```
Stop-Process -processname nunit* -Force
```

I don't have time to look into the actual bug on the NUnit side right now though.

**Comment by davidjward30** [comment]
@chris-smith-zocdoc.  Thanks for the suggestion, but we have powerful rack servers with multiple build agents running on the same OS so this approach would disrupt other agents.

**Comment by CharliePoole** [comment]
@davidjward30 What OS are you using, by the way.

**Comment by davidjward30** [comment]
@CharliePoole - our build agents are all MS Windows - mostly Windows Server 2012 R2 x64 and some Windows 7 x64. The problem seems to occur on both.

**Comment by davidjward30** [comment]
Just writing to confirm that I can easily reproduce this outside of teamcity on Windows 7 x64. Steps

1. Run nunit-console3.exe with 2 assemblies
2. Kill nunit-console3.exe with task manager while both are running.
3. Observe both agent process continue to run but when they complete, the processes stay loaded.

**Comment by CharliePoole** [comment]
OK... I'm convinced. :smile: 

Techically, the processes never complete - they are waiting for the main process to send them another command, which never comes. One possibility is to pass an argument that causes them to exit when complete. The console runner would use that argument while the gui would not.

**Comment by jnm2** [comment]
There isn't a way to connect the lifetime of the dependent processes to the main process is there? That would be awesome because canceling a build would have immediate effect on all processes.

**Comment by rprouse** [comment]
>There isn't a way to connect the lifetime of the dependent processes to the main process is there? That would be awesome because canceling a build would have immediate effect on all processes.

There is a SO answer on how to do that here, http://stackoverflow.com/questions/3342941/kill-child-process-when-parent-process-is-killed

**Comment by jnm2** [comment]
@rprouse that seems ideal!

**Comment by CharliePoole** [comment]
Unfortunately, Job Objects is a solution for users, not for us, because it's based on Windows-specific technology. :-(

We could easily keep track of all the processes we start and ensure we get rid of them on normal termination. In fact, we already do that indirectly by unloading the assemblies. The problem is that there's no general way I'm aware of to get control when the process is being killed.

So that leaves us with the agents monitoring the server (the TestAgency service in the main program) and terminating if it goes away. I think we should do that.

But I think most cases will be eliminated if the console just passes a setting in the package that tells the agent to terminate after running instead of waiting around.

**Comment by jnm2** [comment]
If there is a platform-specific solution for each platform, couldn't we still use it?

The only downside to the terminate-after-running setting is that there is no way to cancel running tests.

**Comment by CharliePoole** [comment]
We could but we've worked hard over the years to avoid that. Once you have different code paths per platform the less used platform is exercised less. Since this is easy to fix without doing that, it seems like a no-brainer.

**Comment by CharliePoole** [comment]
That's two separate solutions for two separate problems.

1. Tests are running. Cancel the console process. Agents notice that the process is gone and terminate. That should be easy since the agents are constantly sending feedback to the console process.

2. Tests already finished. In that case the agent could exit immediately based on the setting passed to it.k We need the setting because the agent doesn't know for whom it is doing work - it could be the gui, which definitely doesn't want it to exit.

**Comment by CharliePoole** [comment]
I reviewed the code and it looks fixable, but unfortunately not the night before we do a release. 😢

**Comment by davidjward30** [comment]
@jnm2 The way we've handled a similar situation in our software is to have the parent process create a uniquely named mutex in the locked state. The child process waits on this mutex in addition to whatever it's waiting on (WaitHandle.WaitAny). If the parent process exits the child process will get an AbandonedMutexException and can exit immediately.  The alternative (and possibly less portable?) method is to pass the parent's PID and have the child wait on that in addition. The code is pretty trivial but I have sample code for the mutex method if you're interested.

**Comment by jnm2** [comment]
Only problem is with PID is PID reuse race condition, but Mutex is a cool idea.

**Comment by CharliePoole** [comment]
Mutex is a good solution for the general case where the child process may not have any further communication with the parent. In this case, the child / parent pair have a client / server relationship, so I think using a Ping() method is the more obvious solution. Agent, in fact, already has a thread that sits waiting on an event before terminating. It could easily do that in a loop with periodic checks that the server still exists and is communicating.

I am somewhat curious as to why cancelling the main process does not lead to a remoting exception in the running agent. I've verified that it doesn't so we must be eating the exception somewhere.

**Comment by tinuroth** [comment]
Maybe, I should not comment on that closed issue, but I am pretty sure this is not yet (fully) solved. Maybe, the use case of canceling the build has been addressed, i.e. to terminate nunit runner agents when the main process gets terminated.

However, we see a lot of nunit runner zombies hang around after builds have properly finished (nunit console 3.9.0). I am 100% sure to see this on Windows 7. On Windows 10 it does not seem to happen. So, we are about to upgrade all our build agents to Windows 10 or resort to a final build step ```Stop-Process -processname nunit* -Force```, as suggested far up in the thread.

**Comment by mikkelbu** [comment]
Hi @tinuroth 
I assume that this is also on TeamCity?
Is it only the agents that are left running?
Can you see where the processes are stuck (e.g. from a dump of the stuck process)

**Comment by tinuroth** [comment]
Not sure I can give you the answers you want, but yes, it is on TeamCity, and yes the problem is about the NUnit Agents being left running:
![image](https://user-images.githubusercontent.com/5224875/46790949-4ab86680-cd40-11e8-8ccd-6c86dcc3a436.png)

On the above snap, there are only three such processes present, without any build running. Sometimes there are more and sometimes there are enough to make the next build fail. Checking the log in such a case suggests that build directory clean-out failed, presumably because files are still locked by the stuck NUnit agents:
![image](https://user-images.githubusercontent.com/5224875/46791290-18f3cf80-cd41-11e8-9ffb-e880a1148242.png)

At least it is enough to kill any NUnit processes and restart the build. That solves the problem.

**Comment by mikkelbu** [comment]
To see where the agents are hanging you will probably need to look at memory dumps.

What if you run the console locally are there also agent running afterwards?
What if you run locally with `--inprocess` are any errors reported?
What if you run locally with `--trace=Debug` are there any errors/warnings in the .trace files?
Are you creating threads and not closing them again?

**Comment by tinuroth** [comment]
Thanks a lot for your looking into this!

Trying to answer your questions:
- yes, agent also get stuck if I ran the same command line locally  
```C:\TeamCity\buildAgent\tools\NUnit.Console.3.9.0\nunit3-console.exe C:\TeamCity\buildAgent\temp\buildTmp\rILH0jnmpIzu4UjMjWhooH0K4kqCN9CD.nunit --result=C:\TeamCity\buildAgent\temp\buildTmp\rILH0jnmpIzu4UjMjWhooH0K4kqCN9CD.nunit.xml --noheader --where cat!=RequiresDwom&&cat!=Slow&&cat!=dotMemory```  
Right at the beginning there are 6 to 8 nunit agents running. Then it settles down to three, but only one is active (CPU not 0, average around 10%). After the run, those three are left stuck. The output on the console is this (relevant parts only):  
```
Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.42000

Test Files
    C:\TeamCity\buildAgent\temp\buildTmp\rILH0jnmpIzu4UjMjWhooH0K4kqCN9CD.nunit

Test Filters
    Where: cat!=RequiresDwom

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\TeamCity\buildAgent\work\848c5e0ba8a40e4c\bin\Release
    BasePath: C:\TeamCity\buildAgent\work\848c5e0ba8a40e4c\bin\Release
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.7.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 12

Test Run Summary
  Overall result: Warning
  Test Count: 2774, Passed: 2767, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 7
    Skipped Tests - Ignored: 7, Explicit: 0, Other: 0
  Start time: 2018-10-12 09:47:17Z
    End time: 2018-10-12 09:56:04Z
    Duration: 526.976 seconds
```
But I did get an unexpected error reported out of the test run, a command line version of the application under test (and used in some performance test) seems to have crashed, probably on closing as no test failure results from that. Nothing you can comment about, but something I have to look into. Could such a crash on closing lead to nunit agents getting stuck?
- with ```--inprocess``` the situation is identical to as described above (it was a little faster, 470 seconds).
- with ```--trace=Debug``` again the same result. But I failed to find any .trace files. Where can I find those? I also tried ```--trace=Verbose```, to no avail, not .trace files anywhere I looked for them.
- yes, we are creating threads, and I do hope we close them. But worth making sure... would not properly closing them result in nunit agents getting stuck?

I'll be out of office for one week, so cannot really follow up here further. I am also not sure it makes sense. I will see how the situation develops with Windows 10 first.
