### ISSUE TITLE
v4.4.0 causes missing method exception for System.Text.Json

### ISSUE THREAD

**Issue by gregsdennis** [nunit/nunit-console#1325]
Originally reported [here](https://github.com/dotnet/runtime/issues/82798).

Minimally reproducible example:
[TestProject1.zip](https://github.com/nunit/nunit/files/10865579/TestProject1.zip)

Error occurs when the test project runs in a .Net version prior to 7.0 and references a .Net Standard 2 project that contains a reference to System.Text.Json Nuget package v7.

Example solution contains:

- ClassLibrary1 - `netstandard2.0`
  - references System.Text.Json Nuget package v7
- TestProject1 - `netcoreapp3.1;net6.0;net7.0`
  - references NUnit3TestAdapter v4.3.1
  - references ClassLibrary1
  - passes all tests
- TestProject2 - `netcoreapp3.1;net6.0;net7.0`
  - references NUnit3TestAdapter v4.4.0
  - references ClassLibrary1
  - passes `net7.0`, fails `netcoreapp3.1` & `net6.0`

Note that this also occurs referencing System.Text.Json Nuget package v6.*.

**Comment by CharliePoole** [comment]
Working in the latest dev build: 3.18.3-dev00011
