### ISSUE TITLE
Any way to install NUnit Console runner without internet access?

### ISSUE THREAD

**Issue by andrewducker** [nunit/nunit-console#1326]
I'm trying to get NUnit Console Runner onto a CI server which does not have internet access, so that I can run unit tests on there.

I was looking for an MSI, or a zip which I could use to install it from/unpack it from.  But the install methods seem to assume internet access.

I've checked https://github.com/nunit/nunit-console/releases and https://docs.nunit.org/articles/nunit/getting-started/installation.html - the latter of which says "You can also download the latest binary zip or an MSI installer of the NUnit Console from GitHub".

Is there any way of getting NUnit onto a server which doesn't have internet access?  Am I missing something obvious?

**Comment by CharliePoole** [comment]
The releases on GitHub include both a zip and n msi, which you can download. See https://github.com/nunit/nunit-console/releases

However, the most recent releease, 3.16.3, appears to have omitted them..

**Comment by CharliePoole** [comment]
I created issue #1327 regarding the missing files in 3.16.3.

**Comment by andrewducker** [comment]
Thank you, I hadn't realised that it was only missing from the latest version.  Good luck getting people to follow the right process!
