### ISSUE TITLE
NUnit downloadable packages zip file naming is confusing and non-intuitive

### ISSUE THREAD

**Issue by hiredgunhouse** [nunit/nunit-console#133]
Here https://github.com/nunit/nunit-console/releases/tag/3.5 you can download a package that is called "NUnit Console 3.5" but the main zip and msi files are named NUnit.3.5.0.zip and NUnit.3.5.0.msi which is very confusing if you consider that here https://github.com/nunit/nunit/releases/tag/3.5 you can download the main package called "NUnit 3.5" which gives you the main zip file named "NUnit-3.5.0.zip".
Can you spot the difference?
NUnit.3.5.0.zip vs NUnit-3.5.0.zip
Very confusing after you download the files cause you can tell which one is which.
Wouldn't it be better if the console package was named xxxxx-console or something similar?

**Comment by rprouse** [comment]
Agreed, the ZIP files that we create in this repo should be renamed.

**Comment by rprouse** [comment]
This is left over from when we split the repositories. It is an easy fix, we just need to update the names in `build.cake`

**Comment by ChrisMaddock** [comment]
Just a note - the zip with the release here is (I think!) built in nunit-distribution, and contains all the extensions too.

Whether that's how it should be or not...not sure!

**Comment by ChrisMaddock** [comment]
I wanted to do some tidying up of nunit-distribution before the next release anyway. The zip packages is made in that repo now, so I'm going to move the issue over there. @hiredgunhouse - feel free to subscribe to the new issue. 😄

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-distribution #9](https://github.com/nunit/nunit-distribution/issues/9) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CharliePoole** [comment]
I'm re-opening this because I think the immediate issue is critical. The long-term fix belongs in the nunit-distribution project, but the badly named files can't wait for the next release. I've renamed files in the past when it was necessary, so I'll look at doing that.

**Comment by CharliePoole** [comment]
I should add, this is also blocking the creation of a Chocolatey console package.

**Comment by CharliePoole** [comment]
Direct renaming is possible for both the zip and the msi. WRT the msi, however, the dialog shows "NUnit 3.5.0" in the title bar. Of course, it would be better to show NUnit Console but I think that's acceptable. I'll spend a little time seeing if I can do a better fix, but not much.

**Comment by CharliePoole** [comment]
I downloaded both files, renamed them and uploaded them again, removing the originals. The release now has NUnit.Console-3.5.0.zip and NUnit.Console-3.5.0.msi.

@nunit/core-team Should we make any effort right now to change the naming in the msi dialogs, while using the same binaries? Or should we wait for the next release?

**Comment by ChrisMaddock** [comment]
Yeah, I think it can wait. 😄 We can 'formally' rename for 3.6.

**Comment by CharliePoole** [comment]
OK, I'll close this then.
