### ISSUE TITLE
Installing Console Runner without Visual Studio

### ISSUE THREAD

**Issue by jfclancey** [nunit/nunit-console#1340]
Hello,

       I'm trying to install console runner on a server in order to automate a test. I'm currently using NUnit.ConsoleRunner.3.9.0 on which Visual Studio is installed. Can I install NUnit.ConsoleRunner.3.9.0 without doing it through Visual Studio?

Thanks,
John

**Comment by stevenaw** [comment]
It is indeed possible. The info for the 3.9 release including links to different download options like an MSI are here: https://github.com/nunit/nunit-console/releases/tag/v3.9

It's also available on chocolatey for scripted installation
https://community.chocolatey.org/packages/nunit-console-runner/3.9.0

However, version 3.9 is quite old and newer versions are available if you wanted. The latest release, 3.16.3, can also be found on chocolatey or in the releases page
