### ISSUE TITLE
nunit-console and nunit-agent to support longPathAware

### ISSUE THREAD

**Issue by poklau** [nunit/nunit-console#1367]
It looks like NUnit console does not support tests with file path exceed MAX_PATH as per document [here](https://learn.microsoft.com/en-au/windows/win32/fileio/maximum-file-path-limitation?tabs=registry). 

This should be as simple as making it long-path aware like this in app.manifest:

```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
```

**Comment by CharliePoole** [comment]
@OsirisTerje @manfred-brands @poklau 
I could finish the PR by merging it into the correct branch but I don't feel confident enough about what this is doing.

If changing the manifest _makes_ an application long-path-aware, that's great. If, as I suspect, it merely _tells_ the runtime that we _are_ long-path-aware, then we need to make sure that's true before changing the manifests. Can anyone shed light on this?

FWIW, I see this as similar to our `Parallelizable` attribute, which simply _promises_ that the test can safely be parallelized but doesn't make it work in case it isn't. :-)

**Comment by poklau** [comment]
@CharliePoole 
I have a locally built binaries that using this for the last 6 months and it's been supporting long-path as expected so far.

Not sure how I can create a test to cover this.

**Comment by CharliePoole** [comment]
That's good enough for me. :-)

**Comment by CharliePoole** [comment]
Merging this into version4 failed, probably because it has gotten a bit out of date. As this is simple, I'll just redo it in both main and version4.

**Comment by CharliePoole** [comment]
@poklau Actually, the merge of your PR turns out to have failed for an unrelated  reason: one of the dependencies in our myget feed no longer existed, having been automatically purged. I fixed it along with applying your changes.
