### ISSUE TITLE
Stuck between versions

### ISSUE THREAD

**Issue by ValentijnMakkenze** [nunit/nunit-console#1371]
Hi,

We want to switch to NUnit 4 but when we did we got this error:
No suitable tests found in ...
Either assembly contains no tests or proper test driver has not been found.

Turned out we where using NUnit.ConsoleRunner 3.16.3 so we downgraded to version 3.15.5
But now our tests hang because of issue #1183: Build hangs when test spawns processes which do not terminate properly 
This issue is fixed in the 16 version but not in the 15 version.

Can issue #1183 be backported to the 15 series or NUnit 4 support be added to the 16 series?

Kind regards,

Valentijn

**Comment by OsirisTerje** [comment]
I'm on travel now,  so not at any computer. Do you see a stacktrace? And does it point to the engine ir the console?  The 3.16 series have a loading issue where we don't know the resolution, and we're therefore careful  with moving code from that to 3.15.  We're going to do that eventually, but we're low on resources.  If the crash is in the console, it is easy to move over.  If it is in the engine it is harder.  We can have a look if we can get 4 support into 3.16.

**Comment by ValentijnMakkenze** [comment]
I cherry-picked #1183 to the release-3.15.3 branch and build that and put it on our buildserver and the tests run OK now.

**Comment by OsirisTerje** [comment]
Awesome!  Feel free to put up a pr on it, and we can see if it works on all tests, adapter incl.

**Comment by ValentijnMakkenze** [comment]
I created a PR but wasn't quite sure which branch to target #1372

**Comment by ValentijnMakkenze** [comment]
Created a new PR with target branch version315 ##1373

**Comment by ValentijnMakkenze** [comment]
Can I do something to help release 3.15.6, with the fix for #1183 ?

**Comment by stevenaw** [comment]
@ValentijnMakkenze 
Can you see if the 3.17 pre-release build works for you?
https://github.com/nunit/nunit-console/releases/tag/V3.17.0-dev.3

It looks like [your commits](https://github.com/nunit/nunit-console/commit/c52aa3db217c834c4133bc4cd84c5a36ccf39949) have also been included in the 3.17 dev build which should, I believe, be built off of 3.15.x and also include a select few commits from the 3.16.x branch. It should include .NET8 support as well, should you need it (https://github.com/nunit/nunit-console/issues/1374)

**Comment by ValentijnMakkenze** [comment]
I tried the 3.17 pre-release and was able to build without problems.

Thanks

**Comment by stevenaw** [comment]
Happy to hear it helped @ValentijnMakkenze !
Thanks for letting us know
