### ISSUE TITLE
Engine should honor the DOTNET_ROOT environment variable if set

### ISSUE THREAD

**Issue by MichalMucek** [nunit/nunit-console#1381]
Add a parameter to NUnit Console for .NET installation/binaries directory path that, when defined, will omit or extend `NUnit.Engine.Internal.TestAssemblyResolver.GetDotNetInstallDirectory()`.

The motivation behind this feature is to enable the NUnit Console to work in Windows environments where .NET is not installed but only .NET binaries are downloaded, e.g. during pipeline execution.

**Comment by stevenaw** [comment]
@MichalMucek  Are the binaries used in your pipeline for net framework or core/net5+?

For the latter, I think the DOTNET_ROOT environment variable would be the standard way to define this if the console runner were updated to support this (https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_root-dotnet_rootx86).

**Comment by CharliePoole** [comment]
@MichalMucek Rather than adding a command-line option, I'm inclined to use @stevenaw 's suggestion and honor any of the DOTNET_ROOT environment variables. Does that work for you?

**Comment by MichalMucek** [comment]
@stevenaw core/net5+

@CharliePoole Sounds good
