### ISSUE TITLE
Namespace regex matching works only for certain Namespace?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#1389]
Here's something I do think is a bug.

### Cases that work

First, let's see the case where the Namespace regex matching is working as per expected, based on the doc [here](https://docs.nunit.org/articles/nunit/running-tests/Test-Selection-Language.html).  

If I use the where filter on a test solution, then this is the output I get:

```
Test Filters
    Where:  namespace =~ TestDebugAssert.AAA.BBB 

=> TestDebugAssert.AAA.BBB.CCC.DDD.DDClass.RunDDD
=> TestDebugAssert.AAA.BBB.CCC.MoreClassesAll.RunMe
=> TestDebugAssert.AAA.BBB.CCC.TestClassCCC.RunDebugAssertCCC
RunDebugAssertCCC
=> TestDebugAssert.AAA.BBB.TestClass3.RunDebugAssert
RunDebugAssert
```

This is correct as it correctly matches everything under the namespace ( and the subs) of `TestDebugAssert.AAA.BBB`

Now I add another condition to filter off the test cases in the namespace `TestDebugAssert.AAA.BBB.CCC`. And here's the result:

```
Test Filters
    Where: namespace =~ TestDebugAssert.AAA.BBB and namespace !~  TestDebugAssert.AAA.BBB.CCC

=> TestDebugAssert.AAA.BBB.TestClass3.RunDebugAssert
RunDebugAssert

```

It still works as expected. Good!

### Case that doesn't work

 So I apply the test selection logic to my main code. I want to include all the tests under the namespace and subnamespace of `MiTS.IntegrationTest.EW3D`, except the ones in the namespace (and its sub) `MiTS.IntegrationTest.EW3D.AsBuiltTest`. Here's the output

```
Test Filters
    Where: namespace =~ MiTS.IntegrationTest.EW3D and namespace !~ MiTS.IntegrationTest.EW3D.AsBuiltTest

=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuilt_BaseSurfaceTopSoilVerification
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuilt_baseSurfaceWithoutTopSoil
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTM("EndAreaAcrossMultipleBoundaries.7z")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTM("AsBuiltMultipleBoundaries.7z")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTM("WKL_AsBuiltOneBoundary_B1.7z")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTM("WKL_AsBuiltMultipleBoundary_A1B1.7z","AS BUILT - A1")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTM("WKL_AsBuiltMultipleBoundary_A1B1.7z","AS BUILT - B1")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTM("WKL_AsBuiltOneBoundary_CombinedA1B1.7z","AS BUILT WBC")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTMAndEndArea("WKL_AsBuiltOneBoundary_B1.7z")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTMAndEndArea("WKL_AsBuiltMultipleBoundary_A1B1.7z","AS BUILT - A1")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTMAndEndArea("WKL_AsBuiltMultipleBoundary_A1B1.7z","AS BUILT - B1")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.AsBuiltTest_DTMAndEndArea("WKL_AsBuiltOneBoundary_CombinedA1B1.7z","AS BUILT WBC")
=> MiTS.IntegrationTest.EW3D.AsBuiltTest.TPTay
=> MiTS.IntegrationTest.EW3D.AsBuiltTopsoilTest.AsBuiltPlatformTopsoil_Test
=> MiTS.IntegrationTest.EW3D.AsBuiltTopsoilTest.AsBuiltTopsoil_Test
=> MiTS.IntegrationTest.EW3D.BoreholeDataGridTest.BoreholeTest_Total
=> MiTS.IntegrationTest.EW3D.CutFillWithPavementTest.WithoutPavementCutFillTest
=> MiTS.IntegrationTest.EW3D.CutFillWithPavementTest.WithPavementCutFillTest

```

And yet, as you can see above,  the tests inside `MiTS.IntegrationTest.EW3D.AsBuiltTest` _are_ still included, as if the to-not-match (`!~`) operator has not effect whatsoever, different from how the previous selection involving `TestDebugAssert.AAA.BBB.CCC` behaves!

This is my command line to call nunit-console:

```
call  "%NunitConsole%\nunit3-console.exe" "%slnFile%" /config:Debug  --where "cat!=Memory && (namespace =~ TestDebugAssert.AAA.BBB )" --labels=Before --skipnontestassemblies --result="%testresultxml%"  --timeout=600000 > "%testresulttxt%"

```

I'm using Nunit console 3.16, and Nunit framework 3.13, and I'm on .Net framework 4.8.

**Comment by stevenaw** [comment]
Thanks for the thorough details @WindingWinter 
Are you able to upload a sample solution which compiles, runs, and reproduces the issue? It would allow comparison to a few known edge case issues with filtering.

**Comment by WindingWinter** [comment]
@stevenaw , I checked further and it's not a bug. The confusion stems from that I thought `AsBuiltTest` is a subnamespace. Alas, it's a class. So there is nothing wrong with nunit console
