### ISSUE TITLE
Does Nunit ITestEventListener support async handler for OnTestEvent

### ISSUE THREAD

**Issue by puagarwa** [nunit/nunit-console#1397]
I am writing a custom reporter by writing a Nunit extension via ITestEventListener as mentioned in the Nunit document [here](https://docs.nunit.org/articles/nunit-engine/extensions/creating-extensions/Writing-Engine-Extensions.html).

I have some requirement where i would like to implement OnTestEvent as async handler. I didnt find any document around it, hence checking if Nunit support async handler for it. 

Another minor question is around console out, i observe console out lines from extension are not showing up in console, for now i am getting around this by writing into a file but i like to see if there is way to flow logs at console form extension.

**Comment by CharliePoole** [comment]
Answered
