### ISSUE TITLE
Fix for #1182 missing in 3.17 (Don't throw exception when VS Solution contains a .NET Standard assembly)

### ISSUE THREAD

**Issue by LinusNilssonTwoday** [nunit/nunit-console#1398]
Issue #1182 was fixed in 3.16. The fix was was ported to main (to become 4.0), but is missing in 3.17. I read somewhere that 3.17 was branched from 3.15, which might explain it. I don't know whether there are more fixes from 3.16 that are missing in 3.17, but #1182 is affecting us at the moment.

Fix in version3: https://github.com/nunit/nunit-console/pull/1268
Port to main: https://github.com/nunit/nunit-console/pull/1299

**Comment by OsirisTerje** [comment]
@LinusNilssonTwoday Thanks for pointing it out.  This seems like an easy one to port over.

**Comment by CharliePoole** [comment]
Strange, I see I merged the change in PR #1282 but it's not there any longer and there is no history of that commit. Well, here goes again.

**Comment by LinusNilssonTwoday** [comment]
Thanks for fixing it (again). :) Will wait for the 3.18 release.
