### ISSUE TITLE
Add vcxproj support to the engine ProjectService

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#14]
@CharliePoole commented on [Thu Dec 25 2014](https://github.com/nunit/nunit/issues/430)

This appears to require a fair amount of effort. See comments on #227.

**Comment by ChrisMaddock** [comment]
@CharliePoole - This should probably be in the vs-loader extension repo, but given there's been no demand since the original PR in 2014, I think we should close this. Would you agree?

**Comment by CharliePoole** [comment]
Agree with moving or closing... up to you guys since it's the engine.

**Comment by ChrisMaddock** [comment]
Great - thanks!
