### ISSUE TITLE
Unlist versions 16.x to the extent possible

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1409]
I see so many answers telling people to use 3.15.5 or 3.17.0. @OsirisTerje has been porting good 16.x fixes to the version3x branch as well as to main where applicable.

We can easily make these versions unlisted on nuget.org and chocolatey .org. I'm not sure what is the best approach for the GitHub releases - maybe just a comment warning people away.

Thoughts?

**Comment by OsirisTerje** [comment]
Agree, we should unlist them, and warning mark them in github.  That should be sufficient.
