### ISSUE TITLE
Simplify MSI build process

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1432]
I've had to make an number of changes to the platforms we support lately, most recently for issue #1430.

The msi package provides the greatest challenge in getting it right the first (or third or fourth) time. In part that's in the nature of the XML format we have to use, which is very complex. But a large part of the problem seems to stem from the two-step process we use, which is...

1. Create an image directory containing what we want in the package.
2. Create the msi package out of that directory

IIRC, I created that process many years ago because it seemed "simpler" to me. The problem is that when any thing fails to work, you have to start by figuring out which of the two steps created the problem - and sometimes it's both!

With this issue, I'd like to experiment with making it a one-step process. It seems that know where each file in the image came from, so, in principle, it should be possible to just grab that each file from that location directly in the `.wxi` entries.

In any case, I'll give it a go.

**Comment by CharliePoole** [comment]
@OsirisTerje If you have any thoughts of dropping the msi, however, let me know and I won't bother with this.

**Comment by OsirisTerje** [comment]
Imho, I would drop the msi.  
I believe we have enough ways of installing this.

**Comment by CharliePoole** [comment]
IIRC, I dropped it in V4. What about V3?

**Comment by OsirisTerje** [comment]
Just drop it.

**Comment by CharliePoole** [comment]
Will do... closing this one...
