### ISSUE TITLE
Eliminate msi package

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1434]
Following a brief discussion under issue #1432, we will eliminate the msi package for the next release. Because the next major release, 2 .0 is already in beta, we will do this breaking change using a minor version upgrade: 3.18.

**Comment by CharliePoole** [comment]
Since this is the __only__ msi package we create, the functionality of creating msi packages may be removed from the scripts at the same time.

**Comment by katediadechko** [comment]
This is unfortunate! The MSI was the easiest and the most straightforward installation option!

**Comment by CharliePoole** [comment]
@katediadechko Sorry to hear that. With limited resources, we are trying to streamline the release process as much as we can.

Have you tried Chocolatey? You can install the runner centrally by a single command on the command-line. And although there is no package that includes a bunch of extensions, you can install any that you want to use the same way.
