### ISSUE TITLE
NUnit.Console 3.17.0 and lower does not work with NUnit version 4.1.0 

### ISSUE THREAD

**Issue by Moshex** [nunit/nunit-console#1441]
When I run my NUnit.Console command with NUnit version 3.14.0 my tests run just fine with this command.
 
This is the command:
` mono ../../../.nuget/packages/NUnit.ConsoleRunner/3.16.3/tools/nunit3-console.exe --labels=Before  --out=TestResult.txt "--result=TestResult.xml;format=nunit2" ./UITests.csproj --trace=Verbose;`

```
NUnit Console 3.16.3 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Thursday, July 11, 2024 2:25:36 PM

Runtime Environment
   OS Version: MacOSX 23.5.0.0 
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    ./UITests.csproj

```

When I run my NUnit.Console command with NUnit version 4.1.0 my tests do not run with the same command.
 
This is the command:

` mono ../../../.nuget/packages/NUnit.ConsoleRunner/3.16.3/tools/nunit3-console.exe --labels=Before  --out=TestResult.txt "--result=TestResult.xml;format=nunit2" ./UITests.csproj --trace=Verbose;`

This is the error:

```
NUnit Console 3.16.3 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Thursday, July 11, 2024 2:27:06 PM

Runtime Environment
   OS Version: MacOSX 23.5.0.0 
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    ./UITests.csproj


Errors, Failures and Warnings

1) Invalid : /Users/{username}/Documents/UITests/UITests/bin/Debug/net6.0/UITests.dll
No suitable tests found in ' /Users/{username}/Documents/UITests/UITests/bin/Debug/net6.0/UITests.dll'.
Either assembly contains no tests or proper test driver has not been found.

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2024-07-11 20:27:06Z
    End time: 2024-07-11 20:27:06Z
    Duration: 0.282 seconds

Results (nunit2) saved as TestResult.xml
```

is there something I need to do to get NUnit.Console to work with NUnit version 4.1.0?

**Comment by CharliePoole** [comment]
All version 3.16 releases have been marked on GitHub as deprecated. Try either 3.15.5 or 3.17.0 and let us know if the problem persists. Even better, try  the latest dev build of 3.18.0 from our MyGet feed.

**Comment by Moshex** [comment]
Thank you for your reply!
With regards to versions 3.15.X and version 3.17.0, I am not able to use those versions at all due to this bug:
https://github.com/nunit/nunit-console/issues/1387#issuecomment-2131315747

Do you happen to know if this issue is fixed in version 3.18.0? 

also to make sure I have the right branch could you give me a link to the repo that you would like me to test to see if this issue is no longer present?

**Comment by CharliePoole** [comment]
The feed is here: https://www.myget.org/feed/nunit/package/nuget/NUnit.ConsoleRunner Pick the latest 3.18 dev build (not 4.0). Issue #`1387 hasn't had any work done on it as far as I can see, I'll take a look at it for 3.18.0.

**Comment by Moshex** [comment]
@CharliePoole 
I tested this version https://www.myget.org/feed/nunit/package/nuget/NUnit.ConsoleRunner/3.18.0-dev00068
and per my testing it fixes both issues, do you know when a prod release of this version will come out?

**Comment by CharliePoole** [comment]
@Moshex Trying for this week as I'll have family visiting for the following two weeks.

**Comment by Moshex** [comment]
Thank you so much please keep me updated!

**Comment by Moshex** [comment]
@CharliePoole is there a prod release of 3.18.0?

**Comment by CharliePoole** [comment]
As I said, I'm trying for this week. FYI, issues close when the fix makes it into the main branch.

**Comment by Moshex** [comment]
I see the new update thank you so much for all your heard work!

**Comment by CharliePoole** [comment]
If you plan to use the dotnet tool version, there's a critical bug which will require a 3.18.1 release.

**Comment by CharliePoole** [comment]
@Moshex The 3.18.1 release is now published.
