### ISSUE TITLE
Unable to install NUnit.ConsoleRunner.NetCore 3.18.0 due to not found settings file 'DotnetToolSettings.xml'

### ISSUE THREAD

**Issue by MichalMucek** [nunit/nunit-console#1446]
When trying to install NUnit.ConsoleRunner.NetCore (.NET Tool) 3.18.0, there's an error:

`Tool 'nunit.consolerunner.netcore' failed to update due to the following:
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'nunit.consolerunner.netcore' failed to install. Contact the tool author for assistance.`

Also, instructions for installing the .NET tool (the .NET CLI tabs) are missing from the nuget.org page for version 3.18.0, while they are present for 3.17.0 and earlier.

**Comment by CharliePoole** [comment]
@MichalMucek Could you provide the exact command you are entering to install the tool?

**Comment by MichalMucek** [comment]
@CharliePoole
`dotnet tool install --global NUnit.ConsoleRunner.NetCore --version 3.18.0`
`dotnet tool install --local NUnit.ConsoleRunner.NetCore --version 3.18.0`

**Comment by CharliePoole** [comment]
Confirming this bug. It looks as if the structure of the package may be incorrect, i.e. the file is there but not in the right place.

**Comment by CharliePoole** [comment]
In addition to fixing this, we should add a test. We do test the runner but we do not execute it via the dotnet command, so that needs to be added. 

Workaround: Use NuGet to install it to a known location and then run the executable directly.
