### ISSUE TITLE
Timeout Attribute no longer working in nunit console 3.18.1?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#1472]
I have a test class that consists only of a single test:

```
       [Test]
       [Timeout(1000)]
       public void TimeOutIssueFail()
       {
           Thread.Sleep(2000);
       }
```

inside a test  project with the config

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>
</Project>

```

I expect it to fail with the below command line:

```
"%NunitConsole%\nunit3-console.exe" "%slnFile%"
```

But somehow, it still passes. I run it in Resharper runner and it fails as expected. I run it with `dotnet test "%slnFile%"`, it also fails as expected.

**Comment by CharliePoole** [comment]
You are correct and I almost closed this since it really seemed like a framework issue. Timeout is implemented in the framework by cancelling your running test. But since you reported that your test works correctly under dotnet test and resharper, I'd like to understand why that's the case.

**Comment by WindingWinter** [comment]
@CharliePoole , after I read the https://github.com/nunit/nunit/issues/4021 I also would have thought that this is behaving correctly. But somehow, like I mentioned, the `Resharper test runner` and `dotnet test --no-build "%slnFile%"` failed-- the expected result should be pass since .Net 8.0 no longer cares about `Thread.Abort`, rendering `Timeout` ineffective. 

In this sense nunit console actually got it right. But why Resharper and dotnet got it wrong?

**Comment by manfred-brands** [comment]
@WindingWinter Even though net 8.0 no longer aborts the test, NUnit still has a timer for the timeout value and will fail the test of it doesn't finish on time.

**Comment by WindingWinter** [comment]
@manfred-brands , this complicates things....

So, should the `Timeout` attribute _still_ work or not in .net 8.0 and above? This point needs to be clarified, so that we as the user of nunit library can decide what to do with the tests that are decorated with the `Timeout` attribute. 

And test runners like `nunit-console`, `dotnet test` can decide how to handle it. Currently  `nunit-console` and `dotnet test` give different results.

**Comment by manfred-brands** [comment]
@WindingWinter The attribute is marked obsolete and should not be used for .net core builds.

See misbehaving discussion in https://github.com/nunit/nunit/issues/4021

**Comment by CharliePoole** [comment]
@manfred-brands I wasn't familiar with the discussion in nunit/nunit#4021 till now. One thing I don't see there is how it handles the property set by the runner in response to the `--timeout` option, `FrameworkPackageSettings.DefaultTimeout`.
Is it used to provide the equivalent of `[CancelAfter]` when it's non-zero, as it does (or did) for `[Timeout]`?

**Comment by manfred-brands** [comment]
@CharliePoole The `FrameworkPackageSettings.DefaultTimeout` sets the `TestCaseTimeout`.
This value is used as a fallback when to `Timeout` has been specified.
The `CancelAfterAfftibute`, just like `TimeoutAttribute`  cannot be specified without a timeout the value has no affect on the `CancelAfter`.

However, like before, if the `DefaultTimeout` is non-zero, it will use an implicit `TimeoutAttribute`.
If a test exceeds that time, it will be "marked as failed", but continues to run in the background. Not ideal.

**Comment by CharliePoole** [comment]
@manfred-brands So no change there from how I  remember it. I wrote the code to detect non-zero `DefaultTimeout` and use that value even when [Timeout] isn't specified on a test. You use that option and then all your tests get a timeout without specifying it. I haven't looked at your implementation, but couldn't you do essentially the same thing for the `CancelAfterAttribute`? Otherwise, the user is forced to specify it on each test.

**Comment by manfred-brands** [comment]
@CharliePoole `CancelAfter` is cooperative, even if I would create a `CancellationToken` for the `DefaultTimeout`, if nothing looks at it, the test would just continue. Marking the test as failed, but keep it running is bad imho.

**Comment by CharliePoole** [comment]
@manfred-brands Yes, the user would have to do something to indicate that the test is cancellable, i.e. `TestExecutionContext.CurrentContext.UseCancellation` has to be true. I can think of a few ways to do that without specifying a timeout. It's probably not a priority at the moment, but as more tests become cancellable individually it could become more important for  users.
