### ISSUE TITLE
Create a .NET 8.0 Console Runner

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1493]
Our package `NUnit.ConsoleRunner.NetCore` uses .NET 6.0. We should either upgrade this to .NET 8.0 or provide alternate builds. @nunit Let's discuss this here.

We have often discussed the functional differences between the standard (net462) build of the runner and the netcore runner. This issue is NOT aimed at adding any new functionality, only at providing new platform support. That is, the runner will continue to run one assembly at a time in process. Discussion of future functionality is needed but separate from this issue.

There is an experimental .NET 8.0 runner currently available on our myget feed as `NUnit.ConsoleRunner.Net80` version 3.18.3-dev00006 and later.

**Comment by CharliePoole** [comment]
@OsirisTerje @nunit 

Options for the netcore runner...

1. Upgrade it to .net 8.0 for 3.19, dropping the separate experimental .net 8.0 runner.
2. Keep both runners, possibly renaming netcore to net60.
3. Have one dotnet tool that switches between 6.0 and 8.0, i.e. a standalone executable containing both 6.0 and 8.0 implementations, with a command-line option to select one or the other and defaulting to net 8.0?

I don't use the dotnet runners myself, so I don't have a strong opinion. The options are listed from easiest to less easy, but none of them are terribly difficult. Options 2 and 3, of course, give us more things to test.

**Comment by mikkelbu** [comment]
I'm in the same situation as Charlie. I don't use the dotnet runner, so I don't have a strong opinion. My initial thought is to take the easiest option unless somebody has another opinion (my guess is that we will first hear the comments after the release, so perhaps go for option 1 and then if a lot of people complain turn this into option 2 in a subsequent release).

**Comment by OsirisTerje** [comment]
I is quite normal to have multiple framework versions in the same package, so I think that is what one do.
When you run the tool, the SDK in use will determine which version of the framework is chosen, based on the runtime environment or SDK version.

**Comment by OsirisTerje** [comment]
I use the netcore runner (when I do use the console that is, bust mostly I use dotnet test), so for it to be viable, it needs to be able to run the correct target frameworks.  

<img width="503" alt="image" src="https://github.com/user-attachments/assets/395ea811-4bbe-4509-881c-b2f559eef7ba">

**Comment by CharliePoole** [comment]
@OsirisTerje You did this in an earlier release of the tool - I believe in3.17.0 but I could be wrong. Both the .NET 6.0 and 8.0 runners were present. In my tests, I found that .NET 6.0 was always run. That's why I removed it. It's easy enough to recreate that and experiment with it, but all the references I have found online tell me that you have to target one version.

I initially thought that you could specify two commands for a tool, but that is rejected on install. If you have an example of a way to make it work with two runtimes, please point me to it.

**Comment by OsirisTerje** [comment]
It is a bit strange, the highest SDK version in the package ,that also is installed on the PC, should be used.  But I haven't experimented with it so I might be wrong.  Also, I haven't found any online references stating this explicitly, so if you have, can you pass a link to them?

**Comment by CharliePoole** [comment]
@OsirisTerje 

Yes, most discussion is about roll-forward, i.e. how to make a tool built for one runtime run under a newer runtime if the old one is not installed. That's clear enough and the .NET 9.0 update makes it easier for users to do without editing any files.

I think our issue is different. We have different code for older runtimes than for newer runtimes. In particular, we are able to load more dependencies using the newer runtimes. That logic would lead us to use the highest level of .NET internally, currently .NET 8.0, soon .NET 9.0. 

On the other hand, if we do that, are we locking out users who are still on .NET 6.0 for one reason or another? I don't really know. Thinking about it I guess I should set up a VM only .NET 6.0 and another with .NET 8.0. My dev machine, of course has everything from .NET Core 2.1 up to .NET 8.0 and that's probably not a typical environment. :-)

I'll keep this one on the back-burner until I have a good block of time to devote to it.

Also, thanks for the birthday greeting. :-)

**Comment by manfred-brands** [comment]
When looking up the Nuget package it points to a [non-existing document](https://docs.nunit.org/articles/nunit/release-notes/console-and-engine.html). I cannot find this in the [running-tests](https://docs.nunit.org/articles/nunit/running-tests/Index.html) section either.

I'm still confused about the why we have all these different ways to run tests. 
Historically yes, we used nunit(gui) to run the test. Is this still needed?
Now we only use `dotnet test` for CI and `VS Test Explorer` to run any tests on all my multi-targeting libraries.
The only reason for a non-dotnet command is to allow running tests on a system with no SDK installed. That particular situation will be addressed with the new MS self-contained runners.

Having said that. Back to your question. Could we have a "loader" tool that loads the appropriate agent. Isn't that how the console (used to) works? The tool itself will target the latest SDK8 but is shipped with agents for older targets.

**Comment by CharliePoole** [comment]
@manfred-brands 

Thanks for pointing out the bad link. I'll create an issue to fix the package. 

Regarding the various ways to run tests, you make a good point. I'm confused as well. Back when I was heavily involved in nunit, I worked on what I've been calling the "standard" console runner. It exists because of a perceived need to execute a number of different test assemblies, possibly with different runtime targets, in a single run, producing a single result file. Most of the complexity of the engine is there in order to deal with that requirement. If it ever ceased to be a need, then the runner and engine could be drastically simplified.

I do think you're right to ask why we need the dotnet nunit tool at all. I know that xunit.net dropped their dotnet tool a long time ago. If the tool didn't exist, there would still be four other ways to run tests: the standard console runner, nunitlite, dotnet test and the test explorer. Since the tool is created by _subtracting_ features from the standard console runner, it clearly doesn't do anything the standard runner does. @OsirisTerje Is this just a matter of not introducing a breaking change? If so, let's take do-as-little-as-possible approach right now and plan on getting rid of it in V4.

**Comment by OsirisTerje** [comment]
I kind of like the ease of installing it, compared to the NUnit.Console, but when I look at the download numbers, they are very very low.  Total is less than 200K.  Last 6 weeks we're talking less than thousand per version.  

With the upcoming self-executind new MS Testing platform adding into the set of runners, I agree this one can go.  Sad, but.....

**Comment by CharliePoole** [comment]
@OsirisTerje 

FWIW, here's how I install NUnit.Console: ` choco install nunit-console-runner`. I'm of the opinion that, for executable applications, chocolatey has all other means of installation beat. I agree that `dotnet tool install` is very easy for the initial installation, but it doesn't get me any extensions, whereas I can do `choco install nunit-extension-some-extension`  and it just works.

I'll drop this issue from 3.19. What about the .net 6.0 runner?

**Comment by CharliePoole** [comment]
Closing this. Discussion will continue on #1500.

**Comment by CharliePoole** [comment]
Just to make things clear... this issue was temporarily abandoned while we discussed eliminating the .NetCore runner entirely on #1500. We decided NOT to remove it and resolved this issue as part of #1492. The new NetCore runner is available in our MyGet feed and will be included in 3.19. It uses .NET 8.0 rather than 6.0.

**Comment by kogoel** [comment]
@CharliePoole : Can you please share the link of MyGet feed , or workaround to fix the issue on our machines.

**Comment by CharliePoole** [comment]
The entire package list is visible here: https://www.myget.org/feed/Packages/nunit

The .NET Core runner is here: https://www.myget.org/feed/nunit/package/nuget/NUnit.ConsoleRunner.NetCore

As of today, the latest version is 3.18.4-dev00005
