### ISSUE TITLE
Failing OneTimeTearDown leads to different Test Verdicts in ConsoleRunner and dotnet test

### ISSUE THREAD

**Issue by z002Holpp** [nunit/nunit-console#1499]
Steps to reproduce:

 ``` csharp
 [TestFixture]
public class VerySimpleTests
{
    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        Assert.Fail();
    }

    [Test]
    public void Test1()
    {
        Assert.Pass();
    }
}
```

**Execute it with both** 
* NUnit Console Runner
* dotnet test

**Expected Behavior:** 
Both runners result in the same overall verdict.

**Actual Behavior:**
Runner results do differ.
NUnit Console Runner marks the test case as well as the whole test run as failed, while dotnet test marks both the test case as well as the run as passed.

**Output of execution with dotnet test:**

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
TearDown failed for test fixture TestProject2.Tests+VerySimpleTests

TearDown : NUnit.Framework.AssertionException : No message provided
StackTrace:    at TestProject2.Tests.VerySimpleTests.OneTimeTearDown() in C:\ws\SHSampleApplication\TestProject2\UnitTest1.cs:line 11

--TearDown
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnit.Framework.Assert.Fail()
   at TestProject2.Tests.VerySimpleTests.OneTimeTearDown() in C:\ws\SHSampleApplication\TestProject2\UnitTest1.cs:line 11
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 17 ms - TestProject2.dll (net8.0)
```

**Output of execution with NUnit3 Console Runner:**
```
NUnit Console Runner 3.18.3 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Tuesday, October 15, 2024 11:29:35 AM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    C:\ws\SHSampleApplication\TestProject2\bin\Debug\net8.0\TestProject2.dll


Errors, Failures and Warnings

1) TearDown Error : TestProject2.Tests+VerySimpleTests
   at TestProject2.Tests.VerySimpleTests.OneTimeTearDown() in C:\ws\SHSampleApplication\TestProject2\UnitTest1.cs:line 11

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\Users\z002p8em\.nuget\packages\nunit.consolerunner\3.18.3\tools
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETCoreApp,Version=v8.0
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    TargetRuntimeFramework: netcore-8.0
    NumberOfTestWorkers: 16

Test Run Summary
  Overall result: Failed
  Test Count: 1, Passed: 0, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2024-10-15 09:29:35Z
    End time: 2024-10-15 09:29:35Z
    Duration: 0.463 seconds

Results (nunit3) saved as TestResult.xml
```

Additional Information:
* Output is from net8 execution, but its the same for net4.8
* Used NUnit Console package: NUnit3-Console 3.18.3
* Used NUnit Version: 4.2.2
* Used NUnit3 Test Adapter Version: 4.6
* Find attached the TestResult.xml of the execution with Console Runner

[TestResult.zip](https://github.com/user-attachments/files/17376137/TestResult.zip)

**Comment by CharliePoole** [comment]
@z002Holpp 
I agree that this discrepancy is very strange. However, it seems as if the console is getting it right:

* The test case passed and that's how it is shown in `TestResult.xml`. Note that OneTimeSetUp and OneTimeTearDown are not part of the test case the way Setup and TearDown are.
* The fixture failed itself failed as is also shown in `TestResult.xml`. The fixture "owns" the OneTimeTearDown, so that's expected.
* The text output only lists the failing item, i.e. the fixture
* All of the above reflects exactly what the NUnit framework decided, which is what any runner ought to do. (The output you see in `TestResult.xml` actually comes to the runner from the framework.)
* The overall run failed because one thing failed. That has been the overall rule for nunit and most unit test frameworks for a long time: If anything fails, the whole thing fails.

Did you file the bug report against NUnit console because you prefer the dotnet test verdict? If so, please explain. If not, we can try to get this report to the right place. :-)

**Comment by z002Holpp** [comment]
@CharliePoole
Thank for your reply. 
In the first place I wanted to make aware of the discrepancy. And I think one can find valid arguments for both the verdicts. E.g. one could argue that the TestFixtureTearDown should be only used for cleanup and it should not give or impact the quality assessment of the test cases and thus the system under test. But I also agree with your view, whenever one thing fails the whole run should fail.

Whatever argumentation you take, in a productive environment like we have it, where in some cases the tests are executed with dotnet test (large AzDo pipeline farms) and the same tests might be executed as well with NUnit Console Runner (isolated machines, e.g. for Performance checks), such a different behavior is problematic. Especially since the return code of dotnet test is 0 while the return code of the console runner is > 0, and many automated tool chains rely on the return code to either pass or fail the whole thing.

To answer your last question:
It would be great if you could try to get this issue into the right place. :-)

**Comment by CharliePoole** [comment]
@OsirisTerje Can you take a look at this and transfer it to the adapter if you think it's a problem there? Otherwise, it may be an issue for the dotnet test command itself.
