### ISSUE TITLE
Allow Extensions on Extensions

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#15]
@CharliePoole commented on [Wed Aug 26 2015](https://github.com/nunit/nunit/issues/791)

Currently, it's possible to extend the engine but extensions may not have extensions, which was one of the capabilities provided by Mono.Addins. Such a capability would be generally useful to users and would most likely be used by us.

For example, we might want to make the ProjectService and extension, allowing us to deploy the engine either with or without that capability. [We now do that by using a special build, the core engine.]

However, since the ProjectService has extensions itself, it cannot yet become an extension.

Implementation would be identical to the existing identification of extension points. The extension assembly would be examined for assembly-level ExtensionPointAttributes. The key issue is to ensure that assemblies are examined in the proper order. This may require introduction of an attribute to indicate dependencies.

**Comment by CharliePoole** [comment]
I took my name off this. I think the @nunit/engine-team should discuss and decide on its priority. Someone can take it on when necessary.

**Comment by ChrisMaddock** [comment]
I'd be tempted to close this one, unless we have a solid feature that depended on it.

It's an interesting idea, but I feel it'll just gather dust, until there's a little more motivation to get it done.

**Comment by CharliePoole** [comment]
One problem we have is that we don't actually know who is writing extensions or what kind or what they need in addition to what they have. At least not until they file an issue. 😞

**Comment by rprouse** [comment]
I agree with @ChrisMaddock on this. I think we should wait until we have a concrete example from users. I say close this and wait for an issue.

**Comment by ChrisMaddock** [comment]
I'm going to close this issue, as I don't think we've yet found a strong enough use-case for it to become a priority. Happy to reconsider in future, if someone wishes to champion the idea.
