### ISSUE TITLE
The --teamcity option silently fails if the extension is not installed

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1507]
Based on the code as well as my memory, this was intentional. Assuming the user is running interactively, it makes sense to just go ahead and run and hopefully it will be clear that the extension is missing. But of course --teamcity is not normally used interactively but when running on a CI server.

It now seems better to me to give an error message and stop the run if the extension is not available.

@OsirisTerje @veleek @NikolayPianikov Does that make sense to you?

**Comment by Quppa** [comment]
We're seeing this new `Option --teamcity specified but TeamCityEventListener is not installed.` exception when we use NUnit.Console 3.19 but I'm a bit confused about why - isn't that DLL bundled again as of 3.18.3 (https://github.com/nunit/nunit-console/issues/1471)? In our case we're using the NUnit Legacy runner and this might be a question for the TeamCity developers.

I've switched back to 3.18.3 for now and everything is working.

**Comment by CharliePoole** [comment]
@Quppa Are you using the standard runner or the .NET Core (.NET 8.0) runner? Did you install NUnit.Console or NUnit.ConsoleRunner? Are you running under TeamCity? Or did you use the option on the command-line? (The option is assumed if you run under TeamCity?

You could either provide more info in a new issue or provide it here so we can decide if you should create one.

**Comment by Quppa** [comment]
1. I think the standard runner (shows up as NUnit Legacy in TeamCity). This is for a .NET Framework project, in case that's relevant (we just use `dotnet test` for .NET projects).
2. NUnit.Console via the TeamCity [agent tools config](https://www.jetbrains.com/help/teamcity/installing-agent-tools.html).
3. Running under TeamCity.

**Comment by CharliePoole** [comment]
I believe NUnit Legacy refers to NUnit V2. That's not what you are running, since we know you are using 3.19. Since it's .NET Framework, then it has to be the standard runner.

If you have a way to do it, run nunit3-console --list-extensions in the same environment. In fact, it wouldn't hurt to run it all the time prior to running your actual tests. If the teamcity extension is not installed, that's one problem, if it is we have a different problem.

**Comment by ohnefuenfter** [comment]
I have the same problem and here is my output from nuint3-console --list-extensions command:

C:\TeamCity\buildAgent\tools\NUnit.Console.3.19.0\bin\net462> nunit3-console --list-extensions
NUnit Console Runner 3.19.0 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Tuesday, December 31, 2024 8:09:32 AM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Installed Extensions
  Extension Point: /NUnit/Engine/NUnitV2Driver
  Extension Point: /NUnit/Engine/TypeExtensions/IService
  Extension Point: /NUnit/Engine/TypeExtensions/ITestEventListener
  Extension Point: /NUnit/Engine/TypeExtensions/IDriverFactory
  Extension Point: /NUnit/Engine/TypeExtensions/IProjectLoader
  Extension Point: /NUnit/Engine/TypeExtensions/IResultWriter

i've also tried to 'install' extension with the .addins file described here
https://docs.nunit.org/articles/nunit-engine/extensions/Installing-Extensions.html#the-addins-file

and result is the same - the list of installed extension as above and the error message in teamcity build (Option --teamcity specified but TeamCityEventListener is not installed.).
do you know other method to force-install teamcitylistener extension ?

by the way - if i switch to the 'standard' Nuint runner - i have the same problem with different message:
The TeamCity NUnit runner requires the following NUnit extensions to be installed: NUnit.Engine.Listeners.TeamCityEventListener. Please follow our instructions at: https://www.jetbrains.com/help/teamcity/?NUnit#NUnit-NUnit3Extensions

the link doesn't explain how to install this extension either

**Comment by CharliePoole** [comment]
Having reviewed the links provided by @ohnefuenfter, I have realized that the term "Legacy NUnit" means something different to JetBrains than it does to the NUnit team. Ignore my earlier comment about that. It also appears that "standard runner" may mean something else to the company than it does to me, so I'll stop using that term in this thread.

From this discussion so far, one thing is clear... the error message is being correctly displayed because the extension is not actually installed. So we have a different problem, which is probably related to the fact that the 3.19 release changed how extensions are located. See issue #1504.

A stated in the issue, `.addins` files are no longer needed as the runner searches for extensions in a set of standard locations using a built-in algorithm. In fact, any .addins files in the initial directory are now completely ignored. I can imagine that this will cause a problem in some special situations but I don't actually know how TeamCity is set up to use NUnit.

I suggest two steps to resolve this...

1. Somebody who is affected should create a new issue about the inability of TeamCity to locate the extension. It will help if you are able to explain exactly what steps are taken to install nunit into your TeamCity agent.

2. Somebody should also create an issue with JetBrains about this problem. It's possible they may need to make some changes and they may be the only folks who can tell us what changes we need to make.
