### ISSUE TITLE
Unexpected behaviour from --framework flag

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#151]
This isn't an option I've used before - so I think this is a bug, but can someone confirm what I'm expected is whats intended?

We just updated R#, and tests started failing. It appears the current resharper is forcing things to run under .NET 4.5, regardless of the framework specified - which is breaking some of our (questionable) tests.

To prove this was the case, I wanted to use `--framework=net-4.5` with the console runner, to force our tests which target .NET 4.0, to run on .NET 4.5. Surprisingly they passed. It looks like the 3.5 engine chooses the project's targeted .NET version, over what was specified on the command line.

The logs showed this:
```
16:55:36.477 Debug [ 1] RuntimeFrameworkService: Current framework is net-4.5
16:55:36.477 Debug [ 1] RuntimeFrameworkService: Requested framework is net-4.5
16:55:36.482 Debug [ 1] RuntimeFrameworkService: Assembly [redacted] uses version 4.0.30319
16:55:36.486 Debug [ 1] RuntimeFrameworkService: Test will use net-4.0 framework
```

I can debug this further, but before I do - am I expecting the right behaviour? If I specify a later framework than targeted on the command line, should the tests run under that?

**Comment by CharliePoole** [comment]
Yes, it should work.

There's a chance that you are using the 4.5 framework but the message is wrong. Can you add a test that works differently in the two? IIRC, there's one in the code somewhere involving the Uri class.

**Comment by ChrisMaddock** [comment]
Thanks Charlie.

Fairly sure this is what's happening, as different behaviour between .net 4.0 and 4.5 was how the issue came up. (Our version was `List.Sort()` subtleties.) Will dig further and take a look.

**Comment by ChrisMaddock** [comment]
Have tracked down the issue, currently, the assembly target is always used, unless unavailable, in which case the current framework is used. It looks like there was a refactor a few months ago which caused the issue, will see if I can improve the tests at the same time.

@CharliePoole - can you clarify what intended functionality is here? I'm guessing the order of priorities should be:

Command Line Specified -> Assembly target -> Current Framework

At the moment, it looks like it falls back 'silently', and only when the required framework is unavailable (and Assembly < Current?). Should it error, if you specify a framework that isn't available? Likewise, should it error, if the assembly target is greater than what's available? (I haven't checked what does happen in that situation yet.)

**Comment by CharliePoole** [comment]
If you specify a framework that's not available it should give an error long before it gets to the point of falling back. IIRC (I'm on my phone) it's in the console or the master test runner.

If the target framework is unavailable, we silently use a higher one but give an error if only lower ones are available.

**Comment by ChrisMaddock** [comment]
Thanks Charlie - you're right. I'd assumed it was all resolved in the same place, didn't know there was a validation stage before hand. Will work on something soon.
