### ISSUE TITLE
Remove some settings used by the engine

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#153]
The engine has a settings service, which is used by clients, primarily the Gui. It uses only four settings internally, as follows:
 * Options.InternalTraceLevel
 * Options.TestLoader.PrincipalPolicy
 * Options.TestLoader.SetPrincipalPolicy
 * Gui.RecentProjects.MaxFiles

I'm using this issue to review the above settings and to propose some changes. Proposal to follow.

**Comment by CharliePoole** [comment]
### Analysis and Proposals

#### Options.InternalTraceLevel
If this setting is present, it is used to initialize the internal trace level for the engine if it has not been set to a non-default value by the client software.

**Analysis:** The setting is redundant, since any client can turn on the trace. There seems to be no need for a default trace value other than Off. Removing it will simplify initialization, since the SettingsService will no longer have to be used before creating any other services.

**Action:** I am proposing to remove this setting and just leave the default at Off.

#### Options.TestLoader.PrincipalPolicy
#### Options.TestLoader.SetPrincipalPolicy.
These settings are used in DomainManager to set the principal policy for the domain.

**Analysis:** The Gui actually uses a different key (Engine.Options rather than Options.TestLoader) to create these settings. At a minimum we should change these settings in the engine to use the new key. However, the setting seems questionable in that it's unlikely that you would want __all__ tests to use a particular setting for PrincipalPolicy all the time. The console runner provides an option for setting it for a single run and  the gui can do the same.

**Action:** I propose to remove these settings and rely on the client for the rather small percentage of test runs that need them. I'd particularly like some feedback on this, since it's not a feature I use myself.

#### Gui.RecentProjects.MaxFiles
This setting is used to determine how many recent files will be retained in the settings.

**Analysis:** As evidenced by the name, this setting is used by the Gui to control how many recent files are listed in the menu. It is limited to a maximum of 24 files. As currently implemented, setting the number of files listed in the gui changes the number saved by the engine so it's not possible for different runners to use a different value.

**Action:** I propose that we eliminate use of this setting in the engine. It's much simpler if the engine always uses the maximum MaxFiles value of 24 and the gui simply reads as many of those as it wants. This will simplify the updating of the list of recent files when the user reduces the number to a value below what's already present and will probably resolve an outstanding bug we have. The setting would continue to exist, but would be used only by the Gui in deciding how many of the saved files to display in the menu.


@nunit/engine-team @nunit/core-team @nunit/gui-team 
Your review of the above is requested.

@nunit/gui-team 
There are many more settings used by the engine only. I'll be following up on them in a separate issue.

**Comment by CharliePoole** [comment]
@nunit/core-team I realize it's a really bad time to be looking for quick feedback, but this change has some interdependencies with the gui so I'm taking it out of design and starting to code a PR. If you see anything that looks like a bad idea here, please let me know.

**Comment by immeraufdemhund** [comment]
I agree with the proposed actions as stated.

**Comment by rprouse** [comment]
@CharliePoole do any of these changes require changes to existing runners or adapters?

**Comment by CharliePoole** [comment]
No, because they are settings that come from the nunit30settings.xml file.

However, upon looking at it, I want to check into SetPrincipalPolicy before dropping it. If the user had an old V2 setting, did we copy it into the V3 settings? I'm not sure but I'll check.

If we did copy it, then users may still be relying on it. If so, then getting rid of it requires a bit more planning - maybe deprecating its use for a release.

If it wasn't copied over, then removing it won't impact anybody.

In either case, I would add a command-line setting for it immediately. I just don't think it makes sense as a default setting.

I may do this as two PRs... the nobrainer stuff first, then this more weighty question.

**Comment by CharliePoole** [comment]
I refreshed my memory on use of settings. NUnit V2 supported three different layers of backward compatible settings. With 3.0, I decided on a clean break so the first time you run NUNit 3.x, you don't have any settings. The consequence for this issue is that none of the settings being removed from the code should ever be active and the code is non-functional.

There's a small chance that somebody would be effected if they manualy edited the XML in the NUnit30Settings.xml file, but that would require pretty deep knowledge of NUnit internals and I don't think we have to worry about it.

**Comment by immeraufdemhund** [comment]
a project long ago that I did I had a background thread that would only be spun up if a "find previous installations" flag was not set and it would search in all known locations of old installations of a program and gather the old settings, translate them to the new and delete the old. I also had a different one that I needed to wait for all settings to be updated first.. in that respect I put a blocking thread with a message to the user saying what I was doing. I know that NUnit is used in many different ways so this might not be as easy...but just throwing that out there.

**Comment by CharliePoole** [comment]
This is a bit simpler. NUnit V2 would start up and look for its settings file in a fixed per-user location. If it didn't find it, it would look for an older version to convert. If it didn't find that, it would check the registry, where the oldest settings had been installed. This never had to happen more than once, because the settings file would end up being populated so that the conversion code wasn't triggered any longer.

However, the NUnit 3 engine is an entirely new program. While there is some correspondence between the older settings and new ones we use, it's relatively minor. So it was simpler to just start with a clean slate, using a different settings file name and not making any attempt to find older settings. For users of the console runner, the impact is minor. For the gui, it's actually desirable, be cause a person may be running both the old gui and the new one and it would be a little confusing if they shared settings.

**Comment by CharliePoole** [comment]
@nunit/core-team Waiting for reviews. :smile:

**Comment by rprouse** [comment]
@CharliePoole  based on your comments, 👍

**Comment by CharliePoole** [comment]
@rprouse Have you looked at the PR as well?
