### ISSUE TITLE
Update Language Level to C# 12

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1540]
Required by #1539

**Comment by manfred-brands** [comment]
Any reason not to go to C# 12 as per .NET 8.0?

**Comment by CharliePoole** [comment]
No, it's just the level I'm working at in my other project. I see the framework is using 12, so I'll do it too.

FYI, in doing this I discovered that the build, which hasn't run for many months, no longer works for V4. Due to EOL events and other stuff. I'm doing a very messy fix to get it working again. Long-lived branches that aren't being worked on should probably be built on a schedule.
