### ISSUE TITLE
Replace 'dev' label used for development builds with 'alpha'

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1545]
@nunit/engine-team 

Whenever a build is merged to the main or version4 branch, the packages are published to our MyGet feed using the "dev" pre-release label. This presents a bit of a problem, since "dev" alphabetically follows "alpha" and "beta" but is intended to precede them logically.

This worked for a long time for two reasons: (1) we don't often use alpha and beta and (2) I have done a lot of behind-the-scenes pruning of builds, eliminating those that shouldn't be used. As we start work on V4, I suspect it will become more of a problem. In fact, that has already happened in my other project, when I was doing alpha and beta builds.

So... I think these automatic package releases should either _be_  alpha builds or use something that precedes "alpha" alphabetically. In the latter case, I have thought of using "adev", "adv" (advance), "adb" (advance dev build) or something similar.

What do you think? If we use alpha, then of course we would go directly to beta when we are ready. Is that a problem?

BTW at the same time, I expect to go to the correct semver 2.0 format, i.e. alpha.1 rather than alpha1 or alpha-1.

**Comment by manfred-brands** [comment]
I'm fine with using `alpha` as development builds. It indicates being neither necessary stable nor necessary fixed in API definitions.

**Comment by OsirisTerje** [comment]
alpha is fine :-)

**Comment by stevenaw** [comment]
I'm also used to the idea of using `alpha` for "nightly" or "development" builds.

**Comment by CharliePoole** [comment]
I'll go with alpha then. For version 3, I'll time the change for right after the 3.19 release. For version 4, I'll do it as soon as I get the recipe working so I won't have to change it twice.
