### ISSUE TITLE
StopOnError command argument should have option to determine how many errors to have before stop

### ISSUE THREAD

**Issue by SH2015** [nunit/nunit-console#169]
Sometimes the build need to be marked as bad or unstable after _n_ number of errors , if we can add option to write for example /stopaterror-number=20 so that mean if 20 tests failed then the test will stop and save resources. 
I am ready to contribute to implement this feature

**Comment by JustinRChou** [comment]
It is an interesting idea.
But isn't it better for you to run all your tests to see all the failures?
I am comparing this to looking at compilation errors and I don't think there is an option to stop compiling after a number of errors.
And I don't know about how much resource could you save unless you are using a testing service to run a bunch of tests across different assemblies.
This could be useful for the test server if it gets implemented.

**Comment by SH2015** [comment]
Most of the times x number of failed tests is enough to let the agent stop, as there is always limited number of agents. 
If that is alot to be added can we let addons events have cancelation token so they can analyze the results and send cancelation token with the event argument ? 
There should be a way to stop the console without killing the process so the test results will not be lost as they only generated at the end of test .

**Comment by CharliePoole** [comment]
I'm not keen on this feature idea. @rprouse What are your thoughts?

**Comment by ChrisMaddock** [comment]
@nunit/engine-team - if @SH2015 is willing to contribute this, let's have the discussion as to whether we think it's a good idea or not. 😄 

@SH2015 - Can you explain why you want this, rather than the existing `--stoponerror`? I can understand wanting to fail as soon as any test fails, and I can understand wanting to run all tests and list all failures. I'm struggling to see the use-case for a middle-ground, listing only some of the failures.

> If that is alot to be added can we let addons events have cancelation token so they can analyze the results and send cancelation token with the event argument ?

If this is feasible, I think allowing test cancellation via add-in is potentially a more generally applicable feature.

**Comment by CharliePoole** [comment]
@ChrisMaddock Yes, that was the idea when I moved it to discussion. Perhaps I should use my words. :smile:

Perhaps we can figure out some way to allow extensions to cancel. @SH2015 Can you expand a bit as to what you had in mind? Are you talking about an engine extension implementing ITestEventListener? You would have to allow for several things with that approach...

1. The events are entirely asynchronous, so the tests would keep running. Generally, a cancellation token only works in a synchronous event - at least as far a I know.

2. The event handlers do not currently have access to the engine to allow actually doing anything like cancelling the run. We would have to do an API change. More important, the events are __designed__ with the intent that they should not be able to influence the running of the tests. It would be a pretty big deal to change that objective.

3. How would you parameterize the event handler to know how many test failures should trigger cancellation? There isn't really a mechanism.

All of the above lead me to conclude that __if__ we wanted to implement this sort of thing, it would require an entirely new extension point in the engine built solely for the purpose of allowing automatic test cancellation. It would likely have to include a newly designed mechanism for extending the runner, as well as the engine!

In fact, this would be an order of magnitude easier to build into the runner itself, if we wanted to support it. I'm still not sure we do. 😞

**Comment by ChrisMaddock** [comment]
Closing this, as the discussion tailed off. @SH2015 - if you have more to add, we can reopen.

**Comment by warpech** [comment]
> I am comparing this to looking at compilation errors and I don't think there is an option to stop compiling after a number of errors.

Compilers definitely have such options, for example `-fmax-errors` in GCC: http://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
