### ISSUE TITLE
DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified() fails when not 3 directories deep

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#17]
@rprouse commented on [Tue Dec 01 2015](https://github.com/nunit/nunit/issues/1105)

Found while testing the 3.0.1 release. The 'fix' for this unit test bb2e37b2 doesn't work if the test is not at least 3 directories deep. The code is correct but the test is not, so I am not going to delay the release for this.

---

@rprouse commented on [Tue Dec 01 2015](https://github.com/nunit/nunit/issues/1105#issuecomment-161168821)

To elaborate a bit, I ran these tests with the command line `.\nunit3-console.exe .\nunit.engine.tests.dll`

If the tests are three directories deep, they pass, if not, they fail with the error 

```
1) Error : NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified() in D:\src\nunit\nunit\src\NUnitEngine\nunit.engine.tests\Services\DomainManagerTests.cs:line 74
```

If it is one level deep (in d:\tmp) or 

```
1) Failed : NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified
  PrivateBinPath
  Expected: Path matching "mp\nunit"
  But was:  "tmp\nunit"
at NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified()
```

if it is two levels deep (d:\tmp\nunit)

---

@CharliePoole commented on [Tue Dec 01 2015](https://github.com/nunit/nunit/issues/1105#issuecomment-161179451)

You know, I knew that was there and figured I would get back to it. It's best to record such things.

**Comment by rprouse** [comment]
From nunit/nunit#1618

```C#
1) Failed : NUnit.Engine.Internal.Tests.DirectoryFinderTests.GetFiles("addins/**/*.dll",17)
  Expected: 17
  But was:  14
at NUnit.Engine.Internal.Tests.DirectoryFinderTests.GetFiles(String pattern, Int32 count)
```

**Comment by CharliePoole** [comment]
Fixed this by eliminating reliance on actual install paths and using a dummy (non-existent) path.
