### ISSUE TITLE
Refactor RuntimeFramework to ensure thread-safety

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#173]
This came up in debugging https://github.com/nunit/nunit-console/issues/168. The inline code comment covers everything, I think.

> //RuntimeFramework was originally created for use in
        // a single-threaded environment. The introduction of parallel
        // execution and especially parallel loading of tests has
        // exposed some weaknesses.
        //
        // Ideally, we should remove all knowledge of the environment
        // from RuntimeFramework. An instance of RuntimeFramework does
        // not need to know, for example, if it is available on the 
        // current system. In the present architecture, that's really
        // the job of the RuntimeFrameworkService. Other functions
        // may actually belong in TestAgency.
        //
        // All the static properties of RuntimeFrameowork need to be
        // examined for thread-safety, particularly CurrentFramework
        // and AvailableFrameworks. The latter caused a problem with
        // parallel loading, which has been fixed for now through a
        // hack added to RuntimeFrameworkService. We may be able to
        // move all this functionality to services, eliminating the
        // use of public static properties here.

ToDo:
- [ ] CurrentFramework
- [x] AvailableFrameworks Interface for GUI dependency
- [ ] AvailableFrameworks
- [ ] MonoVersion/MonoPrefix/MonoExePath (which relate to available versions of mono, not the mono the current RuntimeFramework object represents)
- [ ] GetBestAvailableFramework()

**Comment by ChrisMaddock** [comment]
I've started work on this. RuntimeFramework is a big class, so as well as moving some properties to RuntimeFrameworkService, I also want to move some content out to utility classes. Hopefully then, RuntimeFramework will just end up holding the details of a single framework.

I'm aiming to move the following to instead be accessible via RuntimeFrameworkService:
- CurrentFramework (Plus framework-locating utility class)
- AvailableFrameworks (Plus framework-locating utility classes)
- MonoVersion/MonoPrefix/MonoExePath
- GetBestAvailableFramework

All of this is currently public - but I think it should mostly be internal, excluding CurrentFramework/AvailableFrameworks, which could expose a (enumerable of) IRuntimeFrameworks via the RuntimeFrameworkService. This would potentially be a breaking change for any runners referencing the engine directly. @nunit/gui-team - does the GUI use any of these classes?

@nunit/engine-team - Are we happy with this these (breaking) changes, and in general? My personal thought is that getting the architecture right takes priority here.

**Comment by ChrisMaddock** [comment]
(Moving the now deleted comment to a PR, to keep discussion in one place.)

**Comment by CharliePoole** [comment]
Closing this as obsolete wrt the new codebase. See issue #1168
