### ISSUE TITLE
[Teamcity] Broken characters encoding in tests result output.

### ISSUE THREAD

**Issue by cezarypiatek** [nunit/nunit-console#176]
After migrating our tests from NUnit 2.5.3 to NUnit 3.6 Teamcity starts to display test results with invalid characters set. Sometimes we are using polish characters in test names and until now everything was displayed correctly. For example

previously:
```plaintext
LeaseProductAdditionalRepositoryTest.da_się_przefiltrować_produkty_dodatkowe_po_nazwie 
```
now:
```plaintext
LeaseProductAdditionalRepositoryTest.da_si©_przefiltrowa†_produkty_dodatkowe_po_nazwie 
```

We are using TeamCity 9.1.1 and Nunit3-Console (v3.6)
How to setup correct chars encoding (UTF-8) ?

**Comment by s-tarasov** [comment]
Same problem with test output
`
[Functional.Tests.Web.TestRegistrationFromMain] [Test Output]
���� ॣ����樨 � ����� ������� ��࠭���
��稭��� ॣ������ ���짮��⥫�: TempToDeleteAutoCreation9557493@example.ru � ��஫��: 1234567890
��������� �����襭�
������ ���� ஦����� �� ��뫢��饬 ����
���� ���� ஦����� �����襭
���室�� �� ��࠭��� � १ � �஢��塞 ���� �� ��⨢���

`
We are using TeamCity 10.0.1 and Nunit3-Console (v3.6)

**Comment by rprouse** [comment]
I expect that this may be an issue with the TeamCity event listener that JetBrains wrote for NUnit 3. @NikolayPianikov can you confirm so that we can move this issue to your repo?

**Comment by NikolayPianikov** [comment]
@rprouse yes, please move

**Comment by rprouse** [comment]
Issue moved to [nunit/teamcity-event-listener #36](https://github.com/nunit/teamcity-event-listener/issues/36) via [**ZenHub**](https://www.zenhub.com/)
