### ISSUE TITLE
Add date and time to console output

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#178]
While working on NUnit, I repeatedly run the console tests. Sometimes, especially if I need to interrupt my work for a few minutes, I can't remember if the last run displayed uses the most recent compile or not. If the header display had a third line with the date and time, it would be easier to tell.

The output would use the local time and culture for display and could look like this...

```
NUnit Console Runner 3.7.0
Copyright (C) 2017 Charlie Poole
February 11, 2017 5:26PM
```

If we agree that this change should be made, I'll duplicate it for NUnitLite as well.

@nunit/core-team @nunit/engine-team @nunit/framework-team What do you think?

**Comment by oznetmaster** [comment]
Seems like a good idea good to me.

**Comment by ChrisMaddock** [comment]
I have the same problem - but normally look at the test run start/end time for this. But I don't see the harm in displaying it more noticeably.

**Comment by jnm2** [comment]
I like it.

**Comment by CharliePoole** [comment]
@ChrisMaddock You're right! I forgot about those times, because I'm working on something that hangs the test run, so I don't see them. I'll add the extra date in my current working branch and we can decide whether to keep it when I do the PR. I guess I should use the same format as that used in the summary.

**Comment by mikkelbu** [comment]
@CharliePoole Should we mark this issue with "Help Wanted" + "Good first issue" labels? I guess that the change to solve this issue is quite small.

**Comment by CharliePoole** [comment]
@mikkelbu I agree, it should be quite easy.

**Comment by abborg** [comment]
I would like to pick up and work on this issue. In my local changes, I am using the localized full datetime pattern but I see the value in keeping it consistent in the result report. I am open to suggestions from the team if there is a preferred format.

How the header currently looks on my local changes: 
```
NUnit Console Runner 3.10.0 (Debug)
Copyright (c) 2018 Charlie Poole, Rob Prouse
Friday, October 12, 2018 1:10:34 AM
```
