### ISSUE TITLE
XSLT Transform not honoring --encoding value

### ISSUE THREAD

**Issue by KenHundley** [nunit/nunit-console#181]
Hello,

I'm running into an issue with the junit transform process (needed for Jenkins) in NUnit console v3.6.0

If I omit the transform command the output xml is properly encoded with UTF-8 when --encoding=utf-8 is supplied.  However, if I add back the transform command the output is encoded as ASCII, which won't work for my current test output.

I believe the issue is related to this line:
```C#
public class XmlTransformResultWriter : IResultWriter
{
    public void WriteResultFile(XmlNode result, string outputPath)
    {
        using (var xmlWriter = new XmlTextWriter(outputPath, Encoding.Default))
        {
            xmlWriter.Formatting = Formatting.Indented;
            _transform.Transform(result, xmlWriter);
        }
    }
}
```
and the element "Encoding.Default"

I believe this should be changed to derive the encoding from the supplied encoding argument instead of being hard coded with Default.

I don't mind attempting to fix this if needed, but it's such a small change I wasn't sure that was needed.

Thanks,
Ken

**Comment by KenHundley** [comment]
I also saw a similar line in NUnit3XmlResultWriter

**Comment by CharliePoole** [comment]
First of all, we'd be glad if you want to submit a PR to fix this. As small as it is, there will always be a PR that we review before merging, even if one of the NUnit team fixes it. That's just how we work.

I'll have to review the code but I thought we added the --encoding option to affect the console display of messages, not the creation of the XML. I'd like to be sure we are explaining it correctly in the docs and that we make it work the way we intend. That said, it would be a bit complicated, and maybe unnecessary, to have a separate Encoding set for each file we create. I'll mark this as in design so we can clarify how we want it to work. 

@nunit/engine-team @nunit/core-team  Let's decide as quickly as possible.

**Comment by jnm2** [comment]
For compatibility reasons I vote that any text file and especially XML is always output as UTF-8 with no BOM.

(This also is the default when no encoding is specified in the `StreamWriter` constructor.)

**Comment by KenHundley** [comment]
Actually you're correct. The NUnit xml is UTF-8 regardless of the --encoding value, it only changes to ASCII after the transform is run.

I will take a look at it this weekend and submit a fix. What would you like to happen? Should the transform always produce UTF-8?

**Comment by KenHundley** [comment]
UTF-8 it is

**Comment by jnm2** [comment]
I also strongly suggest using `XmlWriter.Create(Stream)` rather than using the particular constructor.

**Comment by CharliePoole** [comment]
Let's make the XML files all be UTF-8.

As far as how to code it, @jnm2's suggestion is good so long as it works on all platforms. I have a suspicion we might be doing it how we do because of some particular platform. But if the CI passes on Windows, Linux and IoS for all the runtimes we support, we're cool!
