### ISSUE TITLE
Add option to force color output

### ISSUE THREAD

**Issue by vmuriart** [nunit/nunit-console#182]
AppVeyor seems to do some trickery for their console/build log that results on NUnit-console not detect its running from a console, and thus strips out all color information from the output.

`pytest` had the [same issue](http://stackoverflow.com/questions/17069007/how-do-i-force-pytest-to-write-color-output) and resolved it by adding an option to force the use of color regardless of whether the console was detected or not.

Would it be possible to implement a similar solution for NUnit?

Edit: Link to related AppVeyor ticket. http://help.appveyor.com/discussions/problems/6121-ansi-color-codes-nunit3-consoleexe

**Comment by CharliePoole** [comment]
It's a nice idea, but it may not be possible because of how NUnit does color. Needs research.

**Comment by vmuriart** [comment]
I did some research I'll expand a bit more below, but basically there doesn't seem to be *neat* a solution available for `.net`. I'm closing the issue (though feel free to reopen if you want to look more into it 😄 )

[NUnit Console](https://github.com/nunit/nunit-console/blob/96f4d48c613add6e5218bc056f69e412a2c4c24b/src/NUnitConsole/nunit3-console/ColorConsole.cs#L39) writes to the console using `System.Console` and uses the color options available there. AppVeyor seem to redirect the console to a file which in-turn causes `System.Console` to disable colors automatically and no way force the ANSI code to be kept. (that I found atleast).

I found a [project](https://github.com/edokan/Edokan.KaiZen.Colors) that takes a different approach by parsing the ANSI codes directly into the strings to be output and writing that directly. It worked locally, but not on [AppVeyor](https://ci.appveyor.com/project/vmuriart/edokan-kaizen-colors/build/1.0.1).

The only success I had was by using one of my python projects to load up the my `dll` library and it produced the [correct output](https://ci.appveyor.com/project/vmuriart/pythonnet/build/develop-1830/job/qq01vyejyt69t7c3#L105) for `Console.WriteLine("\x1b[36mTEST\x1b[0m");`. When loading the same library directly, it [didn't work](https://ci.appveyor.com/project/vmuriart/pythonnet/build/develop-1830/job/qq01vyejyt69t7c3#L181). I didn't look further into this though.

Other Resources:
http://stackoverflow.com/a/34078058/5208670
https://www.codeproject.com/Articles/24753/Using-ANSI-Colors-within-NET

**Comment by ilanthendral** [comment]
Using PowerShell, Run MSBuild With Custom Color.ps1

msbuild C:\some_path\your.sln | foreach-object -process  { 
    switch ($_){
        { $_.tolower().contains("warning")} {Write-Host $_ -foregroundColor DarkBlue}
        { $_.tolower().contains("error")} {Write-Host $_ -foregroundColor DarkRed}  
        default {Write-Host $_ -foregroundColor Black}
    }
}
