### ISSUE TITLE
NUnit Engine + AppDomain question

### ISSUE THREAD

**Issue by domtheluck** [nunit/nunit-console#184]
Hi everyone,

I trying to integrate the NUnit engine into a console application. I already realized that I still need the agent to be able to run test.

The fact that the agent seems to run in it own AppDomain cause me issues because I want to be able to easily debug my stuff without attaching to the agent process everytime so my question is:

Is it possible to instantiate the engine and run it inside the same app domain as the caller (here the console app)?

Here is my code:

ITestEngine testEngine = TestEngineActivator.CreateInstance();
TestPackage testPackage = NUnitEngineHelper.CreateTestPackage(new List<string> { assemblyPath });
TestFilter testFilter = NUnitEngineHelper.CreateTestFilter(_assembly, feature);
ITestRunner testRunner = _testEngine.GetRunner(testPackage);

testRunner.Run(.......)

I didn't find anything related to this kind of option in the official documentation.

Thanks in advance

**Comment by CharliePoole** [comment]
The engine is instantiated in the primary AppDomain. The tests are run in a separate AppDomain, so as not to corrupt the AppDomain used by the console and engine.

Depending on the settings in your TestPackage, the tests may be run in a separate process, which requires the agent executable to be present. If you don't want that to happen, then you should provide settings in the package to indicate that you want to run in process.

We don't have your helper class here, so it's not clear what it does to create TestPackages, but it sounds like you are allowing it to default to running each test assembly in its own process. If you set the property "ProcessModel" to "InProcess" it will run tests in process. For an example of how the console runner translates its own command-line options to settings in the package see https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L363

**Comment by domtheluck** [comment]
Hi Charlie and thanks for the quick answer.

I tried to set the ProcessModel property to "InProcess" and it works perfectly :)

Great job with NUnit 3 by the way!
