### ISSUE TITLE
NUnit dejo de funcionar 

### ISSUE THREAD

**Issue by vimuriel** [nunit/nunit-console#192]
NUnit.exe se ejecutaba bien, pero ya no ejecuta ocurre un error que indica

"NUnit.exe dejeo de funcionar" 

Versión NUnit-2.6.4

**Comment by rprouse** [comment]
We will need more information to help you with this. Does the process crash with any unit tests, or just specific unit tests? What command line options are you using?

**Comment by ChrisMaddock** [comment]
I'm closing this as not having enough information to work with. Happy to help if you can provide more details, @vimuriel.
