### ISSUE TITLE
Allow comments in @FILE files

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#196]
@somatronicon commented on [Mon Mar 13 2017](https://github.com/nunit/nunit/issues/2080)

In the @FILE files, allow comments. These files could get pretty complex, and having the ability to add comments would be beneficial. Maybe if a line starts with # it's interpreted as a comment? Not sure, just throwing out ideas.

```
# Black list specific tests we don't want to run
--where "method != /.*_(Blah|Blah2|Blah3)$/"
```

Great project by the way :+1: 

---

@JustinRChou commented on [Mon Mar 13 2017](https://github.com/nunit/nunit/issues/2080#issuecomment-286280536)

@CharliePoole 
Is this really a easy fix and wouldn't this involve updating the console runner and the lite runner?

And this is probably extra work but would it make sense to write the comment into the TestResult.xml?

---

@CharliePoole commented on [Mon Mar 13 2017](https://github.com/nunit/nunit/issues/2080#issuecomment-286295357)

I was thinking of this as a console issue but you're right that it applies to NUnitLite as well.

In the console, it's extremely easy to just ignore a full line starting with # - looks like a change of one line. Doing more is possible, but difficult since the individual line can contain # (or any other characters) in quotes. The format was designed to be simple and we probably shouldn't complicate it, since that would require a redesign without a clear benefit.

The NUnitLite implementation is entirely different and treats the entire file as a single string. That looks like an easyfix as well, but more than a single line.

I'll duplicate this under the console as well.

**Comment by somatronicon** [comment]
Awesome, thanks!
