### ISSUE TITLE
Implement Addin model for extensions

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#20]
@CharliePoole commented on [Wed Aug 26 2015](https://github.com/nunit/nunit/issues/792)

The spec for Engine Addins identifies a model for more complex extensions that uses a Type derived from IAddin to actively create and register extensions, similarly to what we did in NUnit V2 addins.

We should investigate whether this is actually needed and, if so, implement it in a future release. If it isn't needed, we may identify further features that serve the same purpose of allowing the creation of more complex extensions or sets of extensions.

**Comment by ChrisMaddock** [comment]
Hi Charlie,

I'd like to close this issue. I think it was an interesting feature when first spec'd out - but 5+ years on, it hasn't garnered a lot of attention, and I personally can't think of any barriers we've yet come across that this functionality would have solved.

Do you have any objection there? If this is something you'd personally be interested in contributing, I'd be happy to discuss it further, but I don't want the issue to sit here gathering dust. 🙂

**Comment by CharliePoole** [comment]
@ChrisMaddock That's OK with me...

Sending a note offline about the general topic of directions I had once (i.e. 5+ years back) wanted to take the engine and how I suggest you handle them.

**Comment by ChrisMaddock** [comment]
Thanks Charlie. 👍
