### ISSUE TITLE
Create Chocolatey package(s) for the console

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#207]
This arises from discussion in nunit/nunit#452

We need to decide whether we want separate packages with and without extensions and which extensions should be supported in the packaging.

**Comment by ChrisMaddock** [comment]
My ideal world would be that our choco packages exactly mirror out NuGet packages. That being we have ConsoleRunner (alone), all extensions individually (which Choco could install in place), and then NUnit.Console as the full package.


That said, that would also be the most time consuming version! I'd be happy with just the NUnit.Console (console + core extensions) - if we decided it wasn't worth the time of creating all the packages.

Either way, I'd want there to be a console + extensions package. That's our most popular NuGet package - and the Choco package I personally need!

**Comment by Roemer** [comment]
Since I actually need this version (the previous one gives Stackoverflow Exceptions when used with OpenCover), I quickly created the chocolatey package and sent it to review: https://chocolatey.org/packages/nunit-console.portable/3.6.1
As soon as you want to take over, feel free to inform me and I will hand the package over to you.

**Comment by CharliePoole** [comment]
@ChrisMaddock I hadn't seen your earlier comment. I planned to do it just as you stated. I don't use zips for my chocolatey packages. Rather, I create a custom nuget package that is intended for use on chocolatey only. As you see it's on my list of things to finish before I leave - I just haven't gotten to it yet.

If you or Rob prefer to take it over sooner, rather than later, we would need to get you known to the chocolatey folks, otherwise you have to go through moderation each time you upload. However, my plan was to get it out with 3.7.

Personally, if I were going to continue with the engine/console project, I would be working to get rid of that "combined" package. It's convenient for users, but it raises the question of which extensions to include. IMO, we have one too many right now. Can users deal with the change if we stop including a particular extensions? I don't know.

@Roemer I kind of wish you had instead volunteered to take over this task instead. Then your package could be reviewed by us and we could decide what we want in it. Official NUnit packages also go live immediately without moderation.

Reviewing your package, I see that it uses the technology that Chocolatey supports for quickly getting packages out without involving the authors of the software. That is, your package a ps1 file that simply downloads a zip from our site. I spent time working with folks to figure out how chocolatey can best be used when the maintainer is also the author of the software. In that case, enhanced nuget packages that directly contain the software itself have a lot of advantages. That's how I did the first experimental package I produced (the project editor) and it works quite well.

Beyond the technology, my concern about the content of the  package (see above) is not a deal-breaker. After all, it's a problem we already have with the zip and msi.

**Comment by Roemer** [comment]
@CharliePoole I see your points and for my software, I also add the binaries directly into the chocolatey package. This was just to have something quickly. The next version (3.7?) can include the binaries as requested.
As a start, it's probably ok to have almost a copy of https://github.com/nunit/nunit-console/blob/master/nuget/runners/nunit.console-runner.nuspec (in a choco folder?) and creating this package in cake with ChocolateyPack. That would be something I could do as a PR as a start.

**Comment by CharliePoole** [comment]
I'd love to see it a PR. As you may have noticed in my comment earlier, I have a long list of things to finish as I phase away from the NUnit project. It's to my advantage if somebody else does some of them. And yet, being human, I want to see them done in a certain way. :smile:

Take a look at the package for the [project editor](https://github.com/nunit/nunit-project-editor/blob/master/nunit-project-editor.nuspec) and see if it is similar to the approach you are talking about.

**Comment by Roemer** [comment]
I hacked something together, see PR #234 . It only creates one choco with addins.

**Comment by CharliePoole** [comment]
Pulled @Roemer 's changes into a new branch, issue-207. Testing locally.

**Comment by Roemer** [comment]
@CharliePoole Should I adjust now something more or is it ok as a first version?

**Comment by CharliePoole** [comment]
I made changes in #207. Take a look and we can discuss more there.

**Comment by CharliePoole** [comment]
@Roemer There has been no feedback from anyone else so I think we should decide what to do. I'm inclined to try for a combined package that does not actually include any code but references subpackages. That's the nuget way and also the chocolatey way.
