### ISSUE TITLE
Master build failing after merging .NET Standard Engine

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#213]
Not sure why the PR builds pass, but the master build is now failing, but the copying of the .NET Standard nuget package is failing.

The package that is created is,

```
src\NUnitEngine\nunit.engine.netstandard\bin\Release\nunit.engine.netstandard.3.7.0-alpha1.nupkg
```

The package that is being copied is,

```
src/NUnitEngine/nunit.engine.netstandard/bin/Release/nunit.engine.netstandard.3.7-alpha1.nupkg
```

Notice one is 3.7.0, but the other is just 3.7.

**Comment by jnm2** [comment]
Is this why?

https://github.com/nunit/nunit-console/blob/master/build.cake#L109

**Comment by CharliePoole** [comment]
We've always built releases, including alphas, locally. If you are tagging and trying to build a release through CI you're doing something new. I tried it myself not too long ago and ran into problems as well.

**Comment by rprouse** [comment]
@jnm2 that might be the cause, although master isn't tagged. Everything else is also building 3.7.0, so I am not sure. I think for now, I will remove the `alpha1` as I don't think it should be in master, just in any release branches that we are building.

**Comment by rprouse** [comment]
@jnm2 I expect you are right and that this will clear itself up once we merge the next change to master, but I don't want this to happen again after another release. Also, as @CharliePoole says, we are currently not building for release using tags and AppVeyor, so I am going to remove the tag code from `build.cake`.
