### ISSUE TITLE
Tests (with Ignored) executed, but exit code -1

### ISSUE THREAD

**Issue by sm-g** [nunit/nunit-console#215]
Given project

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="RunNUnit">
  <ItemGroup>
    <TestAssemblies Include="**\bin\release\Test.dll" />
    <TestAssemblies Include="**\bin\release\Test2.dll" />
  </ItemGroup>

  <PropertyGroup>
    <PathToNUnitDir Condition="$(PathToNUnitDir) == ''">.build\nunit</PathToNUnitDir>
    <NUnitVersion Condition="$(NUnitVersion) == ''">3.6.1</NUnitVersion>
  </PropertyGroup>

  <Target Name="RunNUnit">
    <PropertyGroup>
      <NUnitConsoleName Condition="$(NUnitConsoleName) == ''">nunit3-console.exe</NUnitConsoleName>
    </PropertyGroup>
    <ItemGroup>
      <NunitConsoleExe Include="$(PathToNUnitDir)\**\$(NUnitConsoleName)" />
    </ItemGroup>

    <Exec IgnoreExitCode="True" Command="@(NunitConsoleExe) @(TestAssemblies, ' ') --noheader">
      <Output TaskParameter="ExitCode" ItemName="exitCode" />
    </Exec>
    <Error Text="Error while running tests: @(exitCode)" Condition="@(exitCode) &lt; 0" />
  </Target>
</Project>
```

launched with msbuild 15. Output ended with

> Test Run Summary
>    Overall result: Warning
>    Test Count: 1096, Passed: 1037, Failed: 0, Warnings: 0, Inconclusive: 0, Sk
>  ipped: 59
>      Skipped Tests - Ignored: 59, Explicit: 0, Other: 0
>    Start time: 2017-05-02 15:15:40Z
>      End time: 2017-05-02 15:16:02Z
>      Duration: 22.513 seconds
> 
>  Results (nunit3) saved as TestResult.xml
>  Выход из команды ".build\nunit\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console
>  .exe src\Test\bin\Release\Test.dll src\Test2\bin\Release\Test2.dll --noheader"
>  с кодом -1.
> :\xxx\runtests.proj(43,5): error : Error while running tests: -1

But when I remove `[Ignore()]`ed tests, exit code is 0.

**Comment by CharliePoole** [comment]
Your test run is executing correctly and returning what appears to be the correct test result - assuming that the numbers are what you expect. From the message, it appears that nunit3-console is saving the test result correctly - can you verify that?

After saving the result, it seems as if some error is occurring in the console runner. It's possible that we will see more info if you run nunit3-console from the command-line rather than through msbuild.

**Comment by CharliePoole** [comment]
BTW, what version of the framework are you using?

**Comment by sm-g** [comment]
Yes, results file saved. 
I ran nunit3-console with arguments exactly as msbuild outputed and after that `%ErrorLevel%` is 0.

ImageTargetFrameworkName: .NETFramework,Version=v4.6.1

I try to add `ContinueOnError="true" ` to `<Exec ...` but result is same.

**Comment by CharliePoole** [comment]
Sorry, I meant what version of the NUnit Framework.

**Comment by sm-g** [comment]
NUnit installed with `nuget install NUnit.Console -version 3.6.1`


I found reason: I do `Console.WriteLine($"{loglevel.ToString().ToUpperInvariant()}...")`, it is outputed as 
`ERROR:: rest` (from nunit3-console.exe), but when run from mbuilds same test writes: `EXEC : warning : : rest`.

Solution: `Console.WriteLine($"{loglevel.ToString().ToUpperInvariant().Replace("ERROR", "EROR")}...")`

**Comment by CharliePoole** [comment]
@sm-g The NUnit Framework is entirely separate from NUnit.Console. The framework is the nunit assembly that contains assertions, attributes, etc. and is referenced by your test. However, based on your comment about ERROR/EROR, that's probably not important. 

I think it's very strange that the simple presence of the word "ERROR" in the output causes the failure! It sounds as if MSBUILD is making the check for that string.

**Comment by jnm2** [comment]
> I think it's very strange that the simple presence of the word "ERROR" in the output causes the failure! It sounds as if MSBUILD is making the check for that string.

Cause for `TERROR` 😆

**Comment by rprouse** [comment]
NUnit console returns -1 for invalid command line arguments. I also tried running tests with ignores using the console and it returns 0. Based on your discoveries, it looks like MSBuild is wrapping the execution of NUnit console and changing the return code if it sees error in the output.

Based on that, it sounds like this isn't our bug. Should we close this issue?

Here is my test run,

```
Test Run Summary
  Overall result: Warning
  Test Count: 69, Passed: 58, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 11
    Skipped Tests - Ignored: 9, Explicit: 2, Other: 0
  Start time: 2017-05-03 02:55:53Z
    End time: 2017-05-03 02:55:59Z
    Duration: 6.149 seconds

Results (nunit3) saved as TestResult.xml

C:\src\NUnit\nunit-console\bin\Debug (master)
λ echo %errorlevel%
0
```

**Comment by sm-g** [comment]
@rprouse Yes, it is obviously msbuild related. Sorry for the incorrect statement about `[Ignore]`, I commented running tests then also.
