### ISSUE TITLE
NUnit .NET Standard NuGet package missing some values

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#217]
The .NET Standard nuget package is created from the CSPROJ file. Not all values that we set in the main nuget package are currently set.

**Comment by CharliePoole** [comment]
Should we be creating packages in two different ways, even if it's possible?

**Comment by rprouse** [comment]
I agree because it goes against my keep it simple principal, but it is also nice because it automatically handles package dependencies and always gets the target directories right, so you don't have to change things in multiple places.
