### ISSUE TITLE
Move Distribution back into the nunit-console project.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#218]
As discussed in nunit/governance#1

**Comment by ChrisMaddock** [comment]
This is in progress but blocked in two ways:

1. This failing build - currently passing on Windows, but failing on Linux. Possibly resolved with Cake post-v20, which I believe uses the Roslyn engine on all platforms.
https://travis-ci.org/nunit/nunit-console/jobs/259537651

2. This issue, encountered on upgrading our Cake Script from v19 -> v20 https://github.com/cake-build/cake/issues/1713

**Comment by ChrisMaddock** [comment]
Ah - I found a better source. Looks like this is blocked until Cake v0.22.

https://github.com/Redth/Cake.ExtendedNuGet/issues/15

**Comment by CharliePoole** [comment]
I'm not clear why we need anything beyond basic nuget. That's all I used to generate chocolatey packages out of nuget packages.

**Comment by ChrisMaddock** [comment]
For the components.txt file, which reads the description from the packages.

**Comment by CharliePoole** [comment]
I see. Could you temporarily leave that out? Or is it a better use of time to wait for a fix?

**Comment by ChrisMaddock** [comment]
In my opinion, it's worth waiting. There's no time pressure on this issue at all, as far as I'm aware.

The current version also works with the --experimental flag.

**Comment by skovsende** [comment]
Cake.ExtendedNuGet has now been updated to support Cake 0.22.2, so you should be able to continue now.
