### ISSUE TITLE
Engine modifies TestPackage

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#22]
@CharliePoole commented on [Thu Jan 07 2016](https://github.com/nunit/nunit/issues/1177)

In some situations, when project files are in use, the engine modifies any test package provided to it. This can cause unexpected side effects for the runner calling into the engine. See nunit/nunit-gui#69 for example.

We should review the code and, if possible, avoid modifying the original copy of a test package provided to the engine.

**Comment by ChrisMaddock** [comment]
@CharliePoole Would you say this was still an issue?

The engine modifying the TestPackage to expand projects seems to be a fairly fundamental principle of the (current) design. I'd say that a runner should not expect a 'used' TestPackage to remain unmodified - and we should instead handle the problem you saw through our implementation of Reload - which I think ties in to what you're currently looking at.

Would you agree?

**Comment by CharliePoole** [comment]
What bothered me most was that we modify the argument in the constructor for the TestEngine. It seems easier to explain modification as a result of Load.

However, we would also need to move the creation of the tree of engine runners to the load in order to do this. I think I woud lean toward doing that first.

Having the engine runners __all__ created on Load would be more uniform. Currently, runners in a separate process and runners under a non-specific AggregatingTestRunner are created at load, while the top-level engine runner used by the master runner are created when the master is created. This exception has caused me some problems in the past and the delayed construction would be clearer, I think.

**Comment by ChrisMaddock** [comment]
Fair enough, thanks for clarifying. 🙂
