### ISSUE TITLE
Update --labels switch with option to show real-time pass/fail results in console runner

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#24]
@dybs commented on [Fri Aug 12 2016](https://github.com/nunit/nunit/issues/1738)

When running a large number of test cases, it would be nice to see the pass/fail status of each case in the console as it completes.  Using --labels=All, I can see which tests have run, but the results are not available until all cases have completed.  Seeing which cases fail during a long scenario would allow me to investigate the failures while the remaining tests continue to run.  It also has the advantage of knowing which cases passed/failed if the test scenario happens to crash and doesn't get to write the result file.

Per the discussion in #1735 some ideas are to modify --labels with the following options:
- Results -> same behavior as =All, but includes a Pass/Fail/Error status
- Before -> shows the test case before it executes, and appends the status after the test completes.  Similar to On.
- After -> shows the test case and status together after the test case completes.

---

@CharliePoole commented on [Fri Aug 12 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239549055)

I like this idea, but I would modify/simplify it by preference:
- Off No change
- On No change
- Before / All shows test label when the test starts executing.
- After Shows all tests after they have completed, including status.

Note that All is described as it is supposed to work already. There's currently a bug in that it runs at the end of a test. We should fix that. We should keep All so as not to break existing usage.

The introduction of After means that we have to treat it as also meaning On. That is, if a test produces output, there should be a label before that output and another one after it, together with the test status..

The change should be made in both the console runner and nunitlite. Once we split the repos, this issue will need to be duplicated.

The fix is _relatively_ easy. Depending on who takes it, I can mentor them as needed.

---

@constructor-igor commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239676310)

Hi @CharliePoole,

Probably, I can start to work on the issue.
I checked all existing options of "--labels" parameter. Please, could you help me to understand suggested changes? I added sample with "--lablels=All". As I understand, the issue suggests to add "status" of each test?

![image](https://cloud.githubusercontent.com/assets/1849690/17649703/de4f1d40-6243-11e6-93bf-b165b80bdb28.png)

thank you,
Igor.

---

@CharliePoole commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239684890)

Hi @constructor-igor - I've been meaning to poke you to see what you are up to. :-)

As you probably figured out, all the code is in Console's TestEventHandler and in NUnitLite's TestRunner. There are tests for TestEventHandler but not for TestRunner. :-(

I would first off fix the problem with All, which is supposed to be issued at the start of each test, not at the end. I think I broke this when I was fixing something else.

Once All is correct, you've got Before, since it's intended to work the same way.

After is the new thing, which is supposed to show status of the test. For that, I would use a combination of the `result` and `label` attributes to display a set of values like...
- Passed
- Failed
- Error
- Invalid
- Ignored
- Explicit
- Skipped
- Inconclusive
  In NUnitLite, you'll have the ResultState available to use for equivalent logic.

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239782084)

I am going to start from "All".
But, right now, I don't understand expected behavior of "All".
So, when I'll investigate code I'll contact with you.

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239783383)

You might try this sequence - a bit different order from my first suggestion:
- Change "All" in existing code everywhere to "After" because All is now incorrectly running after the test.
- Add status info to After
- Add "Before" to run before the test
- Add back "All" as a synyonym for Before

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239785294)

I try to build nunit by "build.cmd":
![image](https://cloud.githubusercontent.com/assets/1849690/17663823/258f1ebc-62f8-11e6-8f20-c85dc33fc293.png)

VS2013:
![image](https://cloud.githubusercontent.com/assets/1849690/17664078/1d756e14-62fa-11e6-924f-8ecf9bdee198.png)

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239790081)

Are you using the latest master? Can you build in the IDE?

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239796767)

I cloned today and tried to build via build.cmd and IDE VS2013: same errors.

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239798656)

Using VS 2015?

---

@rprouse commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239803785)

I just got latest from master and ran `.\build.cmd` and it builds fine for me. Maybe do a full clean including deleting your packages folder and rebuild?

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239894381)

I could build nunit solution on other computer.
I tried to build on my computer again (downloaded master to new folder) and  see the error.

I investigate the issue and found, probably, same issues 
- https://github.com/nunit/nunit3-vs-adapter/issues/194
- https://github.com/nunit/docs/issues/44

I continue my investigation.

**Comment by CharliePoole** [comment]
@constructor-igor Now that the console is in another repo, you may need to start over. :-(

**Comment by constructor-igor** [comment]
After split of nunit repository, I can build nunit. but still cannot build nunit-console ;(

![image](https://cloud.githubusercontent.com/assets/1849690/17697523/f28c63d2-63bd-11e6-9b3c-d021d913bb60.png)

Reference Mono.Cecil also has implementation of "ExtensionAttribute":
![image](https://cloud.githubusercontent.com/assets/1849690/17697728/27c40fea-63bf-11e6-9c1d-15b7c3c31b5f.png)

![image](https://cloud.githubusercontent.com/assets/1849690/17697754/5358ad5a-63bf-11e6-80f5-7039b8d7cd5c.png)

So, I cannot understand why new cloned projects have different behavior on different computers. 
additional reference: http://stackoverflow.com/questions/546819/strange-warning-about-extensionattribute

**Comment by CharliePoole** [comment]
This is a well-known problem and I've "fixed" it a few times already. Our addition of Mono.Cecil exacerbates the problem. In the past, this normally only came up in our test assemblies - where we use .NET 3.5 for the test but reference a .NET 2.0 assembly. 

Try removing the attribute definition from nunit.engine assembly. If that fails, just turn off warnings as errors for now.

**Comment by constructor-igor** [comment]
After several attempts, I turned off "warnings as errors".
By the way, option "TestAll" (seems all test related options exclude "Test") doesn't work in "build" in script:

![image](https://cloud.githubusercontent.com/assets/1849690/17735453/e6015eec-648a-11e6-97e5-1664dacf9734.png)

Probably, file BUILDING.md contains obsolete options list:
https://github.com/constructor-igor/nunit-console/blob/master/BUILDING.md

**Comment by rprouse** [comment]
I have update BUILDING.md, it is out of date. `TestAll` was removed since it was a synonym for `Test`

**Comment by CharliePoole** [comment]
There are issues in both repos RE BUILDING.md.

**Comment by constructor-igor** [comment]
I investigated suggested sequence and code (`TestEventHandlerTests`and `TestEventHandler`).

> You might try this sequence - a bit different order from my first suggestion:
> 
> Change "All" in existing code everywhere to "After" because All is now incorrectly running after the test.
> Add status info to After
> Add "Before" to run before the test
> Add back "All" as a synyonym for Before 

I has renamed "All" to "After" and now I want to add "status".
If I understand correctly, to check status it's necessary to create `report` with relevant status (update `expected`) and transfer the it to `handler.OnTestEvent`?
If yes, please, could you help me to prepare new single case in `static TestCaseData[] EventData = new TestCaseData[]`?

```c#
        [TestCaseSource("EventData")]
        public void EventsWriteExpectedOutput(string report, string labels, string expected)
        {
            var handler = new TestEventHandler(_writer, labels);

            handler.OnTestEvent(report);

            if (Environment.NewLine != "\r\n")
                expected = expected.Replace("\r\n", Environment.NewLine);
            Assert.That(Output, Is.EqualTo(expected));
        }

```

**Comment by CharliePoole** [comment]
@constructor-igor I'm driving home from my trip today and can't look at code. I can give you some help this evening (in about 12 hours) or perhaps @rprouse can chime in with advice.

**Comment by CharliePoole** [comment]
@constructor-igor I'm sorry that this fell through the cracks.

Here are a couple of test cases to get you started...

```C#
new TestCaseData("<test-case fullname='SomeName' result='Passed' />", "After", "PASSED => SomeName\r\n"),
new TestCaseData("<test-case fullname='SomeName' result='Failed' />, "After", "FAILED => SomeName\r\n"),
```

We probably need to work out a few things before going much further than that:

1. What are all the possible statuses and how do we recognize them by looking at the `result` and `label` attributes.

2. What should be the layout of the output. In my example, I put the status before the arrow, but it could come elsewhere.

Once you get this basically working, I think you should do a PR. It won't be ready to merge yet but having a PR will make it easier to give line by line comments and should make me quicker to respond. :-)

**Comment by CharliePoole** [comment]
@constructor-igor How's this going - we are about to do a 3.5 release and I'm wondering if this will make it or if we should postpone.

**Comment by constructor-igor** [comment]
Hi Charlie,

I am going to return to nunit activities this week.
When it is planned to release 3.5?

thank you,
Igor.

**Comment by CharliePoole** [comment]
We're aiming to do it in stages, starting at the end of the week. The framework will be first.

**Comment by constructor-igor** [comment]
update:
- created branch (in my fork): https://github.com/constructor-igor/nunit-console/tree/Issue24
- "All" changed to "After"
- Implemented test's status in "After" label
- Added new tests (from previous comment) and updated existing tests

Now I am going to add "Before" status, including tests.
If you can review my changes and send feedback it will help me.

suggested tasks list:
```
You might try this sequence - a bit different order from my first suggestion:

Change "All" in existing code everywhere to "After" because All is now incorrectly running after the test.
Add status info to After
Add "Before" to run before the test
Add back "All" as a synyonym for Before
```

added tests:
```
new TestCaseData("<test-case fullname='SomeName' result='Passed' />", "After", "PASSED => SomeName\r\n"),
new TestCaseData("<test-case fullname='SomeName' result='Failed' />, "After", "FAILED => SomeName\r\n"),
```

**Comment by constructor-igor** [comment]
I add the samples for my better understanding

**Off**
![image](https://cloud.githubusercontent.com/assets/1849690/19114460/bc88d6a0-8b16-11e6-9275-87516e1d8d0a.png)

**On**
![image](https://cloud.githubusercontent.com/assets/1849690/19114492/d860d8fa-8b16-11e6-9adb-1029a0a60364.png)

**After**
![image](https://cloud.githubusercontent.com/assets/1849690/19114519/04400702-8b17-11e6-81eb-0ae77c6b259d.png)

**Comment by CharliePoole** [comment]
@constructor-igor I think it would be easier to review this and possibly make suggestions if you created a PR. Creating a PR doesn't necessarily mean your work is ready to merge. We do it all the time for anything that requires some degree of collaborative review because it enables making comments on specific lines. Just put a line saying **Do Not Merge** at the top of the description.

**Comment by constructor-igor** [comment]
created PR https://github.com/nunit/nunit-console/pull/78

**Comment by rprouse** [comment]
Just a note, this is currently in the 3.6 milestone but we are close to doing the release. We can include this if it gets done before @CharliePoole or I goes to do the release, but if it is still outstanding we will move it out of the milestone. I am not saying this to rush anyone, just letting people know this may not be included in 3.6 😄

**Comment by CharliePoole** [comment]
s/3.6/3.5/

**Comment by CharliePoole** [comment]
I'd like to see if we can get this into 3.5, which means finish it in the next 1 or 2 days. Is that feasible for you @constructor-igor ? I'm willing to help.

Since there are so many comments, I'll summarize what we want as final options...

 * All - Synonym for Before.
 * Before - Displays the standard label with name before the test runs.
 * After - Displays the standard label with name and result after the test completes.
 * On - Displays labels only when output is produced. This is the default.
 * Off - Doesn't display any labels.

We need to retain the behavior that avoids double labels when not needed, but does label interleaved immediate output from parallel tests correctly.

Next, I'll go to the PR and review what's done and what's not done. 😄

**Comment by CharliePoole** [comment]
Or should All be a synonym for Before + After? Before + After + On? Let's discuss combinations after everything else is working.

**Comment by CharliePoole** [comment]
You should rebase this on current master, since there have been a number of changes, especially the addins no longer being present in master.

**Comment by oznetmaster** [comment]
Isn't this going to be in nunitlite as well?  nunitlite 3.5 has already been released, so I was confused by trying to get this into 3.5.

**Comment by CharliePoole** [comment]
I think it should be. If there isn't an issue, please create one.

This is an nunit-console issue, so when we say 3.5, we mean the 3.5 console release, which we are working on. Now that the framework and console/engine projects are separate, there is no future expectation that the release numbers will be the same. The 3.5 release taking place now is the last one.

That said, the code should be very easy to migrate once it's finished and the tests should work as well. The main difference, of course, is that the console deals with XML while nunitlite deals with the framework object model.

**Comment by constructor-igor** [comment]
I need help for "Before". Could you help with test?

**Comment by CharliePoole** [comment]
Sure... here are some tests...
````
new TestCaseData("<start-test fullname='SomeName'/>", "Before", "=> SomeName\r\n"),
new TestCaseData("<start-test fullname='SomeName'/>", "All", "=> SomeName\r\n"),
new TestCaseData("<start-suite fullname='SomeName'/>", "Before", ""),
new TestCaseData("<start-suite fullname='SomeName'/>", "All", ""),
````

**Comment by CharliePoole** [comment]
@rprouse @constructor-igor Since this enhancement is not making it into 3.5, I'm inclined to do a quick fix to the existing bug where "All" is being displayed when the test ends rather than when it starts. What do you think?

**Comment by constructor-igor** [comment]
**--labels=Off**
![image](https://cloud.githubusercontent.com/assets/1849690/19223425/2f3edb2c-8e78-11e6-88d3-6ae6fcb0f1b0.png)

**--labels=On**
![image](https://cloud.githubusercontent.com/assets/1849690/19223430/4654b3e0-8e78-11e6-9f42-792abc801087.png)

**--labels=After**
![image](https://cloud.githubusercontent.com/assets/1849690/19223422/15a0bc6c-8e78-11e6-90d1-92c2780f3d03.png)

**--labels=Before**
![image](https://cloud.githubusercontent.com/assets/1849690/19223432/63dae8e4-8e78-11e6-9af2-f1d61c8b10cc.png)

**--labels=All**
![image](https://cloud.githubusercontent.com/assets/1849690/19223433/7a88dd9e-8e78-11e6-9120-e9d91205a279.png)

**Comment by constructor-igor** [comment]
@CharliePoole yes, if we cannot complete the feature right now, better to fix bug with "All".

**Comment by rprouse** [comment]
@CharliePoole I am okay with the quick fix for All, probably similar to what we added to dotnet-test-nunit. @constructor-igor feel free to carry on with this PR, we will get it in the next release.

**Comment by CharliePoole** [comment]
FYI, the fix is in.
