### ISSUE TITLE
Missing prerequisites .Net 2., 4.0, Mono on Win10

### ISSUE THREAD

**Issue by ipavlu** [nunit/nunit-console#240]
Hi, please drop damned prerequisites testing from MSI package, it does not understand Win10 with built in .Net...

.Net 2.0, 3.5, 4.0 are all present on the machine, just not explicitly, tehre are not even features on win10 that could be enabled as netfx4. It is really incorrect test...

**Comment by jnm2** [comment]
Dunno if this is related, but .Net 2.0 though 3.5 are not present on Win10 until you explicitly install them via 'Turn Windows features on or off.'

**Comment by ChrisMaddock** [comment]
I'll move this to the nunit-distribution repo, where the msi is currently built, and comment further there.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-distribution #18](https://github.com/nunit/nunit-distribution/issues/18) via [**ZenHub**](https://www.zenhub.com/)
