### ISSUE TITLE
Test output from NUnit console 3.6.1 is being written one character per line

### ISSUE THREAD

**Issue by joel74** [nunit/nunit-console#247]
We recently moved from NUnit console 2.6.3 to 3.6.1. For some of our assemblies, the console output is fine. For others, there is a new line between every character.

This is an example of a command that works:
E:\_ops\Utils\NUnit.Console-3.6.1\nunit3-console.exe ".\\TestsArtifacts\\ADEXS.Tests.dll" --where "(cat == Integration || cat == Functional) && cat != DeveloperOnly && cat != Relic" --labels On --timeout 300000 --result:"IntegrationTestResults.xml;format=nunit2"

This is an example of a similar command where output is one character per line:
E:\_ops\Utils\NUnit.Console-3.6.1\nunit3-console.exe ".\\ApiAuthenticationTestsArtifacts\\ApiAuthenticationTests.dll" --where "cat != DeveloperOnly && cat != Relic" --labels On --timeout 300000 --result:"ApiAuthenticationTestResults.xml;format=nunit2"

I grabbed some of the sliced output and put it together, to see if it would be interesting. Here's the first part:

ControlConnection: 06/29/2017 16:55:21.716 -05:00 : Trying to connect the ControlConnection ControlConnection: 06/29/2017 16:55:23.279 -05:00 : Protocol version 4 not supported, trying with version 3 
Connection: 06/29/2017 16:55:24.982 -05:00 : Canceling in Connection 10.131.128.48:9042, 0 pending operations and write queue 0 
ControlConnection: 06/29/2017 16:55:25.451 -05:00 : Connection established to 10.131.128.48:9042 

Any thoughts on what's going on here?

Thanks,
Joel

**Comment by CharliePoole** [comment]
This was fixed in 3.7. Current release is 3.7.1.

**Comment by joel74** [comment]
Thanks. So I take it that this had nothing to do with the console, and was a fix in the framework, since the console is still on 3.6.1. Cheers.

**Comment by CharliePoole** [comment]
@joel74 Right! The console just displays what it receives.
