### ISSUE TITLE
Resolve test projects' namespace situation

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#258]
Same situation as https://github.com/nunit/nunit/issues/2311. This should wait until after the 3.7 release.

**Comment by CharliePoole** [comment]
Sane comment. :smiley:

**Comment by CharliePoole** [comment]
Revisiting this. I'll do it in separate PRs per assembly pair (production + test).

With a few exceptions, I'm using the same  namespace for tests as for the production class they test.
