### ISSUE TITLE
[Question] From Nunit xml test results to TRX file

### ISSUE THREAD

**Issue by jrodrigv** [nunit/nunit-console#268]
Hi all,

I'm trying to transform the Nunit3 test results to a TRX file format. Is there an easy way to do this? Maybe a stylesheet or piece of code used by the Nunit VS Test adapter?

Kind Regards,
Jesus

**Comment by CharliePoole** [comment]
We don't have anything I'm afraid. It's VS, not the adapters, that actually produce a TRX file. If you find something we would be glad to have it as part of our nunit-transforms project.

**Comment by jrodrigv** [comment]
Thanks! We are already working on a way to transform it. I will let you know if we finally manage to it.

**Comment by Gakk** [comment]
@jrodrigv Did you find a way to transform from NUnit3-format to TRX?

**Comment by jrodrigv** [comment]
> @jrodrigv Did you find a way to transform from NUnit3-format to TRX?

Yeah, we ended up creating a stylesheet to transform into TRX :)

**Comment by clicketyclackety** [comment]
> Yeah, we ended up creating a stylesheet to transform into TRX :)

Any chance that convertor might be available? 🤠

**Comment by super-brian** [comment]
@jrodrigv , I need to transform xml to TRX. How can I do it? you said you created a stylesheet. Could you let people use it?
