### ISSUE TITLE
Final Non-Parallelizable Test appears to record incorrect duration when TimeoutAttribute used

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#269]
My test assembly runs with mainly parallel fixtures, via `[assembly: Parallelizable(ParallelScope.Fixtures)]`. There are approx 10,000 tests - within this, I have a couple of tests using TimeOutAttribute I've specifically marked the fixtures `ParallelScope.None`. The below is a minimum example of such a fixture.

    [TestFixture, Parallelizable(ParallelScope.None)]
    public class TestFixture
    {
        [Test, Timeout(100)]
        public void ATest()
        {
        }
    }

When running under NUnit Console, the final Non-Parallelizable Test appears to record an additional ~30 seconds in duration. (Even in the above situation, where the test is empty.) Hence the Timeout fails.

The extra time added to this test, appears to be within the console runner activity. I'm running a single assembly. When I remove the troublesome test, I see that the `test-run` recorded `end-time` is 30 seconds later than the `end-time` of the single test suite. With the bad test - the `bad-test-end-time` roughly matches `test-run-end-time` - but `test-suite-end-time` remains the same. **Meaning the end time of the bad test is AFTER the end time of the assembly test-suite that contains it.**

This bug DOESN'T appear with NUnitLite - where I've previously run these tests.

Some further specifics.
1. This only occurs when I have a mix of ParallelScope.Fixtures and ParallelScope.None. If I have all tests in parallel, or none in parallel, the per-test duration looks to be sensible.
2. The TimeoutAttribute appears key, without this, the test has a normal duration.
3. The overall (reported) test run duration remains constant, whether I use Timeout on the non-parallelizable test, and the test reports taking 30 seconds longer, or not. This makes me suspect a reporting issue, rather than a test-running issue.
4. In terms of the timeline, it appears that the ParallelScope.Fixtures tests are all running first, then the 'none' fixture is ran once those have completed. I'm unsure as to where the additional 30 seconds comes from. 

Additionally, for some reason, the failed test isn't reported in the console. This is the output I see - there's no log of failed tests.

![image](https://user-images.githubusercontent.com/4837132/28460203-ead2ebba-6e08-11e7-94cb-82c562ea499b.png)

I'm suspicious there are two bugs here:
1. What is the console doing for an extra 30 seconds, after the completion of the test-suite run. (The console run also takes ~30 seconds longer than the NUnitLite run.)
2. Why is the 'bad-test' duration incorrect, and outside of the overall test suite run.

There's probably more digging to do here, but only so much I can do at the moment. Appreciate any early thoughts as to what's going on.

**Comment by ChrisMaddock** [comment]
Ok, so I took out the ParallelScope.None, to try and track down the missing 30 seconds. It does seem to be specific to this test assembly, other assemblies I've tried the end-of-test-suite =~ end-of-test-run.

This is the useful bit of the log:
```
11:57:00.898 Debug [16] WorkItemDispatcher: Directly executing ShouldHaveFallbackValue(">>Button.Name")
11:57:33.487 Info  [16] WorkShift: Parallel shift ending
```

That test records it's duration in the results xml as 0.020038 - so there seems to be 30 seconds of something unlogged happening on that thread? Although I don't know what triggers the the 'Parallel shift ending' message - I would have assumed that would be once per worked, but only seems to be once overall? I would need to dig into this to see what it should be doing.

Here is the last section of the log, showing all parallel workers.

```
11:57:33.487 Info  [16] WorkShift: Parallel shift ending
11:57:33.488 Info  [16] WorkItemQueue: ParallelQueue pausing
11:57:33.489 Info  [16] WorkItemQueue: ParallelQueue stopping - 474 WorkItems processed, max size 400
11:57:33.489 Info  [10] TestWorker: Worker#2 stopping - 38 WorkItems processed.
11:57:33.489 Info  [ 9] TestWorker: Worker#1 stopping - 59 WorkItems processed.
11:57:33.489 Info  [16] TestWorker: Worker#8 stopping - 22 WorkItems processed.
11:57:33.489 Info  [11] TestWorker: Worker#3 stopping - 45 WorkItems processed.
11:57:33.489 Info  [14] TestWorker: Worker#6 stopping - 62 WorkItems processed.

11:57:33.489 Info  [13] TestWorker: Worker#5 stopping - 129 WorkItems processed.
11:57:33.489 Info  [11] TestWorker: Worker#3 stopping - 45 WorkItems processed.
11:57:33.489 Info  [11] TestWorker: Worker#3 stopping - 45 WorkItems processed.
11:57:33.489 Info  [14] TestWorker: Worker#6 stopping - 62 WorkItems processed.

11:57:33.489 Info  [11] TestWorker: Worker#3 stopping - 45 WorkItems processed.
11:57:33.489 Info  [14] TestWorker: Worker#6 stopping - 62 WorkItems processed.

11:57:33.489 Info  [13] TestWorker: Worker#5 stopping - 129 WorkItems processed11:57:33.489 Info  [11] TestWorker: Worker#3 stopping - 45 WorkItems processed.
11:57:33.489 Info  [11] TestWorker: Worker#3 stopping - 45 WorkItems processed.
11:57:33.489 Info  [14] TestWorker: Worker#6 stopping - 62 WorkItems processed.
```

**Comment by ChrisMaddock** [comment]
I updated the framework 3.6.0 -> 3.7.1 (a somewhat non-trivial exercise here due to a couple of shared libs referencing dlls) and the problem was fixed.

Damn - that's a couple of hours I'm not getting back!

**Comment by CharliePoole** [comment]
So I'm reading down this thinking "DIdn't I just fix something like this?" Apparently so! 😄 

Regarding workers and shifts... NUnit's workers are unionized and will only work on one shift. So for each shift there can be many workers. 😃

**Comment by ChrisMaddock** [comment]
Thanks Charlie - and thanks for the pre-emptive fix! 😄 

I think I made some assumptions by the "Parallel shift ending" log message being posted from one specific worker thread. I assume in this case, that thread 16 was the 'master worker' or so, which decided when all the work was complete?

**Comment by CharliePoole** [comment]
In fact, it's a worker event being handled by the dispatcher. As each worker finishes a task, the event fires and the dispatcher checks to see if there is no more work in the shift. If not, it terminates the shift and either starts a new one or ends the run completely.
