### ISSUE TITLE
Run Nunit test from .netcoreapp 1.1 dll via console runner

### ISSUE THREAD

**Issue by pavzaj** [nunit/nunit-console#271]
I have some nunit tests in .netcoreapp 1.1 project. Tests are written using Nunit framework 3.7.1 and they test logic from a referenced dll compiled against .netStandard 1.0.
These tests are properly detected and executed by NUnit3TestAdapter 3.8.0 in VS 2017, but when I try to run in via Nunit CLI 3.7.0 I get the following error:

D:\NUnit.Console-3.7.0>nunit3-console.exe D:\github\MyProject\_tests\TestData\SampleLogicNunitTests\bin\Debug\netcoreapp1.1\SampleLogicNunitTests.dll
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    D:\github\MyProject\_tests\TestData\SampleLogicNunitTests\bin\Debug\netcoreapp1.1\SampleLogicNunitTests.dll

Errors, Failures and Warnings

1) Error :
An exception occurred in the driver while loading tests.

Server stack trace:
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-07-25 19:14:26Z
    End time: 2017-07-25 19:14:26Z
    Duration: 0.616 seconds

Results (nunit3) saved as TestResult.xml

What did I do wrong?

**Comment by CharliePoole** [comment]
NUnit3-console does not support .NET Core. IMO, you should get a message that says so.

**Comment by pavzaj** [comment]
Right, I've executed these tests correctly with "dotnet test" command.
Is there any way to run dotnet core tests via some CLI and have xml test execution report or "--teamcity" stdout messages like those from nunit-console?
Or maybe you are planning to release nunit-console for dotnet core some day?

**Comment by CharliePoole** [comment]
We hope to allow running .NET Core tests with the console runner in the future.

**Comment by glerchundi** [comment]
Fall into the same issue, do you have an expected ETA? Thanks!

**Comment by ChrisMaddock** [comment]
I believe you can currently get an xml test report by using the nunitlite-runner - that's currently bundled in the zip.

https://github.com/nunit/nunit/releases

Getting test results from the `dotnet test` CLI is being tracked here: https://github.com/nunit/nunit3-vs-adapter/issues/323. (Pull requests welcome!) The --teamcity integration first relies on the .Net Standard engine being able to load extensions, which is a bigger issue to tackle.

**Comment by CharliePoole** [comment]
We need an issue that tracks precisely the ability to run these tests via the console runner. Running via "some CLI" is a bit too vague. Since there's nothing else going on with this issue, I'm renaming it for that purpose.

General plan: 1. Get a sensible error message when trying to run the app via the console 2. Make it run

**Comment by CharliePoole** [comment]
We currently give the message ".NETPortable test assemblies are not yet supported by the engine."

This is due to dotnet/roslyn#11067. The `TargetFrameworkAttribute` is set to `.NETPortable,Version=5.0` rather than `.NETStandard,Version=1.x`.

We need to try to compensate for this bug, since assemblies that reflect it will be around for a while.

**Comment by CharliePoole** [comment]
PR #278 has fixed the problem of an unclear error message. We now report that .NET Standard is not yet supported.

**Comment by glerchundi** [comment]
@CharliePoole thanks for getting into this. Would love to see this solved as we use console runner as our primary testing tool on our CI servers and we are progressively migrating our .NET Framework libraries to make them work in .NET Standard too.

I can take this one and create a PR in a month or so. I would like to ping you all in case you're already working on it.

**Comment by CharliePoole** [comment]
Although it's assigned to me, I'm currently stuck on detecting the standard level of the test assembly. Any work along those lines would be helpful. As far as I can determine, there is no clean way to do it other than testing for a selection of APIs. That seems very strange to me.

**Comment by glerchundi** [comment]
@CharliePoole, I don't know if this could be helpful or not but I multitargeted a library to `net40;netstandard20;netstandard16` and it seems like the `[TargetFramework]` attribute is a reliable way to determine the version with which it was built, results:

net40:
`[assembly: TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]`
netstandard20:
`[assembly: TargetFramework(".NETStandard,Version=v2.0", FrameworkDisplayName="")]`
netstandard16:
`[assembly: TargetFramework(".NETStandard,Version=v1.6", FrameworkDisplayName="")]`

**Comment by CharliePoole** [comment]
That's what it's supposed to do. I'm dealing with this issue: https://github.com/dotnet/roslyn/issues/11067 which is supposedly fixed but still present in my environment and reported as still present by other folks too.

Now that I think of it, I should create some entirely new projects and see what I get! I've been using the existing nunit test projects for my testing. If this turns out to be a temporary VS glitch, we can just report the error and move on!

**Comment by CharliePoole** [comment]
Taking my name off this to free it up for somebody else.

**Comment by shaulbehr** [comment]
Any word on when NUnit Console is expected to be able to support .NET Standard/Core?

**Comment by ChrisMaddock** [comment]
@shaulbehr No timeline yet, but we're working on it. This PR is one more step down the path: https://github.com/nunit/nunit-console/pull/400

**Comment by ChrisMaddock** [comment]
This issue will be taken care of under https://github.com/nunit/nunit-console/issues/475. We're continuing work on .NET Core support at the moment - please see https://github.com/nunit/nunit-console/projects/1 for the overall project view. 

I'm going to close this issue in favour of the #475 - but please feel free to add any comments over there. 🙂
