### ISSUE TITLE
Insufficient error handling message in ProcessRunner -> RunTests method

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#273]
@Fernell commented on [Fri Jul 28 2017](https://github.com/nunit/nunit/issues/2334)

log.Error("Failed to run remote tests {0}", e.Message); is insufficeint. It lacks details required to diagnose problem. Here is sample of my log:
> An exception occurred in the driver while loading tests.
> Server stack trace: 
>    at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
>    at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
>    at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
>    at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
>    at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Runners.AggregatingTestRunner.RunTestsSequentially(ITestEventListener listener, TestFilter filter, List`1 results, Boolean disposeRunners)
>    at NUnit.Engine.Runners.AggregatingTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Agents.RemoteTestAgent.Run(ITestEventListener listener, TestFilter filter)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

I was unable to recognize error only by this stack trace. I was forced to download nunit3-console binaries and debug it myself. I found out that useful error message was in ex.InnerException which is not returned in error message at all. Please extend error message by adding ex.InnerException message.

---

@ChrisMaddock commented on [Fri Jul 28 2017](https://github.com/nunit/nunit/issues/2334#issuecomment-318662752)

This is an nunit-console issue, I'll move it over to that repository.

@Fernell - we'd appreciate a Pull Request, if you were willing.

**Comment by ChrisMaddock** [comment]
I think this may be a general issue for some of our console logging.

In the framework, we have ExceptionHelper - which flattens exceptions hierarchy, and (theoretically) ensures everything useful is printed. Having an equivalent in the console would be nice.

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/ExceptionHelper.cs#L159

**Comment by ChrisMaddock** [comment]
@Fernell - can you also add what your actual bug was? I don't believe this exception handler should be hit in normal user flow - it may indicate an earlier exception is being handled incorrectly.

**Comment by ChrisMaddock** [comment]
@CharliePoole - Do you know if there was any intentional breaking changes here?

@Fernell - can you share you NUnit project file, so we can see why the defaults didn't work for you?

**Comment by CharliePoole** [comment]
The main difference is that the old console actually loaded the assembly, which requires all references to be present. That automatically gave a clearer error message. In NUnit 3, we examine the references in the test assembly without loading, so any failure occurs a bit later, in the driver, when we actually load it.

What has not changed, at least, intentionally, is how we set the appbase by default when a project is used. That's the potential bug here, along with a better error message.

**Comment by Fernell** [comment]
My old nunit file looked like this:
<NUnitProject>
    <Config name="Debug" binpath="." runtimeFramework="net-4.5">
        <assembly path="BuildOutput\Debug\someTest1.dll" />
        <assembly path="BuildOutput\Debug\someTest2.dll" />
        <assembly path="BuildOutput\Debug\someTest3.dll" />
    </Config>
</NUnitProject>

I needed to change it to this:
<NUnitProject>
    <Config name="Debug" binpath="." appbase="BuildOutput\Debug\" runtimeFramework="net-4.5">
        <assembly path="someTest1.dll" />
        <assembly path="someTest2.dll" />
        <assembly path="someTest3.dll" />
    </Config>
</NUnitProject>

**Comment by ChrisMaddock** [comment]
Thanks @Fernell - that looks like an unintentional change. I wonder if it's related to #116 - I'm not sure what order things are resolved in here.

**Comment by ChrisMaddock** [comment]
#301 improves the error message. I'm now going to move this issue to the nunit-project-loader repo for the potential bug to be investigated here.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-project-loader #13](https://github.com/nunit/nunit-project-loader/issues/13) via [**ZenHub**](https://www.zenhub.com/)

**Comment by davidenq** [comment]
Hi everyone, I'm not sure if it is the same issue #270 but I've found a solution and I've published a [comment](https://github.com/nunit/nunit-console/issues/270#issuecomment-357561587) there with an example.
