### ISSUE TITLE
Wrong date format in Ignored TestFixtures

### ISSUE THREAD

**Issue by alexamz** [nunit/nunit-console#274]
Hi all,

First of all, many thanks to all the contributors to this great and useful project!

We have problems with the start-time and end-time dates in Ignored TestFixtures.
We are using the last version of the NUnit console, the 3.7.0.

This is an example of a test-case header in the xml generated by NUnit Console with a wrong formatted date:

>     <test-case id="0-1071" name="AfterStart_AClientMayConnect" fullname="Port.TCP.UnitTests.TcpServerFactoryTests.AfterStart_AClientMayConnect" methodname="AfterStart_AClientMayConnect" classname="Port.TCP.UnitTests.TcpServerFactoryTests" runstate="Runnable" seed="604943940" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">

On this example we can see that start-time and end-time dates have a wrong date  value "0001-01-01 00:00:00Z ". I would expect to have the date of the execution even if they are skipped. Moreover, if you try to publish these dates to TFS API it will fail because of the date value.

This issue is very easy to reproduce , just adding a [Ignore("some ignore reasons")] on a [TextFixture]. And running Nunit Console to generate the xml result output.

Many thanks!

Have a nice day

**Comment by ChrisMaddock** [comment]
The code for this lives in the NUnit Framework. I'll move this issue over, and comment further over there. 🙂

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit #2339](https://github.com/nunit/nunit/issues/2339) via [**ZenHub**](https://www.zenhub.com/)
