### ISSUE TITLE
ConsoleRunner raises InvalidCastException when converting from Object to ADODB.Recordset

### ISSUE THREAD

**Issue by danielrteles** [nunit/nunit-console#279]
Hi,

I've created a unit test class to validate an SSIS package and Object variables in SSIS are commonly converted to the ADODB.Recordset interface. It works perfectly fine when I run NUnit tests in Visual Studio, but the ConsoleRunner raises an InvalidCastException for the same code.

I've tried many alternatives, but none has worked so far. I've also tried XUnit and it has the same issue, although MSTest processes all tests successfully.

Just as an example, I've created an SSIS package with a ScriptTask which populates a variable of type Object with the number of rows based on the value of another variable of type Int32.

In my test, I'm setting the Int32 variable with value 5 and I expect the Object variable to return 5 rows (what works fine when running the test in Visual Studio).

This is the test code:

'''
[Test]
public void SampleTestMethodForSimulatingTheError()
{
	var ispacFile = Path.Combine(executionPath, IspacFileName);

	var stream = new FileStream(ispacFile, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite);

	var project = Project.OpenProject(stream);

	var package = project.PackageItems["SsisMasterPackage.dtsx"].Package;

	package.Variables["MasterIterationVariable"].Value = 5;

	package.Execute();

	var da = new OleDbDataAdapter();
	var dt = new DataTable();
	var obj = (ADODB.Recordset)package.Variables["ObjectVariable"].Value;
	da.Fill(dt, obj);
	
	Assert.AreEqual(5, dt.Rows.Count);
}
'''

The error returned by the ConsoleRunner is:

'''
1) Error : xxxxxx.SsisTemplate.UnitTests.MasterPackageTests.SampleTestMethodForSimulatingTheError
System.InvalidCastException : Unable to cast object of type 'System.Object' to type 'ADODB.Recordset'.
   at xxxxxx.SsisTemplate.UnitTests.MasterPackageTests.SampleTestMethodForSimulatingTheError() in C:\Projects\SsisUnitTester\src\SSISTemplateUnitTests\MasterPackageTests.cs:line 339
'''

Please, could someone check if this is actually a bug or if there is a way to make it work?

Thanks,
Daniel

**Comment by rprouse** [comment]
Sorry, I don't know much about SSIS, but my guess is that it is an x86/x64 issue. Assuming your tests are AnyCPU, if you run your tests in Visual Studio, by default they run in an x86 process. If you run from the command line, they will run x64.

Try running your tests with the command line option `--x86`. If that fixes it, switch to compiling your test assembly as x86. To do so, go to the Project settings | Build | Platform target, and switch from AnyCpu to x86.

I am going to close this as not an NUnit issue. If you still need help or have feedback, post here, we will see it and try to help.
