### ISSUE TITLE
Force NUnit Console to run AnyCPU tests as x64

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#286]
@jgrossrieder commented on [Thu Sep 07 2017](https://github.com/nunit/nunit3-vs-adapter/issues/384)

Hi,

I recently came across the following issues:
All our solution(Unit Test and library) is compiled in AnyCPU. We have some external library that have a specific version for x86 or x64, so we do 2 setups, one x86 with the global lib + the 32 bit library, and one x64 with the 64 bits libraries.

We have decided to make the unit tests with the x64 version of  libraries(so we copy those one), but once someone let the "Prefer 32-bit" of the build settings of an executable that was referenced by a referenced project of a test unit.

Then we got BadImageException( 0x8007000B ), globally saying that we were trying to use x64 libs in a x86 app. 

I did the following UnitTest just to confirm

```
        [Test]
        public void TestProcess()
        {
            Assert.AreEqual(Environment.Is64BitProcess, true);
        }
```

And it was failing on the build machine. In visual studio, if I set the `Test -> Test Settings -> Default Processor Architecture` to x64, it was working again(and the UnitTest was working too).
But when running myself the nunit3-console, I cannot specify this and the parameters fails.

So I tried to create a `test.runsettings` file with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>  
  <!-- Configurations that affect the Test Framework -->  
  <RunConfiguration>  
    <!-- [x86] | x64    
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->  
    <TargetPlatform>x64</TargetPlatform>  
  </RunConfiguration>  
</RunSettings>  
```

But after having selected it in Visual studio and reopening the solution on another computer, this is not persisted(and the Unit Tests still fails), so I guess it's not the way to go?
Is there a way to "force" the x64 behavior? even if there was a `Prefer 32-bit` in one of the reference project?

* NUnit versions: 3.7.0
* Visual Studio : 2017 Pro 15.3.3
* .Net Platform: .Net 4.6

---

@CharliePoole commented on [Thu Sep 07 2017](https://github.com/nunit/nunit3-vs-adapter/issues/384#issuecomment-327768889)

You reported this as an NUnit3Adapter problem, but in your description you are talking about using the NUnit console runner. Can you please clarify?

---

@jgrossrieder commented on [Thu Sep 07 2017](https://github.com/nunit/nunit3-vs-adapter/issues/384#issuecomment-327769974)

@CharliePoole I'm affraid I'm mistaken, it was for the NUnit console runner, is it possible to move it to there or do I've to close and open another one to the correct place?

---

@CharliePoole commented on [Thu Sep 07 2017](https://github.com/nunit/nunit3-vs-adapter/issues/384#issuecomment-327775592)

Moving this... please add info about your nunit3-console command-line.

**Comment by jgrossrieder** [comment]
Here is the command line I used:

`C:\nunit-console\nunit3-console.exe path-to-my-solution.sln --config=Debug --agents=1 --process=Separate --result=TestResult.xml;format=nunit2 --timeout=300000 --workers=1`

**Comment by CharliePoole** [comment]
Because your command-line uses the solution, NUnit attempts to load all assemblies in the solution, whether they are test assemblies or not.  You should list all the test assemblies on the command line to avoid loading any assemblies unnecessarily.

Because of `--process=Separate` it attempts to load all of them into the same process. From your description, some of them require a 32-bit process and others 64. If some of the assemblies you list on the command-line require 32 bits, while others don't, you should drop the `--process=Separate` option. See further note below, however.

The `--agents` option has no effect, unless you run multiple agent processes.

The `--workers=1` option will defeat any `Parallelizable` attribute contained in your assembly. 

NOTE: These suggestions assume that every __test__ assembly you list on the command-line that requires 32-bits is built with the correct target. If a test assembly targets AnyCpu but needs to run in a 32-bit process, you must use the `--x86` command-line option. If that were the case, you would probably need to use separate runs of the console runner for some of the assemblies.

I'll leave this open  while you try some of these suggestions.

**Comment by jgrossrieder** [comment]
Thank you for the answer:

We are in the process of adding a lot of UnitTests(we were initially having no units tests and now we have like ~20 projects of UnitTests), but we expect to add a lot of them, and we can specify which branch to use. So I don't think we really have a choice to specify the differents projects.

All our Tests projects ON THE BUILD MACHINE are run with 64bits, it's just sometimes we can execute manually some of them in 32 bits.
the `--wokers=1` is intended also, for the moment we run the tests on a low end virtual machine, and we often have 2 different jenkins jobs in parallels.

This being said, I'm not sure to understand why any of thoses suggestions could make the tests running in 32bits instead of 64 bits?

**Comment by CharliePoole** [comment]
Your command-line is forcing all tests to run in the same process even though some of them require different process settings.

Have you __tried__ any of the suggestions? I can respect that you want to understand them first, but sometimes just giving it a shot is the best way forward.

**Comment by CharliePoole** [comment]
BTW, there's an SO question that looks a lot like yours. Is that you? If so, please know that it's a bit of a pita to have to keep explaining it in both places.

**Comment by CharliePoole** [comment]
Closing this as there has been no further info for a number of years.
