### ISSUE TITLE
Stack trace shown for Assert.Warn

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#287]
I'm having a hard time reading my build logs because every Assert.Warn puts 40-50 lines of stack trace under the message. I only see this when looking at NUnit console output.

Is this by design? Is there a way to disable this?

**Comment by CharliePoole** [comment]
Yes. Make this issue a bug and somebody will fix it. 😄 

Our StackTrace filter removes certain class entries from the top of the stack. Most likely, being new, `Warn` isn't one of them. Alternatively, it may only do it for failures. Somebody should fix it.

**Comment by CharliePoole** [comment]
Actually, if you decide this should be fixed, it's a framework issue.

**Comment by jnm2** [comment]
Thanks Charlie, will move.

**Comment by jnm2** [comment]
Issue moved to [nunit/nunit #2429](https://github.com/nunit/nunit/issues/2429) via [**ZenHub**](https://www.zenhub.com/)
