### ISSUE TITLE
Integrate GitVersion in the build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#288]
Initially, I'll follow the implementation on nunit-gui, after which we can discuss changes to tailor it to how we work in this project. The main difference is that the gui is pre-1.0 and therefore doesn't use hotfixes or release branches.

**Comment by ChrisMaddock** [comment]
Going to close this issue, as I don't think it's a priority at the moment. Happy to reconsider, if anyone's willing to champion it.

**Comment by CharliePoole** [comment]
I was once the champion because I thought it would ease my pain in doing releases. At this point, it's you who has to weigh the convenience of automatic versioning against the hassle of manual updates. :smiling_imp:

**Comment by ChrisMaddock** [comment]
It is. I’d love for it to be in place, but I’ve long since come to appreciate that I can’t do everything. 😅

And our current versioning system is sufficiently stable and low maintenance in my eyes that incrementing by hand isn’t too much of an issue.

Integration tests, on the other hand...
