### ISSUE TITLE
`--domain=Multiple` fails running in the agent (separate process).

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#29]
@rprouse commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1742)

Run multiple unit tests with `--domain=Multiple` and it fails with,

```
  Overall result: System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Common.ColorConsoleWriter.WriteLabel(String label, Object option, ColorStyle valueStyle)
   at NUnit.Common.ColorConsoleWriter.WriteLabelLine(String label, Object option, ColorStyle valueStyle)
   at NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport()
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

It works however with `--inprocess --domain=Multiple`. This was found in 3.4.1, we should retest with latest master as @CharliePoole may have fixed this with recent changes.

---

@CharliePoole commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1742#issuecomment-239679659)

I think this is a repetition of #1732 except that it was originally reported using only one assembly. 

---

@CharliePoole commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1742#issuecomment-239691224)

I replicated the problem with my current master. In fact, the key difference is the use of two assemblies. I think that's because `domain=Multiple` is actually ignored if there is only one assembly.

While this is probably not critical in itself, it bothers me because I don't understand what is happening here. The issue now only arises when you force domain:Multiple in a situation where you are running in a separate process per assembly and there is therefore only one assembly in the domain anyway. This has always been handled gracefully before. Let me take a closer look.

**Comment by CharliePoole** [comment]
@rprouse Would you please check this was resolved by PR #42?

**Comment by rprouse** [comment]
This was not fixed by #42 

I am using the latest console from the MyGet feed. To simplify testing, I am using the same test assembly multiple times.

The command line `C:\src\nunit\nunit-tests\packages\NUnit.ConsoleRunner.3.5.0-dev-03240\tools\nunit3-console.exe --domain=Multiple .\nunit-v3.dll .\nunit-v3.dll`

fails with

```
Test Run Summary
  Overall result: System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.ConsoleRunner.ColorConsoleWriter.WriteLabel(String label, Object option, ColorStyle valueStyle)
   at NUnit.ConsoleRunner.ColorConsoleWriter.WriteLabelLine(String label, Object option, ColorStyle valueStyle)
   at NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport()
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

It does work with a single assembly or with  `--inprocess` or `--process=Separate`

@CharliePoole do you think this is serious enough to block the release?

**Comment by rprouse** [comment]
My gut feeling is to move this out of the release. If you agree @CharliePoole please remove the milestone. I only had it in this milestone to confirm.

**Comment by CharliePoole** [comment]
This seems pretty serious to me since it's a commonly used option. I guess it depends on whether it's an easy fix or not. Do you have the XML result handly?

**Comment by CharliePoole** [comment]
Oh... it probably wasn't written.

**Comment by rprouse** [comment]
It does work with `--process=Separate` or `--inprocess` which would be the cases it would be used. It doesn't actually make sense with the default `--process=Multiple` since only one assembly is being tested per process anyway. That is why I thought it was less serious even though people won't understand that.

**Comment by CharliePoole** [comment]
I missed that. I agree.

**Comment by rprouse** [comment]
TestResults are written but not very useful since the agents are crashing,

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run start-time="2016-10-06 22:50:09Z">
  <command-line><![CDATA["C:\src\nunit\nunit-tests\packages\NUnit.ConsoleRunner.3.5.0-dev-03240\tools\nunit3-console.exe" --domain=Multiple .\nunit-v3.dll .\nunit-v3.dll]]></command-line>
</test-run>
```

**Comment by rprouse** [comment]
Maybe we should just document valid combinations and close the issue 😄

**Comment by CharliePoole** [comment]
The intent was to accept the option but not really use an aggregating runner if there is just one assembly. I think we should fix it at some point because it shows the aggregating runner is not as robust as it should be.

**Comment by CharliePoole** [comment]
@ChrisMaddock @rprouse Yet another one about `DomainUsage`, which I think we can close.
