### ISSUE TITLE
Error running tests from assembly built using VS2017 csproj file format

### ISSUE THREAD

**Issue by ManfredLange** [nunit/nunit-console#291]
# Steps to reproduce:

1. In Visual Studio 2017 create a new project to create a new project of type "Class library (.NET Standard)" to contain your tests
2. Edit project file and change the value of <TargetFramework> from "netstandard2.0" to "net461"
3. Add nuget package "NUnit"
4. Add another nuget package, e.g. Autofac, and add code that reference a symbol in that other package
4. Add one or more tests to the test project
5. Build and execute tests using NUnit Console

This fails with FileLoadException because the files of the other nuget package, e.g. Autofac, cannot be loaded. They are not copied to TargetDirectory during build. [**Update 16 Sep 2017:** I stand corrected: the files are copied but nunit-console still falls over with the FileLoadException. I'll re-run the scenario to confirm again and rule out other causes.]

Step 1 can be replaced with using "dotnet new classlib" at a command prompt or in a powershell.

# Environment

Visual Studio 2017 version 15.4 with packages NUnit 3.8.1, NUnit.ConsoleRunner 3.7.0 and Microsoft.Net.Compilers 2.3.2 and using dotnet version 2.0.0.

# Expected Behavior

NUnit engine should resolve and load assemblies that the test assembly may depend on, e.g. using the information from obj/project.assets.json of the test project created in step 1 above.

# Notes

This may already be filed as an issue. I searched existing issues but couldn't find anything obvious. I apologize if this is a duplicate.

**Comment by rprouse** [comment]
Excellent report, thanks. As a temporary workaround, although not a great one, you should be able to use the Visual Studio adapter and the `dotnet test` command.

**Comment by ManfredLange** [comment]
@rprouse Thank you for the suggestion, I'll give that a try.

**Comment by CharliePoole** [comment]
@ManfredLange @rprouse Maybe I'm behind the curve. Can one of you explain why this is a bug? NUnit is supposed to work from assemblies and only assemblies. It does nothing to load any assembly but the first one and all resolution is done by the runtime or - in the case of dynamically loaded assemblies - by the appication itself.

If this were to be implemented, how would you run tests deployed for QC for example?

**Comment by ManfredLange** [comment]
Yes, I agree, it should be able to work off an assembly only. However, with the change in the tooling it seems that it is not sufficient to point nunit3-console to the assembly anymore. Execution will fail with the FileLoadException.

I just reproduced this once more, this time building the project using "dotnet build". It builds fine, just like building from VS2017. Those two build options appear to be the same.

I also tried "dotnet publish" (with no further options), which just copies everything into a target folder and unfortunately causes the same error.

Both scenarios, with and without publish, have the dependent packages files right in the folder of the test assembly (eg bin/Debug/net461). Still the runtime doesn't load them automatically.

Interestingly, the required assembly actually does exist in the folder containing the test assembly. It doesn't seem to be loaded, though.

I then tried the following: I wrote a little console app targeting net461 (yup that works) and added some code that loads the test assembly, retrieves the tests from the assembly (using reflection based on full type names) and then executes them. No need for a NUnit reference in the console app. However, I had to add an AssemblyResolve event handler that loaded the assembly (ie the dependency) sitting right next to the test assembly. Without the event handler my little prototype ran into the same problem. With the event handler present it worked just fine.

In my opinion this small experiment seems to suggest that either the console or the engine may need an AssemblyResolve event handler that can handle this scenario. I'd prefer this over my prototype.

For now I'll be using "dotnet test". Unfortunately it doesn't like the solution file because that runs into a separate bug unrelated to NUnit (and already reported and worked on someplace over at the msbuild guys). So, I'll have to execute all tests in sequence for now instead of parallel.

**Comment by rprouse** [comment]
@charliepoole, the issue is that Visual Studio doesn't copy dependent assemblies into the bin directory when it builds using the new project format.

**Comment by CharliePoole** [comment]
Understood. That was my points to why it shouldn't be seen as an NUnit issue.

**Comment by ManfredLange** [comment]
The challenge I see - and that is why I file this issue - is that in the past (prior to the new csproj file format) it was possible to just point to the assembly and nunit-console would run as expected.

Where does that leave the users of nunit-console? Are we saying don't use it anymore and instead add the test adapter to the project and then use "dotnet test"? If that is our answer then nunit-console will no longer be needed for solutions that consist of only the new csproj file format.

Alternatively, if we say that it's because VS doesn't copy the required files, and therefore it's not an NUnit issue, well... I'm not convinced: The files *are* copied! And yet, nunit-console fails with FileNotFoundException while "dotnet test" works. I'll update the issue description to that effect.

I haven't found an option for "dotnet test" though that allows running things in parallel, so we created a little tool that does that automatically for us using the Task Parallel Library and given a list of the solution's test projects.

I'm happy to continue using nunit-console if given some guidance as to what the direction will be. As it stands, we have changed our build/tests scripts to "dotnet test" instead of nunit-console since we now have several projects with tests that use the new csproj file format.

**Comment by ManfredLange** [comment]
Assuming in my quick check I found the correct line of code there appears to be at least one instance where package Microsoft.NET.Test.Sdk [adds an AssemblyResolve event handler](https://github.com/Microsoft/vstest/blob/b91bd795e53806da15ebc6ad6ebd4cc22e710d72/src/Microsoft.TestPlatform.Common/Utilities/AssemblyResolver.cs#L65). This could potentially explain why nunit-console works with this package referenced and fails while the package is absent.

It may also point towards a possible solution in either nunit-console or the nunit engine. Perhaps an appropriate AssemblyResolve event handler would fix the issue. I used this approach as well in my little console app prototype and that executed the tests without the FileLoadException.

**Comment by rprouse** [comment]
> That was my points to why it shouldn't be seen as an NUnit issue.

I would agree in principle, but we aren't going to change the way that .NET builds. We also support it with the `dotnet test` command because of the Microsoft.NET.Test.Sdk resolve handler (thanks for finding that @ManfredLange, I was actually wondered how it worked for .NET Core projects 😄 )

I wonder however if adding the `Microsoft.NET.Test.Sdk` is the correct solution to this, not the workaround. We know it is required for .NET Core/Standard tests, but it might be more correct to say that it is required for tests that use the new CSPROJ format. 

This could be a documentation issue.

**Comment by ManfredLange** [comment]
My two cents: I think adding Microsoft.NET.Test.Sdk is a workaround for the new csproj format. Based on the experiments it appears that all that is needed is an appropriate AssemblyResolve event handler. 

Everything else coming with Microsoft.NET.Test.Sdk may not be needed. But then again, that package may not be too much of a burden in the first place. If that is the case, perhaps making it a dependency for NUnit for projects in the new csproj format might be the best option.

**Comment by CharliePoole** [comment]
@ManfredLange I would have no problem with using an AssemblyResolve handler if we could do it well. What I'm not clear on is how NUnit can know where to look for the assembly in order to resolve it. The engine has no knowledge that it is running in an output directory created by VS and certainly doesn't know what project format was used. Some application that's calling the engine has to tell it. That makes sense to me if the runner is the VS adapter but not so much sense in the general case. However, I may be missing something so feel free to fill me in. 😄 

BTW, we already use an AssemblyResolve event handler for certain things, so if this is done it should probably be added to that one.

**Comment by CharliePoole** [comment]
@ManfredLange BTW - in case you were not aware - I'm on vacation and many of my limited responses are via my cell. Hence, the infrequency and lack of detail in my posts. 😄

**Comment by CharliePoole** [comment]
Needs to be re-confirmed using the 4.0 codebase.

**Comment by CharliePoole** [comment]
@ManfredLange I'm attempting to clean up very old issues like this one. Although it hasn't been worked on explicitly, SDK-format projects are now supported and various other issues are resolved in the latest 3.16 development builds on MyGet.

I think this is probably still valid, but it will help if you can try your case using one of the dev builds. You should use the latest 3.16 build rather than any of the 4.0 builds - I'll be porting changes to main (and 4.0.--devxxxxx) after the 3.16 release.
