### ISSUE TITLE
4.6.2 test library referencing .netstandard 2 library won't work with ValueTuple

### ISSUE THREAD

**Issue by MihaMarkic** [nunit/nunit-console#293]
I'm getting this when running nunit-console (or test runner within VS2017)

System.IO.FileLoadException : Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. 

Test library is a .net 4.6.2 referencing .netstandard 2.0
[Sample code](https://misc.rthand.com/NUnitValueTuple.rar).

Code being tested:
```
public class Class1
    {
        public static (int A, int B) Test => (1, 2);
    }
```

Test method
```
[Test]
        public void Test()
        {
            var test = ClassLibrary1.Class1.Test;
            Assert.IsTrue(true);
        }
```

**Comment by MihaMarkic** [comment]
Upgradin to .net 4.7 doesn't help

**Comment by MihaMarkic** [comment]
(not a big deal since one can always switch to .netcore for hosting unit tests)

**Comment by mikkelbu** [comment]
Hi @MihaMarkic is this still a problem? I just tried to recreate the problem, but on my machine it worked both in the console and using the NUnitAdapter.

**Comment by MihaMarkic** [comment]
@mikkelbu It still seems so. I've opened my test project referenced in first post, did Tests\Run\All Tests and Test Explorer shows the test as Exclamation with a blue background - I assume it means "it didn't run"
Note: I don't care anymore about this problem since I'm using CodeRush and NCrunch which both work.

**Comment by CharliePoole** [comment]
Looks like @ChrisMaddock intended to close this back in 2020!
