### ISSUE TITLE
Nunit-agent-x86 process never exits when created through TestEngineActivator API in 3.4

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#296]
@ethantang95 commented on [Sat Jul 16 2016](https://github.com/nunit/nunit/issues/1679)

When a test engine/runner is created through the TestEngineActivator API and after the test process finishes, the Nunit-agent-x86 process never exits and therefore is taking up memory still. On Task manager, it is listed as an active process.

This happens even after calling

`
            _testRunner.StopRun(false);
            _testRunner.Unload();
            _testEngine.Dispose();
`

The runner is invoked through this code

`
            var testPackage = new TestPackage(_assemblyInfo.AssemblyFullPath);
            AddTestParameters(testPackage, config);
            var filter = CreateTestFilter(config);

```
        _testEngine = TestEngineActivator.CreateInstance();
        _testRunner = _testEngine.GetRunner(testPackage);

        var listener = new RecordKeepingTestListener(_assemblyInfo.Assembly, this);

        var result = _testRunner.RunAsync(listener, filter);
```

`

The tests themselves do successfully finishes and no uncaught exceptions are thrown in this process. In this case, the same test package can then be ran again through the TestEngineActivator but the old test package process is still in memory

**Comment by CharliePoole** [comment]
Just adding a clarification here to @ethantang95's comment...

The agent process is created through the engine API at the point a test is loaded, not when TestEngineActivator is used to create an instance of the engine.

Additionally, the title seems to suggest that there is some other way to create the agent process other than through the API. There isn't - or at least there isn't any other supported method to do it.

**Comment by ChrisMaddock** [comment]
This may be fixed by https://github.com/nunit/nunit-console/pull/322.

@ethantang95 - if this is still causing you an issue, would you check? We can reopen if there's still a problem.
