### ISSUE TITLE
Agents do not respect the Console WORK parameter when writing log file

### ISSUE THREAD

**Issue by Jevonius** [nunit/nunit-console#300]
I'm digging into #225 and using the `--work` parameter to write the log files to a set location outside of our TC working folder (so that they don't get cleared on the next build). Unfortunately the agent process doesn't get passed this value, so just writes the log file to the default execution location (compare https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/TestEngine.cs#L90 to https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit-agent/Program.cs#L80).

Seems a fairly minor fix (pass across the `--work` parameter, add it as an expected parameter), but wanted to check what the expected/desired behaviour was before doing it and creating a PR?

**Comment by ChrisMaddock** [comment]
I would agree this is an oversight - thanks for offering the PR!

**Comment by CharliePoole** [comment]
This is left over from the time when we didn't use the Work directory for trace output. The console itself and the test framework all use the work directory but the agent was not converted to use it. FWIW the test framework output is what should be of greatest interest to users. The console and agent traces are really only useful for debugging NUnit. Nevertheless, they should all be in the same place!
