### ISSUE TITLE
When test writes something to the stdErr there is no guaranteed way to link a test-output event to a target test using ITestEventListener

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#305]
For example:

- Unit test `SuccessfulStdErrorTest` has code: `System.Console.Error.WriteLine("errorout");`

- ITestEventListener receives the following events:
```
<start-test id="0-1001" parentId="0-1000" name="SuccessfulStdErrorTest" fullname="Foo.Tests.UnitTests1.SuccessfulStdErrorTest" type="TestMethod" />

<test-output stream="Error" testname="Foo.Tests.UnitTests1.SuccessfulStdErrorTest"><![CDATA[errorout
]]></test-output>
```

`test-output` has no information id/parentId about a target test and there is no way to attach this error output. It is important to note that these events could be received from different tests simultaneously.

See this [sample](https://github.com/nunit/nunit-console/files/1418559/sample.zip)

**Comment by CharliePoole** [comment]
We should examine how the console handles this in its own output and see whether the listener can do the same. If a change were needed, however, it would be in the framework. The engine and console only pass the XML received.

**Comment by ChrisMaddock** [comment]
I don't believe the console has any need to tie stderr input back to a specific test - it just prints it alongside the test name, doesn't it?

The adapter, I think relies on unique test names, which we know causes us problems there. Charlie - does the GUI log test-output? And if so, how does that do the association?

This seems like a sensible change to me - unless we're missing something.

**Comment by CharliePoole** [comment]
I'm saying that the console manages to associate error output with the test. If you use labels, we display the test name over it. The fact that test names are non-unique causes us no practical problem. JB decided it was a problem for some reason and created a bunch of ids and parent ids that we don't need in NUnit itself. We modified several events to give them what they wanted. Most likely, they won't want to change their design so they probably need it in the `<testout>` element as well.

But again... it's still not a console issue. 😃

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit #2516](https://github.com/nunit/nunit/issues/2516) via [**ZenHub**](https://www.zenhub.com/)
