### ISSUE TITLE
Run randomaly parallel test on cmd with nunit console 

### ISSUE THREAD

**Issue by rutin31** [nunit/nunit-console#307]
Hi
My nunit project is built like this:
[TestFixture("iphone.json"]
[TestFixture("android.json"]
    [Parallelizable(ParallelScope.Fixtures)]
    public class LoginTest
    {
[Test, Order(1)]
test1()
{}

[Test, Order(2)]
test2()
{}

[Test, Order(3)]
test3()
{}

}

Test explorer look like this:
LoginTest(iphone.json)
    test1
    test2
    test3   
LoginTest(android.json)
    test1
    test2
    test3  
From test explorer I can to run selected tests

To run all tests from cmd with nunit console I used:
C:>nunit3-console C:MyProject\bin\debug\LoginTest.dll

How can I run the selected tests from nunit console on cmd

**Comment by CharliePoole** [comment]
You can use either the `--test` or the `--where` option on the command-line to run selected tests. See https://github.com/nunit/docs/wiki/Console-Command-Line for details of the options.

**Comment by rutin31** [comment]
How can I run test1 for iphone and test1 for android together

**Comment by CharliePoole** [comment]
For your example, assuming there are no other tests...

```
C:>nunit3-console C:MyProject\bin\debug\LoginTest.dll --where "test=~test1"
```

Test Selection Language is very powerful and requires some study to use it. Please read the docs!!!
