### ISSUE TITLE
No driver found if framework assembly reference has uppercase characters

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#309]
.NET assembly references are not case sensitive, but the engine fails to find a driver unless the assembly reference is precisely the lowercase string `"nunit.framework"`.

https://github.com/nunit/nunit-console/blob/416b54d2a215466a861b3fbea82adeb3c820ec62/src/NUnitEngine/nunit.engine/Drivers/NUnit3DriverFactory.cs#L32-L42
We should be doing something similar to:

```cs
return NUNIT_FRAMEWORK.Equals(reference.Name, StringComparison.OrdinalIgnoreCase) && reference.Version.Major == 3;
```

Besides the correctness issue, this prevents us from ever deciding to ship an `NUnit.Framework.dll` (using the conventional namespace styling) in any packaging form.

**Comment by CharliePoole** [comment]
#jnm2 Can you reproduce this error? Or is there some reference confirming that .NET recognizes reference without respect to case on all platforms, even those where the file system mixes case? That would seem to imply that the location of the actual assembly files doesn't use the file system., which would be weird!

As to your final comment, I sincerely hope I'm gone from the scene before we would ever use such an awful naming convention! 😈

**Comment by jnm2** [comment]
Yes, sunk three hours trying everything I could think of before I realized what was happening.

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-names:

> The runtime treats assembly names as case-insensitive when binding to an assembly, but preserves whatever case is used in an assembly name. Several tools in the Windows Software Development Kit (SDK) handle assembly names as case-sensitive. For best results, manage assembly names as though they were case-sensitive. 

I think we should follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle). If someone references `Nunit.framework.dll` for _whatever_ reason, why should the engine fail to run the tests?

Haha! What's wrong with the naming convention? You see it absolutely everywhere in using statements... I don't know of any other project that opts for kebab-casing over pascal-casing.

**Comment by CharliePoole** [comment]
@jnm2 Never heard kebab-case before and had to spend some time on google before I was convinced it isn't a racist reference. Apparently, the words look like the are on a skewer - ie kebab. However, the name appears to be a Wikipedia-created neologism going back only to 2012 and definitely sounds like it was chosen to deprecate the usage. Back in the day, it was just "the way things are done" for filenames.

You're obviously right, however, in terms of how we should examine the reference. It doesn't seem to be very critical however, since our users have to directly reference our assembly in order to use it. I'd fix it whenever we redo the loading of drivers for whatever reason - and of course it applies to all frameworks, not just nunit.

**Comment by lasthero** [comment]
Hi:

I am a first-timer here and I'd like to contribute to this project. This looks like a quick 1 line of code change (as already pointed out by @jnm2 ). Can I work on this one? Thanks.

Chih-Ho

**Comment by jnm2** [comment]
@lasthero For sure! I read back over what Charlie said and had a quick look. These lines should have the exact same fix:

https://github.com/nunit/nunit-console/blob/416b54d2a215466a861b3fbea82adeb3c820ec62/src/NUnitEngine/nunit.engine/Drivers/NUnit2DriverFactory.cs#L53-L57

https://github.com/nunit/nunit-console/blob/416b54d2a215466a861b3fbea82adeb3c820ec62/src/NUnitEngine/nunit.engine.netstandard/Drivers/NUnitNetStandardDriverFactory.cs#L39-L42

https://github.com/nunit/nunit-console/blob/416b54d2a215466a861b3fbea82adeb3c820ec62/src/NUnitEngine/nunit.engine.netstandard/Drivers/NUnitNetStandardDriver.cs#L82

Are you good with that?

**Comment by lasthero** [comment]
@jnm2:
I can give them a shot 😄

**Comment by jnm2** [comment]
Alright, it's yours! I'm assigning the issue to myself to keep track of it. Let us know if you need any help!

**Comment by lasthero** [comment]
@jnm2 - just created a pull request for this issue. Please let me know with any comments. Thanks!

Chih-Ho
