### ISSUE TITLE
--where: namespace !~ 'my.name.space' not supported/hangs in 3.2.0

### ISSUE THREAD

**Issue by avikenjale** [nunit/nunit-console#310]
Currently I have installed on my development machine nunit 3.7, where I can exclude any project/namespace/class using command `nunit3-console my.solution.file.sln /config:Release --where: "namespace !~ 'my.name.space'"`. This works perfectly in seconds. however on my build server installed version is 3.2.0 where same command line arguments runs test step infinitely.  Is the only solution to install new version or is there any alternative?

**Comment by CharliePoole** [comment]
The namespace keyword was only added in NUnit and NUnit-Console 3.7 - you need both to make it work.

You may be able to use `test !~ 'my.name.space'` with the same effect, depending on the structure of your namespaces.

**Comment by avikenjale** [comment]
@CharliePoole,  I tried after your suggestion, however it throws error saying these tests are not available under other projects, as I am running `nunit3-console` against `.sln` file.

**Comment by CharliePoole** [comment]
That's a different matter. Are you saying this works well on your development machine using the solution file? In that case, I'd say it's another bug, which was fixed in the newer release. Is there a reason to be using an old version of nunit on the server? There have been a lot of bug fixes since 3.2, which was released in early 2016 and it's a bit of an anti-pattern to be using different tool versions on the dev machines and the server.

**Comment by avikenjale** [comment]
I agreed to your point. However couldn't understand one thing, thru Visual studio 2015 I have reSharper, where not sure which nUnit test used, however, test run - coverage works perfectly fine, however when I use nunit3-console (3.2)  as `nunit3-console my.solution.file.sln /config:Release` it is looking for tests under normal class-library .dll files whereas `nunit3-console my.solution.file.sln` (expecting debug mode)  works and not looking for tests under normal class-library files. 
> NOTE: I installed 3.7 on local development machine, and everything works perfectly. Just wanted to know what 3.2 fails in `release mode.`

**Comment by CharliePoole** [comment]
That's easy... nunit-console is doing a much simpler job. The only kind of tests that it can run are nunit (v2) tests. So it just takes each assembly and tries to load it as an nunit test file. If it won't load, it's not such a file and can be ignored.

OTOH, nunit3-console can run __any__ test framework for which a driver is provided. We provide a builtin nunit 3 driver and a user-loadable extension for nunit 2. Someone with the need and skill can write a driver for any other framework. So, if you point nunit3-console at an assembly and we don't find a driver that can accept it, that means it is either not a test file or is a test file using some framework we don't understand. We give a message indicating that no driver could be found, which might be slightly obscure.

OTOH, if you tell us to run from a solution file and we can't load the test, there's a question about whether to give an error message or not. We can't tell if you intended a certain file as a test (so we should say we can't find the driver) or if it just happens to be present in the solution (so we should ignore it). In 3.2 we always gave an error message. In later releases, we pass in a flag to indicate that no error should be given in thise cases.
