### ISSUE TITLE
Test cases are not running when using --test option

### ISSUE THREAD

**Issue by jamesaslett1985** [nunit/nunit-console#316]
Hi,

I am using NUnit Console Runner 3.7.0 to execute test cases written in Selenium Webdriver C#. If I only specify the assembly then all of my test cases will execute:

`nunit3-console "D:\Visual Studio Solutions\Selenium WebDriver\MySolution\MyProject\bin\Debug\MyAssembly.dll" `

If I then introduce the _--test_ option in order to only run a specific test...

`nunit3-console --test=MyTestCase "D:\Visual Studio Solutions\Selenium WebDriver\MySolution\MyProject\bin\Debug\MyAssembly.dll" `

...then nothing happens and the test is not run. I have attached the TestResult.xml output.

How can I get around this?

Thanks

[TestResult.txt](https://github.com/nunit/nunit-console/files/1490920/TestResult.txt)

**Comment by ChrisMaddock** [comment]
You need to be using a fully qualified name for the —test option. Namespace and all, does that help? 😊

**Comment by jamesaslett1985** [comment]
Thanks Chris. I've tried `--Solution.Namespace.Test` and `--Namespace.Test` to no avail - am I still missing something? :)

**Comment by ChrisMaddock** [comment]
Try running with —explore, which will list all your tests by name, and then you can work out exactly what the string should be. :-)
