### ISSUE TITLE
Order Attribute in --testlist options

### ISSUE THREAD

**Issue by rodolfo-asantos** [nunit/nunit-console#317]
Is it possible to create an execution order only inside the file in the --testlist option? That is without setting the order attribute in the code?

**Comment by CharliePoole** [comment]
No, the `--testlist` option contributes to the filter that is used when running tests and that merely filters the tests. The order in which they are run is non-deterministic in principle, unless the `OrderAttribute` is used.

In fact, there really isn't anything, even at the API level, to allow a client to control the test execution order unless the client simply makes several different test runs. It might be something to consider in the future, but I would see it as more of a gui feature than for the console in any case.
