### ISSUE TITLE
Handling carriage return and line feeds in test description for tests results xml output file

### ISSUE THREAD

**Issue by EllaVader** [nunit/nunit-console#324]
I"m using the Description property on the Test attribute.  Is there a way to format a long description to have new lines in them?  When I try to add them via "\n"  or "\r" the results in the TestResults.xml file have them look like this `"&#xD; ` and  `&#xA;`  Is there a way to actually have line brakes in the description?

Here is an example of what I"m talking about:  
This:
`[Test, Description("Navigate to known vehicle, and edits the MSRP and selling price on the VLP.\n" +
"It then verifies that the prices was updated on the VDP Pricing tab and then navigates back to the VLP to verify that the price is correct.\n" +
"Additionally, it goes into the history > data changes tab to verify that there is an entry on the data changes tab for the pricing changes")]`

produces this in the TestResults.xml file
`<property name="Description" value="Navigate to known vehicle, and edits the MSRP and selling price on the VLP.&#xA;It then verifies that the prices was updated on the VDP Pricing tab and then navigates back to the VLP to verify that the price is correct.&#xA;Additionally, it goes into the history &gt; data changes tab to verify that there is an entry on the data changes tab for the pricing changes" />`

**Comment by ChrisMaddock** [comment]
Where did you want to see these line breaks in the description? 🙂 I believe this is the correct way to encode linebreaks in xml - in the same way as your `history > data` is encoded as `history &gt; data`.

**Comment by CharliePoole** [comment]
I agree with @ChrisMaddock. The XML for the description contains the line break properly encoded. It's up to the program that displays the description to decode that and display it correctly. If you are simply looking at the XML itself, then you see the encoded version.

**Comment by ChrisMaddock** [comment]
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂
