### ISSUE TITLE
NUnit 3 console runs test for nunit.framework.dll v2 in parallel mode

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#33]
Is it expected behavior? If it is true the TC extensions works incorrectly for this case.
As I know nunit.framework.dll v2 have no attributes for parallel mode. And this issue is critical for the TC extension. Related issue is https://github.com/nunit/teamcity-event-listener/issues/14

**Comment by rprouse** [comment]
I believe that NUnit 3 will run multiple NUnit 2 test assemblies in parallel, but the tests within the v2 tests will not be run in parallel. Is the trouble with multiple assemblies?

**Comment by NikolayPianikov** [comment]
Yes, the the trouble with multiple assemblies.

**Comment by rprouse** [comment]
Why is this a problem for the TC extension? v3 tests run the same way. I assume you handle that?

**Comment by NikolayPianikov** [comment]
Extensions receives 2 message one after another:

1:

`<start-suite id="1-1005" name="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Common.Test.dll" fullname="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Common.Test.dll" />`

2:

`<start-suite id="1-1431" name="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Web.Test.dll" fullname="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Web.Test.dll" />`

After that 

3:
`<start-suite id="1-1006" name="MAP" fullname="MAP" />`

Question: What assembly corresponds `<start-suite id="1-1006" name="MAP" fullname="MAP" />` ?
We have a bunch unstructured messages from different assemblies

**Comment by NikolayPianikov** [comment]
Some kind of XML but from several different files at the same time :)

**Comment by CharliePoole** [comment]
The issue is that the v2 driver is using the same prefix for both assemblies. Both drivers should get their prefixes from a common source.

**Comment by ChrisMaddock** [comment]
Fixed in #564 I believe.
