### ISSUE TITLE
Cant filter on custom attributes via command line where clause

### ISSUE THREAD

**Issue by jmatthews79** [nunit/nunit-console#333]
I have a custom attribute I am using on my nunit tests:

   ` [Impact(Impact.High)]`

The attribute is an enum, here the class that defines that attribute:

   ```
 public enum Impact
    {
        VeryHigh,
        High,
        Low,
        VeryLow
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public class ImpactAttribute : PropertyAttribute
    {
        public Impact ImpactRatio { get; private set; }

        public ImpactAttribute(Impact ratio) 
        {
            this.ImpactRatio = ratio;
        }
    }
```

When I try to call this from the command line using the nunit-console runner it is never picked up. I think it is maybe because it is an enum not a string. The documentation says to call a custom property like:

 `   nunit3-console mytest.dll --where "cat == Urgent || Priority == High"
`
I've tried all types of ways of calling this and its never recognized:

```
    --where "Impact == Impact.High"
    --where "Impact == High"
    --where:Impact==Impact.High
    --where:Impact==High
    --where:Impact=~Impact.High
```

Any ideas? I would like to keep this an enum because there are going to be a lot of people writing tests and if I allow them to put a string value in then I could lose consistent values for this attribute and then filtering may not get all the tests I want.

I also tried this with a string getting rid of the enum and it doesnt work either? I tried on the class and method level

**Comment by CharliePoole** [comment]
Since you don't call any base constructor, you are not actually creating a property. Once you create it, Impact==High should work.

**Comment by mikkelbu** [comment]
AFAICT from [the documentation](https://github.com/nunit/docs/wiki/Property-Attribute) you should either call the base class or set the property dictionary directly via `Properties`

**Comment by jmatthews79** [comment]
@CharliePoole here is my updated code:

 ```
   {
        VeryHigh,
        High,
        Low,
        VeryLow
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public class ImpactAttribute : PropertyAttribute
    {

        public ImpactAttribute(Impact level) : base(level) { }

    }
```

I get this from the runner:

```
Server stack trace: 
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
```

**Comment by jmatthews79** [comment]
@CharliePoole and @mikkelbu I also tried:
```

 [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class RiskPriorityAttribute : TestFixtureAttribute
    {
        /// <summary>
        /// Can be of values 1, 2, 3, 4, 6, 8, 9, 12, 16
        /// </summary>
        public string priority { get; set; }

        public RiskPriorityAttribute(string riskPriority)
        {
            this.priority = riskPriority;
        }
    }

```
and decorated my test fixture like:

`[RiskPriority("4")]`

and tried to call like: 

` --where "RiskPriority==4"`

I can use the --params options and other options with no problems. Like I said I am new to programming so I a probably just messing up the code somewhere,

also tried:
```

  [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class RiskPriorityAttribute : TestFixtureAttribute
    {
        /// <summary>
        /// Can be of values 1, 2, 3, 4, 6, 8, 9, 12, 16
        /// </summary>
        public string priority { get; set; }

        public RiskPriorityAttribute(string riskPriority) : base(riskPriority)
        {
            this.priority = riskPriority;
        }
    }
```

**Comment by mikkelbu** [comment]
@jmatthews79 I did some more digging (I've never used PropertyAttributes), and if I had
```csharp
  public enum ImpactEnum
  {
    VeryHigh,
    High,
    Low,
    VeryLow
  }

  [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
  public class ImpactAttribute : PropertyAttribute
  {
    public ImpactAttribute(ImpactEnum ratio)
      : base(ratio)
    {
    }
  }
```
and some tests decorated with `ImpactAttribute` then I also got an exception with the same stacktrace when trying to filter for a particular value. The exception message was "System.InvalidCastException : Unable to cast object of type 'TestPropertyAttribute.ImpactEnum' to type 'System.String'" and some debugging showed that it originated from here https://github.com/nunit/nunit/blob/fd88391412747dc12904a8c5addbe0b4e83d9d23/src/NUnitFramework/framework/Internal/Filters/PropertyFilter.cs#L55-L65 where we assume that all values are strings. The [Test-Selection-Language documentation](https://github.com/nunit/docs/wiki/Test-Selection-Language) also somewhat implicitly states that filtering will only work on string value
> When defining a property, you should keep the limitation to string values in mind. For example, a PriorityAttribute taking values of "High", "Medium" and "Low" could be used for filtering, while one that took the integers 1, 2 and 3 could not.

However, we can make a minor hack above and change `: base(ratio)` to `: base(ratio.ToString())` then it will be possible to do filtering like `.\nunit3-console.exe <PATH_TO_DLL> --where:Impact==High`

**Comment by jmatthews79** [comment]
@mikkelbu thanks for the response. That did the trick you rock!

**Comment by mikkelbu** [comment]
@jmatthews79 You are most welcome. Ps. I've also made a slight improvement to the documentation 😄 .

**Comment by CharliePoole** [comment]
Yeah... It's really not possible for a filter to have anything but strings. Everything we filter on is also a string with the possible exception of properties. Since you could be using the property for some other purpose, we allow other values, but for selection, as currently defined, only strings will do.
