### ISSUE TITLE
fileOpen dialog loose focus on opening

### ISSUE THREAD

**Issue by dimm23** [nunit/nunit-console#334]
In selenium test running by nunit3-console.exe i'm opening fileOpen dialog for uploading file, but when fileOpen dialog is opened it loose focus and test cant enter file path.
This is an example:

Driver.FindElement(By.XPath("//div[@class='fileuploader-input']")).Click(); // it open fileOpen dialog
SendKeys.SendWait(product.photo_url);
SendKeys.SendWait(@"{ENTER}");

(From Visual Studio it works correctly)

**Comment by jnm2** [comment]
I wonder what is making the difference? `[Apartment(ApartmentState.STA)]`?

**Comment by mikkelbu** [comment]
Closing this, due to lack of activity. Feel free to comment further, the team will still get the notifications, and the issue can be reopened if new information appear. 🙂

**Comment by jnm2** [comment]
@dimm23 I'm not familiar with Selenium, but I think a minimal repro project would be all I would need to be able to come back with an answer.

**Comment by dimm23** [comment]
@jnm2 Project placed on server and after connecting to it by RDP problem is reproducing. Looks like focus switchs to connection window.

**Comment by jnm2** [comment]
@dimm23 Not sure which connection window you mean. Did you find the cause outside NUnit, or is it still something we have to fix?
