### ISSUE TITLE
What's the target release date for 3.8?

### ISSUE THREAD

**Issue by blachniet** [nunit/nunit-console#339]
What's the target release date for 3.8?

I originally asked this question in the Gitter chat room: https://gitter.im/nunit/nunit?at=5a4fd1926117191e612dbed6.

**Comment by rprouse** [comment]
I hope to get the release out later this month. I am currently targeting the 26th, but may move it up if there are no high priority issues we want to get in. @nunit/framework-and-engine-team can you flag issues that we should be watching for the release?

**Comment by blachniet** [comment]
Thank you!

**Comment by ChrisMaddock** [comment]
There are two remaining on my radar. The first is the open PR to finish off the app domain unload changes, the second is the settings dict issue. Im happy for anyone else to take over the second if they have time - hoping to get both tied up in the next couple of weeks.

Ideally I’d like to also get in improved error handling for socket exceptions, and a fix for the nunit/sln process model, as I’m suspicious that might be the cause of some of them. Both of those are unlikely to fit in my available time, however! ☹️

**Comment by mikkelbu** [comment]
@ChrisMaddock I can probably take over the second one, but I'm a bit unsure what the problem is. But I will write my question in #285.
