### ISSUE TITLE
NUnit-Console : providing a file containing space in parameters value does not work

### ISSUE THREAD

**Issue by marshall777** [nunit/nunit-console#344]
Hello,

I am trying to run nunit-console.exe using a file containing test parameters.
Some parameters value contains spaces and it seems like it does not work.

To do so, I run nunit-console with :
```powershell
.\nunit3-console.exe ..\xxx.Tests.dll @..\myfile
```

And myfile contains :
```
-p=Corporation1Name=Name of the first corporation
```

When I run this, it seems like NUnit takes "Name" as the parameter value and considers what comes after each space as another assembly file to test :
```
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    ..\xxx.Tests.dll
    of
    the
    first
    corporation
```

I tried using double quotes to enclose parameter value but it does not work either. However, when I use double quote into the command line (not using the @FILE syntax), it works well.

e.g. this works well :
```powershell
.\nunit3-console.exe ..\xxx.Tests.dll -p=Corporation1Name="Name of the first corporation"
```

but this does not work :
```powershell
.\nunit3-console.exe ..\xxx.Tests.dll @..\myfile
```
with myfile containing :
```
-p=Corporation1Name="Name of the first corporation"
```

I also tried to run these commandes using cmd.exe instead of powershell.exe but the exact same behavior appear.

Could you confirm this is indeed a bug or is there something wrong in the syntax I am using ?

Thanks

**Comment by CharliePoole** [comment]
Try this

```
-p "Corporation1Name=Name of the first corporation"
```

**Comment by marshall777** [comment]
This solves my issue, Thanks for the tip
