### ISSUE TITLE
Could not load file or assembly when I run tests for x86 assembly without any additional arguments

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#35]
Following error occurs: Could not load file or assembly 'foo.tests.dll, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
[1102895896.zip](https://github.com/nunit/nunit-console/files/425040/1102895896.zip)

When I added  -x86 argument tests work fine. Is it expected behavior?

**Comment by rprouse** [comment]
NUnit should auto-detect that the assembly is x86. Is the test assembly actually AnyCpu but referencing an x86 assembly? If so, we cannot detect that it should be x86.

If not, is the assembly originally C++/CLR, C# or another language? Unfortunately, the PE headers are different depending on the language.

Could you also run corflags on foo.tests.dll? `corflags foo.tests.dll`

You should get this for an x86 C# assembly,

```
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.6.1055.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v2.0.50727
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x3
ILONLY    : 1
32BITREQ  : 1
32BITPREF : 0
Signed    : 0
```

**Comment by NikolayPianikov** [comment]
@rprouse 

I have it:
Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x3
ILONLY    : 1
32BITREQ  : 1
32BITPREF : 0
Signed    : 0

Integration tests use Roslyn to create mocks and they worked some short time ago

**Comment by rprouse** [comment]
I successfully ran with the 3.4.1 install and with the latest master build, but using your Zip file fails. I am guessing that there is something wrong with the packaging, but I don't have time to look at it until later.

**Comment by NikolayPianikov** [comment]
@rprouse thank you. Yes it works on the master branch, but not for the last MyGet package. May be it related to https://github.com/nunit/nunit-console/issues/30

**Comment by NikolayPianikov** [comment]
It is working too

**Comment by rprouse** [comment]
Sounds like this is fixed now. Closing.
