### ISSUE TITLE
NUnit Console can't be run on a Mapped Network Drive

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#358]
@CharliePoole commented on [Sun Oct 26 2014](https://github.com/nunit/nunit/issues/311)

This was originally an nunit-console issue...

nunit-console.exe throws the following error while i tried to execute from Mapped Network Drive

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NUnit.ConsoleRunner.Runner' threw an exception. ---> System.Security.SecurityException: That assembly does not allow partially trusted callers. at NUnit.ConsoleRunner.Runner..cctor() The action that failed was: LinkDemand The assembly or AppDomain that failed was: nunit-console-runner, Version=2.6.3.13283, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77 The method that caused the failure was: NUnit.Core.Logger GetLogger(System.Type) The Zone of the assembly that failed was: Internet The Url of the assembly that failed was: file:///Z:/jenkinsworkspace/workspace/FlashUpload/tools/NUnit/lib/nunit-console-runner.DLL --- End of inner exception stack trace --- at NUnit.ConsoleRunner.Runner.Main(String[] args) at NUnit.ConsoleRunner.Class1.Main(String[] args)

i tried the following methods to fix.

added loadFromRemoteSources enabled="true" in nunit-console.exe.config
But the change did not solve the problem.

---

@CharliePoole commented on [Thu Jan 29 2015](https://github.com/nunit/nunit/issues/311#issuecomment-71943718)

This has been a long-standing situation with NUnit. The only way to run NUnit from a mapped drive is to specifically enable full trust on your machine.

---

@ChrisMaddock commented on [Tue Jan 23 2018](https://github.com/nunit/nunit/issues/311#issuecomment-359921117)

I believe this just came up here: https://stackoverflow.com/questions/48402851/nunit-console-incorrect-parameter

Moving this issue to the console repo. I'm not sure if it's something we will deal with any time soon - but we should keep it tracked.

**Comment by CharliePoole** [comment]
@rprouse @mikkelbu @jnm2 

Chris considered this a bug, whereas I thought it was a long-time limitation of NUnit, which does no harm provided foliks are aware of it. What do you all think?

**Comment by CharliePoole** [comment]
This is now over four years old and has had no further input. I'm going with my own feeling that it's a long-time limitation of NUnit and not a problem for most users. The workaround is to run under full trust.
