### ISSUE TITLE
TestExplorer in Visual Studio 15.5.x navigates to Feature.cs code behind 

### ISSUE THREAD

**Issue by QAGal2** [nunit/nunit-console#362]
Given NUnit.Console* 3.7, NUnit 3.9.0,  Visual Studio 15.5.4 (or 15.5.2), SpecFlow & SpecFlow.NUnit 2.2.1
Then double click on a test in Test Explorer,  brings us to the feature.cs code behind file instead of the feature file. This issue began after I upgraded from Visual Studio 15.4.4 (no other changes).

**See Specflow Thread**: https://github.com/techtalk/SpecFlow/issues/990 
      community is pointing cause to NUnit

[DemoFeatureIssue.zip](https://github.com/nunit/nunit-console/files/1667773/DemoFeatureIssue.zip)
Video of behavior: https://www.screencast.com/t/LG6GTFbWGIny

**Comment by rprouse** [comment]
Visual Studio 15.5 handles source locations now whereas NUnit handled it previously. On my phone right now, but will report to the VS team. This issue also belongs in the adapter repo, I will move it there.

**Comment by OsirisTerje** [comment]
@rprouse VS doesnt quite handle it yet, it is still behind a feature flag, so this sounds like our stuff.  But, agree, belong so far in adapter repo.

**Comment by rprouse** [comment]
Thanks @OsirisTerje, moving to the adapter repo. @QAGal2 please follow the issue there.

**Comment by rprouse** [comment]
This issue was moved to nunit/nunit3-vs-adapter#441
