### ISSUE TITLE
nunit3-console.exe v3.8.0 does not support .sln files

### ISSUE THREAD

**Issue by Heteroculturalism** [nunit/nunit-console#374]
I just upgraded the NUnit.ConsoleRunner Nuget package from 3.7.0 to 3.8.0.  When I did so and ran

<Path to Nuget Packages>\NUnit.ConsoleRunner.3.8.0\tools\\nunit3-console.exe <Path to .sln file> --config=UnitTest 

It says "File type is not supported".  Has support for solution files (.sln) been dropped as of 3.8.0?

**Comment by CharliePoole** [comment]
It sounds like you don't have the `vs-project-loader` extension installed. Perhaps it was wiped out when you upgraded.

**Comment by ChrisMaddock** [comment]
Just tried - I can't reproduce this.

@Heteroculturalism - please follow Charlie's advice above and check the extension is installed. (Try `nunit3-console --list-extensions` to verify.) We can reopen this issue if there's more to add.

**Comment by abdulkhameer** [comment]
Hi All,
I am using Nunit Console Runner 3.8.0 to execute my nunit test cases. It is working fine if i run the project dll in my development machine (OS-win 7, Chrome version v65, VS2015) but if i copy all the set up into my test PC (OS -Win10, Chrome 65,VS2015) it is giving me The HTTP request to the remote WebDriver server for URL http://localhost:50665/ session timed out . 

Please help me to understand what is the difference in Environment.

**Comment by mikkelbu** [comment]
Hi @abdulkhameer 
Please create a new issue as this does not sound like it is related to "File type is not supported". That being said you'll need to provide some more information for us to be able to help you. "WebDriver server for URL http://localhost:50665/ session timed out" does not sound like a problem in the console.

**Comment by jgrossrieder** [comment]
I just got the same issue. Upgraded from Console runner 3.5.0 to 3.8.0.

I tried the `--list-extensions` command:
```
D:\Dev\BB>"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --list-extensions
NUnit Console Runner 3.8.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.42000

Installed Extensions
  Extension Point: /NUnit/Engine/NUnitV2Driver
    Extension: NUnit.Engine.Drivers.NUnit2FrameworkDriver
  Extension Point: /NUnit/Engine/TypeExtensions/IService
  Extension Point: /NUnit/Engine/TypeExtensions/ITestEventListener
    Extension: NUnit.Engine.Listeners.TeamCityEventListener (Disabled)
  Extension Point: /NUnit/Engine/TypeExtensions/IDriverFactory
  Extension Point: /NUnit/Engine/TypeExtensions/IProjectLoader
    Extension: NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader
      FileExtension: .nunit
    Extension: NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader
      FileExtension: .sln .csproj .vbproj .vjsproj .vcproj .fsproj
  Extension Point: /NUnit/Engine/TypeExtensions/IResultWriter
    Extension: NUnit.Engine.Addins.NUnit2XmlResultWriter
      Format: nunit2
```
Seems to have everything to open my sln

**Comment by mikkelbu** [comment]
@jgrossrieder 
I just downloaded the latest stable version of the nuget package NUnit.Console (version 3.8). If I call with `--list-extensions` then I get the same extensions as you, but on my machine I'm possible to run against a sln-file.Can you tell if there is anything special about the sln or can you provide a minimal example? Also try to run with the option `--trace=verbose` and see if there is anything interesting in the `InternalTrace.YYYY.log` file.

```
PS C:\Users\Mikkel\Source\Repos\Warn\packages\NUnit.ConsoleRunner.3.8.0\tools> .\nunit3-console.exe C:\Users\Mikkel\Source\Repos\Warn\Warn.sln
NUnit Console Runner 3.8.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Users\Mikkel\Source\Repos\Warn\Warn.sln


Errors, Failures and Warnings

...

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\Users\Mikkel\Source\Repos\Warn\packages\NUnit.ConsoleRunner.3.8.0\tools
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.7.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Failed
  Test Count: 5, Passed: 1, Failed: 1, Warnings: 3, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2018-08-28 17:26:48Z
    End time: 2018-08-28 17:26:49Z
    Duration: 1.078 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by CharliePoole** [comment]
I seem to remember that we give the "not recognized" message whenever there is an exception we don't understand... unless that has been fixed in the code.

**Comment by abdulkhameer** [comment]
Hi All, 
Please see the below link.
https://github.com/SeleniumHQ/selenium/issues/5457
I am facing same issue in my win 10 test PC. my nunit scripts run only immediate restart of pc. If i try after some time it wont work. What is blocking me after some time for same scripts. 
Can you guys help me please. it has become severity issue for my automation .

Other Info:
Win 7 (Dev or Test network) : Working
Win 10 (Test) : Not working
Win 10 (Dev) : working

**Comment by mikkelbu** [comment]
Hi @abdulkhameer 
This issue is about "nunit3-console.exe v3.8.0 does not support .sln files" as the titel states, so please open a new issue. That being said, I don't find any information in SeleniumHQ/selenium#5457 that indicates that this is an NUnit problem. I rather sounds like a Selenium problem

**Comment by jgrossrieder** [comment]
@CharliePoole So how can I find the real error? I can't find it anywhere.

@mikkelbu I tried to run the same with version 3.9. Here are the files:

> InternalTrace: Initializing at level Debug
> 16:15:01.066 Debug [ 1] ServiceManager: Added SettingsService
> 16:15:01.066 Debug [ 1] ServiceManager: Added DomainManager
> 16:15:01.066 Debug [ 1] ServiceManager: Added ExtensionService
> 16:15:01.066 Debug [ 1] ServiceManager: Added DriverService
> 16:15:01.066 Debug [ 1] ServiceManager: Added RecentFilesService
> 16:15:01.066 Debug [ 1] ServiceManager: Added ProjectService
> 16:15:01.066 Debug [ 1] ServiceManager: Added RuntimeFrameworkService
> 16:15:01.066 Debug [ 1] ServiceManager: Added DefaultTestRunnerFactory
> 16:15:01.076 Debug [ 1] ServiceManager: Added TestAgency
> 16:15:01.076 Debug [ 1] ServiceManager: Added ResultService
> 16:15:01.076 Debug [ 1] ServiceManager: Added TestFilterService
> 16:15:01.076 Info  [ 1] ServiceManager: Initializing SettingsService
> 16:15:01.076 Info  [ 1] ServiceManager: Initializing DomainManager
> 16:15:01.076 Info  [ 1] ServiceManager: Initializing ExtensionService
> 16:15:01.076 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
> 16:15:01.076 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
> 16:15:01.086 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
> 16:15:01.086 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
> 16:15:01.086 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
> 16:15:01.086 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
> 16:15:01.086 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
> 16:15:01.086 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
> 16:15:01.086 Info  [ 1] ExtensionService: Processing file C:\Program Files (x86)\NUnit.org\nunit-console\nunit.bundle.addins
> 16:15:01.106 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\nunit.v2.driver.dll assembly for Extensions
> 16:15:01.156 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2FrameworkDriver
> 16:15:01.156 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\nunit-v2-result-writer.dll assembly for Extensions
> 16:15:01.156 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2XmlResultWriter
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty Format = nunit2
> 16:15:01.166 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\nunit-project-loader.dll assembly for Extensions
> 16:15:01.166 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnitProjectLoader
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .nunit
> 16:15:01.166 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\vs-project-loader.dll assembly for Extensions
> 16:15:01.166 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type VisualStudioProjectLoader
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .sln
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .csproj
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vbproj
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vjsproj
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vcproj
> 16:15:01.166 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .fsproj
> 16:15:01.166 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\teamcity-event-listener.dll assembly for Extensions
> 16:15:01.166 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type TeamCityEventListener
> 16:15:01.166 Info  [ 1] ServiceManager: Initializing DriverService
> 16:15:01.176 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
> 16:15:01.176 Info  [ 1] ServiceManager: Initializing RecentFilesService
> 16:15:01.176 Debug [ 1] ServiceManager: Request for service ISettings satisfied by SettingsService
> 16:15:01.176 Info  [ 1] ServiceManager: Initializing ProjectService
> 16:15:01.176 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
> 16:15:01.176 Info  [ 1] ServiceManager: Initializing RuntimeFrameworkService
> 16:15:01.176 Info  [ 1] ServiceManager: Initializing DefaultTestRunnerFactory
> 16:15:01.176 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
> 16:15:01.176 Info  [ 1] ServiceManager: Initializing TestAgency
> 16:15:01.186 Info  [ 1] ServiceManager: Initializing ResultService
> 16:15:01.186 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
> 16:15:01.186 Info  [ 1] ServiceManager: Initializing TestFilterService
> 16:15:01.186 Debug [ 1] ServiceManager: Request for service IResultService satisfied by ResultService
> 16:15:01.186 Debug [ 1] ServiceManager: Request for service ITestFilterService satisfied by TestFilterService
> 16:15:01.186 Debug [ 1] ServiceManager: Request for service IExtensionService satisfied by ExtensionService
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service IRuntimeFrameworkService satisfied by RuntimeFrameworkService
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service TestAgency satisfied by TestAgency
> 16:15:01.206 Debug [ 1] ServiceManager: Request for service IRuntimeFrameworkService satisfied by RuntimeFrameworkService
> 16:15:01.446 Debug [ 1] RuntimeFrameworkService: Assembly C:\Users\myUser\myProject\someExecutable.exe uses version 4.0.30319
> 16:15:01.446 Debug [ 1] RuntimeFrameworkService: Assembly C:\Users\myUser\myProject\someExecutable.exe targets .NETFramework,Version=v4.7.2
> [...] 350 others projects, exactly the same
> 16:15:01.576 Debug [ 1] RuntimeFrameworkService: Current framework is net-4.5
> 16:15:01.576 Debug [ 1] RuntimeFrameworkService: Requested framework is net-4.5
> 16:15:01.576 Debug [ 1] RuntimeFrameworkService: Test will use net-4.5 framework
> 16:15:01.576 Info  [ 1] ProcessRunner: Running 
> 16:15:01.586 Info  [ 1] TestAgency: Getting x86 agent for use under net-4.5
> 16:15:01.586 Debug [ 1] TestAgency: Using nunit-agent at C:\Program Files (x86)\NUnit.org\nunit-console\nunit-agent-x86.exe
> 16:15:01.586 Debug [ 1] ServiceManager: Request for service RuntimeFrameworkService satisfied by RuntimeFrameworkService
> 16:15:01.586 Debug [ 1] TestAgency: Launched Agent process 192 - see nunit-agent_192.log
> 16:15:01.586 Debug [ 1] TestAgency: Command line: "C:\Program Files (x86)\NUnit.org\nunit-console\nunit-agent-x86.exe" 1a62b9bc-376d-4d8f-869d-89d320b111bb tcp://127.0.0.1:52655/TestAgency --pid=10952 --trace:Verbose --work=C:\Users\Vibrosight\AppData\Local\Apps\OpenCover
> 16:15:01.586 Debug [ 1] TestAgency: Waiting for agent {1a62b9bc-376d-4d8f-869d-89d320b111bb} to register
> 16:15:01.796 Debug [ 1] TestAgency: Returning new agent {1a62b9bc-376d-4d8f-869d-89d320b111bb}
> 16:15:01.876 Info  [ 1] ProcessRunner: Done running 
> 16:15:01.886 Info  [ 1] ProcessRunner: Unloading 
> 16:15:01.886 Debug [ 1] ProcessRunner: Stopping remote agent
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping TestFilterService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping ResultService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping TestAgency
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping DefaultTestRunnerFactory
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping RuntimeFrameworkService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping ProjectService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping RecentFilesService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping DriverService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping ExtensionService
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping DomainManager
> 16:15:01.966 Info  [ 1] ServiceManager: Stopping SettingsService

Nothing suspicious to me.

> In the mentionned nunit-agent_192.log, nothing else:
> InternalTrace: Initializing at level Debug
> 16:15:01.626 Info  [ 1] NUnitTestAgent: Agent process 192 starting
> 16:15:01.626 Info  [ 1] NUnitTestAgent: Running under version 4.0.30319.42000, .NET 4.5
> 16:15:01.626 Debug [ 1] NUnitTestAgent: Agent process has the COMPLUS_Version environment variable value "NULL" overridden with "v4.0.30319", restoring the original value.
> 16:15:01.626 Debug [ 1] ServiceManager: Added SettingsService
> 16:15:01.626 Debug [ 1] ServiceManager: Added ExtensionService
> 16:15:01.626 Debug [ 1] ServiceManager: Added ProjectService
> 16:15:01.626 Debug [ 1] ServiceManager: Added DomainManager
> 16:15:01.626 Debug [ 1] ServiceManager: Added InProcessTestRunnerFactory
> 16:15:01.626 Debug [ 1] ServiceManager: Added DriverService
> 16:15:01.626 Info  [ 1] NUnitTestAgent: Initializing Services
> 16:15:01.636 Info  [ 1] ServiceManager: Initializing SettingsService
> 16:15:01.636 Info  [ 1] ServiceManager: Initializing ExtensionService
> 16:15:01.636 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
> 16:15:01.636 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
> 16:15:01.636 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
> 16:15:01.636 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
> 16:15:01.636 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
> 16:15:01.636 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
> 16:15:01.636 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
> 16:15:01.636 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
> 16:15:01.636 Info  [ 1] ExtensionService: Processing file C:\Program Files (x86)\NUnit.org\nunit-console\nunit.bundle.addins
> 16:15:01.656 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\nunit.v2.driver.dll assembly for Extensions
> 16:15:01.686 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2FrameworkDriver
> 16:15:01.686 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\nunit-v2-result-writer.dll assembly for Extensions
> 16:15:01.686 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2XmlResultWriter
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty Format = nunit2
> 16:15:01.686 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\nunit-project-loader.dll assembly for Extensions
> 16:15:01.686 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnitProjectLoader
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .nunit
> 16:15:01.686 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\vs-project-loader.dll assembly for Extensions
> 16:15:01.686 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type VisualStudioProjectLoader
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .sln
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .csproj
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vbproj
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vjsproj
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vcproj
> 16:15:01.686 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .fsproj
> 16:15:01.686 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\addins\teamcity-event-listener.dll assembly for Extensions
> 16:15:01.696 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type TeamCityEventListener
> 16:15:01.696 Info  [ 1] ServiceManager: Initializing ProjectService
> 16:15:01.696 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
> 16:15:01.696 Info  [ 1] ServiceManager: Initializing DomainManager
> 16:15:01.696 Info  [ 1] ServiceManager: Initializing InProcessTestRunnerFactory
> 16:15:01.696 Info  [ 1] ServiceManager: Initializing DriverService
> 16:15:01.696 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
> 16:15:01.696 Info  [ 1] NUnitTestAgent: Starting RemoteTestAgent
> 16:15:01.696 Info  [ 1] RemoteTestAgent: Agent starting
> 16:15:01.706 Info  [ 1] RemoteTestAgent: Connecting to TestAgency at tcp://127.0.0.1:52655/TestAgency
> 16:15:01.716 Debug [ 1] RemoteTestAgent: Registered with TestAgency
> 16:15:01.716 Debug [ 1] NUnitTestAgent: Waiting for stopSignal
> 16:15:01.856 Debug [ 6] ServiceManager: Request for service ITestRunnerFactory satisfied by InProcessTestRunnerFactory
> 16:15:01.856 Debug [ 6] ServiceManager: Request for service ITestRunnerFactory satisfied by InProcessTestRunnerFactory
> 16:15:01.856 Debug [ 6] ServiceManager: Request for service IProjectService satisfied by ProjectService
> 16:15:01.856 Debug [ 6] ServiceManager: Request for service DomainManager satisfied by DomainManager
> 16:15:01.876 Info  [ 6] DomainManager: Creating application domain domain-
> 16:15:01.876 Debug [ 6] ServiceManager: Request for service IDriverService satisfied by DriverService
> 16:15:01.886 Info  [ 6] RemoteTestAgent: Stopping
> 16:15:01.886 Info  [ 9] RemoteTestAgent: Waiting for messages to complete
> 16:15:01.886 Info  [ 9] RemoteTestAgent: Attempting shut down channel
> 16:15:01.886 Info  [ 9] RemoteTestAgent: Set stop signal
> 16:15:01.886 Debug [ 1] NUnitTestAgent: Stop signal received
> 16:15:01.886 Info  [ 1] NUnitTestAgent: Agent process 192 exiting cleanly


What can I do to find more about what is preventing my solution to be analyzed?

**Comment by jgrossrieder** [comment]
@CharliePoole Can this be reopened?

**Comment by CharliePoole** [comment]
@jgrossrieder Looking back, I don't see any explanation of what your exact symptoms are. Can you show us your command-line and the output you are getting? Can you provide a simple repro?

**Comment by jgrossrieder** [comment]
> @jgrossrieder Can you also share the sln-file and csprojs? (perhaps with sensitive information censored)

I would love too, but I'm not allowed, this is really a big solution(350 projects) redacting everything would take days and mean nothing anymore :(

**Comment by jgrossrieder** [comment]
maybe you can give me something to try in debug?
