### ISSUE TITLE
NUnit3 Multiple Categories

### ISSUE THREAD

**Issue by heyitsmesuraj** [nunit/nunit-console#378]
In the transition from NUnit version 2 to 3, I have a problem to include/exclcude multiple categories. Since, there is an option in NUnit2, where categories can be declared by comma separator but that cannot be achieved in NUnit3.

In NUnitV3, we have to mention 'cat' every time like
--where "cat != A && cat != B && cat != C && cat != D && cat != E "

Can we achieve this by comma separator like --where "cat != A ,B,C ,D,E "

Thanks,
Suraj

**Comment by xiuzhen1103** [comment]
same question

**Comment by xiuzhen1103** [comment]
same question

**Comment by CharliePoole** [comment]
I'm closing this as won't fix. The transition from NUnit 2 to 3 fixed a bunch of problems with categories not being allowed to contain certain characters. The proposed syntax would require going back to the old style by forbidding ',' in a category. That could impact the console, engine, framework and indirectly all other runners!
