### ISSUE TITLE
Exception / Failure in OneTimeSetUp with and without SetUpFixture

### ISSUE THREAD

**Issue by Tyonoro** [nunit/nunit-console#380]
Hello Guys.

There is a different behavior when having an exception in OneTimeSetUp  in a SetUpFixture or not.
In both cases I have 3 test cases and:

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            throw new Exception($"OneTimeSetUp failed.");
        }

If the OneTimeSetUp is not in a SetUpFixture:

![withoutsetupfixture](https://user-images.githubusercontent.com/3657544/36847679-5f3d4bfc-1d5f-11e8-8682-0ee81254118e.png)

If the OneTimeSetUp is in a SetUpFixture:

![withsetupfixture](https://user-images.githubusercontent.com/3657544/36847691-688b23be-1d5f-11e8-8007-54a4b0fec71f.png)

Is this intended? Thx a lot

**Comment by CharliePoole** [comment]
@Tyonoro Did you intend to close this?

**Comment by rprouse** [comment]
I am going to reopen for now so that it doesn't get lost. I don't think they should be reported differently. This issue belongs in the framework repo though. I will move after we confirm if you intended to close this issue. @Tyonoro?

**Comment by Tyonoro** [comment]
@CharliePoole @rprouse 
This item was closed intentionally. I made a mistake: 
One test throws an exception in the OneTimeSetUp and the other one does an Asser.Fail(). 
=> Both show same behavior if both throw exception or both do Assert.Fail().
