### ISSUE TITLE
Add License Header Manager to project

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#383]
License Header Manager is a Visual Studio extension that allows you to easily insert our standard license header into files. Not everyone needs to use it, but if they do, it will make their lives easier. https://github.com/rubicon-oss/LicenseHeaderManager

This needs us to add a `.licenseheader` file to the solution. See https://github.com/rubicon-oss/LicenseHeaderManager/wiki/License-Header-Definitions

**Comment by CharliePoole** [comment]
PR #876, fixing issue #793 initiated checking of correct headers in a different way back in February. Although it doesn't insert the headers automatically, I think it takes care of 90% of the issue. If others feel differently we can discuss and reopen.
