### ISSUE TITLE
NUnit Runner 2.6.4 is not sorted according to number in Specflow scenario outline

### ISSUE THREAD

**Issue by akkiapte1990** [nunit/nunit-console#387]
Hi All,

I am working on NUnit Runners 2.6.4 in which I found that for specflow scenario outline the test case numbers are coming in sorted format. Could you please assist with this. I don't understand on which basis it exactly sorting. Could anyone help on this? Attached is the screenshot of the same
![nunit issue](https://user-images.githubusercontent.com/37657235/37765459-2b7b5cdc-2dea-11e8-83c2-ad5463f7ca6c.PNG)

**Comment by akkiapte1990** [comment]
Thanks Rob for your response. 

 

Actually, we want to run test cases ascending order, but because of this unsorted list, we are facing some issue. 

 

Because of that, we are searching sorting functionality for NUnit Runner. It is good if you suggest any other option for this

 

Thanks,

Akshay Apte

 

----- Original message -----

**Comment by ChrisMaddock** [comment]
Closing this - NUnit 2.x is no longer supported from this repo. Some work is still being done on 2.x over at https://github.com/nunit-legacy.
