### ISSUE TITLE
FileNotFound exception when running nunit-console against .NET Core 2.1 app

### ISSUE THREAD

**Issue by shaulbehr** [nunit/nunit-console#392]
I have a .NET Core 2.1 unit test project, which is using NUnit 3.10.1
My version of NUnit Console is 3.8.0

Command line:

> nunit3-console.exe unittests.dll --labels=on

Error:

> 1) Error :
> NUnit.Engine.NUnitEngineException : An exception occurred in the driver while loading tests.
>  ----> System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework' or one of > its dependencies. The system cannot find the file specified.
> --NUnitEngineException
>
> Server stack trace:
>    at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
>    at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
>    at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
>    at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

**Comment by ChrisMaddock** [comment]
NUnit Console doesn't yet support .NET Core. You need to use `dotnet test` instead.

See https://github.com/nunit/nunit-console/issues/364 and https://github.com/nunit/nunit-console/issues/388

**Comment by shaulbehr** [comment]
Rats. Oh well...thanks.
