### ISSUE TITLE
Isolated COM libraries

### ISSUE THREAD

**Issue by BlackGad** [nunit/nunit-console#395]
Is there way to setup console to launch tests from my managed assembly which contains reference to isolated com library? 

Current test result:
```
System.Runtime.InteropServices.COMException : Retrieving the COM class factory for component with CLSID {*****} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
```

For generic application app.manifest is used.
Similar to this [technic](https://msdn.microsoft.com/en-us/library/ms973913.aspx) (step 6/7)

**Comment by rprouse** [comment]
Most of us haven't used COM in years 😄 

We will need more information from you to help though. What have you tried? Can you share some code samples?

**Comment by BlackGad** [comment]
yeah) 

Will create simplified sample for you later.

My flow:
1) Old hardware API via COM component
2) My project which includes that COM as isolated component (using manifest)
3) Library with NUnit test fixtures
4) TeamCity step: NUnit runner (via console runner)

Problem here: cannot launch my tests with out real COM registration. Also in my case there are 2 COM components x86/x64

**Comment by BlackGad** [comment]
https://github.com/BlackGad/PS.COMNunitSample/ here you go. Use batch files to build and run solution from .Batch folder. (Command line from VS)

**Comment by CharliePoole** [comment]
@BlackGad Having just taken over this project, I'm cleaning up old issues. This one has had no further discussion since 2018, so I'm closing it. However, we will still see and respond to any comments here and can re-activate the issue if it persists using the latest release of the console and engine.
