### ISSUE TITLE
Getting exit code -5 with NUnit console runner 3.8, using NUnit 3.10

### ISSUE THREAD

**Issue by abelbraaksma** [nunit/nunit-console#405]
The console runner exits with exit code `-5`. However, [when I lookup the source here](https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L50), this is commented out. There is no additional information with the exit (no errors, apart from the usual from failing tests).

My project uses 3.10 most recent NUnit framework, the console runner is 3.8, it is run from within TeamCity. What does this exit code mean and if it is valid, is it possible to give some more information when this situation occurs?

**Comment by ChrisMaddock** [comment]
Please see this thread, and the other linked threads. https://github.com/nunit/nunit-console/issues/403

I'll close this issue as a duplicate - we can reopen if there's anything further to discuss however. 😄

**Comment by abelbraaksma** [comment]
@ChrisMaddock, I looked through the other threads, but not sure I understand it correctly. Are you saying that `-5` should *not* have been used? 

And perhaps more to the point: what can cause this issue? I have no problem running these tests in several environments, but at least in one environment, this error repeatedly happens and on the same spot, what are possible causes of this error? AppDomain unload sounds like something totally out of my influence. Besides, my tests don't do anything too fancy (I think), though there are a lot of them.

**Comment by mikkelbu** [comment]
@abelbraaksma In version 3.8 we made the "Unable to unload AppDomain, Unload thread timed out." error fail the build by making the console return the exit code "-5". Before it just returned "0" if a `NUnitEngineUnloadException` had been thrown by the engine.

Unfortunately, this broke a lot of builds which would prior succeed, so in version 3.9 we have reverted to the old behaviour and will just write a warning to screen and exists with the normal code if a `NUnitEngineUnloadException` if thrown.

You can try to pinpoint the error by running the tests in process by using the `--inproces` command line option.

**Comment by ChrisMaddock** [comment]
Mikkel has covered the history well. We added -5 as a way to ensure users were aware that their tests weren't unloading cleanly, however this turned out not to be the right approach.

> There is no additional information with the exit (no errors, apart from the usual from failing tests).

This is an interesting comment - you should definitely be seeing information about which app domain failed to unload. Can you share post your entire console output?

> And perhaps more to the point: what can cause this issue? 

See: https://docs.microsoft.com/en-us/dotnet/api/system.cannotunloadappdomainexception?view=netframework-4.7.2#remarks

Unless you are doing something specifically with app domains - it is more than likely the second point there - you have some threads which cannot be terminated at the point NUnit attempts to unload the app domain. (Of course, it could be either of the other two reasons, and their could be a bug in NUnit - but if so, you're the first person to find it! 🙂)

**Comment by abelbraaksma** [comment]
@ChrisMaddock  and @mikkelbu thanks! To summarize: the unload exception is raised equal to the unload exception of .NET. The reasons on that page don't seem applicable to my situation, but this is a vast project so I'll need some digging. I'll try to run with the console (outside TeamCity), though i already know that with NCrunch and the VS test runner these issues do not arise.

The curious thing is now that running it again a few times at some point seemed to have alleviated the issue, this morning the error wasn't raised. There were no changes in the NUnit runner used, nor in the project. This by itself could point to a race condition of some sorts, though I don't know whether that could result in failing to unload an AppDomain.

You asked for more info, but there isn't any. I looked through each build log and while the penultimate logged item is different each time (a successful or failing test), it then abruptly ends with this:

![image](https://user-images.githubusercontent.com/16015770/38873998-587528ea-4257-11e8-98c2-4ead1bd5ca1c.png)

The words `NUnitUnloadException` or even just `Domain` do not appear anywhere in the log (plenty of exceptions though, but that's why we use NUnit  ;) ).

**Comment by ChrisMaddock** [comment]
@abelbraaksma - sounds like somethings swallowing the NUnit Console output. I'm not a TeamCity user I'm afraid - so can't advise there!

See this post for the output the NUnit console will give you: https://github.com/nunit/nunit-console/issues/403#issuecomment-380747132

**Comment by abelbraaksma** [comment]
@ChrisMaddock, many thanks for bearing with me. For about a week or so, the errors disappear. Now the `-5` exit code is back. So I tried with the suggestion above using `--inprocess`, but this gives me an `-4` exit code instead, however, this time with some more information:

```text
[23:26:55][Step 4/4] Runtime Environment
[23:26:55][Step 4/4]    OS Version: Microsoft Windows NT 10.0.14393.0
[23:26:55][Step 4/4]   CLR Version: 4.0.30319.42000
[23:26:55][Step 4/4] 
[23:26:55][Step 4/4] Test Files
[23:26:55][Step 4/4]     D:\TeamCity\Win16_Speedy\temp\buildTmp\0u7cZlKfyo7kDSJRl0zYIy7j4Qh37pad.nunit
[23:26:55][Step 4/4] 
[23:26:55][Step 4/4] 
[23:26:55][Step 4/4] Errors, Failures and Warnings
[23:26:55][Step 4/4] 
[23:26:55][Step 4/4] 1) Invalid : D:\TeamCity\Win16_Speedy\temp\buildTmp\0u7cZlKfyo7kDSJRl0zYIy7j4Qh37pad.nunit
[23:26:55][Step 4/4] File type is not supported
[23:26:55][Step 4/4] 
[23:26:55][Step 4/4] Test Run Summary
[23:26:55][Step 4/4]   Overall result: Failed
[23:26:55][Step 4/4]   Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
[23:26:55][Step 4/4]   Start time: 2018-05-01 21:26:55Z
[23:26:55][Step 4/4]     End time: 2018-05-01 21:26:55Z
[23:26:55][Step 4/4]     Duration: 0.041 seconds
[23:26:55][Step 4/4] 
[23:26:55][Step 4/4] Results (nunit3) saved as D:\TeamCity\Win16_Speedy\temp\buildTmp\0u7cZlKfyo7kDSJRl0zYIy7j4Qh37pad.nunit.xml
```

The contents of the file that it says it doesn't recognize is:

```xml
<NUnitProject>
<Settings activeconfig="active" appbase="D:\TeamCity\Win16_Speedy\work\6096e657108389e2\projects"/>
<Config name="active">
<assembly path="D:\TeamCity\Win16_Speedy\work\6096e657108389e2\projects\myproject.exe"/>
</Config>
</NUnitProject>
```

I don't see anything weird here, but perhaps the config file needs to be different when running with `--inprocess`.

**Comment by ChrisMaddock** [comment]
I think you’re probably hitting https://github.com/nunit/nunit-console/issues/386

If you pull the latest build of master from our myget feed, the -5 error code should no longer be returned, and a warning issued instead. Details of that in the repo read me. :-)

**Comment by CharliePoole** [comment]
So with 3.8, you at least get a special exception indicating the reason for the error. Next step would be to find the "reason for the reason", that is, why does your test cause the AppDomain to hang. Does your test create any threads, which may not be terminating properly? Are you possibly relying on a Timeout to end things cleanly, with the timeout (possibly) not working because of some state of  the thread in question? Those are the things I would look out.

That doesn't solve the problem, of course, which is how can we give better information about this kind of error without necessarily failing the entire test run.

**Comment by ChrisMaddock** [comment]
> I downgraded to 3.7, and to 3.6.x (without -inprocess) and both gave exit code -100. 3.8, as mentioned in the OP, gives -5, but I understand that is on the list of things to be fixed.

This _is_ fixed in the master branch - and you can get the latest build of that from the link below. 🙂 

https://www.myget.org/feed/nunit/package/nuget/NUnit.ConsoleRunner

**Comment by abelbraaksma** [comment]
Aha, thanks! And @charliepoole, I assumed similar things, so I switched off all parallel and multi threading that we use in this project. I don't use custom appdomains, basically this project sticks pretty much with F#, C# and the BCL, nothing too fancy there I think, not even any native calls.

But there must be something, I'll keep looking.

**Comment by zilber** [comment]
hi, ChrisMaddock. I have tried using the master branch, but the console runner is only the core without the addins.  I tried to copy manually the addins from 3.8 official version but I got errors when running. Can you please how to can I add the addins to the master branch? maybe I must build the nunit solution myself or is there any other better way to bundle the addins with master?
thanks.

**Comment by CharliePoole** [comment]
If you are using a nuget package of the console runner then you must install the nuget packages for any extensions you use.

**Comment by ChrisMaddock** [comment]
@zilber Just use the NUnit.Console package rather than NUnit.ConsoleRunner. 😄 
https://www.myget.org/feed/nunit/package/nuget/NUnit.Console

**Comment by CharliePoole** [comment]
Either approach should work.

**Comment by zilber** [comment]
I did just that, but then got same issue as here: https://github.com/nunit/nunit-console/issues/412. Any way to workaround this problem?
thanks.

**Comment by abelbraaksma** [comment]
Just a heads-up, mystery solved for the exit code -5 (and on some other versions, exit code -100). 

In case you're curious (and thanks for all your patience and help!):

There appeared to be a statically inlined method that caused a stack-overflow. It is understandable that NUnit cannot deal with `StackOverflowException`, though I know there are some (complex) ways to track them (one program that does this correctly is NCrunch). The hard part in finding the exception was that the test causing it was never in the log and the moment it happened changed between runs.

The exception in other test engines never occurred because it was *only* triggered in a Debug.Assert that only fired in very specific circumstances, that were true on the build server when run from TeamCity and that were triggered by daylight savings time switching, but not true when run from the commandline on the same server (ouch, I know, that dependency should never have been there).

Of course, it would still be very nice to see a stacktrace and perhaps there's something that can be done by catching a first-chance exception or something, I don't know. Either way, I am not too surprised now that I know the underlying reason.
