### ISSUE TITLE
Split RuntimeFramework into separate RuntimeFramework and TargetFramework classes

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#406]
This has come out of https://github.com/nunit/nunit-console/issues/394.

The RuntimeFramework functionality is one of the [more legacy](https://github.com/nunit/nunit-console/issues/173) areas of our code base - and could use a refactor to better fit the NUnit 3 architecture. 

RuntimeFramework is currently used for two purposes, both to detect available runtimes (e.g. full framework, mono, CF), and to determine the target framework of an assembly (e.g net45, netcore20). There's something of a mismatch here as a net45 could of course run on .NET Framework or Mono, so the Runtime.Any enum exists. (Although it's not technically 'Any' I don't believe, as this bit of code still supports Silverlight and CF!)

With supporting .NET Standard and .NET Core for https://github.com/nunit/nunit-console/issues/394 and https://github.com/nunit/nunit-console/issues/271, this bit of codes going to need some additional complexity. Accordingly, I'd like to refactor and do the following:

1. Refactor for thread-safety and proper division of RuntimeFrameworkService and RuntimeFramework responsibilities (As #173)
2. Remove all support for Silverlight and CF. (I _think_ this class used to be shared with NUnit Framework? Or was it that the NUnit 2 console supported these platforms?)
3. Split out separate classes for 'runtime' (e.g. full framework, mono, .NET Core) and 'target' (.NET, .NET Standard etc.)

Any thoughts? 🙂

**Comment by rprouse** [comment]
All good by me 😀

**Comment by ChrisMaddock** [comment]
Superceeded by https://github.com/nunit/nunit-console/issues/702 - I think unfortunately the problem is a little bigger than this one class 😭
