### ISSUE TITLE
--labels=All does not output anything after the test is over.

### ISSUE THREAD

**Issue by MarkKharitonov** [nunit/nunit-console#415]
The behavior is seems by design, because of the code in the TestEventHandler constructor:
```
    public TestEventHandler(TextWriter outWriter, string labelsOption)
    {
      this._outWriter = outWriter;
      labelsOption = labelsOption.ToUpper(CultureInfo.InvariantCulture);
      this._displayBeforeTest = labelsOption == "ALL" || labelsOption == "BEFORE";
      this._displayAfterTest = labelsOption == "AFTER";
      this._displayBeforeOutput = this._displayBeforeTest || this._displayAfterTest || labelsOption == "ON";
    }

```
I would have expected to find there the following line of code:
`this._displayAfterTest = labelsOption == "ALL" || labelsOption == "AFTER";`

It seems to be a bug. It certainly is a problem for me.

**Comment by mikkelbu** [comment]
@MarkKharitonov I don't know much about the history of the naming, but the discussion in #186 indicates that `All` was an original option which meant that the console should "display label at the start of **all** tests". The discussion also covers that this is a very unfortunate naming given the additional options added in #186.

https://github.com/nunit/nunit-console/pull/186#issuecomment-284647537 contains the following 
> So basically, there is no way currently to show a label both when the test starts as well as the end. If you use Before, you see the start but you only see where it ended if there is normal output. If you use After, you can see the end but not the start.
> 
> Should we have Both? Or wait till it's asked for?

And so far you are the first one to ask for `Both` AFAIK.

**Comment by MarkKharitonov** [comment]
I understand.
We may not need both at the end. Right now we do. I wonder why to code it so tight. This property could be a list of strings, instead of just a string. Then the user would decide what it should be - After, Before or "After,Before" or whatever combination makes sense.
Anyway, I understand it is not a bug.

**Comment by ChrisMaddock** [comment]
I agree with @mikkelbu's comments here. The naming is unfortunately 'legacy' - at the point new 'After/Before/Both' options were added, we didn't want to change the behaviour of the pre-existing 'All' option, and break people's existing set ups. 

I'm going to close this issue, as I don't think there's any action to be taken. @MarkKharitonov - please shout if you disagree, and we can reopen! 🙂
