### ISSUE TITLE
Unmanaged AccessViolationException causes Agent Process to hang

### ISSUE THREAD

**Issue by holpstxl** [nunit/nunit-console#416]
Hi all,

We observed that an unmanaged AccessViolationException coming from a code snipped like 

```
void NativeObject::AccessViolation()
{        
         printf("Attempting access violation exception" );

         int *a = 0;
         *a = 10;
};
```

causes the runner process or the test agent respectively to hang (the corresponding process has then to be killed manually). This behavior seems to be specific to this exception type, other unmanaged exceptions like DivisionByZeroException are wrapped by the Runtime and lead to a failed test case, as expected.

A reproducer for this problem can be found at 
https://github.com/holpstxl/CorruptedStateException

I found that there are some related issues already, that seems to be solved also, but I can reproduce the issue with the below mentioned version of NUnit.

Additional Information:
•	Not sure if this belongs to NUnit Framework or NUnit Console. Pardon me if I submitted it in the wrong repository.
•	Related Issue: https://github.com/nunit/nunit/issues/2091 (“When a native exception of corrupted state is thrown, nunit test thread crashes and the nunit-console process hangs”)
•	Used NUnit Framework Version: 3.10.1
•	Used NUnit Console Version: 3.8.0

**Comment by Yozer** [comment]
Adding
`<legacyCorruptedStateExceptionsPolicy enabled="true" />`
to nunit3-agent config solves this issue. Nunit3-agent is not freezing anymore.

I'm not sure why adding HandleProcessCorruptedStateExceptionsAttribute didn't work. It might be a bug  in .NET Framework.
[Documentation ](https://docs.microsoft.com/en-US/dotnet/framework/configure-apps/file-schema/runtime/legacycorruptedstateexceptionspolicy-element) says that both ways should catch exceptions that were raised by corrupted process states.

**Comment by mikkelbu** [comment]
Seems to duplicate #336

**Comment by ChrisMaddock** [comment]
I agree - closing in favour of #336. Good spot Mikkel. 🙂

**Comment by jnm2** [comment]
Fyi: this was never fixed. The PR has never had any effect because https://github.com/nunit/nunit/pull/1775 added `[assembly: AllowPartiallyTrustedCallers]` and the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=netframework-4.8) say this means that `[HandleProcessCorruptedStateExceptions]` is ignored:

> The HandleProcessCorruptedStateExceptionsAttribute attribute is ignored when it is encountered in partially trusted or transparent code, because a trusted host should not allow an untrusted add-in to catch and ignore these serious exceptions.
