### ISSUE TITLE
OneTimeSetUp: System.NullReferenceException

### ISSUE THREAD

**Issue by mark4asp** [nunit/nunit-console#422]
My test consistently fails with the following exception.

	Message: OneTimeSetUp: System.NullReferenceException : Object reference not set to an instance of an object.

I've tried running it with and without a [OneTimeSetUp] method, replaceing that method attribute by a [Setup]. I've tried NUnit 3.6.1 and 3.8.1, with the test attributed with either [Test] or [TestCase(true)].

Always the same error message and the point of failure either just after exiting the [OneTimeSetUp] method (when I have one), or prior to the [Setup] method. It never reaches the [Test] method is called.  There's nothing in the Event Viewer associated with this. 

My system: VS2017 community, Win 10 pro, with the latest Windows Updates (done today). Nunit 3.8.1, NUnit 3 test adaptor ver 3.10.0.0. I run it from the VS Test Explorer.

Is there a way to get more information on this?

**Comment by ChrisMaddock** [comment]
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂
