### ISSUE TITLE
Engine can't handle ProcessModel.Multiple plus DomainUsage.Multiple

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#428]
I discovered and worked around this while coding the GUI.

Put both of the above settings into a test package for a single assembly and the engine fails to load the assembly. The settings make no sense anyway. Since each assembly will be in it's own process, there is no need for multiple domains.

However, if specified by mistake, the engine should really ignore the DomainUsage setting.

**Comment by ChrisMaddock** [comment]
Is this the same issue as https://github.com/nunit/nunit-console/issues/29? 🙂

**Comment by CharliePoole** [comment]
It could be, or just related. If you interpret #29 to mean that the console should never send that combination, then they are different. I think we need both: engine should not crash and our runners should never send the combination. Belt and suspenders. :-)

I fixed the GUI. I'm OK if you want to call this a duplicate. I'm running a stateless protocol in my head here, so I didn't recognize this as one I'd seen before. :-)

**Comment by mikkelbu** [comment]
> However, if specified by mistake, the engine should really ignore the DomainUsage setting.

Why should we ignore the wrong setting instead of failing with an appropriate message to help the user correct the problem?

**Comment by CharliePoole** [comment]
Provided we can limit the error to specification in the command-line, I think that would be OK. It definitely should not be an error if it's specified in the settings file or an nunit project file. Once it hits the engine, we kind of lose the info about where the setting came from, so it has to be caught early.

Historically, we have always accepted contradictory settings from the user and allowed the failure to occur. Recently we have started to give some error messages for contradictory settings and maybe that's the way you would like to do it in the future. It's not 100% straightforward, however.

1. If command-line contains both `--process:Multiple` and `--domain:Multiple` that's the simplest case  and can easily be ignored or reported as an error.

2. If it contains no `--process` but has `--domain:Multiple` I don't think we can assume it's an error. Of course, process:Multiple is the default, but you may be running an nunit project that specifies something else. The command-line processor doesn't know that.

3. Also, even though the console runner does not use the settings file, we might change it to use it at some time. And other runners use it.

My conclusion is that you have to silently ignore the setting __at the engine level__ where you don't know what runner is involved or where the settings came from. OTOH __at the console level__ you could give an error message without problem in case 1.

**Comment by CharliePoole** [comment]
With the 4.0 codebase, it's no longer possible to specify these options.
