### ISSUE TITLE
Nunit console runner returns -1 (INVALID_ARG) despite running the required tests

### ISSUE THREAD

**Issue by kditrj2d** [nunit/nunit-console#444]
I am seeing the runner return -1 (INVALID_ARG), despite all of the tests appearing to be executed. (I have quite a few tests marked to be ignored and a couple that are currently inconclusive).

I am using the console runner from version 3.7.0. Here is the command-line. I have put new-lines in between each parameter to make it read easier here. The fixture list consists of 37 (space-delimited) items:

nunit3-console.exe
fixture-list
--work=C:\Temp\OutputFiles
--noheader
--framework=net-4.0
--process:Multiple
--result=C:\Temp\NunitOutput.xml
--agents=4
--where !(cat==Developmentt||cat==Integration||cat==RabbitMQInstalled)

I see this output from the end of the run, but the runner returns -1:

Run Settings
    ProcessModel: Multiple
    RuntimeFramework: net-4.0
    DisposeRunners: True
    WorkDirectory: C:\Temp\OutputFiles
    MaxAgents: 4
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Warning
  Test Count: 20542, Passed: 20464, Failed: 0, Warnings: 0, Inconclusive: 2, Skipped: 76
    Skipped Tests - Ignored: 76, Explicit: 0, Other: 0
  Start time: 2018-07-27 11:05:01Z
    End time: 2018-07-27 11:13:58Z
    Duration: 537.907 seconds

Results (nunit3) saved as C:\Temp\NUnitResults.xml
I have tried with 3.8.0 to the same result. (I reverted to 3.7.0 because I read about an issue with the 3.8.0 runner returning -5 when app domains are not being properly released and I thought that this might be causing the non-zero return value, but having reverted and found the same behaviour I got MSBuild to output the return value and it is -1 not -5.)

Any ideas as to why this might be happening?

**Comment by CharliePoole** [comment]
Try running with --trace:Verbose to see what's happening internally. You'll get lots of log files for this but start with the one for the nunit3-console process itself.

Beyond that, try to reduce the number of assemblies to find which assembly causes the problem. I'd try with half, then one quarter, etc.

**Comment by kditrj2d** [comment]
There was nothing of any significance in any of the log files that I inspected after setting tracing to Verbose.
I managed to isolate the issue to one test out of 33,000.  The test is a SpecFlow.  The errant step does this:

        [Then(@"any further writes to the context cause an exception")]
        public void ThenAnyFurtherWritesToTheContextCauseAnException()
        {
            var context = ScenarioContext.Current.Get<UcmdPerThreadWritingContext>();
            try
            {
                context.Write(GetSegment(0));
                Assert.Fail(); //Exception should have been thrown here
            }
            catch (InvalidOperationException)
            {
                Assert.Pass();
            }
        }

When I refactor it to this (which is how I would have written it were I the original author), the problem goes away:

        [Then(@"any further writes to the context cause an exception")]
        public void ThenAnyFurtherWritesToTheContextCauseAnException()
        {
            var context = ScenarioContext.Current.Get<UcmdPerThreadWritingContext>();
            Assert.Throws<InvalidOperationException>(() => context.Write(GetSegment(0)));
        }

So I have an immediate solution.  Then I though about trying to provide a simple reproduction example to post here.  I wrote a SpecFlow that simply called Assert.Pass("Hello").  The test passed, BUT the console output contained "error: Hello".  So it looks as though there is something strange going on with the Assert.Pass() method.  The documentation states that "The Assert.Pass method allows you to immediately end the test, recording it as successful.", but when you use it the runner returns -1 instead of zero.

For the purposes of clarity, I was using NUnit version 3.7.1 here.  You may want to try this with the latest version.  I would be interested to hear whether this behaviour is 'by design' or whether it is a bug.

**Comment by CharliePoole** [comment]
I'm curious so I'll check further, but the message format "error: Hello" would seem to indicate that some other bit of software is intervening between the original `Assert.Pass` and the output. NUnit itself should just display "Hello". Note that some runners (notably vstest.console) cause an error if the detect the string "error:" in the output. (!@$!)

**Comment by kditrj2d** [comment]
The message that I reported was what I saw within the console window in the R# test runner within VS2017.  Is it possible that the word "error:" refers to the STDERR being used to output the text "Hello"?

**Comment by CharliePoole** [comment]
I'm afraid that all bets are off using the R# runner, at least as far as diagnosing NUnit. 😢 

It could mean that, but NUnit itself doesn't use STDERR except for output that is specifically sent there by the user.

I ran a straight NUnit test with `Assert.Pass("Hello")` using nunit3-console 3.8 and nunit.framework 3.10.1. The result code was 0. When I get a chance I'll use the older console. What version of the framework are you running? So far, it looks like this may be an artifact of SpecFlow... IIRC, SpecFlow generates the actual test code that NUnit runs, right?

SpecFlow comes up a lot. IMO, somebody on the @nunit/framework-team should probably get familiar with it.

**Comment by kditrj2d** [comment]
Specflow is really just an automated unit-test writer.  It converts a text file into an NUnit fixture containing one or more unit tests.  The user provides step definitions in the form of public methods in a Bindings class and the unit test code identifies and calls them at run-time using custom attributes.  My point here is that at run-time there is just the NUnit console runner and the generated code.  I have attached a simple C# project (zipped) that contains a SpecFlow scenario and implementation.  When I run using NUnit console from 3.7.1 the single test passes but the console runner returns -1.  You _should_ be able to compile and run it too.
[NunitConsoleRunnerIssue.zip](https://github.com/nunit/nunit-console/files/2238972/NunitConsoleRunnerIssue.zip)

**Comment by kditrj2d** [comment]
Actually there isn't much to see when you look at the generated code.  It looks to me as if this may be an issue with SpecFlow rather than the NUnit runner.  I concur that a simple vanilla NUnit test containing just Assert.Pass() behaves as expected.  I will refer this issue to the people who maintain SpecFlow.

**Comment by mikkelbu** [comment]
Hi @kditrj2d 

I just tried you example and both on master and on 3.7.0 it exits with 0 on my machine (note that I did not download 3.7.0, but instead compiled it from source).

```
PS C:\src\NUnit\nunit-console\bin\Release> .\nunit3-console.exe C:\temp\ExamineProblems\NunitConsoleRunnerIssue\src\bin\
Debug\NunitConsoleRunnerIssue.dll
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\temp\ExamineProblems\NunitConsoleRunnerIssue\src\bin\Debug\NunitConsoleRunnerIssue.dll

=> NunitConsoleRunnerIssue.AssertPassFeature.DoNothing
Given nothing
-> done: AssertPassSteps.GivenNothing() (0.0s)
When I do nothing
-> done: AssertPassSteps.WhenIDoNothing() (0.0s)
Then nothing happens
-> error: Hello
=> NunitConsoleRunnerIssue.AssertPassFeature
-> Using app.config

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\src\NUnit\nunit-console\bin\Release
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-07-29 21:55:20Z
    End time: 2018-07-29 21:55:21Z
    Duration: 1.285 seconds

Results (nunit3) saved as TestResult.xml
PS C:\src\NUnit\nunit-console\bin\Release> $LASTEXITCODE
0
```

**Comment by kditrj2d** [comment]
Interesting that you also see the characters 'error:' prior to 'Hello'

**Comment by mikkelbu** [comment]
As far as I can tell the "error: " comes from
https://github.com/techtalk/SpecFlow/blob/0e588d4963f6f094664b7738ea342654752b218f/TechTalk.SpecFlow/Tracing/TestTracer.cs#L76-L79

Ps. @kditrj2d If I create an augmented version of the console with additional output when we exit would you then be able to use this version to help pinpoint the issue?

**Comment by kditrj2d** [comment]
I have tried a few more things.
If I run the example within PowerShell, the exit code using $LASTEXITCODE is 0 as expected.
If I run the example in a windows batch file then the exit code using echo %errorlevel% is also 0 as expected.

I  am getting the unexpected behaviour when I run within an 'Exec' task in MSBuild.

Here's the simplest build-target that exhibits the problem:

 ```
 <Target Name="Build" DependsOnTargets="ValidateInputs;Info">
    <Exec ContinueOnError='true' Command='$(NunitRunnerPath) C:\temp\TestAssembly.dll'>
      <Output TaskParameter="ExitCode" PropertyName="ReturnCode"/>
    </Exec>
    <Message Importance="High" Text="NUnit returned $(ReturnCode)" />
    <Error Text="NUnit execution failed!" Condition="'$(ReturnCode)' != '0'" />
  </Target>
```

When 'TestAssembly' is a vanilla C# assembly containing this:

    [TestFixture]
    public class Class1
    {
        [Test]
        public void TestAssertPass()
        {
            Assert.Pass();
        }
    }

then the return code is zero as expected.

When 'TestAssembly' is the example I posted earlier (a simple SpecFlow containing Assert.Pass()) the return code is -1.  If I remove the Assert.Pass() from the SpecFlow, the return code is 0 as expected.

@mikkelbu Does this information allow you to reproduce the behaviour that I see?

**Comment by mikkelbu** [comment]
@kditrj2d I think it that Charlie's comment in https://github.com/nunit/nunit-console/issues/444#issuecomment-408686036 is spot on. 

If I have the test 
```c#
[Test]
public void Test1()
{
  Console.Write("Error: some text");
}
```
and the msbuild target 
```xml
  <Target Name="Build2">
   <Exec Command='PATH\nunit3-console.exe ErrorInOutput.exe'>
     <Output TaskParameter="ExitCode" PropertyName="ReturnCode"/>
   </Exec>
   <Message Importance="High" Text="NUnit returned $(ReturnCode)" />
   <Error Text="NUnit execution failed!" Condition="'$(ReturnCode)' != '0'" />
 </Target>
```
Then the test works as expect in VS (both using R# and the NUnit adapter) and using nunit-console directly.
However, if I execute the msbuild task then I get the error
```
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 30-07-2018 10:54:14.
Project "PATH\ErrorInOutput.csproj" on node 1 (Build2 target(s)).
Build2:
  PATH\nunit3-console.exe "...\ErrorInOutput.exe"
  NUnit Console Runner 3.9.0
  Copyright (c) 2018 Charlie Poole, Rob Prouse

  Runtime Environment
     OS Version: Microsoft Windows NT 10.0.15063.0
    CLR Version: 4.0.30319.42000

  Test Files
      ...\ErrorInOutput.exe

  => ErrorInOutput.Program.Test1
EXEC : error : some text [PATH\ErrorInOutput.csproj]
  Run Settings
      DisposeRunners: True
      WorkDirectory: PATH
      ImageRuntimeVersion: 4.0.30319
      ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
      ImageRequiresX86: True
      RunAsX86: True
      ImageRequiresDefaultAppDomainAssemblyResolver: False
      NumberOfTestWorkers: 8

  Test Run Summary
    Overall result: Passed
    Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
    Start time: 2018-07-30 08:54:14Z
      End time: 2018-07-30 08:54:15Z
      Duration: 0.599 seconds

  Results (nunit3) saved as TestResult.xml
PATH\ErrorInOutput.csproj(66,4):
 error MSB3073: The command "PATH\nunit3-console.exe "...\ErrorInOutput.exe"" exited with code -1.
Done Building Project "PATH\ErrorInOutput.csproj" (Build2 target(s)) -- FAILED.


Build FAILED.

"PATH\ErrorInOutput.csproj" (Build2 target) (1) ->
(Build2 target) ->
  EXEC : error : some text [PATH\ErrorInOutput.csproj]
  PATH\ErrorInOutput.csproj(66,4): error MSB3073: 
  The command "PATH\nunit3-console.exe "...\ErrorInOutput.exe"" exited with code -1.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.97
```
If I change `"Error: "` to e.g. `"Error "` then the task is executed without error. 

Ps. I don't see any trace of `NUnit returned` in the output?

**Comment by kditrj2d** [comment]
@mikkelbu Brilliant!  Well done!

I can reproduce the behaviour Mikkel outlined above, namely that a simple unit test containing a write to the console including the text "error:" causes an MSBuild Exec task to report a non-zero return code from the test runner.  If the console text does not contain the colon character, a zero return code is reported as expected.

I had this:
A call to Assert.Pass(string message) within a SpecFlow scenario.
SpecFlow (for what ever reason) inserted the text "error: " prior to the supplied text during its console output
The MSBuild Exec task reported a non-zero return code.

From this I conclude that there is no fault within NUnit.
I will approach the SpecFlow authors to try and discover why the "error:" is prepended to the message string on the Assert.Pass() call.

I think that this issue can be closed now.

**Comment by mikkelbu** [comment]
@kditrj2d  I just found out another way to make the problem "disappear". You can set `IgnoreStandardErrorWarningFormat="true"` on the `Exec`-element. This tells msbuild that it should not examine the output for standard error and warnings.

I'll close the issue, but please add more comments if new information appear, e.g. from the SpecFlow project (or just link the issues).

**Comment by kditrj2d** [comment]
@mikkelbu Thanks.  I will take a look.

**Comment by rojaadi** [comment]
@mikkelbu by setting IgnoreStandardErrorWarningFormat="true" at exec element , still return code is -1, if there is other alternative can you please share

**Comment by mikkelbu** [comment]
@rojaadi How are you executing the tests?

**Comment by rojaadi** [comment]
@mikkelbu i am executing as follows
 public void Number()
        {
            var result = SerialNumber;
            Assert.AreEqual("", result);
        }

**Comment by mikkelbu** [comment]
@rojaadi This is just a test. I was asking how you are executing the tests. `IgnoreStandardErrorWarningFormat="true"` only works if you run the tests using a MSBuild Exec task.

You'll need to provide more information for us to help you:
* How you run the tests (nunit-console directly or other tooling calling nunit-console)
* The expected and actual output
* Extract packages in play (like SpecFlow above)
* ...
Otherwise, we will just be guessing

**Comment by rojaadi** [comment]
@mikkelbu as follows:
 <Exec Command="$3rdParty\nunit\NUnit.Runners.2.6.3\tools\nunit-console.exe UnitTests.nunit /config:Fast /noshadow /xml:&quot;D:\output\test-results\IDFXD&quot;"
          IgnoreStandardErrorWarningFormat="True"
          CustomErrorRegularExpression="Test Failure \:"
          CustomWarningRegularExpression="Assert failed\:"/>
    <Delete Files="$(FilesToDelete)"/>

Error : The command "3rdParty\nunit\NUnit.Runners.2.6.3\tools\nunit-console.exe UnitTests.nunit /config:Fast /noshadow /xml:"D:\output\test-results\IDFXDNUnitTests.xml"" exited with code 1.
 
public void Number()
{
var result = SerialNumber;
Assert.AreEqual("", result);
}

**Comment by CharliePoole** [comment]
The message as copied indicates a return code of 1, not -1. A code of (positive) 1 means that 1 test failed. The saved XML file should contain the actual error message.

**Comment by rojaadi** [comment]
Thank you @CharliePoole and @mikkelbu  i will look into the xml file

**Comment by mikkelbu** [comment]
@rojaadi Also note that this issue is about NUnit 3 (the console version 3.7.0) whereas yours are NUnit 2( version 2.63).

**Comment by rojaadi** [comment]
@CharliePoole and @mikkelbu  error got fixed it was due to the sequence of .proj executing. Thank you so much for your support
