### ISSUE TITLE
Output CI version info to console

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#446]
I'm using Cake to pull the latest prerelease from the MyGet feed via `#tool nuget:https://myget.org/f/nunit/?package=NUnit.ConsoleRunner&prerelease`. I want the version to float, but I want to be able to know after the fact which MyGet build of NUnit Console was used in my CI builds. For example, the Cake script ran against `3.9.0-dev-04024` but I can't see that by reading my CI log:

```
NUnit Console Runner 3.9.0
Copyright (c) 2018 Charlie Poole, Rob Prouse
```

To fix this, can we have the AppVeyor CI build patch AssemblyInfo.cs with the current build number? I'd be happy to do it if you like the idea. (Where I work, we do AssemblyInfo.cs patching on projects where we can't move to the new SDK yet and pass an MSBuild property.)

Then, we'd replace this:

https://github.com/nunit/nunit-console/blob/3427b07274a271f6de81d8526adc1a8d95d2c956/src/NUnitConsole/nunit3-console/Program.cs#L161-L164

With this:

```cs
string versionText = FileVersionInfo.GetVersionInfo(
    executingAssembly.ManifestModule.FullyQualifiedName).ProductVersion;
```

**Comment by ChrisMaddock** [comment]
Fine by me!
