### ISSUE TITLE
results xml-file in nunit2 format does not confirm to xsd

### ISSUE THREAD

**Issue by jjvdgeer** [nunit/nunit-console#451]
When running:

nunit3-console.exe -result TestResults.xml;format=nunit2 SomeTest.dll SomeOtherTest.dll

it seems that the TestResults.xml is generating does not adhire to the xsd (as found [here](https://github.com/nunit/nunitv2/blob/2.6.4/doc/files/Results.xsd)) I get a Result.xml which looks like this:

```xml
<test-results ...>
  <environment .../>
  <culture-info .../>
  <test-suite type="Assembly" name="SomeTest.dll" .../>
  <test-suite type="Assembly" name="SomeOtherTest.dll" .../>
</test-results>
```

However, according to the xsd, it's not allowed to have more than one test-suite element within the test-results:

```xsd
<xs:complexType name="resultType">
	<xs:sequence>
		<xs:element name="environment" type="environmentType" />
		<xs:element name="culture-info" type="culture-infoType" />
		<xs:element name="test-suite" type="test-suiteType" />
	</xs:sequence>
	...
</xs:complexType>
```

This is causing me problems as the xunit plugin for Jenkins rejects these results-files.

This is using NUnit-Console 3.8.0.

**Comment by ChrisMaddock** [comment]
Hi @jjvdgeer,

The nunit2 result writing is handled by an extension to the engine. I'll move this issue over to the repository where it lives, and comment further there! 🙂

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-v2-result-writer #13](https://github.com/nunit/nunit-v2-result-writer/issues/13) via [**ZenHub**](https://www.zenhub.com/)
