### ISSUE TITLE
Run .NetCore 2.0 test from command line 

### ISSUE THREAD

**Issue by b7ns** [nunit/nunit-console#458]
I have two prjects my library and test.
The test library contains only a simple test and reference to my library
```csharp
    [TestFixture]
    class Class1
    {
        [Test]
        public void simple_test_false()
        {
            Assert.IsFalse(false, "false");
        }
    }
```

Nuget packages installed for the test project:
* nunit" Version="3.10.1"
* NUnit3TestAdapter "3.10.0"
* Microsoft.NET.Test.Sdk 15.8.0" 

dotnet verion 2.1.400

Running test from Visual Studio Test Explorer (2017), everything works fine, but when I running its from console I have  the following output:

```console
Build started, please wait...
Build started, please wait...
Build completed.

Test run for d:\dev\testlib\src\testlib\bin\Debug\netstandard2.0\TestLib.dll(.NETStandard,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
System.IO.FileNotFoundException: Unable to find tests for d:\dev\testlib\src\testlib\bin\Debug\netstandard2.0\TestLib.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
Build completed.

Test run for d:\dev\testlib\test\TestLib.Test\bin\Debug\netcoreapp2.0\TestLib.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1,2002 Seconds
```
How to get rid of this error?

Sorry for my English.

**Comment by mikkelbu** [comment]
Hi @b7ns 
Can you provide the exact command you use to run the tests. Currently, I only see the output. That being said it looks like an error in `dotnet test` (see Microsoft/vstest#1129).

**Comment by rprouse** [comment]
@b7ns are your tests multi-targeted? The `Test run for d:\dev\testlib\src\testlib\bin\Debug\netstandard2.0\TestLib.dll(.NETStandard,Version=v2.0)` seems odd. Tests must target .NET Core or full framework. Can you copy in the CSPROJ file you are using?

**Comment by b7ns** [comment]
Thanks @mikkelbu
It's my fault.
Yes, I ran the test command in the solution folder. When I run in the test folder, It's all right.

**Comment by mikkelbu** [comment]
> @b7ns are your tests multi-targeted? The Test run for d:\dev\testlib\src\testlib\bin\Debug\netstandard2.0\TestLib.dll(.NETStandard,Version=v2.0) seems odd. Tests must target .NET Core or full framework. Can you copy in the CSPROJ file you are using?

Note that it says
```
Test run for d:\dev\testlib\src\testlib\bin\Debug\netstandard2.0\TestLib.dll(.NETStandard,Version=v2.0)
...
Test run for d:\dev\testlib\test\TestLib.Test\bin\Debug\netcoreapp2.0\TestLib.Test.dll(.NETCoreApp,Version=v2.0)
```
so my guess was that `TestLib.dll` is the production assembly and `TestLib.Test.dll` the test assembly.
