### ISSUE TITLE
nunit3-console.exe process hangs after test

### ISSUE THREAD

**Issue by yank0x1** [nunit/nunit-console#469]
I'm using nunit 3.9 console runner, and running tests using commands from jenkins.

The problem is that often when there is test failure the nunit3-console.exe process hangs infinitely, which jams the jenkins job.

I saw similar issues posted about nunit console 2.x

Tried running with --inprocess flag and through agent, still it often hangs.

Thanks ahead

**Comment by ChrisMaddock** [comment]
Hi @yank0x1 - please can you share you command line, and run with `--trace=Debug`, and then share the logs.

**Comment by yank0x1** [comment]
Hi thanks for the quick reply.

this turned out to be false alarm, since i found out a process was spawned from the teardown of the test and it prevented it from closing.

the issue didn't reproduce after. if it shows up i'll update with details.

best regards,
Rami

**Comment by ChrisMaddock** [comment]
Thanks for the update!
