### ISSUE TITLE
Multiple TestFixtureAttributes on Base class are not ran in console app

### ISSUE THREAD

**Issue by britianoates** [nunit/nunit-console#47]
When we compile and run the following from nunit console, we only see the double version of the test.  We have seen both types run in Visual Studio.  We have rechecked our expectations against the documentation at http://www.nunit.org/index.php?p=testFixture&r=2.6.3.

    public class ExampleInheritenceProblem<T> : ExampleInheritenceProblemBase<T>
    {
        [Test]
        public void MyTest()
        {
            Assert.Pass(_type.ToString());
        }
    }

    [TestFixture(typeof(int))]
    [TestFixture(typeof(double))]
    public abstract class ExampleInheritenceProblemBase<T>
    {
        public Type _type;

        protected ExampleInheritenceProblemBase()
        {
            _type = typeof (T);
        }
    }

Expected:  2 tests to be ran
Actual:   1 tests is ran

**Comment by britianoates** [comment]
Workaround:  Giving null argument values does not cause problems and somehow causes all TestFixtures to be found and executed.

    public class ExampleInheritenceProblem<T> : ExampleInheritenceProblemBase<T>
    {
        [Test]
        public void MyTest()
        {
            Assert.Pass(_type.ToString());
        }
    }
    
    [TestFixture(0, TypeArgs = new []{typeof (int)})]
    [TestFixture(0, TypeArgs = new []{typeof (double)})]
    public abstract class ExampleInheritenceProblemBase<T>
    {
        public Type _type;

        protected ExampleInheritenceProblemBase()
        {
            _type = typeof (T);
        }
    }

**Comment by britianoates** [comment]
Clarification:  Passing 0 in as an unused argument results in 2 tests to be executed.  Passing null in results in 1 test executing.

**Comment by CharliePoole** [comment]
Marking this invalid and closing because it's on a defunct repository. See comment at https://github.com/nunit/nunit-console.

I created a new issue at nunit/nunit#476 but your subsequent comments aren't on it. Kindly repost.
