### ISSUE TITLE
--explore output doesn't take into account --where option

### ISSUE THREAD

**Issue by StarkeyKy** [nunit/nunit-console#470]
When running the command 
`nunit3-console.exe" "Test1.dll" --explore:"Test1Output.txt";format=cases  --where="cat!=Category1 && cat!=Category2"`

The Test1Output.txt will display the whole list of tests found in the test file. Instead, could we please have the output take into account the --where option and remove any found tests matching the condition set with --where?

Thanks!

**Comment by CharliePoole** [comment]
This seems to duplicate a number of old issues that have been closed, in particular nunit/nunit#1143. If you are using the 3.8 console and the 3.7 or higher framework, you should not see this problem. Can you confirm what versions you are using?

**Comment by StarkeyKy** [comment]
Thanks @CharliePoole! You are correct that we are on an older version for the framework. Updating the frame work looks to have resolved the issue.
