### ISSUE TITLE
Failed to load extension from: error in win 10

### ISSUE THREAD

**Issue by abdulkhameer** [nunit/nunit-console#471]
Hi All,

I am facing the below issue while running test scripts using visual studio in my windows 10 dev pc. please help me to resolve this.

![error1](https://user-images.githubusercontent.com/11190751/45281213-c1213900-b4f4-11e8-89be-e1ef4d7368ca.png)

**Comment by mikkelbu** [comment]
Hi @abdulkhameer 
It does not sound like an NUnit problem. By googling the message I found the following [similar stackoverflow question] (https://stackoverflow.com/questions/43571119/loading-of-unpacked-extensions-is-disabled-by-the-administrator?rq=1) which sounds like it is more a Selenium/ChromeDriver problem. So I think that you will get better help on forums for these products as most of us do not know much about Selenium/ChromeDriver.

**Comment by ChrisMaddock** [comment]
Closing this, as it looks like the problem may lie outside of NUnit.

Happy to reopen if anyone has more to add. 🙂
