### ISSUE TITLE
need to run specific number test scenario using nunit runner 3.9.0

### ISSUE THREAD

**Issue by somnath4993** [nunit/nunit-console#474]
i want execute specific test case at one time, suppose i have 10 test scenario, in that any 5 were get passed and now i want to execute only failed test scenario, 
i want help on that, in 2.6 GUI my work was done very smooth, but now it is very hectic for me

**Comment by CharliePoole** [comment]
The answer depends on what you mean by a specific test scenario. Selecting named test methods? Certain fixtures? Specific arguments? 

In all cases you willing either the --test or the --where option but the details will vary.

Please post an example to receive more help.

**Comment by CharliePoole** [comment]
I'm sorry, but that's still not clear. You asked about running tests from the console runner but are showing a display from some other environment... Visual Studio? Resharper?

Also, it's not clear whether the "Scenarios" are NUnit test cases, fixtures, etc.

**Comment by somnath4993** [comment]
whatever i have attached it was earlier version of nunit 2.6,  i have written scenarios in feature file

**Comment by CharliePoole** [comment]
If each of the names is a test case in NUnit, then I suggest using the --test or --testlist option on the command-line.

You will need to specify the fullname of each test to be run.

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
