### ISSUE TITLE
.NET Standard engine to load extensions

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#476]
The .NET Standard Engine should be able to load engine extensions. See spec discussed in https://github.com/nunit/nunit-console/issues/394

Blocked by: #388

Motivations for this include:
https://github.com/nunit/nunit-v2-result-writer/issues/12
https://github.com/nunit/vs-project-loader/issues/25

**Comment by nvborisenko** [comment]
Based on `TestEngine.cs` it seems this supported by `netstandard2.0`. If it's true, do we have plans to release it via nuget?

**Comment by ChrisMaddock** [comment]
Hey, nvb - yes and yes!

Next release is hopefully soonish, there’s just currently a bug with .NET standard extension loading we need to fix first, and we’ve all been a little busy recently! For now, you could use a ‘nightly build’ package from our myget feed - link in the readme!
