### ISSUE TITLE
Allow running of .NET Core assemblies via the .NET Framework 2.0 console/engine

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#478]
This would mean that the current console can be used to run tests across all platforms, and all functionality combined.

Currently blocked by: https://github.com/nunit/nunit-console/issues/266, https://github.com/nunit/nunit-console/issues/388

**Comment by CharliePoole** [comment]
This was our long-term plan for NUnit 3, as opposed to having a .NET Core console runner. See #475 comment.

**Comment by ChrisMaddock** [comment]
Fixed by #923, I believe.
