### ISSUE TITLE
NUnit Console v3.9.0 doesn't appear to pick up on extensions in TeamCity

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/nunit-console#482]
Hi all,

Wondering if I'm doing something off but this really seems like a bug, enough so that I wanted to try here. 

## Symptom 

* I have `NUnit.Console` v3.9.0 installed in my solution, which brings in all the other extensions needed, per the docs.
* For my TeamCity build, I extracted the NUnit runner location into a parameter so I could be sure it was consistent. It is set as `%teamcity.build.checkoutDir%/Src/packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe
`. The parameter name is `%nunit-runner-location%`.
* I have two build steps -- one to run `%nunit-runner-location% --list-extensions` so I can see them, and the other to run the unit tests using the `%nunit-runner-location%` parameter. 

Screenshot showing the extensions being listed and then directly below that, an error saying that the extensions are required.

![image](https://user-images.githubusercontent.com/2148318/46625729-0f7d2400-cb03-11e8-943d-4f807eb30908.png)

Any idea what I can do here? I've been racking my brain about what I could be missing but I'm out of ideas.

**Comment by SeanKilleen** [comment]
FWIW, my solution currently has:

* NUnit.Console v3.9.0
* NUnit.ConsoleRunner v3.9.0
* NUnit.Extension.NUnitProjectLoader v3.6.0
* NUnit.Extension.NUnitV2Driver v3.7.0
* NUnit.Extension.TeamCityEventListener v1.0.4
* NUnit.Extension.VSProjectLoader v3.8.0

**Comment by SeanKilleen** [comment]
Strangely enough, when supplying the working directory as the build's working directory, this seems to have potentially fixed it. I still see the error, but the tests actually run and complete. Looking into it.

**Comment by CharliePoole** [comment]
IIRC there was a team city bug around this issue. They were incorrectly interpreting the output of --list-extensions.

**Comment by ChrisMaddock** [comment]
Indeed, see the issue below for the background. 

https://github.com/nunit/nunit-console/issues/468

As I understand, the issue doesn’t block tests, and will be fixed in the next version on teamcity.

Let us know if there’s anything we’ve missed. 😊

**Comment by ChrisMaddock** [comment]
That said, I don’t know why setting the working directory would make a difference. 😕

**Comment by SeanKilleen** [comment]
✅ Confirming: [that bug](https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FTW-56765) does appear to be the case here. 

Really unfortunate bug -- all my tests pass, but the build logs an error, and thus I cannot merge pull requests. 

Thanks for pointing me in the right direction!

**Comment by ChrisMaddock** [comment]
No worries - hope the next TC version isn't too far off!
