### ISSUE TITLE
Disable shadowcopy in Nunit 2.6.4

### ISSUE THREAD

**Issue by shl2000** [nunit/nunit-console#492]
Hi, 

I've an issue reagrding Nunit 2.6.4.
When a test is launched from HP LeanFT it starts Nunit-console and the test is running.
It however fails with this error:

Directory: C:\Users\XXXXX\AppData\Local\Temp\nunit20\ShadowCopyCache\11248_636758935043736828\Tests_316877530\assembly\dl3\44f03713\008230f5_dc5ed401\TestData
JsonDictionaries does not exist

I know that shadow copy can be disabled by runng Nunit-console with /Noshadow, but since nunit-console it launched from LeanFT we cannot use that option.

Can shadowcopy be disabled in nunit-console.exe.config file?
If so what is the syntax?

**Comment by CharliePoole** [comment]
A `.runsettings` only applies to running under the VS adapter, not the console. The console takes settings from the NUnit settings file and the command-line.

However... although you state that LeanFT runs nunit-console, the info I have found via Google indicates that it uses the NUnit VS adapter, not the console. I'm not familiar with LeanFT so perhaps I missed something. Anyway, to get more info from us, please tell us exactly what NUnit software you installed along with LeanFT.

**Comment by shl2000** [comment]
Hi,

We are using Nunit 2.6.4.
It is configured from LeanFT from a LTFRemoteAgent.exe.config file. Here is the part regarding Nunit:

 <nunit>

        <!framework version="3" path="C:\Program Files (x86)\NUnit.org\nunit-console" />

<framework version="2" path="C:\Nunit\NUnit-2.6.4\bin" />

!      <nunitFrameworkPath>C:\Nunit\NUnit-2.6.4\bin</nunitFrameworkPath>
</nunit>


-->


    
    <remoteAgent allowRun="true">
      <nunitFrameworkPath>C:\Nunit\NUnit-2.6.4\bin</nunitFrameworkPath>
      <testAssetDir></testAssetDir>
        
      <javaAssets>%CLASSPATH%;$LEANFT_INSTALL_DIR\SDK\Java/*</javaAssets>
    </remoteAgent>
    

When we tried to change in the Nunit-console.exe.config file it failed. 
A new nunit console exe file was conpiled that starts the nunit console with /noshadow enabled and that works. That is however only a workaround.
Is there somethere in the Nunit-console.exe.config the shadow copy can be disabled?

Our nunit-console.config file looks like this:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
 <startup>
    <supportedRuntime version="v1.1.4322" />
    <supportedRuntime version="v1.0.3705" />
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
  </startup>

  <runtime>
    <loadFromRemoteSources enabled="true"/>
    
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="lib;addins"/>
   </assemblyBinding>

   
   <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"
			appliesTo="v1.0.3705">

      <dependentAssembly> 
        <assemblyIdentity name="System" 
                          publicKeyToken="b77a5c561934e089" 
                          culture="neutral"/>
        <bindingRedirect  oldVersion="1.0.5000.0" 
                          newVersion="1.0.3300.0"/>
      </dependentAssembly>

      <dependentAssembly> 
        <assemblyIdentity name="System.Data" 
                          publicKeyToken="b77a5c561934e089" 
                          culture="neutral"/>
        <bindingRedirect  oldVersion="1.0.5000.0" 
                          newVersion="1.0.3300.0"/>
      </dependentAssembly>

      <dependentAssembly> 
        <assemblyIdentity name="System.Drawing" 
                          publicKeyToken="b03f5f7f11d50a3a" 
                          culture="neutral"/>
        <bindingRedirect  oldVersion="1.0.5000.0" 
                          newVersion="1.0.3300.0"/>
      </dependentAssembly>

      <dependentAssembly> 
        <assemblyIdentity name="System.Windows.Forms" 
                          publicKeyToken="b77a5c561934e089" 
                          culture="neutral"/>
        <bindingRedirect  oldVersion="1.0.5000.0" 
                          newVersion="1.0.3300.0"/>
      </dependentAssembly>

      <dependentAssembly> 
        <assemblyIdentity name="System.Xml" 
                          publicKeyToken="b77a5c561934e089" 
                          culture="neutral"/>
        <bindingRedirect  oldVersion="1.0.5000.0" 
                          newVersion="1.0.3300.0"/>
      </dependentAssembly>

    </assemblyBinding>

  </runtime>
  
</configuration>
