### ISSUE TITLE
File is not supported (.sln file)

### ISSUE THREAD

**Issue by MPasadu** [nunit/nunit-console#495]
Hey,
I tried to run our solution in the nunit3-console which worked fine with the following parameters:
--agents=1
--workers=1
"[Path to Solution file]"

Now I added some more parameters making the list look like this:
--agents=1
--workers=1
--config=DEBUG
--trace=Verbose
--labels=All
--wait
--skipnontestassemblies
"[Path to Solution file]"

Now I get the "File is not supported" Error. I guess I am doing something wrong? Any parameter that does not work when using a .sln file?

**Comment by mikkelbu** [comment]
Sounds related to #439 and #386.

**Comment by ChrisMaddock** [comment]
@MPasadu were you able to identify which option was causing the error here?

**Comment by ChrisMaddock** [comment]
That would be brilliant - thanks @MPasadu 😄

**Comment by MPasadu** [comment]
It seems to be the `--config=DEBUG` because when I remove that line, the error is not showing instantly like before.

**Comment by MPasadu** [comment]
InternalTraceLog:
`InternalTrace: Initializing at level Debug
15:32:41.467 Debug [ 1] ServiceManager: Added SettingsService
15:32:42.155 Debug [ 1] ServiceManager: Added DomainManager
15:32:42.170 Debug [ 1] ServiceManager: Added ExtensionService
15:32:42.170 Debug [ 1] ServiceManager: Added DriverService
15:32:42.170 Debug [ 1] ServiceManager: Added RecentFilesService
15:32:42.170 Debug [ 1] ServiceManager: Added ProjectService
15:32:42.170 Debug [ 1] ServiceManager: Added RuntimeFrameworkService
15:32:42.170 Debug [ 1] ServiceManager: Added DefaultTestRunnerFactory
15:32:42.201 Debug [ 1] ServiceManager: Added TestAgency
15:32:42.201 Debug [ 1] ServiceManager: Added ResultService
15:32:42.201 Debug [ 1] ServiceManager: Added TestFilterService
15:32:42.217 Info  [ 1] ServiceManager: Initializing SettingsService
15:32:42.311 Info  [ 1] ServiceManager: Initializing DomainManager
15:32:42.311 Info  [ 1] ServiceManager: Initializing ExtensionService
15:32:42.326 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
15:32:42.483 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
15:32:42.701 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
15:32:42.701 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
15:32:42.701 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
15:32:42.717 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
15:32:42.717 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
15:32:42.717 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
15:32:42.889 Info  [ 1] ExtensionService: Processing file D:\migRaven\Dev\Dev-7\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit.nuget.addins
15:32:42.967 Info  [ 1] ExtensionService: Scanning directory D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.NUnitProjectLoader.3.6.0\tools for extensions
15:32:43.389 Info  [ 1] ExtensionService: Scanning directory D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.VSProjectLoader.3.8.0\tools for extensions
15:32:43.405 Info  [ 1] ExtensionService: Scanning D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.NUnitProjectLoader.3.6.0\tools\nunit-project-loader.dll assembly for Extensions
15:32:43.998 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnitProjectLoader
15:32:44.030 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .nunit
15:32:44.045 Info  [ 1] ExtensionService: Scanning D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.VSProjectLoader.3.8.0\tools\vs-project-loader.dll assembly for Extensions
15:32:44.045 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type VisualStudioProjectLoader
15:32:44.045 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .sln
15:32:44.045 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .csproj
15:32:44.045 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vbproj
15:32:44.045 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vjsproj
15:32:44.045 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vcproj
15:32:44.045 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .fsproj
15:32:44.045 Info  [ 1] ServiceManager: Initializing DriverService
15:32:44.061 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
15:32:44.092 Info  [ 1] ServiceManager: Initializing RecentFilesService
15:32:44.092 Debug [ 1] ServiceManager: Request for service ISettings satisfied by SettingsService
15:32:44.092 Info  [ 1] ServiceManager: Initializing ProjectService
15:32:44.108 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
15:32:44.108 Info  [ 1] ServiceManager: Initializing RuntimeFrameworkService
15:32:44.108 Info  [ 1] ServiceManager: Initializing DefaultTestRunnerFactory
15:32:44.108 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
15:32:44.108 Info  [ 1] ServiceManager: Initializing TestAgency
15:32:47.201 Info  [ 1] ServiceManager: Initializing ResultService
15:32:47.201 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
15:32:47.201 Info  [ 1] ServiceManager: Initializing TestFilterService
15:32:47.201 Debug [ 1] ServiceManager: Request for service IResultService satisfied by ResultService
15:32:47.201 Debug [ 1] ServiceManager: Request for service ITestFilterService satisfied by TestFilterService
15:32:47.201 Debug [ 1] ServiceManager: Request for service IExtensionService satisfied by ExtensionService
15:32:47.764 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
15:32:47.764 Debug [ 1] ServiceManager: Request for service IRuntimeFrameworkService satisfied by RuntimeFrameworkService
15:32:47.764 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
15:32:47.764 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
15:32:47.826 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
15:32:47.826 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
15:32:48.733 Debug [ 1] RuntimeFrameworkService: Current framework is net-4.5
15:32:48.733 Debug [ 1] RuntimeFrameworkService: Requested framework is any
15:32:48.733 Debug [ 1] RuntimeFrameworkService: Test will use net-4.5 framework
15:32:48.795 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
15:32:48.795 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
15:32:48.795 Debug [ 1] ServiceManager: Request for service TestAgency satisfied by TestAgency
15:32:48.811 Info  [ 1] ProcessRunner: Running migRaven.sln
15:32:48.826 Info  [ 1] TestAgency: Getting standard agent for use under net-4.5
15:32:48.826 Debug [ 1] TestAgency: Using nunit-agent at D:\migRaven\Dev\Dev-7\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit-agent.exe
15:32:48.842 Debug [ 1] ServiceManager: Request for service RuntimeFrameworkService satisfied by RuntimeFrameworkService
15:32:49.139 Debug [ 1] TestAgency: Launched Agent process 212 - see nunit-agent_212.log
15:32:49.139 Debug [ 1] TestAgency: Command line: "D:\migRaven\Dev\Dev-7\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit-agent.exe" 77a3c2b0-9692-4b56-8bdd-d4bba9111351 tcp://127.0.0.1:59962/TestAgency --pid=9404 --trace:Verbose --work=C:\Users\mpadmin\Desktop
15:32:49.154 Debug [ 1] TestAgency: Waiting for agent {77a3c2b0-9692-4b56-8bdd-d4bba9111351} to register
15:33:04.467 Debug [ 1] TestAgency: Returning new agent {77a3c2b0-9692-4b56-8bdd-d4bba9111351}
15:33:06.529 Info  [ 1] ProcessRunner: Done running migRaven.sln
15:33:06.529 Info  [ 1] ProcessRunner: Unloading migRaven.sln
15:33:06.623 Debug [ 1] ProcessRunner: Stopping remote agent
15:33:13.655 Info  [ 1] ServiceManager: Stopping TestFilterService
15:33:13.655 Info  [ 1] ServiceManager: Stopping ResultService
15:33:13.655 Info  [ 1] ServiceManager: Stopping TestAgency
15:33:13.702 Info  [ 1] ServiceManager: Stopping DefaultTestRunnerFactory
15:33:13.702 Info  [ 1] ServiceManager: Stopping RuntimeFrameworkService
15:33:13.702 Info  [ 1] ServiceManager: Stopping ProjectService
15:33:13.702 Info  [ 1] ServiceManager: Stopping RecentFilesService
15:33:13.718 Info  [ 1] ServiceManager: Stopping DriverService
15:33:13.718 Info  [ 1] ServiceManager: Stopping ExtensionService
15:33:13.718 Info  [ 1] ServiceManager: Stopping DomainManager
15:33:13.718 Info  [ 1] ServiceManager: Stopping SettingsService
`
nunitAgentLog:
`InternalTrace: Initializing at level Debug
15:32:51.608 Info  [ 1] NUnitTestAgent: Agent process 212 starting
15:32:52.748 Info  [ 1] NUnitTestAgent: Running under version 4.0.30319.42000, .NET 4.5
15:32:52.779 Debug [ 1] NUnitTestAgent: Agent process has the COMPLUS_Version environment variable value "NULL" overridden with "v4.0.30319", restoring the original value.
15:32:52.858 Debug [ 1] ServiceManager: Added SettingsService
15:32:52.873 Debug [ 1] ServiceManager: Added ExtensionService
15:32:52.873 Debug [ 1] ServiceManager: Added ProjectService
15:32:52.873 Debug [ 1] ServiceManager: Added DomainManager
15:32:52.873 Debug [ 1] ServiceManager: Added InProcessTestRunnerFactory
15:32:52.873 Debug [ 1] ServiceManager: Added DriverService
15:32:52.873 Info  [ 1] NUnitTestAgent: Initializing Services
15:32:52.904 Info  [ 1] ServiceManager: Initializing SettingsService
15:32:53.014 Info  [ 1] ServiceManager: Initializing ExtensionService
15:32:53.139 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
15:32:53.717 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
15:32:53.904 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
15:32:53.920 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
15:32:53.936 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
15:32:53.936 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
15:32:53.936 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
15:32:53.936 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
15:32:54.170 Info  [ 1] ExtensionService: Processing file D:\migRaven\Dev\Dev-7\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit.nuget.addins
15:32:54.389 Info  [ 1] ExtensionService: Scanning directory D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.NUnitProjectLoader.3.6.0\tools for extensions
15:32:54.826 Info  [ 1] ExtensionService: Scanning directory D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.VSProjectLoader.3.8.0\tools for extensions
15:32:54.842 Info  [ 1] ExtensionService: Scanning D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.NUnitProjectLoader.3.6.0\tools\nunit-project-loader.dll assembly for Extensions
15:32:55.373 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnitProjectLoader
15:32:55.404 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .nunit
15:32:55.420 Info  [ 1] ExtensionService: Scanning D:\migRaven\Dev\Dev-7\packages\NUnit.Extension.VSProjectLoader.3.8.0\tools\vs-project-loader.dll assembly for Extensions
15:32:55.420 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type VisualStudioProjectLoader
15:32:55.420 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .sln
15:32:55.436 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .csproj
15:32:55.436 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vbproj
15:32:55.436 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vjsproj
15:32:55.436 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vcproj
15:32:55.436 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .fsproj
15:32:55.436 Info  [ 1] ServiceManager: Initializing ProjectService
15:32:55.436 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
15:32:55.451 Info  [ 1] ServiceManager: Initializing DomainManager
15:32:55.451 Info  [ 1] ServiceManager: Initializing InProcessTestRunnerFactory
15:32:55.451 Info  [ 1] ServiceManager: Initializing DriverService
15:32:55.467 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
15:32:55.483 Info  [ 1] NUnitTestAgent: Starting RemoteTestAgent
15:32:55.530 Info  [ 1] RemoteTestAgent: Agent starting
15:32:58.514 Info  [ 1] RemoteTestAgent: Connecting to TestAgency at tcp://127.0.0.1:59962/TestAgency
15:33:04.639 Debug [ 1] RemoteTestAgent: Registered with TestAgency
15:33:04.639 Debug [ 1] NUnitTestAgent: Waiting for stopSignal
15:33:05.639 Debug [ 5] ServiceManager: Request for service ITestRunnerFactory satisfied by InProcessTestRunnerFactory
15:33:05.654 Debug [ 5] ServiceManager: Request for service ITestRunnerFactory satisfied by InProcessTestRunnerFactory
15:33:05.654 Debug [ 5] ServiceManager: Request for service IProjectService satisfied by ProjectService
15:33:05.654 Debug [ 5] ServiceManager: Request for service DomainManager satisfied by DomainManager
15:33:06.264 Info  [ 5] DomainManager: Creating application domain domain-d6e6c3d0-migRaven.sln
15:33:06.405 Debug [ 5] ServiceManager: Request for service IDriverService satisfied by DriverService
15:33:06.623 Info  [ 5] RemoteTestAgent: Stopping
15:33:06.733 Info  [ 9] RemoteTestAgent: Waiting for messages to complete
15:33:06.748 Info  [ 9] RemoteTestAgent: Attempting shut down channel
15:33:06.764 Info  [ 9] RemoteTestAgent: Set stop signal
15:33:06.764 Debug [ 1] NUnitTestAgent: Stop signal received
15:33:06.764 Info  [ 1] NUnitTestAgent: Agent process 212 exiting cleanly
`

**Comment by ChrisMaddock** [comment]
@MPasadu thanks - although the logs were less useful than I was hoping. 😞 

If the issue is specific to `--config=DEBUG`, then it's likely that there is something specific to that config in your sln file, that is causing the issue. Are you able to share the sln file?

**Comment by MPasadu** [comment]
Unfortunately I don't think I can share the .sln file.  But maybe it is because in the solution there are different configurations for the projects. Some run x86, some run x64, some any cpu, some have mixed platforms... 

Maybe this can be the issue? The test projects are all x64 though.

**Comment by CharliePoole** [comment]
@MPasadu Do you actually have a "DEBUG" (all caps) configuration in the solution?

**Comment by MPasadu** [comment]
@CharliePoole Well...no I don't. Just started again with "Debug", seems to run fine now. 

Thanks for helping me pinpoint this mistake @ChrisMaddock, @CharliePoole
