### ISSUE TITLE
Update target information in BUILDING.md

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#5]
@ChrisMaddock commented on [Wed Aug 10 2016](https://github.com/nunit/nunit/issues/1730)

Some of the target information is outdated in BUILDING.md. Some targets no longer exist, others have incorrect dependency information (e.g. testing relying on building.)

Suggest this waits until after the split, as I'm sure it will only change more - maybe we also rewrite it in a more future-proof way. :smile: 

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1730#issuecomment-239930574)

Duplicating this in both repositories.

**Comment by ChrisMaddock** [comment]
This was done at some point.
