### ISSUE TITLE
Move VS project loader to its own repo

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#50]

**Comment by rprouse** [comment]
@CharliePoole should we start closing these split issues? Is this done?

**Comment by CharliePoole** [comment]
@rprouse I was going to close each one as I finished it. This particular one is ready to close unless you'd like to do a review. I'll do the cleanup of nunit-console all at once as part of closing the Epic.

**Comment by rprouse** [comment]
@CharliePoole, I've looked through the new repo,that is why I was asking about this issue in particular. I will close.
