### ISSUE TITLE
Real time test execution progress in Nuint ( Multiple test case scenario )

### ISSUE THREAD

**Issue by rajeeshmenoth** [nunit/nunit-console#504]
Hi,

How to get each test case real time execution progress in NUint ? In our scenario we are passing multiple test cases ( Eg, word, excel , outlook ,etc ) in NUnit console using "or" command. The execution happening in remote machine with the help of WinAppDriver. So we are getting overall test case execution result ( pass or failed) at the end the execution. 

Is it possible to get each test case execution status in console ? In one test case we have multiple steps so the overall result is depend upon test steps execution.

Any examples ?

**Comment by ChrisMaddock** [comment]
You probably want to look creating an Event Listener engine extension, with the ITestEventListener interface: https://github.com/nunit/docs/wiki/Event-Listeners


The TeamCity event listener is an example of how this might be done, although it is quite a complex one - they can be much simpler! See: https://github.com/nunit/teamcity-event-listener!

**Comment by CharliePoole** [comment]
If you are happy to merely have the final result (pass/fail) of each test without error messages, etc. then you can use --labels:After on the nunit3-console command-line.

**Comment by ChrisMaddock** [comment]
Ah - I didn't know the 'after' labels showed that! Much simpler!
