### ISSUE TITLE
Add higher-level unit tests for structure of TestRunners

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#514]
We've had a number of issues recently which have related to the structure and order of TestRunners created. This is currently a relatively complex area of code, key concerns being:

- Multiple assembly test packages
- 'Project' test packages
- Test Packages which are a mix of the above
- Precedence of top level process/domain options over options specified at lower levels in the Test Package

Currently, we have the following open issues in or around this area: https://github.com/nunit/nunit-console/issues/495, https://github.com/nunit/nunit-console/issues/439, https://github.com/nunit/nunit-console/issues/428, https://github.com/nunit/nunit-console/issues/418, https://github.com/nunit/nunit-console/issues/386, https://github.com/nunit/nunit-console/issues/382, https://github.com/nunit/nunit-console/issues/357, https://github.com/nunit/nunit-console/issues/29, https://github.com/nunit/nunit-console/issues/615

One issue I've always found in addressing these problems, is that the only testing we currently have in this area is tests of `DefaultTestRunnerFactory`, which only test the top level runner returned. To address this, I'd like to add some higher-level tests, which take a constructed test package, and test the entire structure of TestRunners that will be built.

In the long run, I would plan for this suite of tests to replace `NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed`. It's turning into a pretty big piece of work however, so I'll do this as multiple PRs instead.

Progress:

To-do's on this:

- [x] Tests for multiple projects
- [x] Tests for mix of projects and assemblies
- [x] Tests for both types of TestPackage ctor
- [x] Replace all `CorrectRunnerIsUsed` tests
- [x] Replace all `CheckInternalRunner` tests

**Comment by CharliePoole** [comment]
This is a great idea. I think there is a lot to be done and that having a separate set of higher-level (integration?) tests in their own assembly might be better than combining them into the unit test assembly.

Maybe you could come up with a structure or framework that allowed other tests to be added, thereby sharing the workload.

**Comment by ChrisMaddock** [comment]
To-do's on this:

- [ ] Tests for multiple projects
- [ ] Tests for mix of projects and assemblies
- [ ] Tests for using the TestPackage(string) ctor vs the TestPackage(List<string>) ctor. (These currently give different results, which I feel they should not! To be investigated further.)

@CharliePoole - I thought the bottom item would perhaps affect the GUI runner. Have you come across this yet, or do you also use the `TestPackage(List<string>)` ctor, regardless of the number of files in play?

**Comment by CharliePoole** [comment]
@ChrisMaddock I only use the list constructor in the GUI. 

Of course a user could use the string constructor and then call the engine API so it should be tested.

**Comment by ChrisMaddock** [comment]
Thanks Charlie. I decided this case justified it's own issue - would appreciate any thoughts on #598. 🙂
