### ISSUE TITLE
Appveyor CI failing on master

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#515]
It failed on the last merge, and on #516. 😞 Taking a look...

**Comment by mikkelbu** [comment]
Wonder if it is related to the following error? (from my phone so I cannot figure out how to make code blocks)


C:\projects\nunit-console\src\NUnitEngine\mock-assembly\mock-assembly.csproj : error NU3005: Package 'Microsoft.NETCore.Platforms 2.0.0' from source 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder': The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8). [C:\projects\nunit-console\NUnitConsole.sln]

**Comment by ChrisMaddock** [comment]
Exactly my conclusions. 😄 Appveyor made a change on the 13th Dec from what I could find, which fits with when out builds started failing. 😒 

I'm just seeing if upgrading the tests to .NET Core 2.2 works...seeing as I'm not holding out much hope for a quick fix on that issue...

**Comment by ChrisMaddock** [comment]
Siiigh, it doesn't.

As far as I can see, we can't currently build anything that cross-targets .NET Core 2.x and .NET Core 1.x on Appveyor. I wonder why the framework builds aren't failing in the same way. 🤔 

I'm out of time for today - anyone else is welcome to pick this up, if they fancy a dig. Feel free to work on the issue-515 branch, where I've upgraded all projects to .NET Core 2.2 in the hopes that that might fix this...

**Comment by ChrisMaddock** [comment]
Switched to previous appveyor image. Ticket opened here: https://help.appveyor.com/discussions/problems/18758-nuget-package-restore-failing-for-net-core-20-since-dec-13-windows-image-update
