### ISSUE TITLE
Break up multiple console error messages with colour

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#519]
Working on the NUnit tests recently, and trying to separate out the lines in multiple test failures made my eyes go a little square! What would people think to altering out colour scheme, so that the actual test failure 'header' line itself was written in read, and then the information below it written back in white. This would help provide separation between tests.

Same would also need to apply for warnings, of course.

![image](https://user-images.githubusercontent.com/4837132/50384597-d5153300-06be-11e9-8736-f6b507437d47.png)

**Comment by CharliePoole** [comment]
Sounds good to me. One line of red would call sufficient attention to it.
