### ISSUE TITLE
.NET Standard 2.0 engine crashes when .NET Framework extensions are in Global NuGet Cache

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#524]
_Found by @Xambey via [Gitter](https://gitter.im/nunit/nunit?at=5c2e001233e089363b3a5581)_

The .NET Standard 2.0 Engine currently throws if it attempts to load a .NET Framework extension (by design.) The NuGet packaging for the engine however includes a `.addins` file which attempts to locate and load all other NuGet packages installed alongside the engine. As later versions of NuGet download all packages to a global cache (e.g. _C:\Users\Chris\.nuget\packages\_), this means the engine can throw due to packages from an entirely separate project.

The fix should be to only throw when netfx extensions are located _directly_, rather than found from directories or wildcards. This behaviour would be consistent with current behaviour when attempting to load an invalid engine extension.

cc @rprouse - I think this needs fixing before the new .NET Standard builds are released. Not sure I'll have time in the near future, but I'm happy to look at this one when I can get round to it. Anyone else is welcome to jump in first!

**Comment by rprouse** [comment]
I thought this would be a problem but didn't document it and then forgot about it. I agree that we should complete this before releasing. I will leave it as unassigned for now. Either of us can grab it when we have time, just assign to yourself so I know and I will do the same.
