### ISSUE TITLE
Duplicate ids when loading a project

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#533]
When loading an NUnit solution in the TestCentric GUI, I get an exception that there is a duplicate id when attempting to add the test to a dictionary of all tests in the tree. The same happens with NUnit projects, which lead me to suspect the engine rather than the project loader.

Here's what I see happening when I load a solution file:

1. I create a package using `new TestPackage("testcentric-gui.sln")`. This gives me an anonymous package representing the command-line with one subpackage named for the solution.

2. I call `GetRunner(TestPackage package)`, which has the side effect of expanding the package. The second-level package (testcentric-gui.sln) now has 14 subpackages. The engine has correctly assigned unique ids 59 through 72 to them.

3. I call `Runner.Explore(TestFilter.Empty)`. The package remains unchanged. The tests that are returned make no use of the id prefixes that were created. That is, there are no tests 59-xxxx, etc. All the tests use the prefix "1-", which represents the Id of the solution project package rather than any of the assembly subpackages.

Researching, this appears to happen here: https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/Runners/DirectTestRunner.cs#L130

The `DirectRunner` is called with a test package, which may or may not have subprojects. As each subproject is loaded, the Id of the __parent__ project is used for the driver. I think the subproject id has to be used.

We have never detected this because we don't actually rely on unique ids across multiple assemblies in either the console runner or the adapters. We don't have tests that guarantee
1. That each driver is given a unique prefix.
2. That every test has a unique test ID.
This could easily be done by building a dictionary of ids, just as the GUI does.

**Comment by mikkelbu** [comment]
This sounds related to #33, but these are different problems right?

**Comment by CharliePoole** [comment]
@mikkelbu Did you mean to  type #33? It's about running tests in parallel.

**Comment by mikkelbu** [comment]
The issue is also about different assemblies getting the same prefix, but I'm not sure if the two issues are related. See e.g. https://github.com/nunit/nunit-console/issues/33#issuecomment-240500598.

**Comment by CharliePoole** [comment]
Right... but in that case the V2 driver was at fault. So yes, it is similar but we assumed the V3 driver was working correctly. Seems like it may not have been.

Was #33 ever fixed in the v2 driver do you think?

**Comment by CharliePoole** [comment]
OK I see what you mean. The code that I think is at fault would affect any driver, V2 or V3.
