### ISSUE TITLE
How does NUnit enumerate tests in an assembly?

### ISSUE THREAD

**Issue by Compynerd255** [nunit/nunit-console#545]
When NUnit gets a test assembly to process, what part of the code is responsible for determining the list of tests and test cases that it has to run, in order to properly schedule them? I'm interested because I'd like to implement a sort of "poor man's parallelism" for our test suite, by dividing a single test assembly between multiple isolated processes (we can't use the `Parallelizable` attribute yet because we rely too much on global variables).

**Comment by CharliePoole** [comment]
The console and engine (this repo) don't do the identification of tests. That happens in the framework.

What the runner __can__ do is pass in a filter to decide which tests get run. The selection can be based on categories or namespaces. 

This approach would require staging multiple instances of the console runner in your script. Each run would return it's own results. In short, it won't be pretty.

As an alternative, start identifying fixtures that __can__ run in parallel and gradually add to their number. Usually, fixture parallelism is easier to implement than test case parallelism.

**Comment by OlegYanushkevich** [comment]
@CharliePoole, I also thought long about how the order of parallel test runs from the library is determined and I would be very grateful if you clarified this question.

**Comment by CharliePoole** [comment]
Not sure what exactly you want clarified. Could you explain further?

**Comment by OlegYanushkevich** [comment]
@CharliePoole, Would you explain how framework determines the order of execution of test suites from the library, if all test suites are set to the maximum level of parallelism. Particularly interesting is the case when the library contains a huge number of nested namespaces, and for almost any namespace there is a setup fixture. Can I guess in what order the tests will be performed in these namespaces?
Thanks for your attention.

**Comment by CharliePoole** [comment]
The order of execution is not specified and, with parallel execution, pretty much unpredictable. For cases where ordering is important - hopefully rare - you can use the OrderAttribute but in parallel situations, that only determines the order in which tests are queued for execution and started.

**Comment by rprouse** [comment]
I am closing this as an answered question. Feel free to continue posting if you need more info.
