### ISSUE TITLE
Configurable '--explore' option to either extract list of tests or test fixtures.

### ISSUE THREAD

**Issue by dpisanu** [nunit/nunit-console#548]
Hi,

I was looking for a way to extract all test fixtures instead of the individual tests.
Is there a 'hidden' flag to switch or would this be a complete new configuration option for the --explore mode?

**Comment by CharliePoole** [comment]
The option isn't hidden, but may not be obvious. If you run "nunit3-console -h" you'll see that the --explore option let's you specify a format. There are only a few built-in formats but you can create your own by writing and installing a result writer extension. Alternatively, use the user format and create an XML transform that produces what you want.

**Comment by dpisanu** [comment]
Hmmmm. 
It was an option that was missing in Nunit 2.x that we did our own Workaround using the NUnit.Util.TestLoader and Register an own loader.Events.TestLoaded event callback.

```csharp
var loader = new NUnit.Util.TestLoader();
loader.Events.TestLoaded += NodeLoadEvent;
loader.LoadProject(assembly);
loader.LoadTest();
```
```csharp
private static void NodeLoadEvent(object sender, TestEventArgs args) {
   var test = args.Test as TestNode;
   if (test != null) {
      AddNode(test);
   }
}

private static void AddNode(TestNode node) {
   if (node.IsSuite) {
      // write suit metadate to file
   }
   else {
      // write test stub metadate to file
   }
}
```

This way I was able to create a testlist either of test fixtures or all test stubs in an assembly.
I'll have to look into the Format writer extensions and see what data goes into those.

**Comment by CharliePoole** [comment]
@dpisanu Sorry... I missed your last comment...

"as I see it the writer extensions are handling in what format something is put to file. The Content is still the same."

That's not correct... of course the content is limited to what is available, but it's your choice what you want to write to the file. The engine already includes a number of built-in "extensions":

nunit3 - writes all the content (XML) as is, without change to a file. This is the default for a test run.
cases - writes the names of test cases to the console or a file as plain text
user - transforms the XML according to a user-provided XSL transform

There is also one true extension, which you can install separately...

nunit2 - Converts the XML back to the old NUnit V2 format (as much as possible, of course)

You are completely free to create an extension that does what you want.

Of course, you could also write a TestListener type of extension and do essentially what you did for V2, that is, handle each individual test as it is loaded.

You can find the info about how to create extensions in the docs at https://github.com/nunit/docs/wiki/Writing-Engine-Extensions

**Comment by dpisanu** [comment]
Hey @CharliePoole . thx for the update. Am already in the middle of writing an own writer. 
Quick technical implementation question. Is there a reason why parameterized test cases are listed as a test suit containing test cases?
Feels off on my end.

**Comment by CharliePoole** [comment]
Having the suite of parameterized cases as a test allows you to run that test using a simple test name filter or by selecting it in a GUI that displays suites.

**Comment by rprouse** [comment]
@dpisanu do you need more help with this? I am going to close this as a question. Feel free to post here if you need more info.

**Comment by dpisanu** [comment]
Sorry for the delay. 
Would you like to have this Option in nunit? I can create a PR to provide this Export functionality out of the box.

**Comment by CharliePoole** [comment]
My suggestion would be to provide it as a separate extension first. Then, if it's desired, moving it into NUnit is pretty easy. Harder to go the other way. :smile: 

Were you thinking of an alternate format, e.g. "fixtures" rather than "tests"?
