### ISSUE TITLE
How to retrieve log for each Unit Test case with Pass/Fail status from Nunit console

### ISSUE THREAD

**Issue by batchuhari** [nunit/nunit-console#55]
Hi ,
How to get the pass or fail status for each test case. while running below command , it was creating a XML file and its stores all the information for each test case.
"nunit-console.exe  /labels  /result:console-test.xml  F:\project\test\bin\Release\Application.Test.dll  /framework=net-4.5".   
It was printing in console like 

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
***** Application.Test.TestARule
***** Application.Test.TestConstructor
***** Application.Test..TestEvaluating
Tests run: 3, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0.23005096791134 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

But how to get the pass or fail status for each test case in stdout. like 
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
***** Application.Test.TestARule :passed
***** Application.Test.TestConstructor :passed
***** Application.Test..TestEvaluating   :passed
Tests run: 3, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0.23005096791134 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

**Comment by CharliePoole** [comment]
This duplicates #24
