### ISSUE TITLE
Appveyor CI failing due to nuget restore

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit-console#556]
Builds are failing on AppVeyor in nuget restore, see e.g. https://github.com/nunit/nunit-console/pull/549#issuecomment-465684710.

```
...
Installing NUnit 3.11.0.
  OK https://ci.appveyor.com/nuget/nunit/FindPackagesById()?id='System.Reflection.TypeExtensions'&semVerLevel=2.0.0 472ms
NU3005: Package 'Microsoft.NETCore.Platforms 2.0.0' from source 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder': The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).
  GET https://www.myget.org/F/nunit-analyzers/api/v3/flatcontainer/nunit/index.json
  NotFound https://www.myget.org/F/nunit-analyzers/api/v3/flatcontainer/nunit/index.json 194ms
...
```

The problem with nuget is the same as in #515 which should be solved by #525, but it seems like the solution is not enough. 

AppVeyor had new images uploaded 11 February (see e.g. [AppVeyor Windows images update](https://www.appveyor.com/updates/2019/02/11/). There was no changes to msbuild, but nuget was bumped, so nuget now probably calls to the same msbuild version that was failing in #515.

**Comment by rprouse** [comment]
I missed this before my comments on Charlie's PR. I see that your PR attempt hasn't worked @mikkelbu. Since an older version of NuGet.exe worked, could we include that older version and do the restore using that?

**Comment by mikkelbu** [comment]
@rprouse That would probably work, but I've found another solution which is even simpler (but it took a lot of attempts 😄).

**Comment by CharliePoole** [comment]
Nice!
