### ISSUE TITLE
Allow the runner to discover all the tests in any of referenced assemblies from running project (or at least allow to specify it manually)

### ISSUE THREAD

**Issue by agat366** [nunit/nunit-console#561]
* NUnit 3.11.0 and NUnit3TestAdapter 3.12.0
* Visual Studio Enterprise 15.7.0
* dotnet cli 2.2.101 version
* .net core 2.1

The main problem is that when I add references to another project(s) which contain tests, the test adapter doesn't discover them automatically (the referenced assemblies).

This is required as some of the tests I am defining are hosted in .NET Standard library (as I have to run the tests on different platforms, including Xamarin). Yes, I know I can't run tests from .NET Standard directly, that's why **I run them as a reference attached to .NET Core**.

Currently I am creating an inheritor in .NET Core project from the Test Class of .NET Standard project so this way (either running via `VS` or `dotnet run`) the tests are (discovered and) run well.
However, this is not quite handy and flexible, as this way I have to inherit from every class containing tests existing in the referenced assembly.
For example, with Xamarin testrunners I can just specify this:             `nunit.AddTestAssembly(typeof(TemplateTests).Assembly);`
but I can't find how to achieve the same with .NET Core project.

Is there any way to do that or improve in the future?

**Comment by rprouse** [comment]
We've received no feedback on this issue in nearly a month so I am going to close as won't fix. If anyone has a compelling argument, please post and we will consider reopening.
