### ISSUE TITLE
Where are the checksums for your downloads?

### ISSUE THREAD

**Issue by ghost** [nunit/nunit-console#570]
Can you please place references to these on your site?  I do not wish to register my work e-mail via your Google Group site.  Thank you!

**Comment by rprouse** [comment]
I am going to put this up for discussion. There isn't an easy way to add checksums to GitHub releases and we don't list all of our packages on our website. Hopefully soon, our NuGet packages and our MSI will be signed ensuring authenticity, but until then downloading from NuGet or GitHub over HTTPS pretty much guarantees authenticity. We've reserved the NUnit prefix on NuGet so nobody else can release similar packages anymore.

This is seldom asked for. What is your workflow that this would help with?

**Comment by CharliePoole** [comment]
The last two releases (3.13.1 and 3.13.2) included checksums. I've added this to the 3.14 milestone for reporting purposes.
