### ISSUE TITLE
Space characters in the work directory path are not properly handled

### ISSUE THREAD

**Issue by Funbit** [nunit/nunit-console#571]
When nunit3-console constructs the command line to run an agent, it does not properly double-quote the work directory path, that causes the runner to fail.

Here is a sample internal trace log:

```
14:40:58.747 Debug [ 1] TestAgency: Command line: "C:\Contoso\bin\Release With Spaces\TestPackage\nunit-agent.exe" f3ab647d-8aa4-4cb9-8032-a55f48aae46e tcp://127.0.0.1:60774/TestAgency --pid=16708 --trace:Debug --work=C:\Contoso\bin\Release With Spaces\TestPackage
14:40:58.748 Debug [ 1] TestAgency: Waiting for agent {f3ab647d-8aa4-4cb9-8032-a55f48aae46e} to register
14:40:59.350 Error [ 1] ProcessRunner: Failed to run remote tests Unable to acquire remote process agent
```

As you may see, the last part:
```
--work=C:\Contoso\bin\Release With Spaces\TestPackage
```

contains the path without quotes.

The problem is in the "nunit-console-3.9\src\NUnitEngine\nunit.engine\Services\TestAgency.cs" source file inside LaunchAgentProcess method. 

Current code looks like this:

```
agentArgs += " --work=" + workDirectory;
```

The fixed version:

```
agentArgs += " --work \"" + workDirectory + "\"";
```

For now, we'll be using our custom fixed nunit-console build, but it would be great if the issue is fixed in the next official release. Thank you!

**Comment by ChrisMaddock** [comment]
Thanks @Funbit. We'd love a pull request to fix this, if you'd be interested!
