### ISSUE TITLE
Nunit Tests on Linux Containers

### ISSUE THREAD

**Issue by jibinjose087** [nunit/nunit-console#577]
I am trying to run unit test using Linux containers, the final build output of my code is testapp.exe file so I have build the testapp.exe using a windows agent. Copied the build files and created a linux mono docker image but when I am trying to execute the tests inside the container I am getting the following error. Is there any way to get rid of this error? The CMD command that I am using to execute the tests is as follows.

CMD mono /app/nunit/nunit3-console.exe /app/xxxxx/xxxxx/bin/Release/testapp.exe --test="xxxxxxx.xxxxxx.xxxxxTests.xxxxxx.xxxxxxxTest" --workers=2 --dispose-runners --result=/tmp/Result.xml

1) SetUp Error : xxxxxxx.xxxxxx.xxxxxTests.xxxxxx.xxxxxxxTest System.IO.IOException : Cannot create /app/xxxxx/xxxxx/bin/Release/testapp.exe because a file with the same name already exists. at System.IO.Directory.CreateDirectory (System.String path) [0x0006a] in <7b0d87324cab49bf96eac679025e77d1>:0 at System.IO.DirectoryInfo.Create () [0x00000] in <7b0d87324cab49bf96eac679025e77d1>:0 at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()

Is this Nunit-console trying to rebuild the code again?

**Comment by rprouse** [comment]
What platform is your tests targeting? Are they Mono or are they .NET Core?

NUnit Console will not try to rebuild your tests, it should just load the assembly then find and execute your tests.

**Comment by jibinjose087** [comment]
Its a .net project and I build the code using Visual Studio and copied the same to a docker container with Linux mono as image. Then executed the test cases from it using CMD command which results in above error.

**Comment by rprouse** [comment]
Are you using the official Mono image (https://hub.docker.com/_/mono)? If so, which version?

The NUnit Console is installed in /app/nunit. How did it get there? Did you install it as part of your own Docker image? If so, can I see your Dockerfile?

**Comment by ChrisMaddock** [comment]
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂
