### ISSUE TITLE
System.Configuration.ConfigurationErrorsException thrown in multiple domain mode.

### ISSUE THREAD

**Issue by mrsneeze** [nunit/nunit-console#58]
I have an issue that I was finding when using multiple domain mode and assemblies with user configuration.

If you have both multiple AppDomains specifided in nunit and a project that contains several modules that use the configuration system they can fail with the exception:
System.Configuration.ConfigurationErrorsException : Configuration system failed to initialize
----> System.Configuration.ConfigurationErrorsException : Unrecognized configuration section userSettings. (C:\Users\username\AppData\Local\NUnit_Software\test-domain-Components.Mi_Url_zeii3t5j3suizxytnaaivzomze5k3svw\3.4.1.0\user.config line 3)

The problem is that windows stores user configuration, it using only the first 25 characters of the AppDomain name in the directory. When nunit creates a test domain it's called test-domain-<assembly namespace>, so we're already using 12 characters for test-domain-. This means that the domains are using the same configuration area if they have the same first 13 characters of the assembly namespace - in our case, that's Components.Misc.Utils and Component.Misc.Client (eg) both give the test-domain-Components.Mi_Url_zeii3t5j3suizxytnaaivzomze5k3svw directory in the exception. The two assemblies will thus use the same file, which causes this error if one assembly has no user settings. There's also likely to be some potential unexpected conflicts in settings.

We can work around this using a single domain and a single separate process, but that isn't always possible.

I've made a simple fix that solves this problem in a fork - I've added the hash of the string into the domain name. This should usually be different for different domains - there's obviously some risk that similar domains will be created, but I think that is managably small. Better solutions I'm sure exist, such as a longer hash of the assembly name.

The patch I've used is: 

```
--- a/src/NUnitEngine/nunit.engine/Services/DomainManager.cs
+++ b/src/NUnitEngine/nunit.engine/Services/DomainManager.cs
@@ -57,7 +57,7 @@ namespace NUnit.Engine.Services
         {
             AppDomainSetup setup = CreateAppDomainSetup(package);

-            string domainName = "test-domain-" + package.Name;
+            string domainName = "domain-" + package.Name.GetHashCode().ToString("x") + "-" + package.Name;
             // Setup the Evidence
             Evidence evidence = new Evidence(AppDomain.CurrentDomain.Evidence);
             if (evidence.Count == 0)
```

**Comment by CharliePoole** [comment]
@mrsneeze I edited your post for legibility... the patch has to be "fenced in" by triple backticks to avoid the special characters it contains being interpreted as markup.

Anyway... good idea and an easy fix for anyone who wants to take it on.

**Comment by mrsneeze** [comment]
Ooops! Forgot to check the preview...

I can create a pull request for that patch - would that be useful?

**Comment by rprouse** [comment]
@mrsneeze A pull request would be welcome 👍
