### ISSUE TITLE
Console runner not found category

### ISSUE THREAD

**Issue by KellsoHP** [nunit/nunit-console#604]
`public class InDevAttribute : CategoryAttribute`
`{`
` public InDevAttribute() : base("InDev") { }`
`}`

![image](https://user-images.githubusercontent.com/29897598/55614329-c5b58380-579d-11e9-8109-ef93c31344f9.png)

When a class is inherited from the Category attribute, it converges.
If you specify explicitly `[Category("InDev")]`, then all the tests are.

**Comment by CharliePoole** [comment]
This looks to me like it should work. However, check the character set in your file. Otherwise, someone needs to step through the NUnit code.

**Comment by CharliePoole** [comment]
BTW, what happens if you use the default base constructor? That's  the intended way to create your own categories.

**Comment by KellsoHP** [comment]
> BTW, what happens if you use the default base constructor? That's the intended way to create your own category attributes.

Nothing, the attribute is not found

**Comment by CharliePoole** [comment]
Well then, to state the obvious, something is broken. :smiling_imp: 

My memory says this used to work and we had tests for it. We certainly must not have tests right now or they would be failing. I'm curious so I'll take a look.

**Comment by CharliePoole** [comment]
NUnit's own tests verify that inherited attributes work. Here's an example of a definition that is verified to work in our tests.

```c#
    [AttributeUsage(AttributeTargets.Method, AllowMultiple=false, Inherited=false)]
    public class CriticalAttribute : CategoryAttribute { }
```

Have you given us the complete definition of your attribute? Don't you have an `AttributeUsageAttribute`?

**Comment by CharliePoole** [comment]
@KellsoHP  Haven't heard back from you regarding the last comment and question, so closing this. If you provide any more info so we can reproduce it, we can re-open.
