### ISSUE TITLE
Unload + Load changes TestPackage IDs

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#607]
In order to differentiate tests in different assemblies, each package and subpackage is given an ID, which is eventually passed to the driver executing the tests of each assembly. The framework then uses the ID as a prefix for all the test IDs it generates, e.g. `5-1234`, where `5` is the package ID.

All existing NUnit runners merely load the tests once and never reloads them. Even the VS test adapter works that way, since Visual Studio creates a new process each time tests are to be re-discovered.

However, in creating a GUI that reloads tests, it is more convenient if each fresh test load starts the sequence of TestPackage IDs over at `0`. In that way, provided the same projects and assemblies are being reloaded without change, all test IDs will continue to match.

I came across this issue working on the TestCentric GUI. Because of somewhat serious problems with the engine's `ITestRunner.Reload` (to be treated in a separate issue) I decided to stop using that method and replace it with a sequence of `Unload` followed by `Load`. This works fine except that the visual state of the test tree can no longer be restored. That's because the IDs saved no longer match those of the reloaded tests.

For example, in a simple `.nunit` project containing two assemblies, the initial IDs are

```
0 = the test run
1 = the project
2 = the first assembly
3 = the second assembly
```

After unload/reload, the IDs are

```
4 = the test run
5 = the project
6 = the first assembly
7 = the second assembly
```

What I would like to do is reset the counter used for TestPackage IDs to 0 whenever a complete new load is performed through the `MasterTestRunner`. I don't believe this will have any negative impact on other runners, which only load the tests once, and it will make test results much more predictable.

**Comment by CharliePoole** [comment]
Testing out a fix in the TestCentric/nunit-console repository. I simply added resetting the next ID value to zero in the constructor that takes a list of files rather than a single file.

This should work with the current usage pattern but it still seems fragile because someone might use the constructor in some other way in the future. The ultimate solution is probably to provide a static method to re-initialize the generation of IDs.

**Comment by CharliePoole** [comment]
@ChrisMaddock Any thoughts as to the best way to handle this?

My current code just sets the "_nextID" field to 0 in the constructor that takes an`IList`. That feels like something of a hidden side effect. Another option I can think of is to have a method like `InitializeIDGenerator()`. We could also have a public setter to set up the static next ID, but that's a bit too easy to abuse in my view.

**Comment by ChrisMaddock** [comment]
All these suggestions feel a little fragile. Is a static int on TestPackage suitable for this?

What about if there was an internal setter for `TestPackage.ID`, and MasterTestRunner was responsible for allocating each package an ID?

**Comment by CharliePoole** [comment]
In retrospect, probably not, but I was trying to live with it since it's already there. TestPackages have had a unique ID generated in the constructor for four years now, so changing it runs the risk that somebody has relied on it's being done there.

If we went the way you suggest, packages would have to start out either as now or with an empty ID.
MasterTestRunner, when passed a test package would have to (re)assign the id for the top level and any subpackages as well as for any new subpackages it created on its own. This sounds more correct in some ways but also more complicated.

To use an internal method, we would of course have to add `InternalsVisibleTo` to the api assembly so that the engine assembly could access the internal field. It feels a little odd having internals in an api assembly, but could definitely be done.

Given all the constraints, I would personally lean toward a public method or a setter for the seed, documenting the effect if it is used incorrectly. I'm happy to go however you want though.

**Comment by ChrisMaddock** [comment]
>TestPackages have had a unique ID generated in the constructor for four years now, so changing it runs the risk that somebody has relied on it's being done there.

Good point. I'd prefer the MasterTestRunner approach if we were starting from scratch, but probably best not to change it now. Ahh hindsight! 😄 

We never defined exactly what the ID should be. How about a different approach to the problem - rather than resetting the counter and trying to recreate the same ID, could we use something deterministic to the package? The TestPackage object hash?

**Comment by CharliePoole** [comment]
The ID could be any unique string. Use of a sequence number came about back in NUnit V2, where it was used as an index to a list of the assemblies being run. If anyone is counting on it's being the string representation of an integer, I think that's too bad and we could change it.

Using the object hash has a few drawbacks, however...

1. Some of my MasterTestRunnerTests use the same assembly multiple times. They would come up with the same ID. This is probably only a test artifact and could be fixed.

2. You could never run the same assembly twice, either on the command-line or from the GUI. I don't know if anyone does that as a performance test for example.

3. If you changed the properties in any way, then the ID would change. The package would look to a GUI like a new package rather than a reload of an existing package. This one could be fixed by using a generated id based on the full name of the assembly or other file, but that runs into problems 1 and 2.

I went through all this years ago. I'd really wanted a better solution than a sequential ID, but I found the problem is more complicated than it initially appears.

BTW what we see here is one of the reasons I wanted to keep an NUnit GUI. A GUI pushes the limits of any API in ways that batch processing doesn't always do.

In the longer term, I would love to see a different solution, with persistent package IDs. In the short, I think we have to keep doing what we are doing with the constructor, possibly adding a new constructor or a setter - I think we can do that and preserve backward compatibillity - and having a method used by long-running clients (like the GUI) to basically reset the generation back to zero. If the new code is purely additive, I thiink we can maintain the 3.0.0.0 assembly version, as promised. Of course, that would all have to be tested.

If you like, I can create a PR.

An alternative, fairly obvious if you think of it, is to __stop__ using the package ID as the prefix for tests and have the MTR map package IDs to prefixes it generates itself.

In spite of the obviousness, I only just thought of it. I could do a spike for that approach as well.

**Comment by ChrisMaddock** [comment]
All the above make sense if the ID has is tied to the assembly - but I don't think any of those cause an issue if the hash is tied to the TestPackage object itself? Do you think there's any reason why that wouldn't work?

**Comment by CharliePoole** [comment]
It would depend on the implementation of the hash, of course. I just can't think of an implementation that solves all of the above.

**Comment by CharliePoole** [comment]
To clarify a hash based on the object identity of the test package, works if the test package is modified but never replaced. I think it will take some coding to see if that's possible. I'm willing to try anyway.

**Comment by CharliePoole** [comment]
@ChrisMaddock OK... I've worked through this. Your ideas about object identity gave me the key.

My solution is that any client that wants a clean reload with the same ids retained has to use the same test package. Test packages can have their settings changed without changing their identity. You can't change what files they refer to without creating a new package. So the problem should be soluble by the runner.

To verify this, I modified my simulated reload (load plus unload) in the GUI so the test package is no longer destroyed and recreated. It works fine!

For a true engine-based reload we'll need to do more, but I think this can be closed without action if you agree.

**Comment by CharliePoole** [comment]
On second thought, we should at least add some documentation. I'll create a PR.
