### ISSUE TITLE
TestPackage(string) constructor fails under certain process/domain modes

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#615]
Found under the tests from #514.

Under certain situations, the `TestPackage(string)` constructor, creates a different set of TestRunners to the `TestPackage(IList<string>)` ctor, for a single-assembly package. We decided in #598 that both of these constructors should leave to the same end result.

The combinations which don't work are listed below. None of these are high-priority, as using neither Process:Multiple or Domain:Multiple makes much sense when you only have a single assembly - however both ctor's should have the same behaviour here. 

```
ProcessModel:Single DomainUsage:Multiple
ProcessModel:Multiple DomainUsage:Default
ProcessModel:Multiple DomainUsage:None
ProcessModel:Multiple DomainUsage:Single
ProcessModel:Multiple DomainUsage:Multiple
```

This 'list' variant is the more popular option, which looks to be the one working correctly.

**Comment by ChrisMaddock** [comment]
Behaviour also differs when running a single project file, in the .NET Standard 2.0 build only.

**Comment by ChrisMaddock** [comment]
This ctor creates a different ITestRunner to the normal for projects too - I haven't tested, but I imagine a number of these options don't work. Getting this controlled under test in #616 before making changes...

**Comment by CharliePoole** [comment]
The TestPackage(string) constructor no longer exists, nor do ProcessModel and DomainUsage, so this seems safe to close. :-)
