### ISSUE TITLE
[Feature] Extend <start-run> data for ITestEventListener

### ISSUE THREAD

**Issue by elv1s42** [nunit/nunit-console#625]
Hello,
This is not a bug but a feature request to improve this extension: https://github.com/nunit/docs/wiki/Event-Listeners.

At the moment I think we don't have enough information about the tests when run is started.
Consider the following example:
``` csharp

[Extension(Description = "My NUnit Extension")]
public class MyEventListener : ITestEventListener
{
     public void OnTestEvent(string report)
     {
         var xmlNode = XmlHelper.CreateXmlNode(report);

         switch (xmlNode.Name)
         {
             case "start-run":
             {
                 //Some custom logic here...
                 break;
             }

```

At the moment the only data I'm getting here is the string `<start-run count='0'/>`
But it whould be nice to get some information like test run start `DateTime`, the command which is used to run the tests, engine version, clr version.

The use case for this change is simple: this data can be used for creating custom real-time test run reports based on `ITestEventListener` extension point.

I did a small investigation and it looks like the change should be quite simple, we could extend RunTests method [here](https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs#L425) (@CharliePoole, please correct me if I'm wrong)

If you agree this is a useful feature I can prepare pull request with possible code changes, but first we may need to choose the data to be available in `<start-run>` section.

Thank you

Regards,
Evgeniy

**Comment by CharliePoole** [comment]
I'll leave the usefulness of this up to the @nunit/engine-team.

If it is done, those elements, which are now added to the `test-run` element, would have to be additionally added to the `start-run` element.

**Comment by ChrisMaddock** [comment]
I'd have no objection to accepting a PR here. @elv1s42 - would you come up with a list of the items you'd want to add? I wonder if we should instead have a convention, that `start-run` will contain all the same elements that `test-run` does. (Wherever possible)

By the way, if you're planning on making use of this event, are you aware of this outstanding issue?
https://github.com/nunit/nunit-console/issues/441

**Comment by elv1s42** [comment]
Hi @ChrisMaddock and @CharliePoole !

Thank you very much for quick response. 

I agree the `start-run` should include (if possible) the same arguments as `test-run`, but what should I do with `command-line`? I think it should be the child of `run-start`.

So now we have this `run-start` element:
``` xml
<start-run count='0'/>
```

I'll include some more data and `start-run` will look like this:
``` xml
<start-run count='0' engine-version="3.8.0.0" clr-version="4.0.30319.42000" start-time="2018-07-04 08:36:04Z">
   <command-line><![CDATA[C:\_NUnit3.8\nunit-console\nunit3-console.exe  C:\Tests\SomeTests.nunit]]></command-line>
<start-run>
```

So the total list of new elements is:
 - `engine-version` as a new attribute for `start-run` element
 - `clr-version` as a new attribute for `start-run` element
 - `start-time` as a new attribute for `start-run` element
 - `command-line` as a child of `start-run` node

Please confirm the list of elements and their location.

Regards,
Evgeniy

**Comment by ChrisMaddock** [comment]
This looks good to me - would be good just to get confirmation from others someone else on @nunit/engine-team before going ahead. 🙂

**Comment by CharliePoole** [comment]
Looks good to me as well.

**Comment by elv1s42** [comment]
Hi @ChrisMaddock,
 
I've implemented the changes [here](https://github.com/nunit/nunit-console/pull/629)

Thank you

**Comment by mikkelbu** [comment]
#629 did not auto-close this issue, as "Resolving" is not one of the recognised keywords.
