### ISSUE TITLE
Have a consistent download url for console

### ISSUE THREAD

**Issue by dfev77** [nunit/nunit-console#631]
Please use a consistent url download for the zip console so that automated processes can make use of it without a need to update our tools on each nunit version.

https://github.com/nunit/nunit-console/releases/download/3.10/NUnit.Console-3.10.0.zip
https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Console-3.9.0.zip
https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Console-3.8.0.zip

**Comment by CharliePoole** [comment]
A "latest" or "stable" URL seems possible in addition to the downloads for each version, which are needed by some people.

**Comment by ChrisMaddock** [comment]
Hey @dfev77 - thanks for raising this. 

If you're referring to the 'format' of the URL (in using v3.9 vs 3.9) - then I think we did I one-time switch to the "v" format in between 3.8 and 3.9 - as this better integrates with some GitHub functionality. (I think there's a typo in your original post - everything from 3.9 onwards uses the 'v3.9' format - acorss both the framework and console repos.) Unfortunately this part of our release process isn't automated yet, but we aim for it to be consistent between releases.

If you're instead referring to a single URL which always fetches the latest version, as Charlie suggests, then instead I'd suggest using something like the below, to find the file through the GitHub API.
https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

I'm going to close this ticket as I don't believe there are any active changes we'll want to make for this - but feel free to comment further if you disagree, we'll still get the notifications.

**Comment by dfev77** [comment]
@ChrisMaddock, not sure which is the typo that you mention, but my issue is that the 3.10 version is not using the "v" prefix. 
Right now I see that the "v" is back in the download link.

Thanks for the "latest" link, will give it a try.

**Comment by ChrisMaddock** [comment]
> @ChrisMaddock, not sure which is the typo that you mention, but my issue is that the 3.10 version is not using the "v" prefix.
Right now I see that the "v" is back in the download link.

I thought 3.10 was always using the v - but if I’m wrong and someone’s quietly changed it - my apologies!

**Comment by rprouse** [comment]
@ChrisMaddock the v in the format should be consistent, but it is whatever I type in when I create the release. One more reason to automate our releases 😉
