### ISSUE TITLE
Labels option: Rename On as OnOutputOnly, and deprecate On and All

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#636]
Copy and pasted from #630, discussed there. I'll make sure this goes in before 3.11.

My thoughts on the existing API (that I think we're in agreement on) is that `On` and `All` are now ambiguous and not futureproof. I suggest the following changes, as which would allow us to clean up the current API, and better make further changes in future.

| Option | Change |
|---------|----------|
| `Off` | No change |
| `After` | No change |
| `Before` | No change |
| `BeforeAndAfter` | Show labels at start and end of each test case - as per this PR. |
| `OutputOnly` | New option, replaces 'on', but with a less ambiguous name. |
| `On` | Deprecate - Remove doc and print warning, as per `--params` |
| `All` | Deprecate - Remove doc and print warning, as per `--params`  |

**Comment by CharliePoole** [comment]
We should do same for NUnitlite.

BTW, I realized its not a problem for the GUI. I just expose checkboxes for what I support.
