### ISSUE TITLE
Engine initializes DriverService too early

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#639]
The `DriverService` is added before the `ExtensionService`, on which it depends. There is no obvious error because the `DriverService` is written so that it can function if the `ExtensionService` is not available (e.g.: under .NET Core).

This only happens in `TestEngine`'s self-initialization. When used in the agent, it is initialized by the agent and no problem arises. The biggest visible effect is that you can't run NUnit V2 tests in process.

**Comment by ChrisMaddock** [comment]
Fixed by https://github.com/TestCentric/testcentric-gui/issues/340.
