### ISSUE TITLE
Build.ps1 fails if spaces in path

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#64]
@ChrisMaddock commented on [Thu Sep 29 2016](https://github.com/nunit/nunit/issues/1811)

If the nunit repo is in a location with spaces in the path, the build.ps1 bootstrapping script fails.

The [latest version from Cake](https://github.com/cake-build/cake/blob/develop/build.ps1) appears to fix this issue. It does however:
- Specify a specific Cake version. I haven't yet looked at how this interacts with our current method of specifying in packages.config, but we should look in to that.
- Install the .NET Core cli. Are we ok with this?

Duplicating this in nunit-console, as it looks to have the same build.ps1

**Comment by mikkelbu** [comment]
@ChrisMaddock The script works now. I just tested it with the path "F:\Source\Path Space\nunit-console". I guess that the commit a5c3785ed8d6a35868bc169f07e40e889087fd2e corrected this behaviour.

**Comment by ChrisMaddock** [comment]
Great - thanks for looking into that @mikkelbu! 😄
