### ISSUE TITLE
Run tests on in-memory assembly

### ISSUE THREAD

**Issue by varsanyid** [nunit/nunit-console#643]
Hi!

Is it possible to populate a TestPackage with an in-memory assembly that has been emitted to stream and not present on the disk? I'm using .NET core 2 and nunit.engine.netstandard 3.8.0.

**Comment by rprouse** [comment]
Interesting question. First, I'd recommend using the latest release of the NUnit Engine which contains a .NET Standard target of the engine. The version of the engine you are using is deprecated.

To start though, you might want to try creating a .NET Core console app and using NUnitLite. I'm not positive it will work, but it will be a great first step.

It would look something like this;

```C#
public static int Main(string[] args)
{
    Assembly asm = CreateInMemoryAssembly();
    return new AutoRun(asm).Execute(args);
}
```

Let us know how it goes...

**Comment by varsanyid** [comment]
Cheers! I'll get back to you asap.

**Comment by varsanyid** [comment]
Thanks @rprouse, following your advice I managed to make it work! However, Execute returns an int, but there is an overloaded version which accepts a TextWriter but the result I get is rather raw. 
```C#
var testReportBuilder = new StringBuilder();
var writer = new ExtendedTextWrapper(new StringWriter(testReportBuilder));
var executedAssemblyResult = new AutoRun(inMemoryAssembly).Execute(new string[] { }, writer, null);
```
The builder gets populated with this plain text data:
```
{NUnitLite 3.12.0 (.NET Standard 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: ...
  CLR Version: ...

Test Files ...

Test Discovery
  Start time: 2019-06-15 21:24:35Z
    End time: 2019-06-15 21:24:35Z
    Duration: 0.055 seconds

Errors, Failures and Warnings

1) Failed : Namespace.Class.Method
  Expected: < 1, 5, 9, 12, 22, 31, 45, 58, 114 >
  But was:  null
   at Namespace.Class.Method()

Run Settings
    Number of Test Workers: 8
    Work Directory:  ...
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 1, Passed: 0, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 1, Errors: 0, Invalid: 0
  Start time: 2019-06-15 21:24:35Z
    End time: 2019-06-15 21:24:35Z
    Duration: 0.112 seconds

}
```
Omitted some parts. I guess this is the raw data captured from the stream that was supposed to write to stdout? Is there a way to capture a formatted version of it, or it's not meant to behave like that at all?

**Comment by rprouse** [comment]
If you want to go a bit deeper, the next step is to look at the NUnitLite code, specifically the [TextRunner class](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite/TextRunner.cs). In it, look at how it creates and uses it's `_runner` member and how it implements the `ITestListener` interface. That interface will give you access to the test events as they happen.

If you wanted to create a more full-featured test runner that works with any version of NUnit, then you need to switch over to the [NUnit Console project](https://github.com/nunit/nunit-console) and use the engine, possibly starting at the [ConsoleRunner class](https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console/ConsoleRunner.cs) as an example.

**Comment by varsanyid** [comment]
Thanks for your time, @rprouse! I'm closing the issue as I've got everything answered.
