### ISSUE TITLE
Run a single test programatically

### ISSUE THREAD

**Issue by anunay1** [nunit/nunit-console#654]
Hi, 

I am using nunit3 version 3.12.0, & I want to run a single test, I am trying the below code, but it throws and exception, 
            ITestEngine engine = TestEngineActivator.CreateInstance();
            TestPackage package = new TestPackage(testExecutable);
            runner = engine.GetRunner(package);
            runner.Load();
            TestFilter filter = new TestFilter(testcasesName);
            XmlNode result = runner.Run(new NullListener(), filter);
![image](https://user-images.githubusercontent.com/7989610/59906778-282a3180-9427-11e9-8312-baf15285f0a9.png)

Has anyone tried the same? Urgent help will be highly appreciated.

**Comment by ChrisMaddock** [comment]
`TestFilter`'s parameter needs to be an XML string, rather than just the test name itself.

I would instead make use of the `ITestFilterService` to build your filter, something a little like this:

```
var testFilterService = engine.Services.GetService<ITestFilterService>();
var testFilterBuilder = service.GetBuilder();
testFilterBuilder.AddTest(testcaseName);
TestFilter filter = testFilterBuilder.GetFilter();
```

Hope that helps - let us know if you hit any further problems. 🙂

**Comment by anunay1** [comment]
Hi Chris 
Thanks a lot for the response, I tried the sample code, it does not throw any exception, but it does not start the test execution, below is the modified code: 
            string testExecutable = Path.GetDirectoryName(Application.ExecutablePath) + "\\nUnitSample.dll";

            ITestEngine engine = TestEngineActivator.CreateInstance();
            TestPackage package = new TestPackage(testExecutable);
            runner = engine.GetRunner(package);
            var testFilterService = engine.Services.GetService<ITestFilterService>();
            var testFilterBuilder = testFilterService.GetTestFilterBuilder();
            testFilterBuilder.AddTest(testcasesName);
            TestFilter filter = testFilterBuilder.GetFilter();
            XmlNode result = runner.Run(new NullListener(), filter);

**Comment by CharliePoole** [comment]
The name you pass has to be the FullName of your method.

**Comment by anunay1** [comment]
You mean with namespace by full name

**Comment by CharliePoole** [comment]
Yes.

**Comment by anunay1** [comment]
Thanks, it works.
