### ISSUE TITLE
Mono: Stacktrace missing files and line numbers

### ISSUE THREAD

**Issue by ArnaudValensi** [nunit/nunit-console#662]
Hi, 

For my CI and my TDD workflow, I need to display the stacktrace with the line number on the console, but I cannot figure out how.

Here what I have with nunit3-console:
```
$ mono --debug --optimize=-inline nunit3-console.exe ../../../Ecs.Tests/bin/Debug/EcsTests.dll
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
mercredi 3 juillet 2019 04:06:23

Runtime Environment
   OS Version: MacOSX 18.6.0.0
  CLR Version: 4.0.30319.42000

Test Files
    ../../../Ecs.Tests/bin/Debug/EcsTests.dll


Errors, Failures and Warnings

1) Failed : EcsTests.BagTest.Capacity
  Expected: 25
  But was:  24
  at EcsTests.BagTest.Cap () [0x00000] in <7cec980c48ea4a1880f73954ca19d517>:0
  at EcsTests.BagTest.Capacity () [0x00000] in <7cec980c48ea4a1880f73954ca19d517>:0

...
```

But it works in Visual Studo for Mac 2019 (which is Xamarin rebranded and use mono under the hood for .net framework projects):

<img width="788" alt="image" src="https://user-images.githubusercontent.com/604486/60558373-49552100-9d49-11e9-9bf5-76e61f7a9134.png">

I have the same problem with xunit, https://github.com/xunit/xunit/issues/1978

I am on a mac.

My config:
```
$ mono --version
Mono JIT compiler version 5.20.1.19 (2018-10/886c4901747 Tue Apr  9 12:37:29 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

My csproj file:
```
$ cat Ecs.Tests.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\NUnit.3.12.0\build\NUnit.props" Condition="Exists('..\packages\NUnit.3.12.0\build\NUnit.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{AB1EDD63-FEB9-48BD-8E9F-06458C72F7B9}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>EcsTests</RootNamespace>
    <AssemblyName>EcsTests</AssemblyName>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="nunit.framework">
      <HintPath>..\packages\NUnit.3.12.0\lib\net45\nunit.framework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="RegisterTest.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="BagTest.cs" />
    <Compile Include="EntitiesTest.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ecs\Ecs.csproj">
      <Project>{C9670E64-D4E2-44F4-8180-4606198A140F}</Project>
      <Name>Ecs</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
</Project>
```

To build I tryed using Visual Studio for Mac and `msbuild /p:Configuration=Debug Ecs.Tests/Ecs.Tests.csproj`

Older issue:
- https://stackoverflow.com/questions/22637506/nunit-mono-not-printing-stack-trace-line-number-even-with-debug

I see that a change about pdb file had occured in mono 5.0.0 https://www.mono-project.com/docs/about-mono/releases/5.0.0/

**Comment by ChrisMaddock** [comment]
Sorry - we're a little lacking on the team for people familiar with mono, but happy to accept a PR if anyone can figure out the problem. Will leave this open in case anyone in the mono community is able to help.

**Comment by tdctaz** [comment]
Just encountered the same issue and found this bug. After a bit of investigation I found that mono now only shows filenames and line numbers in stacktraces when mono is invoked with `--debug`. Nunit engine starts the nunit agent without passing `--debug` to mono.

Using the console with `debug` or `debug-agent` would start mono with `--debug` but would also try to attach a debugger which is not what you would want.

In TestAgency.cs changing
```if (debugTests || debugAgent) monoOptions += " --debug";```
to
```monoOptions += " --debug";```
would change the issue, if a PR with this change is acceptable then I'll be happy to make it

**Comment by ChrisMaddock** [comment]
Great, thanks @tdctaz - we'd appreciate the PR!

One thought, could you checkout whether adding the `--debug` option all the time has any impact on the speed of tests running normally? My only thought is that if it's a significant slowdown, we might want to make it opt-in, and perhaps create a new flag for the option.

**Comment by ChrisMaddock** [comment]
For anyone watching this issue, the fix is now available in a beta release. Thanks to @tdctaz for contributing the solution!

We've seen a couple of flaky builds in our CI since this fix was merged. I'm _hoping_ it's coincidental and not related, but I'd be keen for further testing here to make sure we're not introducing instability by enabling the debug option.

The beta release is available on GitHub and NuGet - please give it a whirl and let us know any feedback! 👍
