### ISSUE TITLE
NUnit console extremely slow on docker Windows container

### ISSUE THREAD

**Issue by bnm22** [nunit/nunit-console#665]
Hi, this is more of a question vs an issue. I am trying to run my project's unit tests on a Windows docker container and it takes an extremely long time. 

Running on:
2016 Windows container 8 cpus: 83 minutes
2012R2 Windows Server 8 cpus: 3 minutes
2010 Windows 12 cpus: 90 seconds

I tried NUnit console versions 3.6.1 and 3.8. Any ideas would be greatly appreciated. Thank you!

**Comment by mikkelbu** [comment]
Hi @bnm22 I've not hear this before. How many resources have you assigned to the docker deamon (can be found on the advanced pane)?

**Comment by bnm22** [comment]
I have the Docker Desktop app installed and doesn't appear I assigned anything in particular to the deamon. I tried running the container at my machine max resources, 12 cpus and 32GB memory. 

This is my daemon.json on my local machine. 
`{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false
}`

**Comment by bnm22** [comment]
Found out it was bad unit tests. Thanks for the help!
