### ISSUE TITLE
One incorrect test fails all tests in test fixture

### ISSUE THREAD

**Issue by toolmagic** [nunit/nunit-console#673]
NUnit 3.12.0
NUnit.TestRunner 3.10.0
.NET Framework 4.7.2 Class Library project

I added only one incorrect test (Test1) to test class and it fully stopped testing for the test fixture.
If I run tests with NUnit console, I get no reports about tests in that class.

Expected behavior: NUnit console reports FAILED for Test1 and PASSED for Test2

```csharp
    [TestFixture]
    public class Class1
    {
        [Test]
        public void Test1([Range(0.1, 10.1, 1.0)] Action x) // Error
        {
        }

        [Test]
        public void Test2()
        {
            Assert.IsTrue(true);
        }
    }
```

**Comment by CharliePoole** [comment]
Stale issue using extremely old version of the runner... closing.
