### ISSUE TITLE
Incorrect path of dlls extracted from sln file

### ISSUE THREAD

**Issue by kataik** [nunit/nunit-console#68]
I love the feature of getting all assemblies extracted from the **solution file**, because it eases the CI scripts for us. However when testing on Linux, the following statement:

`mono ./src/T_GitLabCi/packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./src/T_GitLabCi/T_GitLabCi.sln /noresult`

results in

`Could not find file "/builds/kataik/gitlab_test/src/T_GitLabCi/T_GitLabCi\T_GitLabCi.csproj"`

Please notice the backslash between the file name and the directory path.

**Comment by rprouse** [comment]
Since this issue is not in the vs-project-loader extension, I am moving it there.

**Comment by rprouse** [comment]
Issue moved to [nunit/vs-project-loader #1](https://github.com/nunit/vs-project-loader/issues/1) via [**ZenHub**](https://www.zenhub.com/)
