### ISSUE TITLE
Explore option to list only or not list ignored tests

### ISSUE THREAD

**Issue by ivo-tsenov-axway** [nunit/nunit-console#685]
Hi,

Is there a way or can you add a way to list all the tests that are "Ignored" or filter and not shown them?

I think this is useful for statistics purposes when you have a lot of tests and try to list them with --explore parameter.

E.g.:
nunit3-console My.Tests.dll --where:"class=AccountTests and **Ignore=true**" --explore
//here I expect to get a list of all tests from AccountTests class that are ignored
or
nunit3-console My.Tests.dll --where:"class=AccountTests and **Ignore!=true**" --explore
//here I expect to get a list of all tests from AccountTests class that are not ignored since currently the explore option will list of of them and then on the run you will see which will be ignored/skipped

Sorry if such option already exist but I was not able to find it.

**Comment by ChrisMaddock** [comment]
Hi @ivo-tsenov-axway,

I don't believe there's way way you can filter out Ignored tests with the current `--where` parameter, although someone might correct me. 

This would however be pretty easy to do with making your own `IResultWriter` extension. There's some docs on that [here](https://github.com/nunit/docs/wiki/Result-Writers). What you'd want to write would be almost identical to the current [TestCaseResultWriter](https://github.com/nunit/nunit-console/blob/f98bd132d9bd25330e3cbf996571414b68b582b6/src/NUnitEngine/nunit.engine/Services/ResultWriters/TestCaseResultWriter.cs), just with an extra level of filtering. For an example of how to package things up, you may want to look at the [NUnit v2 result writer](https://github.com/nunit/nunit-v2-result-writer), although of course yours will be a lot more simple.

Let us know how you get on. 🙂

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
