### ISSUE TITLE
Update Engine tests to run on LTS .NET Core version

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#693]
The Engine tests currently run on .NET Core 2.0, which is no longer supported. I'm going to bump them up to run 2.1. (Tried this ages ago and CI was the blocker - hopefully it's more mature now!)

Long term, I'd love to do more thorough testing in regards to different platforms/runtimes along the lines of what @jnm2 suggested in https://github.com/nunit/nunit/issues/3223. But right now, this is in my way, so I'm just going to tweak. 🙂

**Comment by jnm2** [comment]
For AppVeyor, `image: Visual Studio 2019` will help. What do you think about replacing the `netstandard1.6` builds with `netstandard2.0`, similar to https://github.com/nunit/nunit/issues/3320?

**Comment by ChrisMaddock** [comment]
Thanks...although I didn't think to check that earlier - bizarrely, this worked 'first time'. 😱 Used up all my good luck for the year there!

Engine currently has 1.6 and 2.0 builds. I agree there's probably little value in a 1.6 build, if the lowest the framework provides is now 2.0.

I want to do a release within the next month or so...can we push removing 1.6 to release N+1, as I think that will include other potentially-breaking packaging changes (such as distributing a .NET Core Console) - and it seems a little friendlier to group those all in one release?

**Comment by jnm2** [comment]
Sounds good!
