### ISSUE TITLE
.NET 2.0 Engine Tests hang on NUnit Framework 3.12

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#695]
The problematic test appears to be:

`NUnit.Engine.Runners.Tests.TestEngineRunnerTests<LocalTestRunner>.RunAsync`

https://github.com/nunit/nunit-console/blob/af4092f72f8a352f85d22ffc98790b96d08e122a/src/NUnitEngine/nunit.engine.tests/Runners/TestEngineRunnerTests.cs#L139-L154

Suspect this might be a side-effect of the async changes in Framework 3.12. @jnm2, if you get a minute, mind having a quick nose, and seeing if you have any ideas? I very much don't have your level of async knowledge here! 🙂

No urgency - the engine can stay on framework 3.11 for now. It just caught me out while I was upgrading other things.

**Comment by jnm2** [comment]
I can't think of anything, but I will sure look into it this weekend and let you know.

**Comment by ChrisMaddock** [comment]
Awesome, thank you! No major urgency - I just encountered this when trying to get `PlatformAttribute` for the .NET Core Console tests - which is only in v3.12. I just worked around it instead. 🙂

**Comment by ChrisMaddock** [comment]
Never diagnosed this, but I've just upgraded the Framework to the most recent master build for the .NET 5.0 fixes, and that works fine. 🙂
