### ISSUE TITLE
3.11 Release

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#697]
Hi all,

It's been a little over half a year, and I'd like to do another engine/console shortly. Based on personal commitments, I'm hoping to do a bunch of the prep over the next week, then the actual release later in November.

In terms of on-going work:
- I'd like to include @CharliePoole's engine split
- I'm not expecting to include the .NET Core Console, based on the amount of remaining work. I am however hoping to have that ready for release 3.12 - which I think might be good to do a little earlier, so we can finally get that one out and about!
- I'd personally prefer _not_ to include @jnm2's TCP work - as I'd like to smoke-test that for a few months on our own CI, before releasing it, in case of any similar flakiness problems that we have with the old remoting. I also consider that a (hugely important!) unblocker for other issues, rather than a feature of it's own - so don't see any particular reason to add extra risk to the release. Any objections, Joseph? 🙂 
- Charlie - aware you have a few other issues for TestCentric you're hoping to resolve. Can you please add anything to the 3.11 milestone that you want to get into this release, based on the above timescales?
- I'm still assigned to an issue to tidy up the `--labels` API, which I will get round to, and do think should go in
- Anyone on @nunit/engine-team able to think of anything else?

When we're a little closer, I'm hoping to identify a certain MyGet package to act as 'beta' - and invite known-main-runner-maintainers to pull it in and run any integration tests. (I'd love to do that more formally in future...but we need a little more build automation for that, I think - unfortunately my time only stretches so far!)

@rprouse - I'll need your help this time around, in terms of releasing packages onto NuGet/Choco etc - do these timescales work for you? 🙂

**Comment by CharliePoole** [comment]
Sounds good. WRT the engine split, still waiting for reviews so it can be merged.

I'd love to see a new release of the V2 framework driver incorporated into the console release. That too is waiting for review.

I'll go through my stuff and see if there is anything else.

**Comment by jnm2** [comment]
@ChrisMaddock Nope, that works great for me!

**Comment by ChrisMaddock** [comment]
Thanks Charlie. Will do some reviewing and merging over the next couple of days, wanted to get that .NET Core Console work moving today...given I've had the unfinished branch for the best part of a year now! 😬

**Comment by rprouse** [comment]
I'd also like to get the NuGet packages signed. I've started the process of obtaining the cert from the .NET Foundation. It could take a couple of weeks to complete. Once I have that, we can setup the build and release process to automatically sign the release packages.

**Comment by ChrisMaddock** [comment]
Hey @rprouse, hows the package signing going? 🙂 I'd like to get back to this within the next couple of weeks, if that works for you?

**Comment by rprouse** [comment]
@ChrisMaddock sorry I missed this, I was on vacation when you sent it. I have the certs and credentials now, so I need to setup the signing. Since you want to release first, I'll do it in this project first.

**Comment by ChrisMaddock** [comment]
No worries - thanks for the update! 😊

**Comment by ChrisMaddock** [comment]
An update on 3.11: I was hoping to do a pre-release build today, but a couple of big issues have come up which really need resolving first. Fingers crossed we'll have something out within the next few weeks.

**Comment by ChrisMaddock** [comment]
Version 3.11 is now released on GitHub - thank you to everyone who's contributed! 🎉 

New packages will be pushed to NuGet and Chocolatey over the next week, once other team members are available. 🙂
