### ISSUE TITLE
Engine will not recognize .NET Framework versions beyond 4.5

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#713]
I found this when working on the GUI, which lists installed frameworks in it's menu. There's a bit of a complication in that some later framework versions use three-components, like 4.6.1. This breaks code in `RuntimeFramework`, which assumes it's dealing with a CLR version.

See more info in testcentric/testcentric-gui#447, which I'm working on. If desired, we can figure out how to backport the fix to NUnit when I finish it.

**Comment by ChrisMaddock** [comment]
Yeah, this bit of the codebase is in need of some overhaul - I've got some vague plans in #702. Would love some help along those lines though. :-)

The later versions of .NET make this much easier than what's available in .NET 2.0. This is one area I was hoping to write simple .NET Standard code, and hope we eventually end up running that instead.

**Comment by CharliePoole** [comment]
At the moment, I'm making bottom-up, incremental changes, with the goal of an overhaul in mind, and trying to get a handle on the code. (Yes, I once wrote most of it, but it has changed quite a bit since then)

I think this change (which I'm making already in the GUI engine) would help in where you want to go even if you make substantial changes later because it includes test cases you would need to deal with.

**Comment by ChrisMaddock** [comment]
Sounds good. If you're interested, I had an 'almost ready' branch of an incremental step at this a few months ago, but looks like I never pushed it. I'll try and recover it soon.

**Comment by CharliePoole** [comment]
The corresponding issue to this one in the GUI, TestCentric/testcentric-gui#447 has been closed by PR TestCentric/testcentric-gui#450. I think the same sort of fix would work in NUnit's engine and doesn't preclude the longer-term change @ChrisMaddock talks about.

**Comment by ChrisMaddock** [comment]
Looks great to get the current functionality back up to date @CharliePoole - would appreciate a PR, if you're happy to.

**Comment by CharliePoole** [comment]
I can do that.
