### ISSUE TITLE
NUnit3-console 3.10.0 hang

### ISSUE THREAD

**Issue by boshman** [nunit/nunit-console#717]
I could use some advice. I can run unit tests locally within Visual Studio and at the command line without issue. When I copy my project to our Win2016 server, build with msbuild, and run the tests over there, nunit3-console hangs. I looked through the logs (attached), but I don't see anything significant.

In case it matters, I'm targeting .Net Framework 4.7.2 and the server is running inside an AWS EC2 instance. 

Command line: 

`nunit3-console MAXCAPDataHub.Tests.dll --trace=verbose 
--test=MAXCAPDataHub.Tests.S3FileSystemTests.DoSomethingTest`

I'm trying to run a single unit test out of the 8 that exist in the assembly.

[InternalTrace.5452.log](https://github.com/nunit/nunit-console/files/3991086/InternalTrace.5452.log)
[InternalTrace.5760.MAXCAPDataHub.Tests.dll.log](https://github.com/nunit/nunit-console/files/3991087/InternalTrace.5760.MAXCAPDataHub.Tests.dll.log)
[nunit-agent_5760.log](https://github.com/nunit/nunit-console/files/3991088/nunit-agent_5760.log)

**Comment by ChrisMaddock** [comment]
Hiya,

Two suggestions:

1. What version of the Nunit framework does your test assembly reference? Can you try upgrading to latest, if it’s not already? This is reminding me of a previous bug.

2. Try adding —workers=4 to your command line.

**Comment by boshman** [comment]
Answers below:

1. I'm referencing v3.12.0 of nunit framework
2. I'm running with --workers=4 right now, but it appears to be in a holding pattern. 

One additional note: I left the test running when I went to bed last night, and it did eventually finish. I guess I wasn't waiting long enough. It took about 13 minutes to complete. 

Do you have any advice on how I can track down the delay? My hope is to get an automated nightly build that includes unit testing so if the unit tests take even an hour to run it won't be a problem. However, these tests execute in just a couple of seconds on my laptop so I would like to figure out the hold up if I can. Thanks in advance.

[nunit-agent_5948.log](https://github.com/nunit/nunit-console/files/3991782/nunit-agent_5948.log)
[InternalTrace.3900.log](https://github.com/nunit/nunit-console/files/3991783/InternalTrace.3900.log)
[InternalTrace.5948.MAXCAPDataHub.Tests.dll.log](https://github.com/nunit/nunit-console/files/3991784/InternalTrace.5948.MAXCAPDataHub.Tests.dll.log)

**Comment by CharliePoole** [comment]
According to the log, everything is running non-parallel, so adding workers won't have any impact. Your test 8 tests are taking 7 minutes or so and the one-time teardown for the fixture is taking about 4 minutes. It all happens on the same thread, number 8.

**Comment by boshman** [comment]
I have been specifying the `--test=xxx` option at the command line, so only a single test should be run. I'll take out the `--worker=4` option to remove that from the equation. I have some OneTimeSetup and OneTimeTearDown logic in the test assembly. I think I'll comment out code in those methods next and see if that reveals anything.

**Comment by boshman** [comment]
I'm closing the issue because the underlying problem is an unhandled exception from a call to an AWS S3 method that is timing out before returning the error details.
