### ISSUE TITLE
Eliminate use of Mono.Cecil

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#718]
I'm writing this as a suggestion or idea for the NUnit Engine. As it happens, I'm following up in the TestCentric engine and will be glad to share the code if I'm successful.

Back in 2008 or 2009, I wrote a class to read PE headers into memory and examine the various assembly flags and other header fields. We used it for a while.

At the time, we were working on engine extensions and (originally) were using `Mono.Addins` to implement them. That meant we would be loading `Mono.Cecil` anyway, because `Mono.Addins` used it. So, we eliminated the `AssemblyReader` class in favor of `Mono.Cecil`. That was done here: https://github.com/nunit/nunit-console/commit/370d6081a38aee21eea332b4ea28026158bbee3c#diff-6f6d92c3a7b16401c609d5413097d4d4

However, we no longer use `Mono.Addins` but still use `Mono.Cecil`. This is problematic for two main reasons:

 * Newer versions of Mono.Cecil are not available for all the platforms where we need it. As a result, we mix two versions in our builds.
 * For our usage, Mono.Cecil is overkill. We probably use 5% of what it's capable of doing.

What we need to do is as follows:

1. Examine an assembly even if we are not currently running under the runtime it targets.
2. Make sure it's a .NET assembly.
3. See if 32-bit execution is required.
4. Get the runtime version (CLR version) used for the assembly
5. Look at assembly references to find what test framework it uses.
6. Examine assembly attributes, in particular the `TargetFrameworkAttribute`.

The `AssemblyReader` class already did the first four of these items at the time we dropped it. I'm looking at it to see about adding items 5 and 6 for the TestCentric engine.

**Comment by ChrisMaddock** [comment]
I think we might have discussed this on the Testcentric repo - but absolutely in agreement that this would be a good move. 👍

**Comment by CharliePoole** [comment]
@ChrisMaddock The TestCentric part of this is now done and waiting for review. Once merged I'll do a 1.4.1 release, which will include publishing the metadata assembly on nuget.org. I've already made the changes to nunit-console locally, but of course it won't build in CI until the package exists.

**Comment by CharliePoole** [comment]
TestCentric 1.4.1 is released now, including the TestCentric.Metadata package. I'll continue my work using that package.

My overall strategy here is to do as little as possible, particularly where there is uncertainty in the future path. So, in this case, using the TC package is the STTCPW (simplest thing that could possibly work).

Subsequently, we may follow several different paths...

1. If it looks as if TC can eliminate having a separate engine, then the assembly could move over to NUnit.

2. If it looks as if TC cannot eliminate it's engine, then we can either leave it under TC or move it to NUnit - in which case TC would reference the package. Where it should go will depend most on who is going to maintain it.

3. Building separate versions of the metadata assembly for NUnit and TestCentric is the least desirable outcome but is obviously an option.
