### ISSUE TITLE
Remove .NET Standard 1.6 build

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#725]
.NET Standard 1.6 is no longer supported by the framework or Micrsoft - and is has various limitations in the engine. I propose removing it in the next release of the engine.

**Comment by mano-si** [comment]
@ChrisMaddock Starting on this. You can assign it to me. 😊

**Comment by CharliePoole** [comment]
@ChrisMaddock This means that people using an older version of the framework, with .NET standard 1.6 support, will no longer be able to run there tests using that engine. Of course, they will run under the 2.0 build, but isn't that breaking to some degree? And what happens if one of those folks has a test machine with only .NET Core 1.1 installed, for some reason?

Personally, I don't feel strongly about this either way, but I've been very confused about the degree of "breaking" required before we say we won't do something. In the past, I was quite willing to "break" minor things but there has been a lot of team pushback against that idea for the past few years. I'm using this as a sort of test case to try to understand what level of backward compatibility people really want to support.

**Comment by ChrisMaddock** [comment]
Great - thanks @mano-si!

---

@CharliePoole I'd agree this is a breaking change. This isn't a definition you'll like I'm afraid, but my personal view is that each breaking change is a trade off, where we weigh up the benefits vs the potential cost to users. Here's some of my thoughts on why we should go for this one.

1. The benefit to the project is high. There's a currently high cost in adapting code to support this legacy platform.
2. The potential impact to users is low. Two reasons:
 a. .NET Core 1.x never went into full LTS. My experience of people's use is that 1.x was very much the experimental warm-up to 2.x.
b. .NET Core appears to have a different upgrade culture around it, with no need to rely on a user's own installation. If you control the infrastructure, you can upgrade as required. If you're running on a user's machine, you can deploy a self-contained application, and still upgrade as required. That's very different from running on .NET Framework of course - and reflected in Microsoft's support and release cadence.
3. The NUnit framework has set a precedent here, but dropping .NET Standard 1.x support already.
4. The .NET Standard 1.x build has been around for a relatively short time, and then engine has a much lower direct user base than console. Vastly the main consumer of the .NET Standard engine (in user numbers) is the adapter, which doesn't the build.
5. It's a clear-cut break for a end-user - no subtle change in behaviour. A user with a .NET Standard 1.6 project will no longer be able to upgrade the NuGet package. 

All that said, I opened this issue to invite discussion, so thank you for that!

What would be important to me with this one, is that we make the change clear in our release notes. I'd like to add a 'breaking changes' section - once again, time is always the issue - need more automation in our releases. 🙂 

Side-note: this is another reason I'd love extensible agents. We could remove things like this to an archived extension, with no debate over ongoing support or breaking changes, and people who want to continue to work on old legacy platforms using the latest NUnit can do just as they please. 😄

**Comment by CharliePoole** [comment]
It's not so much a matter of liking or not liking the definition, it's understanding it and advertising it. I believe that __any__ change can break somebody. Even fixing a bug can break someone who relied on the bug. What we need is a definition that causes us to take action. Up to now, we have been saying (I think) that a "breaking change" is one we will not make except for a major upgrade. Your logic above makes sense, but I'm surprised you don't feel it should wait for 4.0.

If we want to say that some breaking changes call for a major upgrade and others don't,  we can. But then "breaking" becomes somewhat meaningless and we may need to define two more terms or at least add some qualifier. Basically, what I'm saying is that there is no "correct" definition of "breaking", there are only more or less useful definitions.

The main break I see here, in addition to what you listed, is that we have claimed full backward compatibility with all framework versions >= 2.0 up to now.

I should also add that this is a compatibility issue for TestCentric, which now runs .NET Core 1.1  tests as well as 2.1 and 3.1.

**Comment by CharliePoole** [comment]
@ChrisMaddock Is there an issue for "extensible agents?"

I might put that a bit differently, btw. It seems like it's the `TestAgency` that needs to be extensible, just like the `ProjectService` for example. Then the agents themselves could become extensions.

**Comment by ChrisMaddock** [comment]
> @ChrisMaddock Is there an issue for "extensible agents?"
> I might put that a bit differently, btw. It seems like it's the TestAgency that needs to be extensible, just like the ProjectService for example. Then the agents themselves could become extensions.

Not yet, like so many things, just needs to time to write something up. But we're on the same wavelength.

---

@mano-si's offered to have a look at this issue, and I don't want to lose focus on that amongst a lot of meta-discussion. Unless there's anything we want to discuss further relating to this particular issue, let's move the versioning discussion elsewhere - either the engine team pages, or a new issue sound good. 🙂

**Comment by CharliePoole** [comment]
OK. I'll keep that idea in mind, however.

**Comment by CharliePoole** [comment]
@mano-si We haven't heard from you for a  while. If you are not working on this, I'll start on it. Note that with PR #851 we will no longer build `nunit.engine` under 1.6.

**Comment by CharliePoole** [comment]
@ChrisMaddock I see that @mano-si is no longer assigned, so I took this myself. I'll build on top of the code for #851, which can be merged if you like or we can wait for the whole thing to be done. Shouldn't take long in any case. I'm glad I did #851 anyway, because I found out a lot of things about the build in the process.

To clarify... I am assuming you also want to remove all .NET Core 1.1 builds as well. Is that correct?

**Comment by mano-si** [comment]
@CharliePoole Yes please take it up. I had started on it but wasn't able to progress much.

**Comment by ChrisMaddock** [comment]
Sorry Charlie for the slow reply. I've commented on the PR instead. 👍

**Comment by CharliePoole** [comment]
@ChrisMaddock I've done the same thing in my GUI build and realized I could also delete `MultipleTestDomainRunner`. I can do that in this issue as well or do it separately later. Which would you prefer?
