### ISSUE TITLE
.NET global tool fails to run on macOS: Could not load file or assembly 'nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by bruno-garcia** [nunit/nunit-console#726]
I'm not sure this is the right repo so please point me at it otherwise.

I've installed `nunit.runner` via `dotnet`:

`dotnet tool install nunit.runner -g`

Entered the output directory of a Xamarin.UITest project (which tests work correctly via VS for Mac), and ran:

```
20:18 $ nunit.runner SymbolCollector.Android.UITests.dll 
NUnitLite 3.11.0 (.NET Standard 2.0)
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64
  CLR Version: 4.0.30319.42000

Test Files
    /Users/bruno/git/symbol-collector/test/SymbolCollector.Android.UITests/bin/Debug/SymbolCollector.Android.UITests.dll

Test Discovery
  Start time: 2020-01-12 19:27:14Z
    End time: 2020-01-12 19:27:14Z
    Duration: 0.037 seconds

Errors, Failures and Warnings

1) Invalid : SymbolCollector.Android.UITests.dll
Could not load file or assembly 'nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'. The system cannot find the file specified.

  ----> Could not load the specified file.

Run Settings
    Number of Test Workers: 8
    Work Directory: /Users/bruno/git/symbol-collector/test/SymbolCollector.Android.UITests/bin/Debug
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2020-01-12 19:27:14Z
    End time: 2020-01-12 19:27:14Z
    Duration: 0.005 seconds

Results (nunit3) saved as /Users/bruno/git/symbol-collector/test/SymbolCollector.Android.UITests/bin/Debug/TestResult.xml
```

Listing the current directory's files I see:

```
20:16 $ ll
total 60728
drwxr-xr-x  9 bruno  staff   288B 12 Jan 20:16 .
drwxr-xr-x  4 bruno  staff   128B 12 Jan 19:25 ..
-rw-r--r--  1 bruno  staff   4.5K 12 Jan 19:46 SymbolCollector.Android.UITests.dll
-rw-r--r--  1 bruno  staff   992B 12 Jan 19:46 SymbolCollector.Android.UITests.pdb
-rw-r--r--  1 bruno  staff   2.2K 12 Jan 20:16 TestResult.xml
-rwxr--r--  1 bruno  staff    27M 10 Dec 16:22 Xamarin.UITest.dll
-rw-r--r--  1 bruno  staff   2.4K 10 Jan 23:23 debug.keystore
-rwxr--r--  1 bruno  staff   385K 14 May  2019 nunit.framework.dll
-rwxr--r--  1 bruno  staff   1.9M 14 May  2019 nunit.framework.pdb
```
I can see `nunit.framework.dll` is there, and the version is the error message raises is the exact one I'm using:

```
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="Xamarin.UITest" Version="3.0.5" />
  </ItemGroup>
```

As a work around I'll just download the `exe` and run it with `mono` but it would be nice to use `dotnet tool install` to automate CI.
Any directions on sorting this out would be appreciated.

**Comment by mikkelbu** [comment]
I'm guessing that the problem is that nunit.runner is compiled against version 3.11 of the NUnitLite - see https://github.com/qakit/nunit.runner/blob/d7dc0dace728a2e7a3cf00b40701353c0bbbb0c7/src/nunit.runner.csproj#L16. I'm unsure if it possible to make a "nunitlite runner" that will work across versions.

Ps. Note that nunit.runner is not made by the NUnit project.

**Comment by ChrisMaddock** [comment]
Hey @bruno-garcia, is there a reason you’re not able to use dotnet test? Docs link belo. 😊

https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard

**Comment by bruno-garcia** [comment]
Unfortunately `dotnet test` doesn't work here
This is a Xamarin.UITest project which still doesn't use the SDK style csproj.

**Comment by ChrisMaddock** [comment]
Thanks - I wasn’t aware of that limitation. 😊

**Comment by bruno-garcia** [comment]
@mikkelbu I changed the dependency from the test project to `NUnit 3.11` and indeed it that error went away.
It was replaced though with:

```
1) Error : SymbolCollector.Android.UITests.Tests.AppLaunches
System.IO.FileNotFoundException : Could not load file or assembly 'Xamarin.UITest, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

  ----> System.IO.FileNotFoundException : Could not load the specified file.

--FileNotFoundException
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

I've downgraded 4 versions from `Xamarin.UITest` but the problem persists.
Sadly `Xamarin.UITest` doesn't explicitly depend on `NUnit` so I'm not sure what version would work correctly with it.

I hope once `nunit.runner` dotnet tool is built against nunit 3.12 this problem will be sorted.

**Comment by mikkelbu** [comment]
Regarding `nunit.runner` you can try to create an issue in https://github.com/qakit/nunit.runner and if that fails then the implementation is very short - in essence just creating an instance of `AutoRun()` and calling `Execute`.

I'm unsure if that will solve the problem with "Could not load the specified file". Perhaps `nunit.runner` could find the file if it used `Assembly.LoadFrom` instead of `Assembly.LoadFile`?

Ps. what version is the `Xamarin.UITest` in output directiory?

**Comment by bruno-garcia** [comment]
Thanks for the reply. I'll raise this on the other repo as a FYI. I've worked around it (copied all the `net35` build into my repo) and won't be spending more time on this for a while now. I could try again with global tools if a new version comes up compiling against 3.12.

Xamarin.UITest: 3.0.5
