### ISSUE TITLE
Running win32 x86 release config fails - No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by wiredsource** [nunit/nunit-console#73]
Hi guys

I'm struggling to find a bug regarding our release unit tests which has become unstable using both NUnit 2.6.4 and 3.4.1 console runner...

Both Debug and Release build is being tested using Jenkins but a periodically fail is happening on the Release config. Is it the same files and project.

I have been debugging this issue using your source. It seems that the agent-x86 crashes during the Release test. 
Error:
No connection could be made because the target machine actively refused it...
![image](https://cloud.githubusercontent.com/assets/5127350/19068955/f4cc0d2c-8a24-11e6-9368-e8b715d2ff62.png)
- I have given the Nunit files full rights in the firewall. -> no success 
- Build a x86 only edition of the console runner so the --inprocess handle could be used, -> no success
- added a --timeout=15000, --worker=1 --agents=1 -> no success
- Debugged my own tests for deadlocks and corrupt memory e.g. access violations.

NUnit.console config:
![image](https://cloud.githubusercontent.com/assets/5127350/19069081/9ecc05ca-8a25-11e6-958a-f649ec3aea31.png)

unittest general config (4.5 .NET is that a problem?):
![image](https://cloud.githubusercontent.com/assets/5127350/19069099/b1119a74-8a25-11e6-8f71-7bcbcec3341b.png)

Can you help me with this issue?

**Comment by rprouse** [comment]
What errors did you get when you ran with `--inprocess`. It usually gives more useful error messages, or did it just crash?

**Comment by wiredsource** [comment]
Hi again

It just crashes and leaves these log using --trace=debug:
**InternalTrace.12736.Win_UnitTest.dll.log**
InternalTrace: Initializing at level Debug
08:57:22.502 Debug [ 1] DefaultTestAssemblyBuilder: Loading C:\Users\rbalslev\Desktop\RBA2_DevBranch\sw\BSP\win32\Release\Win_UnitTest.dll in AppDomain test-domain-
08:57:22.521 Debug [ 1] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
08:57:22.538 Debug [ 1] DefaultTestAssemblyBuilder: Found 1021 classes to examine
08:57:22.616 Debug [ 1] DefaultTestAssemblyBuilder: Found 24 fixtures with 100 test cases
08:57:22.732 Info  [ 1] DefaultTestAssemblyRunner: Running tests
08:57:22.739 Debug [ 1] WorkItemDispatcher: Enqueuing Win_UnitTest.dll
08:57:22.740 Debug [ 1] WorkShift: NonParallel shift adding queue NonParallelQueue
08:57:22.741 Debug [ 1] WorkShift: NonParallel shift assigned worker Worker#STA_NP
08:57:22.742 Info  [ 6] TestWorker: Worker#STA_NP starting 
08:57:22.742 Info  [ 1] WorkShift: NonParallel shift starting
08:57:22.742 Info  [ 1] WorkItemQueue: NonParallelQueue starting
08:57:22.742 Info  [ 6] TestWorker: Worker#STA_NP executing Win_UnitTest.dll
08:57:22.756 Debug [ 6] WorkItemDispatcher: Enqueuing EALTests
08:57:22.756 Info  [ 6] TestWorker: Worker#STA_NP executing EALTests
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinADCTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinAuxiliaryTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinBspSimulatorTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinCompressionTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinDoorSensorTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinEventflagTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinFirmwareUpdateTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinFSTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinGPIOTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinIniFileTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinMailboxTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinModemControlTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinMutexRecursiveTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinMutexTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinPowerMeasurementTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinRmmwInfoTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinRTCTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinSemaphoreTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinThreadTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinTimerTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinUARTTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinVersionTest
08:57:22.780 Debug [ 6] WorkItemDispatcher: Enqueuing WinXmlParserTest
08:57:22.780 Info  [ 6] TestWorker: Worker#STA_NP executing WinADCTest
08:57:22.783 Debug [ 6] WorkItemDispatcher: Directly executing ADCDefaultNameTest
08:57:22.783 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.796 Debug [ 6] WorkItemDispatcher: Directly executing ADCDeleteTest
08:57:22.796 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.804 Debug [ 6] WorkItemDispatcher: Directly executing ADCGetAllADCChannelTest
08:57:22.804 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.807 Debug [ 6] WorkItemDispatcher: Directly executing ADCGetNoOfChannelsTest
08:57:22.807 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.809 Debug [ 6] WorkItemDispatcher: Directly executing ADCScanRateTest
08:57:22.809 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.814 Debug [ 6] WorkItemDispatcher: Directly executing ADCSetNameTest
08:57:22.814 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.817 Info  [ 6] TestWorker: Worker#STA_NP executing WinAuxiliaryTest
08:57:22.818 Debug [ 6] WorkItemDispatcher: Directly executing PowerTest
08:57:22.818 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.824 Info  [ 6] TestWorker: Worker#STA_NP executing WinBspSimulatorTest
08:57:22.825 Debug [ 6] WorkItemDispatcher: Directly executing BspSimulatorEnablePowerMeasurementSimulationTest
08:57:22.825 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.828 Debug [ 6] WorkItemDispatcher: Directly executing BspSimulatorInstantiationTest
08:57:22.828 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.835 Info  [ 6] TestWorker: Worker#STA_NP executing WinCompressionTest
08:57:22.837 Debug [ 6] WorkItemDispatcher: Directly executing CompressionTest
08:57:22.837 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.843 Debug [ 6] WorkItemDispatcher: Directly executing CompressionTestVector
08:57:22.843 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.849 Debug [ 6] WorkItemDispatcher: Directly executing DataSectionTest
08:57:22.849 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.853 Debug [ 6] WorkItemDispatcher: Directly executing RSPAChunkCRCOkTest
08:57:22.853 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.900 Debug [ 6] WorkItemDispatcher: Directly executing RSPAChunkTest
08:57:22.900 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:22.972 Debug [ 6] WorkItemDispatcher: Directly executing RSPAChunkTestWith2Files
08:57:22.972 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.160 Debug [ 6] WorkItemDispatcher: Directly executing RSPACRCBadTest
08:57:23.160 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.208 Debug [ 6] WorkItemDispatcher: Directly executing RSPACRCOkTest
08:57:23.208 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.253 Debug [ 6] WorkItemDispatcher: Directly executing RSPADatasectionsTest
08:57:23.253 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.296 Debug [ 6] WorkItemDispatcher: Directly executing RSPADIDATest
08:57:23.296 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.350 Debug [ 6] WorkItemDispatcher: Directly executing RSPATest
08:57:23.350 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.420 Debug [ 6] WorkItemDispatcher: Directly executing ScalarToByteArrayTest
08:57:23.420 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.424 Info  [ 6] TestWorker: Worker#STA_NP executing WinDoorSensorTest
08:57:23.425 Debug [ 6] WorkItemDispatcher: Directly executing CallbackSetup
08:57:23.425 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.428 Info  [ 6] TestWorker: Worker#STA_NP executing WinEventflagTest
08:57:23.429 Debug [ 6] WorkItemDispatcher: Directly executing EventflagAutoResetFalse
08:57:23.429 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.438 Debug [ 6] WorkItemDispatcher: Directly executing EventflagAutoResetTrue
08:57:23.438 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.461 Debug [ 6] WorkItemDispatcher: Directly executing EventflagSetTest
08:57:23.461 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.515 Debug [ 6] WorkItemDispatcher: Directly executing EventflagSetThreadWaitTest
08:57:23.515 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.528 Debug [ 6] WorkItemDispatcher: Directly executing EventflagTimeout
08:57:23.528 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.541 Info  [ 6] TestWorker: Worker#STA_NP executing WinFirmwareUpdateTest
08:57:23.542 Debug [ 6] WorkItemDispatcher: Directly executing ApplicationUploadTest
08:57:23.542 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.546 Info  [ 6] TestWorker: Worker#STA_NP executing WinFSTest
08:57:23.548 Debug [ 6] WorkItemDispatcher: Directly executing FSFileInfoTest
08:57:23.548 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.562 Debug [ 6] WorkItemDispatcher: Directly executing FSFileLength
08:57:23.562 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.567 Debug [ 6] WorkItemDispatcher: Directly executing FSFilePositionTest
08:57:23.567 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.578 Debug [ 6] WorkItemDispatcher: Directly executing FSFindTest
08:57:23.578 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.588 Debug [ 6] WorkItemDispatcher: Directly executing FSMakeDir
08:57:23.588 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.596 Debug [ 6] WorkItemDispatcher: Directly executing FSNestedDirTest
08:57:23.596 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.603 Debug [ 6] WorkItemDispatcher: Directly executing FSReadlineTest
08:57:23.603 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.619 Debug [ 6] WorkItemDispatcher: Directly executing FSReadSeekTest
08:57:23.619 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.626 Debug [ 6] WorkItemDispatcher: Directly executing FSWrite
08:57:23.626 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.633 Info  [ 6] TestWorker: Worker#STA_NP executing WinGPIOTest
08:57:23.634 Debug [ 6] WorkItemDispatcher: Directly executing GPIOGetAllGPIOTest
08:57:23.634 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.637 Debug [ 6] WorkItemDispatcher: Directly executing GPIOGetNoOfGPIOChannelsTest
08:57:23.637 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.639 Debug [ 6] WorkItemDispatcher: Directly executing GPIOSetNameTest
08:57:23.639 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.641 Debug [ 6] WorkItemDispatcher: Directly executing GPIOTest
08:57:23.641 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.647 Info  [ 6] TestWorker: Worker#STA_NP executing WinIniFileTest
08:57:23.648 Debug [ 6] WorkItemDispatcher: Directly executing IniFileDifferentTypeTest
08:57:23.648 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.669 Debug [ 6] WorkItemDispatcher: Directly executing IniFileOverWriteTest
08:57:23.669 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.680 Debug [ 6] WorkItemDispatcher: Directly executing IniFileReadWriteTest
08:57:23.680 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:23.689 Info  [ 6] TestWorker: Worker#STA_NP executing WinMailboxTest
08:57:23.691 Debug [ 6] WorkItemDispatcher: Directly executing MailBoxDetachTest
08:57:23.691 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.205 Debug [ 6] WorkItemDispatcher: Directly executing MailBoxMailboxSendTest
08:57:24.205 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.222 Debug [ 6] WorkItemDispatcher: Directly executing MailBoxMessageReceiveAsFIFOTest
08:57:24.222 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.228 Debug [ 6] WorkItemDispatcher: Directly executing MailBoxMessageReceiveTest
08:57:24.228 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.242 Debug [ 6] WorkItemDispatcher: Directly executing MailBoxMessageSendTest
08:57:24.242 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.267 Debug [ 6] WorkItemDispatcher: Directly executing MailBoxMultipleTest
08:57:24.267 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.297 Info  [ 6] TestWorker: Worker#STA_NP executing WinModemControlTest
08:57:24.298 Debug [ 6] WorkItemDispatcher: Directly executing ApnTest
08:57:24.298 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.303 Debug [ 6] WorkItemDispatcher: Directly executing CallbackSetup
08:57:24.304 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.312 Debug [ 6] WorkItemDispatcher: Directly executing PasswortTest
08:57:24.313 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.321 Debug [ 6] WorkItemDispatcher: Directly executing PowerTest
08:57:24.321 Debug [ 6] WorkItem: Running test on own thread. Timeout
08:57:24.328 Debug [ 6] WorkItemDispatcher: Directly executing StateTest
08:57:24.328 Debug [ 6] WorkItem: Running test on own thread. Timeout


**InternalTrace.12736.log**

InternalTrace: Initializing at level Debug
08:57:22.286 Debug [ 1] ServiceManager: Added SettingsService
08:57:22.296 Debug [ 1] ServiceManager: Added DomainManager
08:57:22.297 Debug [ 1] ServiceManager: Added ExtensionService
08:57:22.297 Debug [ 1] ServiceManager: Added DriverService
08:57:22.297 Debug [ 1] ServiceManager: Added RecentFilesService
08:57:22.297 Debug [ 1] ServiceManager: Added ProjectService
08:57:22.297 Debug [ 1] ServiceManager: Added RuntimeFrameworkService
08:57:22.297 Debug [ 1] ServiceManager: Added DefaultTestRunnerFactory
08:57:22.297 Debug [ 1] ServiceManager: Added TestAgency
08:57:22.298 Debug [ 1] ServiceManager: Added ResultService
08:57:22.298 Debug [ 1] ServiceManager: Added TestFilterService
08:57:22.298 Info  [ 1] ServiceManager: Initializing SettingsService
08:57:22.301 Info  [ 1] ServiceManager: Initializing DomainManager
08:57:22.302 Debug [ 1] ServiceManager: Request for service ISettings satisfied by SettingsService
08:57:22.302 Info  [ 1] ServiceManager: Initializing ExtensionService
08:57:22.304 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
08:57:22.305 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
08:57:22.315 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
08:57:22.315 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
08:57:22.315 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
08:57:22.315 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
08:57:22.315 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
08:57:22.315 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
08:57:22.317 Info  [ 1] ExtensionService: Processing file C:\Program Files (x86)\NUnit.org\nunit-console\Release\nunit.engine.addins
08:57:22.339 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\Release\addins\nunit.v2.driver.dll assembly for Extensions
08:57:22.375 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2FrameworkDriver
08:57:22.379 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\Release\addins\nunit-v2-result-writer.dll assembly for Extensions
08:57:22.380 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2XmlResultWriter
08:57:22.381 Info  [ 1] ExtensionService:         ExtensionProperty Format = nunit2
08:57:22.381 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\Release\addins\nunit-project-loader.dll assembly for Extensions
08:57:22.385 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnitProjectLoader
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .nunit
08:57:22.385 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\Release\addins\vs-project-loader.dll assembly for Extensions
08:57:22.385 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type VisualStudioProjectLoader
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .sln
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .csproj
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vbproj
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vjsproj
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vcproj
08:57:22.385 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .fsproj
08:57:22.385 Info  [ 1] ExtensionService: Scanning C:\Program Files (x86)\NUnit.org\nunit-console\Release\addins\teamcity-event-listener.dll assembly for Extensions
08:57:22.387 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type TeamCityEventListener
08:57:22.387 Info  [ 1] ServiceManager: Initializing DriverService
08:57:22.388 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
08:57:22.390 Info  [ 1] ServiceManager: Initializing RecentFilesService
08:57:22.390 Debug [ 1] ServiceManager: Request for service ISettings satisfied by SettingsService
08:57:22.391 Info  [ 1] ServiceManager: Initializing ProjectService
08:57:22.392 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
08:57:22.392 Info  [ 1] ServiceManager: Initializing RuntimeFrameworkService
08:57:22.392 Info  [ 1] ServiceManager: Initializing DefaultTestRunnerFactory
08:57:22.392 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
08:57:22.392 Info  [ 1] ServiceManager: Initializing TestAgency
08:57:22.404 Info  [ 1] ServiceManager: Initializing ResultService
08:57:22.404 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
08:57:22.404 Info  [ 1] ServiceManager: Initializing TestFilterService
08:57:22.404 Debug [ 1] ServiceManager: Request for service IResultService satisfied by ResultService
08:57:22.404 Debug [ 1] ServiceManager: Request for service ITestFilterService satisfied by TestFilterService
08:57:22.404 Debug [ 1] ServiceManager: Request for service IExtensionService satisfied by ExtensionService
08:57:22.416 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
08:57:22.416 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
08:57:22.416 Debug [ 1] ServiceManager: Request for service IRuntimeFrameworkService satisfied by RuntimeFrameworkService
08:57:22.416 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
08:57:22.422 Debug [ 1] RuntimeFrameworkService: Current framework is net-4.5
08:57:22.422 Debug [ 1] RuntimeFrameworkService: Requested framework is any
08:57:22.425 Debug [ 1] RuntimeFrameworkService: Assembly C:\Users\rbalslev\Desktop\RBA2_DevBranch\sw\BSP\win32\Release\Win_UnitTest.dll will be run x86
08:57:22.425 Debug [ 1] RuntimeFrameworkService: Assembly C:\Users\rbalslev\Desktop\RBA2_DevBranch\sw\BSP\win32\Release\Win_UnitTest.dll uses version 4.0.30319
08:57:22.429 Debug [ 1] RuntimeFrameworkService: Test will use net-4.0 framework
08:57:22.430 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
08:57:22.431 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
08:57:22.431 Debug [ 1] ServiceManager: Request for service DomainManager satisfied by DomainManager
08:57:22.443 Info  [ 1] DomainManager: Creating AppDomain test-domain-
08:57:22.445 Debug [ 1] ServiceManager: Request for service IDriverService satisfied by DriverService
08:57:22.466 Info  [ 1] NUnitFrameworkDriver: Loading Win_UnitTest.dll - see separate log file
08:57:22.729 Info  [ 1] NUnitFrameworkDriver: Running Win_UnitTest.dll - see separate log file

**Comment by wiredsource** [comment]
The crash is not consistent. It can run 5 times without failing and then fails. But it is typically every 3th time and only under the Release configuration... Actually i have made the debug and release alomost identically in settings so no optimization. It seems that it is only the runtime library that differs.. e.g. /MD and /MDd

Could it be a race condition in the tests that are failing because og the optimized runtime (/MD) ???

**Comment by wiredsource** [comment]
Hi again

I have tried changing the target frameworkj on the unit test from v4.5 => v4.0 but it didn't change anything still this periodically crash of the nunit agent x86...


Does the agent have any problem with spawning multiple threads within a single test?
I have some stress test cases spanning from 10-64 threads each with a 8192 stacksize.

**Comment by wiredsource** [comment]
update:

I have tried to run the test class that typically fails. (mutex test) and it seems that the test that are failing is the stress as i mentioned earlier.

But running the test class using --where "class =~ WinMutexTest" the test does not fail at all... I tried running it 50 times in a row without failure...

I think it tells me that somethings wrong in another place right??? @rprouse

**Comment by rprouse** [comment]
@wiredsource It might be something wrong in another place, but I am not sure what. Are there any objects used indirectly by your WinMutexTest that are also used by other tests?

Your tests aren't running in parallel, so one thing that could be happening is the garbage collector is kicking in sometimes when you run the Mutex test and something that is getting disposed/cleaned up is causing the crash. It just tends to happen in the Mutex test either because it is long running or because of the memory pressure of creating all of those thread.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
