### ISSUE TITLE
iconUrl is deprecated in NuGet packages

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#733]
The `<iconUrl>` element used in our nuspec files has been deprecated. We should switch to using `<icon>` instead. See the docs [here](https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl).

Contributions very welcome here, if anyone's willing! 😁 I'd recommend copying our existing images into the `/nuget/` folder in the directory, for the simplest solution, and then upgrading the nuspec files accordingly.

**Comment by mikkelbu** [comment]
One can follow the approach described in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file

Note
> You should specify both `PackageIcon` and `PackageIconUrl` to maintain backward compatibility with clients and sources that do not yet support `PackageIcon`. Visual Studio will support `PackageIcon` for packages coming from a folder-based source in a future release.

**Comment by CharliePoole** [comment]
We should also check to see what chocolatey wants. Although they use a nuspec file, they do some things differently from nuget.org.

**Comment by manoharsingh2110** [comment]
@CharliePoole @ChrisMaddock I would love to help out here. Please assign it to me if its unassigned.

**Comment by ChrisMaddock** [comment]
Brilliant - thanks @manoharsingh2110¬

**Comment by CharliePoole** [comment]
FYI in making this change for the TestCentric GUI, I ascertained that chocolatey still requires the iconic element, so no change needed there.

**Comment by manoharsingh2110** [comment]
@ChrisMaddock Do we already have 'icon.png' file checked in? Pardon me if am unaware. If no, can I just download from the link https://cdn.rawgit.com/nunit/resources/master/images/icon/nunit_256.png

Also, I have a couple more basic questions on PR process, let me know if I could mail you or ping in slack?

**Comment by ChrisMaddock** [comment]
Hey @mano-si - no worries. We use Gitter here, want to try that? Maybe best to post in the main nunit/nunit channel - that way one of the other team can jump in if they're online before I am. :-) 

👉  https://gitter.im/nunit/nunit

> Do we already have 'icon.png' file checked in?

All our imagine files are currently kept in the nunit/resources repository, but yes - we will want to check a copy in. That link you posted links to the nunit/resources repository, so either way works. 😄

**Comment by mano-si** [comment]
> Hey @mano-si - no worries. We use Gitter here, want to try that? Maybe best to post in the main nunit/nunit channel - that way one of the other team can jump in if they're online before I am. :-)
> 
> 👉 https://gitter.im/nunit/nunit
> 
> > Do we already have 'icon.png' file checked in?
> 
> All our imagine files are currently kept in the nunit/resources repository, but yes - we will want to check a copy in. That link you posted links to the nunit/resources repository, so either way works. 😄

Awesome. Thanks. 👍
