### ISSUE TITLE
Create separate agents for .NET 2.0-3.5 and .NET 4.x

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#740]
We had some offline discussion related to the direction taken in the TestCentric GUI with issue TestCentric/testcentric-gui#518. At @ChrisMaddock request, I'll implement the same fix for NUnit.

Steps planned:

 - [x] Move current NET20 agents to a separate subdirectory under "agents"
 - [x] Create NET40 agent in a sibling directory
 - [x] Modify TestAgency to use correct agent and eliminate use of environment variable to distinguish
 - [ ] Modify packaging to use the same structure

Initially, we have to come up with a directory structure that works both in development, when tests run out of the bin directory and in packages where the package structure is what counts.

**Comment by CharliePoole** [comment]
For the initial commit on PR #741, I created something that works for running tests in the bin directory but not yet for the packages. I'd like to discuss what structure the @nunit/engine-team would like to see before moving forward.

Current structure under bin\Release\ or bin\Debug\ is as follows:

```
bin\XXX
    agents
        net20
        net40
    net20
    net35
    netcoreapp1.1
    netcoreapp2.1
    netstandard1.6
    netstandard2.0
```

In creating the image directory used for packages, I adapted that structure and left the image unchanged so that all packages still build. "Small" problem, however: they don't actually work yet because TestAgency is looking for agents in an agents directory.

I can go ahead and make the packages look like the above structure - basically flat except for agents being in a subtree. I'm not in love with that because it mixes directory names that state "what it's for" with those that tell you "what it targets."

Here's one possibility as an example...

```
bin\XXX
    agents
        net20
        net40
    console
        net20
        netcoreapp2.1
    tests
        net35
        netcoreapp1.6
        netcoreapp2.1
```

Other options:
 1. Currently, the net40 agent is actually using a net20 engine just as it has always done. We could build the engine for 4.0 as well
 2. I could have a separate top-level subdirectory for `engine` but I instead just let the console builds copy the appropriate assemblies. I can see going either way.

Please let me know which way you want to go and I'll finish this up.

**Comment by mikkelbu** [comment]
Just at a quick glance I prefer the second structure, as I agree with your concern about the mixing of concerns. 

Regarding the other options:
1. I think it is fine as it is. What would the benefit of having a net40 engine be (e.g. use different codepaths features for net40)? Or is it just to make the output more consistent?
2. I like how it is now. I think it is more simple

**Comment by CharliePoole** [comment]
@mikkelbu Thanks for the feedback. I'll do another commit with that structure and change the packages to match.

**Comment by mikkelbu** [comment]
@CharliePoole Perhaps we should wait for some more feedback?

**Comment by CharliePoole** [comment]
I'd love that if it should happen. :smile: @ChrisMaddock @jnm2 ?

**Comment by ChrisMaddock** [comment]
Sorry - been away! The easy ones first...

> 1. Currently, the net40 agent is actually using a net20 engine just as it has always done. We could build the engine for 4.0 as well
2. I could have a separate top-level subdirectory for engine but I instead just let the console builds copy the appropriate assemblies. I can see going either way.

1. Do we have any need to do that? Seems we can keep things simple, until we need to add additional builds. 🙂 
2. Yeah, again, I don't see any particular motivation to change what we already have here.

On the first structure - what had been in my head, is that each platform subdirectory would remain self-contained, as it currently is. As in - if I downloaded the zip, and just wanted the .NET 2.0 console, I could just extract that subfolder, and leave the rest. So I was expecting something that looked a little like this...

```
bin\XXX
    console
        net20
              agents
        netcoreapp2.1
              agents
    tests
        net35
        netcoreapp1.6
        netcoreapp2.1
```

More practical questions, what about if we ever wanted to make a certain agent only available from (e.g. the net20 engine can use this agent, but the netcoreapp2.1 engine cannot. How would we restrict them then - in code? (Perfectly possible, just a consideration.)

To be honest, I'm not sure I have any strong feelings here. I guess the NuGet package would need to look a little more like the above, to keep with NuGet's `/lib/net20` file structure - would it be easier to keep everything consistent, rather than try and locate the agent differently, depending on the particular packaging method being used?

**Comment by CharliePoole** [comment]
OK... I'm not 100% sure where this leads me. Maybe we should temporarily set aside the structure in the `bin/XXX` directories and talk of packaging. Then we can work backwards to `bin`, making sure that the agents are located by following the same relative path in both cases.

So, using nuget as an example, here is the current structure of the ConsoleRunner package...

```
tools
  // all files here
```

The two agents (standard and x86) are in the same directory as the engine, so easy to find.

With two net40 agents added, we could either give them new file names or use a separate directory. I think the separate directory is lots simpler since we don't know how many agents there will be in the future. So I think the new structure should be...

```
tools // everything is still here except the agents
  agents
    net20 // net20 agents and dependencies
    net40 // net40 agents and dependencies
```

I see only one possible problem with this. Some dependencies will be copied into three locations. In my own work on TestCentric I ended up deciding that's a rather small price to play for the simplicity of keeping the engines completely isolated.

If we do the above, the relative path to the agents will be `agents/{runtime}`. In order to keep the ability to run tests out of the bin directory, while developing, we should move the agents under the directory containing the console as you suggest.

That will give us

```
bin\XXX
    net20
        agents
            net20
            net40
    net35
    netcoreapp1.1
    netcoreapp2.1
    netstandard1.6
    netstandard2.0
```

I can do that if you like. I'm not in love with putting two leves of runtime into the structure, which is why I suggested a top-level structure that's functional (agents, console, tests) with the runtimes broken out underneath that. I can see now that it creates the problem of two different relative paths to find the agents depending on whether we are running out of the bin directory or the installed package. However, I guess the engine could check for the location of the agents directory on startup and work with that path from then on.

So... which way shall I go? :smiley:

**Comment by ChrisMaddock** [comment]
Hmm, I hadn't considered that the agents couldn't all live in one directory, as they'd have the same file name.

Could we rename the agent assembly to say what it is, using the csproj? So like we currently do with x86, we'd have `nunit-agent-net20.exe`, `nunit-agent-netcore21-x86.exe` and so on.

Then we could do what your suggesting, but without the multiple levels of runtime in the filestructure. I also prefer naming the files themselves in general I think - it would avoid any confusion if the files ever end up out of their correct subdirectory!

**Comment by CharliePoole** [comment]
OK... that's doable. I'll do another pass to get rid of the agents directory and have separate name for each one. Currently, there's no .NET Core agent, so I won't have to deal with anything more than net40 and net20. So this will get us back to just a tools dir in the nuget package.

**Comment by CharliePoole** [comment]
Hmm... Not so doable as I thought! I played around with using setting `AppendTargetFrameworkToOutputPath` to false as well as using `AssemblyName` with `TargetFramework` to set the name of the created file. It doesn't work for me and there seem to be lots of issues about this out there.

I'm back to using directories unless someone has a working example with varying file names in a single project.

**Comment by ChrisMaddock** [comment]
Doesn't it work to specify `<AssemblyName>` inside a conditional property group, for each framework? Or am I missing the problem?

**Comment by CharliePoole** [comment]
It isn't working at all. At least not in combination with setting `AppendTargetFrameworkToOutputPath` false. I've seen some issues about this as well. I'll experiment a bit more but if it only works with some particular update or patch, I would think it's too fragile to be relied on.

**Comment by CharliePoole** [comment]
What's the minimum VS required for nunit-console these days?

**Comment by CharliePoole** [comment]
I went back and did a series of experiments...

1. If I add `<AssemblyName>nunit-agent-$(TargetFramework)</AssemblyName>` to the projects, the output files are named as desired. This works.

2. If I add `<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>` then the output goes to the speciffied output directory without net20/net40 being added but the output only containes `nunit-agent.dll` and `nunit-agent-x86`. This is not surprising, since we can assume one of the two overwrites the other.

3. If I add __both__ settings to the projects, however, I still only get two assemblies, `nunit-agent-net40.dll` and `nunit-agent-net40-x86.dll`.

This is clearly a bug when the two features are used together, which makes the combination impossible for us to use right now. I think we have to stick with separate directories.

**Comment by ChrisMaddock** [comment]
@CharliePoole does the solution need this level of automation, when we only have two runtimes? Can't we just do this? (Warning: pseudo-code)

```
<PropertyGroup Condition="'$(TargetFramework)'=='net40'">
   <AssemblyName>nunit-agent-net40.exe</AssemblyName>
  </PropertyGroup>
<PropertyGroup Condition="'$(TargetFramework)'=='net20'">
   <AssemblyName>nunit-agent-net20.exe</AssemblyName>
  </PropertyGroup>
```

**Comment by CharliePoole** [comment]
@ChrisMaddock I tried that as well. It works exactly the same as using `$(TargetFramework)` in a single `AssemblyName` element, i.e. correctly by itself but incorrectly when used in conjunction with `AppendTargetFrameworkToOutputPath`.

**Comment by ChrisMaddock** [comment]
Oh...sorry. I missed what was going on. That's irritating.

**Comment by CharliePoole** [comment]
Definitely!

**Comment by CharliePoole** [comment]
@ChrisMaddock Latest commit seems to do it. In the build directory as well as every package, the agents directory is located either under or in a sibling directory to that containing the engine. That is, either at `./agents` or `../agents`. The `TestAgency` checks both paths.

I added a very simple set of checks on the content of each package. I may expand that into a separate general-use package at some point.
