### ISSUE TITLE
NUnit.ConsoleRunner 3.11.1 regression where --testparam or --tp not passed to NUnit

### ISSUE THREAD

**Issue by ajeetd** [nunit/nunit-console#755]
Running `NUNIT3-CONSOLE  ./bin/Release/tests.dll --tp key=value` in NUnit.ConsoleRunner 3.10.0 successfully passes the test parameter (key and value) through to NUnit. However, in version 3.11.1 the parameter is not passed through.

Installation in both cases was through NuGet. Tested with NUnit 3.11.0 and 3.12.0 and it is clear that only the version of NUnit.ConsoleRunner is a factor here.

**Comment by mikkelbu** [comment]
Hi @ajeetd 

I just tried to compile the NUnit.ConsoleRunner code on tag v3.11.1 and if I run the resulting code with `.\nunit3-console.exe .\nunit3-console.tests.dll --tp Key=value` against a test
```csharp
        [Test]
        public void TestParams()
        {
            var x = TestContext.Parameters["Key"];
            Assert.That(x, Is.EqualTo("NOPE"));
        }
```
then I get the following from the console
```
NUnit Console Runner 3.11.1 (.NET 2.0)
Copyright (c) 2020 Charlie Poole, Rob Prouse
...
Test Files
    .\nunit3-console.tests.dll

Test Parameters---
   Name: Key Value: value
Runtime Environment
...
Errors, Failures and Warnings

1) Failed : NUnit.ConsoleRunner.Tests.ConsoleRunnerTests.TestParams
  Expected string length 4 but was 5. Strings differ at index 0.
  Expected: "NOPE"
  But was:  "value"
  -----------^
   at NUnit.ConsoleRunner.Tests.ConsoleRunnerTests.TestParams() in C:\src\NUnit\nunit-console\src\NUnitConsole\nunit3-console.tests\ConsoleRunnerTests.cs:line 34

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\src\NUnit\nunit-console\bin\Release\net35
    TestParametersDictionary:
        Key -> value
    TestParameters: Key=value
    ImageRuntimeVersion: 2.0.50727
    ImageRequiresX86: False
...
```
So when you run with testparameters are they then reported in the output from the console, and can you provide a small projects that shows the problem.

**Comment by ajeetd** [comment]
@mikkelbu I can confirm I also see the testparameters reported in the output from the console as you demonstrate. The issue I encounter takes place when implementing the NUnit.Engine.ITestEventListener. In the OnTestEvent, I parse the report param as XML, and it looks like the test parameters are not found within the TestParametersDictionary.

As you suggest I will put together a project that demonstrates the issue. I will try to post this within the week.

**Comment by ajeetd** [comment]
Hi @mikkelbu, here are steps on how to reproduce the issue. If you like I can share a VS Project with you somewhere too.

After the setup you have already done above to run NUnit using the console runner, add a Listener to your project. This one here prints out the key value pair passed in by the use of the --tp arg. Remember to change the namespace to whatever your project uses.

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Xml.Linq;
using NUnit.Engine;
using NUnit.Engine.Extensibility;

namespace NUnit_Bug_Repro
{
    [Extension(EngineVersion = "3.4")]
    public class ExampleListener : ITestEventListener
    {
        public void OnTestEvent(string report)
        {
            Console.WriteLine("--- OnTestEvent --- ");
            var doc = XDocument.Parse(report);
            if (doc.Root.Name == "test-suite")
            {
                var settings = doc.Root.Element("settings");
                foreach (var setting in settings.Elements())
                {
                    if (setting.Attribute("name").Value.Equals("TestParametersDictionary"))
                    {
                        var testParams = setting.Elements();
                        foreach (var param in testParams)
                        {
                            Console.WriteLine("--- Key Value ---");
                            Console.WriteLine(param.Attribute("key").Value);
                            Console.WriteLine(param.Attribute("value").Value);
                        }
                    }
                }
            }
        }
    }
}

```

For the listener to be recognized and used you need to add the .addins file inside \packages\NUnit.ConsoleRunner.3.11.1\tools (or \packages\NUnit.ConsoleRunner.3.10.0\tools) as described here:[https://github.com/nunit/docs/wiki/Engine-Extensibility#locating-addins]( https://github.com/nunit/docs/wiki/Engine-Extensibility#locating-addins)

Now run `NUNIT3-CONSOLE tests.dll --tp key=value`

If you run with NUnit.ConsoleRunner 3.11.1 the listener will not print the key and value. If you run with NUnit.ConsoleRunner 3.10.0 they will be printed as expected. Please note that when you upgrade/downgrade the NUnit.ConsoleRunner you must add the .addins file again for the listener to be recognized.

**Comment by ChrisMaddock** [comment]
Hi @ajeetd,

Thanks for the repro here, that was really helpful. I've done some digging, and looks like this was the result of the bug fix for https://github.com/nunit/nunit-console/issues/603.

Unfortunately, the engine behaviour that your code was relying on here was unintended, and "fixed" in a bug fix for the engine. The Test Params are now reported for each assembly under the `test-run` event instead. I did have a look at restoring the previous behaviour, but as the `test-suite` events are now passed directly from the framework, it's non-trivial. 

I'm going to close this issue as an unintentional breaking change, but not one I think we should revert. Thanks for taking the time to highlight this to us, however.
