### ISSUE TITLE
Carry CurrentDirectory over to agent Processes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#758]
This issue is identical to TestCentric/testcentric-gui#577 which will may end up creating an additional incompatibiility with the nunit engine.

Beginning with NUnit 3, we made it a policy that we wouldn't change the user's working directory (aka CurrentdDirectory) and that we wouldn't rely on the working directory for much of anything - currently only as a default location for saving logs and result files.

We followed through with that promise by removing all NUnit code that changes the working directory and providing the `TestDirectory` property to users who need to know where the current test assembly is located.

However, from a naive user point of view, there is __one place__ where the CD is changed. When we launch an agent process, the CD of that process is the location of the agent assembly. This is true no matter what directory the user was in when the test was launched.

This is easy to fix. `TestAgency` merely has to set `Process.StartInfo.WorkingDirectory` to the value of `Environment.CurrentDirectory`. Then, tests run with `--process:Multiple` will have the same working directory as those run in process.

I don't consider this a breaking change, since it's highly unlikely that anyone is counting on the cd being set to directory where the agent is installed. However if the @nunit/engine-team feels it is breaking, we should track it as a potential V4 change.

**Comment by CharliePoole** [comment]
I feel this is high priority WRT making a decision. That will enable me to move ahead on the TestCentric side of things. Actual implementation could be normal or low as far as I'm concerned.

**Comment by ChrisMaddock** [comment]
Fixing the inconsistency between different test running modes makes sense. I think we can treat this as a bug fix, and not wait till v4, in my opinion.

**Comment by CharliePoole** [comment]
I've already done a PR on the TestCentric side. I'll do another one here. Code is slightly different due to some refactoring I did previously.

**Comment by jnm2** [comment]
Sounds like the right change. I don't know enough about addins, but could this impact someone's addin implementation?

**Comment by CharliePoole** [comment]
Extensions? To break one, it would have to be written with the assumption that the current directory is the location of the particular build of the agent being used __or__ the one from which the user ran the command. Since those are two different places. I'd see that as an error. The extension would only work when run inprocess (one way) or out of process (the other).
