### ISSUE TITLE
Question: Run "Nunit3 Unit Test Project" from console

### ISSUE THREAD

**Issue by sisillV** [nunit/nunit-console#76]
Hi,
I am new with Nunit and I need help to run my "Nunit3 Unit Test Project" from console
I am with win10; Microsoft Visual Studio Enterprise 2015; 
I create "Nunit3 Unit Test Project" in Visual Studio using Selenium. And I want to run the tests from this project from the console.
I don't know how to do it.
1. I download C:\Users\xxxxx\Documents\NUnit-3.5.0\bin but there I don't find nunit-console.exe
2. I don't know how to create dll file from my "Nunit3 Unit Test Project"

Is there step by step guide how to install nunit-console; How to create this dll files from my "Nunit3 Unit Test Project" in Visual Studio. 

I try to run: nunit-console NUniTest.csproj and nunit3-console NUnitEsTax.csproj from different locations but always tell me that:
'nunit-console' is not recognized as an internal or external command

Best Regards,
Stanislava

**Comment by sisillV** [comment]
Hi again,
I found my dll file in debug folder and I manage to run the tests from the console using NUnit-3.4.1 which I don't unzip I install using ".msi" 
How to run the tests with 3.5 version?

**Comment by rprouse** [comment]
The 3.5 console runner hasn't been released yet. You don't need to use the same version of the framework and console runner.
