### ISSUE TITLE
Nunit Console - Worker configuration

### ISSUE THREAD

**Issue by msscribner** [nunit/nunit-console#767]
I'm having issues configuring --Worker argument.  I'm trying to figure out the maximum number of Workers my environment supports.   The environment consists of 6 Vm's.   

(All VM's are configured with 4 CPUs. )
- VM #1 : NUnit Console 3.10 (msi).  
- Selenium Grid 
  VM #2:    HUB 
  VM #3:    Node  
  VM #4:    Node  
  VM #5:    Node  
  VM #6:    Node  

- If I set the Worker to 4, then each VM gets a single browser. 
- If I set the Worker to 10, then each VM gets 2 browsers, and 2 vm's get 3 browsers (for a total of 10 browsers).   
- If I set the Worker to > 10, I get unpredictable results... Often see multiple browsers w/o any tests executing.

What should be the maximum Worker configuration for the environment I described.

**Comment by ChrisMaddock** [comment]
Hi @msscribner,

I think this depends on how you configure outsourcing tests to your selenium grid.

The workers argument very simply defines the number of threads NUnit should parallelise your tests on. Anything beyond that depends on your own set up. You can verify this is working as you expect by adding the `--trace=Debug` flag and reviewing the logs - it should show you which tests are being executed on which worker threads.

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
