### ISSUE TITLE
Console indentation is not consistent

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#772]
The green doesn't line up:

![image](https://user-images.githubusercontent.com/8040367/82154805-736ae100-983e-11ea-8efc-f5e0d5f4a9b5.png)

Other places, indentation increases either 2 or 4 spaces at a time:

![image](https://user-images.githubusercontent.com/8040367/82154831-93020980-983e-11ea-87b1-fc52acf08956.png)

**Comment by CharliePoole** [comment]
Aligned indents on 4 and 8 spaces and shortened labels so test count, pass, fail, etc. line fits in an 80 character window. Output of --list-extensions option uses 4, 6 and 8 spaces for compactness. We can tweek this further of course.
