### ISSUE TITLE
Extension loading broken on Linux when installed from nuget package

### ISSUE THREAD

**Issue by ermshiperete** [nunit/nunit-console#775]
NUnit.ConsoleRunner comes with a `nunit.console.nuget.addins` file that tries to find extensions that are installed in directories parallel to the on nunit3-console is in. However, this fails on Linux with the global nuget package location (`$HOME/.nuget/packages`), because nuget converts the path names to lowercase whereas NUnit looks for the exact camelcase directoryname.

These are some of the file I have that show the problem:

```
$HOME/.nuget/packages/nunit.consolerunner/3.11.1/tools/nunit3-console.exe
$HOME/.nuget/packages/nunit.consolerunner/3.11.1/tools/nunit.console.nuget.addins
$HOME/.nuget/packages/nunit.extension.nunitv2resultwriter/3.6.0/tools/nunit-v2-result-writer.dll
```

**Comment by CharliePoole** [comment]
Do we know if this behavior by nuget is documented as opposed to being their bug?

**Comment by ermshiperete** [comment]
It doesn't seem to be directly documented - at least I'm not able to find anything. However, I'm fairly sure that it is intentional given the fact that the [API is case-insensitive](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource).

And thinking about it, it does make sense: there's the possibility that a newer version of a nuget package has a name that differs by case only. The API treats those two versions as having the same package ID. Given the fact that the packages are stored in the global package location by package id and then package version, converting the names to lowercase keeps that relationship even on a case-sensitive file system as Linux uses.

**Comment by CharliePoole** [comment]
That's good enough for me. :smiley:
