### ISSUE TITLE
Add DotNetAnalyzers.DocumentationAnalyzers

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#782]
The doccomments in this repo haven't always kept in sync with the code. As recommended by @jnm2 in https://github.com/nunit/nunit/issues/3475 - this will help keep things tidy. In the framework project they chose to suppress DOC100 - I think it makes sense for us to do the same.

> I would recommend that we add the design-time tool https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers to our Directory.Build.props and follow all its prompts. It's been awesome in every project where I've seen it. I know it catches this particular case.

**Comment by CharliePoole** [comment]
I don't quite see the problem here. With warnings as errors, any mismatch between doc comments and the actual method header shows up in all my builds. If you want to enforce stylistic standards, then you need more but I don't think that's such a good idea anyway.

**Comment by ChrisMaddock** [comment]
See Sean's comments on #870 for why we decided not to take this any further.

**Comment by SeanKilleen** [comment]
@ChrisMaddock could you please re-open this? We got some outreach on #870 and I think we could make another go of it.

**Comment by ChrisMaddock** [comment]
Great! I'll reopen the PR as well - feel free to just close it again if you'd rather start from scratch.

**Comment by CharliePoole** [comment]
@SeanKilleen This got re-opened in January at your request. Is it still something you are working on?

**Comment by SeanKilleen** [comment]
Hi @CharliePoole -- thanks for the ping. This fell off my radar and since I can't prioritize it, I think it can be closed. 

Anyone interested in resurrecting it in the future can see the comments on #870 for a good starting point.
