### ISSUE TITLE
Simplify headers on source files

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#793]
I'm proposing that we shorten and simplify the file headers as follows:

1. Eliminate the license text in order to make it shorter.
2. Eliminate copyright dates so we no longer need to update them.
3. Add mention of contributors just as a matter of fairness.

The actual text to be used should be agreed upon. As a start, I propose the following:

```
// *****************************************************************************
// Copyright (c) Charlie Poole, Rob Prouse and Contributors.
// Licensed under the MIT License. See LICENSE.txt in root directory.
// *****************************************************************************
```
Based on experience doing this for TestCentric, I suggest that we review
the name of the license file now. If we want to change it later, as I did, we'll
have to edit all the headers! (Mine is now LICENSE)

**Comment by ChrisMaddock** [comment]
All in favour of simplification. I'm not very well-versed in copyright, so happy to defer to your expertise as to what's acceptable and what's not here, Charlie. 

I like the addition of contributors. Follow-up question - do we need a header at all? Would it be sufficient just to have the licence in root?

**Comment by CharliePoole** [comment]
I've become convinced that there is less expertise about this subject out there than there seems to be. Lots of people talk as if they were experts, but the top lawyers have a tendency to hedge their opinions, especially when it comes to Open Source, where so little has actually been settled through case law.

Some people do without headers but  I like having a short header because people sometimes copy a file or two and it serves to remind them where they got it. I also like having a NOTICES file that acknowledges where we get stuff from, even where it's not required.

**Comment by CharliePoole** [comment]
@mikkelbu @jnm2 @rprouse 

As you can see, @ChrisMaddock and I tossed this around and were waiting for input from the rest of the @nunit/engine-team. It has been sitting for a long-time. If we wanted to do this, I think right after a new release would be good  timing.

In case you're wondering why I bring it up now, we just had a contributor who was a bit confused about what to put in the header of new files. So if we do this, I'd also like to document it. It's a simple change, which I can make mechanically if we want to go ahead.

**Comment by mikkelbu** [comment]
I think it is a god idea, as I think the current format takes too much space when opening a file without providing much additional benefit. Also I think the naming is fine.

Ps. You probably already considered this, but note that this also affects all the current PRs (I've checked how many new files they add)

**Comment by CharliePoole** [comment]
@mikkelbu Thanks. Yes, it's better if there are not so many PRs hanging out when we do this. I figured most would be closed for the release. I also have some quite old ones I may need to delete.

**Comment by rprouse** [comment]
I totally agree with shortening the license. I find the current headers to be redundant and take up too much space. I think the format that you propose is fine unless someone wants to propose something better?

I'd even be fine with simplifying it down to one line like

```
// MIT Copyright (c) 2009 Charlie Poole, Rob Prouse
```

Putting the Licence.txt in the root is so common, I think that it is even redundant to mention that, but if you feel it is need,

```
// MIT Copyright (c) 2009 Charlie Poole, Rob Prouse. See LICENSE.txt
```

**Comment by rprouse** [comment]
We could also follow the lead of the Microsoft's and other .NET Foundation projects and use this or a various thereof,

```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
```

**Comment by CharliePoole** [comment]
@rprouse Part of what I'm proposing is that we drop the year entirely. Then we never have to update the headers again.

From my reading, those who keep a header in the file are doing it so as to retain info when or if the single file gets copied. That way, companies know where a file came from and can use it as they like. That makes a bit of sense to me as I've had people propose a file for use where they didn't remember where it came from.

So to me, it's a nice middle road to include license name and, copyright names, without dates in the header. Addition of "and contributors" is just a nicety so as to recognize lots more people than you and I have contributed and see license is probably optional. But I would prefer to agree on the exact header before doing a PR, so as to avoid having to redo it.

BTW, another useful thing might be to have to have a build script target to list any non-standard headers.

**Comment by rprouse** [comment]
I missed the lack of year in yours and am fine with leaving it out. I am fine with your proposal or any of my proposals without the year. I suggested the .NET Foundation version after checking a few other large .NET Foundation projects like Cake build and the CLR.

Does anyone else on the @nunit/core-team have a preference?

**Comment by ChrisMaddock** [comment]
I would prefer it to be as simple as possible. I like Rob's idea of a single line, and Charlie's suggestions of removing the year, and adding in "contributors".

For the sake of agreeing something, how about:

```
// Copyright (c) Charlie Poole, Rob Prouse and Contributors. MIT Licence - see LICENCE.TXT
```

**Comment by CharliePoole** [comment]
I'll do a PR making that change and also add a task to run if we want to change the standard one-liner. @ChrisMaddock Would you want it to be the same text for both engine and console? Or "Engine contributors" vs "Console contributors" (since you proposed separate versioning for the two elsewhere)

**Comment by ChrisMaddock** [comment]
I think just "contributors" is fine myself.
