### ISSUE TITLE
Remove CHANGES.TXT to simplify release process

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#803]
The release process is currently quite manual and time consuming. There's lots of improvements we could make here, but this one I think is low-hanging fruit.

Currently we have to create two versions of the changelog, one in text format and one in markdown. I'd like to suggest removing  CHANGES.TXT from the repo, and just have on docs site. This would involve updating the various packages that currently include CHANGES.txt to link to the change log instead.

Thoughts welcome. 🙂

**Comment by rprouse** [comment]
Thoughts? I've thought of doing the same thing many times. Let's do it and make the MD version in the docs site the authoritative version.

**Comment by CharliePoole** [comment]
I think I'd leave CHANGES.txt but delete all content, just leaving a sentence that says the info has been moved to the docs site. We then would not have to update it any longer.
