### ISSUE TITLE
NUnit Console Runner 3.12.0-beta1 reports that format nunit2 is unknown

### ISSUE THREAD

**Issue by heyitsmesuraj** [nunit/nunit-console#809]
NUnit Console Runner 3.12.0-beta1

Unknown result format: nunit2

**Comment by CharliePoole** [comment]
How have you installed the console? Did you also install the v2 result writer extension?

**Comment by heyitsmesuraj** [comment]
Yes, I installed the console from NuGet using PackageReference.
<PackageReference Include="NUnit.ConsoleRunner.NetCore" Version="3.12.0-beta1" />
But, I did not install the v2 result writer extension. Is v2 result writer extension is required for Nunit v3.12?

**Comment by heyitsmesuraj** [comment]
I installed both extensions and try to execute the following command and the result is format nunit2 is unknown.

nunit3-console.exe <dll location> --test=<testname> --result=../TestResult.xml;format=nunit2

**Comment by CharliePoole** [comment]
Try quotes around the argument of `--result`

**Comment by ChrisMaddock** [comment]
Hey Suraj, thanks for trying the Beta!

This below part of your command line means that you require the NUnit v2 result writer extension:

```
format=nunit2
```

I presume you've previously used the NUnit.Console package? The extension is included with that package by default, but not with the NUnit.ConsoleRunner.NetCore package - mainly as there isn't yet a release of the extension that works with the .NET Core Engine. @runehalfdan has volunteered to help out and look at that - hopefully we might be able to release something soon.

I would say however - are you sure you need your TestResult.xml file in the v2 format? It's best to use the default v3 format, if you can.

**Comment by CharliePoole** [comment]
Ah! Sorry, I didn't see the comment that mentions .Net Core.

**Comment by heyitsmesuraj** [comment]
Thank you, @ChrisMaddock 
Currently, I am using bamboo for running the selenium tests. The bamboo does not support the XML generated by v3 format. So, I need XML in v2 format. Somehow I managed myself by converting the XML v3 to v2 for now. :)

**Comment by CharliePoole** [comment]
@heyitsmesuraj 
Since you use NUnit.ConsoleRunner.NetCore I'd like to ask for your comments on #1045
