### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#81]
README.md needs to be updated so that the badges at the top point to the console builds and NuGet and so that the information is correct for this repository.

**Comment by ChrisMaddock** [comment]
Maybe we should also change the references to "NUnit 3.0" to instead just be "NUnit 3?" 😄 

(cc @Sebazzz here, looks like you're on this?)

**Comment by CharliePoole** [comment]
I see @sebazz did something in his fork, but he hasn't done a PR. While this doesn't have to be done for the release, it should at least get finished right afterwards.

@Sebazzz Should I assign this to you?

**Comment by Sebazzz** [comment]
Apparently my response on the mail didn't arrive here...

Anyway: I've updated the readme as far as possible, except for the AppVeyor badge which is secured using a token which I don't have. So, I can either create the pull request now and @nunit/core-team can update the badge themselves or you give me the badge token as supplied by AppVeyor and you have a ready-to-merge pull request.

**Comment by CharliePoole** [comment]
@rprouse I don't know how this works, so please decide. :-)

**Comment by rprouse** [comment]
@Sebazzz the code for the AppVeyor master branch code is

[![Build status](https://ci.appveyor.com/api/projects/status/81uhucr7tlq2kwup/branch/master?svg=true)](https://ci.appveyor.com/project/CharliePoole/nunit-console/branch/master)

```md
[![Build status](https://ci.appveyor.com/api/projects/status/81uhucr7tlq2kwup/branch/master?svg=true)](https://ci.appveyor.com/project/CharliePoole/nunit-console/branch/master)
```

**Comment by Sebazzz** [comment]
Got it, pull request is in the basket.
