### ISSUE TITLE
System.PlatformNotSupportedException : System.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by uRalidia** [nunit/nunit-console#819]
Hi, I can't run a test with a database connection from my own test application. Both the application and the test DLLs are .NET Core 3.1

System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.

Please help

**Comment by mikkelbu** [comment]
Hi @uRalidia 
I don't think that this is related to the NUnit Console have you tried some of the suggestions suggested in this thread dotnet/SqlClient#289 ?

**Comment by uRalidia** [comment]
Hi,

this doesn't work. I tried Microsoft.Data.SqlClient or System.Data.SqlClient and still the same problem.
Tests is running on NUnitTestEngine.

**Comment by uRalidia** [comment]
Problem solved. Missing bound NuGet references from System.Data.SqlClient. Thank you for your help.

**Comment by mikkelbu** [comment]
No problem. I'm closing this issue, as I don't think it is related to the NUnit Console.
