### ISSUE TITLE
SpecFlow - error when try to  load the plugin: BoDi.ObjectContainerException- Interface cannot be resolved

### ISSUE THREAD

**Issue by cosminPintea** [nunit/nunit-console#821]
- Method of installation (e.g. NuGet, zip, msi)
- install using NuGet

- Version of the NUnit Engine/Console
- All versions of the NUnit Framework in use

 Microsoft Visual Studio Professional 2019
Version 16.7.6
VisualStudio.16.Release/16.7.6+30611.23
Microsoft .NET Framework
Version 4.8.04084

The version of all the dependency is in the attached test project.
[TestsFor2166.zip](https://github.com/nunit/nunit-console/files/5399409/TestsFor2166.zip)

I use "NUnit.Engine" to start test execution. I have changed the version of the "NUnit.Engine" library to a prerelease version "3.12.0-beta1". 
And this behavior is present when I am trying to run tests using "Test Explorer" from VS 2019. If I change to the previous "NUnit.Engine" version everything is OK.

Also please refer to: 
https://github.com/SpecFlowOSS/SpecFlow/issues/2166

This is the actual exception that pops up when I execute tests with VS 2019 Text Explorer:
There is no error if I start test execution programmatically using the prerelease version of NUnit.Engine.

Setup failed for test fixture UMPGContractsCoPubRecoupmentAutomation_NUnitAssemblyHooks
BoDi.ObjectContainerException : Interface cannot be resolved: TechTalk.SpecFlow.UnitTestProvider.IUnitTestRuntimeProvider('nunit')

**Comment by SabotageAndi** [comment]
I debugged the project and what I found out is, that the code in https://github.com/SpecFlowOSS/SpecFlow/blob/master/TechTalk.SpecFlow/Plugins/RuntimePluginLoader.cs?rgh-link-date=2020-10-16T14%3A35%3A05Z#L25 is returning `null` in case that the `NUnit.Engine` NuGet package is added. Without it, the code works.

My assumption is, that something in `NUnit.Engine` changes assembly loading/resolving. Any ideas about it?

**Comment by CharliePoole** [comment]
Each runner is built to use a particular version of the engine. In this case, the runners in question are the console and the NUnit VS Test adapter, which is used by Test Explorer. Each of them includes a copy of the engine. If you install both runners in the same directory, you must choose versions that use the same engine build. The console and engine are built together and so the 3.12 engine uses the 3.12 console. Each release of the adapter will generally use the latest stable production build of the engine.

Unfortunately, the release notes don't indicate which version of the engine is used by each version of the adapter. It would be handy if someone created a table showing that information. I can see in the source that the latest 3.17 build uses the 3.11.1 engine.

**Comment by cosminPintea** [comment]
Ok. It is clear now. There are any rules when "NUnit3TestAdapter" is released (to be in sync with the NUnit.Engine release )? For example, right now I use the "NUnit.Engine" version "3.12.0-beta1". The "NUnit3TestAdapter" version "4.0.0-alpha.1" doesn't refers to "NUnit.Engine" version "3.12.0-beta1".
My question is: when "NUnit3TestAdapter" version 4.0.0 will be released it will reference "NUnit.Engine" version 3.12.0?
Just a note here:  I have fixed my issue by splitting my project into two separate projects. In one project I use "NUnit3TestAdapter"  to run tests from VS (local runs for debug/dev purpose) and another project (console) to start tests programmatically in CI/CD pipeline. 
Thanks for the clarification.

**Comment by CharliePoole** [comment]
The adapter is a separate project and the usual practice is to reference the latest full (not pre-) release of the engine. IMO, the actual versions need to be documented somewhere. As for 4.0 of the adapter, @OsirisTerje is the lead and would have to answer that.

**Comment by OsirisTerje** [comment]
@cosminPintea As @CharliePoole  says, the adapter will use the latest full version of the engine.  If the 3.12 is release pretty soon, it will be included in 4.0.0

**Comment by ChrisMaddock** [comment]
Hi Terje - there's one major problem with the .NET Core console not loading dependencies correctly. I was hoping to resolve that before releasing 3.12 - although time has been short recently, so I may end up delaying it a further release.

**Comment by CharliePoole** [comment]
I wrote a blog post to explain this problem and document the engine versions used by each release of the adapter...

http://charliepoole.org/technical/nunit-engine-version-conflicts-in-visual-studio.html

**Comment by SabotageAndi** [comment]
So as far as I understood the blogpost, this can't work at all. Or?

**Comment by cosminPintea** [comment]
I think we can close this. Basically, the user needs to manually ensure that what he installed in the C# project follows the compatibility table from Charlie post in case he uses multiple runers in the same project(like me use Visual Studio Test Adapter to run tests from VS but also NUnit Engine to programmatically start the tests). From my understanding, there is nothing to do from the spec flow side.

**Comment by ChrisMaddock** [comment]
Thanks all - I've just created #826 as a master issue to cover this problem. It's not going to be an easy one to fix... any suggestions and contributions welcome!
