### ISSUE TITLE
Reported issues with dependency loading in .NET Core Console

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#828]
Users have reported issues with assembly loading in the .NET Core Console. Ref: https://github.com/nunit/nunit-console/issues/806#issue-671998124 and https://github.com/nunit/nunit-console/issues/806#issuecomment-674191820.

Workaround: add `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to the test project csproj.

Contributions very welcome to fix this - and if anyone is able to provide a small minimum repro project for this, that would also be very helpful.

**Comment by CharliePoole** [comment]
Eventually I'll have time to do it but I don't right now, so it may help if someone compares the console runner with my TestCentric GUI runner, which does not __appear__ to have the same issue.
