### ISSUE TITLE
NUnit 3 - RemoteTestRunner is missing

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit-console#833]
HI
I'm trying to upgrade from Nunit v2 to v3, and after upgrade, I noticed that RemoteTestRunner is missing.
Any suggestions?
Best Regards,
Nadeem Bader

**Comment by ChrisMaddock** [comment]
Mikkel asks a good question. 🙂 

If you do need to create your own runner, you can take a look at the `ITestFilterService`. Use that to get an instance of an `ITestFilterBuilder`, and then use `.SelectWhere()` to build you clause. That method takes a string expressed in NUnit's [Test Selection Language](https://docs.nunit.org/articles/nunit/running-tests/Test-Selection-Language.html).

**Comment by ChrisMaddock** [comment]
I'm going to close this issue, as there's been no further comments. Please feel free to add more if needed. 🙂
