### ISSUE TITLE
Need timeout setting for all unit tests in MSBuild command

### ISSUE THREAD

**Issue by sharmg10** [nunit/nunit-console#834]
We are executing all unit tests after build using this command but sometimes some unit tests hang for a long time.

msbuild myproject.proj /t:Clean;BuildWithoutIM; QualityAssurance; /p:Configuration="debug" /p:Platform="Any CPU" /p:SolutionNameList=%SLN%

So I want to set a timeout for all Nunit test cases in the above command. Please suggest if there is a solution.

**Comment by ChrisMaddock** [comment]
Hi,

The NUnit Console doesn't yet have a feature for this, there's an open feature reqyest for that functionality here: https://github.com/nunit/nunit-console/issues/437

You might be able to manipulate this with MSBuild, depending how you're running you NUnit tests inside you MSBuild proj file. If you're using `Exec`, there's a `Timeout` option, see the docs: https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task

I'll close this issue as I think the NUnit part is covered by #437, and we don't maintain an MSBuild task ourselves. Happy to provide suggestions if we can though.
