### ISSUE TITLE
ArgumentNullException - at System.RuntimeTypeHandle.GetToken(RuntimeType type)

### ISSUE THREAD

**Issue by iyevhen** [nunit/nunit-console#841]
Getting ArgumentNullException not on every run with `-100` exit code.
While tests are passed successfully. 

* NUnit.ConsoleRunner.3.11.1
* Installed via NuGet.exe - `CALL "%NUGET_CLI%" install NUnit.ConsoleRunner -OutputDirectory "%~dp0build\tools" || goto :eof`
* Run script `"%NUNIT_CLI%" %testdll%  --noh  --teamcity  --work "%~dp0build\Release\%INSTALLER_PLATFORM%"  --result "%~dp0build\Release\%INSTALLER_PLATFORM%\reports\nunit_report.xml"  || goto :eof`

![image](https://user-images.githubusercontent.com/107732/102081161-7485e000-3e18-11eb-9516-c6cd3f9011d4.png)

**Comment by ChrisMaddock** [comment]
Hi @iyevhen,

There's not much to go on here - you say this isn't on every run? Please can you try two things to debug this further:

1. Add the `--trace=Debug` flag to your command line, which will have the Console write out log files. Once you see the crash again, hopefully those log files should have more information.

2. Add the `--inprocess` flag, and see if you get a more useful stack trace from running your tests in the main NUnit Console process.

Thanks - let us know how it goes.

**Comment by iyevhen** [comment]
Thanks, will attach Debug logs once I catch this error.

**Comment by ChrisMaddock** [comment]
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂
