### ISSUE TITLE
NUnit.ConsoleRunner.NetCore cannot find extensions

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#843]
Latest build cannot find any extensions. We should add the hint "../../../../../NUnit.Extension.*/**/tools/" to the file ".\tools\netcoreapp3.1\any\nunit.console.nuget.addins"

[InternalTrace.27768.log](https://github.com/nunit/nunit-console/files/5709742/InternalTrace.27768.log)

**Comment by CharliePoole** [comment]
@NikolayPianikov 
Since you use NUnit.ConsoleRunner.NetCore I'd like to ask for your comments on #1045

**Comment by NikolayPianikov** [comment]
@CharliePoole 

> @NikolayPianikov Since you use NUnit.ConsoleRunner.NetCore I'd like to ask for your comments on #1045

done

**Comment by CharliePoole** [comment]
@NikolayPianikov Are you sure this is an issue of finding extensions or simply that there are no .NET Core extensions avaialble?

**Comment by CharliePoole** [comment]
@NikolayPianikov Ping!

**Comment by NikolayPianikov** [comment]
@CharliePoole Maybe you are right, I will try reproduce it again

**Comment by NikolayPianikov** [comment]
I just tried it and it looks like you are right about .NET Standard. I close this ticket.

**Comment by CharliePoole** [comment]
We can't support .NET Standard for test assemblies so think the same limitation was built into extensions. Possibly, we should allow .NET Standard for extensions but it would require a bit of rewriting. Let me know if the non-support becomes a problem.
