### ISSUE TITLE
Eliminate .NET Standard 1.6 build of nunit.engine assembly

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#849]
This came up in some discussons within the team on other topics...

Now that the engine has been split in to `nunit.engine` and `nunit.engine.core`, the `nunit.engine` assembly is only loaded 
in the main process and therefore only needs to support the runtime used by that process. The .NET Standard 1.6 build is no longer needed and may be removed. 

The 1.6 build of `nunit.engine.core` is not being removed at this time. It remains to be seen whether we will continue to maintain the .NET Standard 2.0 build of the engine or if we will switch to a .NET Core build.

**Comment by CharliePoole** [comment]
@nunit/engine-team This turns out to be complicated by the fact that we have not yet split the tests of `nunit.engine` and `nunit.engine.core` into separate files. This is a low-priority task @ChrisMaddock and I have talked about doing when there's time. It doesn't actually block this one but will require adding a lot more conditional code to eliminate tests (e.g. of MasterTestRunner), which should not run under .NET Core 1.1.

My preference is to go a head and split the two test files as a part of this rather than adding more #if statements. What do you all think?

**Comment by ChrisMaddock** [comment]
Would it be better just to remove the .NET Standard 1.6 build from all assemblies? We don't yet have the ability to run agents targeting different platforms in the .NET Standard/Core engines - meaning this target for nunit.engine.core would end up unused. 

Given it's proving a heavy maintenance cost already (Ref #725), I'd rather we got rid of it completely, than continued maintaining something that isn't in use. We can always reinstate later, if we decide it's a platform we want to continue supporting running tests on.

**Comment by CharliePoole** [comment]
Too many issues hanging around too long! I had forgotten that issue and was operating under the false understanding that you didn't feel comfortable doing it in the 3.x series. I've gotten far enough that I may create a PR just for the part I have done... removing it from .NET Core... before going on to do more.

```
<meta>
If we have some small breaking changes, like this one, I wonder if we shouldn't consider breaking with the tradition that major releases only come along every  10 years or so.! :smiling_imp: 
</meta>
```

**Comment by CharliePoole** [comment]
One reason I __like__ having an old version like 1.6 is that it allows us to exercise supporting agents for runtimes we don't support in the primary engine. What if we removed the 1.6 build and then worked on a plugin agent for the same runtime?

**Comment by ChrisMaddock** [comment]
> If we have some small breaking changes, like this one, I wonder if we shouldn't consider breaking with the tradition that major releases only come along every 10 years or so.! 😈

I've very much thought the same recently. I've also thought about decoupling the engine and console versions - as I think we have far more change going into the engine at the moment, and a breaking change for the engine doesn't necessarily mean a breaking change for a runner. I also think we can afford to do (well documented) breaking changes to the engine much more readily, given the userbase.

> What if we removed the 1.6 build and then worked on a plugin agent for the same runtime?

I would _love_ to see this exist in practice! If it's something you'd like to work on, by all means throw up an issue!

**Comment by CharliePoole** [comment]
I'm in the process of trying out some techniques on the GUI, which I think will work for the engine as well.

**Comment by CharliePoole** [comment]
Superseded and incorporated by #725
