### ISSUE TITLE
Allow local build to succeed even if all runtimes are not installed

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#853]
One of my machines has an older version of VS2019 and fails the build when it comes time to run .NET 5.0 tests (it has a pre-release). It seems to me that we should that all runtimes we use be available on CI systems, and set up the agents so that it works, as we now do. OTOH, on a local developer machine, it may be more convenient to just skip any build or test that's not supported.

@nunit/engine-team What do you think?

**Comment by ChrisMaddock** [comment]
This is the behaviour I intended when I added .NET 5.0 tests. 🙂 I expect it's the fact there's a pre-release version installed which is causing the problems - if you have a good repo, mind submitting a fix?

**Comment by CharliePoole** [comment]
I'll test uninstalling the pre-release and take a look at the code.

**Comment by x789** [comment]
For the development on NUnit I have set up an extra VM, because I did not want to install all frameworks on my development system that are required by the build script.
Therefore I would like it if the build script for a local build does not require all frameworks. That way I could develop on my usual system and only have to use the VM from time to time.

By the way, my local build also failed some days ago because of a missing NET 5.0 runtime. On my system I had neither the release version nor a preview version of .NET 5.0 installed at that time.

**Comment by CharliePoole** [comment]
I have verified the same thing. The script simply attempts to run tests using .NET 5.0, without any test.  I'll add one.

Are there any other runtimes we might want to treat the same way?

**Comment by mikkelbu** [comment]
Fyi. I also like this, as I've a couple of computers with only prerelease installed (usually I just hack the build script)

**Comment by ChrisMaddock** [comment]
Sorry folks - from a quick look, looks like all the logic is there but it's missing a `return`. 🤦‍♂️ 

Charlie - I think what's happening is that the lines below should display the Warning and then return. Instead, it's warning and then continuing to try and run the tests anyway, which wasn't what I intended! 

https://github.com/nunit/nunit-console/blob/55855bb21d35e589b0eb792d0b23aa9234385213/build.cake#L736-L746

> Are there any other runtimes we might want to treat the same way?

When I added this functionality, I did it primarily for .NET 5.0 and included all the .NET Core runtimes at the same time, as they all go through the same path. The stuff I did only works for running tests, so any platforms that the build targets which are missing I think will fail earlier in the script? An enhancement on that sounds like it could be nice, but more difficult to do.

**Comment by CharliePoole** [comment]
@ChrisMaddock Ah well, I already re-invented a good part of what's already there! Note to self: Spend more time reading the code. :confused: 

WRT other frameworks... I came to the same conclusion. .NET 5.0 is the only runtime under which we test, which is not required for building. We could do more, but it's not that big an issue. If we don't drop .NET Standard 1.6 completely, I would be in favor of doing the work to make it optional in the build.

**Comment by mikkelbu** [comment]
@ChrisMaddock I've set the milestone to `3.12.0`, please change it, if it is wrong 😃

**Comment by ChrisMaddock** [comment]
Perfect - thanks! 🙂
