### ISSUE TITLE
Eliminate DomainUsage setting

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#860]
In a separate discussion, @ChrisMaddock expressed the desire to eliminate user control of how the runner and engine use AppDomains. I've been through the codebase to look at the impact and I can see it would enormously simplify a lot of code, particularly the test code. This issue is for the purpose of opening discussion on making the change. I'm flagging it as an idea for discussion by the @nunit/engine-team.

Some notes...

1. We can't eliminate AppDomains themselves for some platforms, they are needed. However, we can make their use an internal implementation detail outside of the control of users.
2. The command-line `--domain` option would be dropped.
3. The `DomainUsage` enumeration would be dropped.
3. Both the saved setting and the package setting for DomainUsage would disappear.
4. All the tests that utilize DomainUsage would be eliminated.
5. I believe that the nunit project loader would simply ignore the domain setting in `.nunit` files, but this would have to be tested.
6. The nunit project loader should probably be modified at some point.
7. This is a breaking change for the console, engine and nunit project loader extension.

FWIW, I favor doing this as part of a 4.0 release that resolves all the breaking issues we currently have, without necessarily adding a lot of new functionality. The new stuff can come in 4.1, 4.2, etc.

@ChrisMaddock Hope you don't mind that I added a new "breaking" label. :smile:

**Comment by ChrisMaddock** [comment]
Absolutely agree with this idea - the various domain options add high complexity and complexity for a low use feature.

I presume we would also remove the `--domain=None` option? Anyone know why that was added, or a sensible use case for it?

**Comment by CharliePoole** [comment]
I'm now remembering that VS has some way to tell the adapter to run without creating an AppDomain. So this is another one that should involve @OsirisTerje .

**Comment by CharliePoole** [comment]
I can't remember why it was originally added, but I know I've regretted it for a long time. :smiling_imp: 

I think it has to do with some actions not being permitted in a secondary AppDomain. So some software can't run except in the primary AppDomain. IMO however that's what NUnitLite is for.

**Comment by CharliePoole** [comment]
@ChrisMaddock Are we ready to move this to a feature and work on it?

**Comment by ChrisMaddock** [comment]
I think so. 👍

**Comment by CharliePoole** [comment]
This was merged to dev-4.0 and closed. I'm reopening it so as to replicate it in main.
