### ISSUE TITLE
Give agents individual names

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#877]
Working on the GUI implementation of pluggable agents, I realized that users creating agents would probably not use our naming convention and that I would have to allow for it.

That led me to realize that it might be a nice feature for each of our agents to have a different name... like `net20-agent`, `netcore31-agent`, etc. That way users could tell immediately which agent had been selected to run their tests when a problem arose.

I'm initially calling this an idea and a breaking change. I think it's at least "a little bit" breaking anyway. Not  sure if it's sufficiently breaking to make it wait to 4.0 @nunit/engine-team What do you think?

**Comment by ChrisMaddock** [comment]
Sure, why not!

Can you clarify why you consider this breaking? Agent behaviour is completely internal to the engine, isn't it?

**Comment by CharliePoole** [comment]
Well, it's breaking only because some user could say it broke them, if they did something relying on the file name, like launching the agent themselves. Personally, I would prefer to exclude something like this from the definition of "breaking."

**Comment by ChrisMaddock** [comment]
I agree - I would say that the scenario you describe isn't supported. I've recategorised this as an enhancement accordingly. 🙂

**Comment by CharliePoole** [comment]
Note... Due to various issues with Visual Studio, using one project to create assemblies with different names turns out to be unworkable. Instead, I'll create a project for each target runtime, sharing the source code. This isn't all bad, since many of these will eventually be removed to become pluggable agent extensions.
