### ISSUE TITLE
Stop Bundling V2 Framework Driver

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#880]
Although the V2 Framework Driver is a separate project, it's distributed with the console msi.

I propose we stop doing that for V4.

As a separate issue, I plan to archive both the extension and the V2 legacy project itself once V4 is released.

**Comment by CharliePoole** [comment]
Based on your "thumbs up" I moved this from idea to feature. Let me know if I'm mistaken!

**Comment by CharliePoole** [comment]
Implementation note: Unlike other extensions, the V2 framework driver has some special code in the engine itself. If we keep that code, the legacy extension will continue to work. Implementer will need to decide this.

**Comment by ChrisMaddock** [comment]
That’s interesting, I didn’t know that. If we removed that code, then we’re also removing the only (known) thing that uses the i frameworkdriver interface, right? I wonder if removing that as well would be a sensible simplification...

**Comment by CharliePoole** [comment]
It would be a simplification and would make life easier. OTOH it re-defines the engine as being one that runs nunit tests only rather than one that is open to running any kind of test. It's a big vision change as well as breaking.

I wish we knew whether anyone else uses the framework driver extension! Google shows me nothing other than our own pages. One guy on SO was using it for the wrong reason.

An option is to redefine the interface so we no longer do special stuff for the V2 driver. IIRC it needed the special code because we use a different driver for the same framework assembly name based on the version.

If NUnit dropped IFrameworkDriver, I might continue to support it in the TestCentric engine. I'm not sure.
