### ISSUE TITLE
Decide whether to support NUnit projects

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#881]
There seem to be arguments on both sides. We should decide now because it will have to wait for another major release to drop this support if we don't do it with V4.

**Comment by ChrisMaddock** [comment]
Is this an issue for the console/engine v4, or for the extension itself? The engine doesn't specifically support NUnit projects in anyway I don't think (does it?) - it instead supports IProjects, which I think is valuable piece of extensibility functionality. (At least, given the fact it already exists!)

Any decision here should bear in mind that I think TeamCity uses NUnit projects as part of it's normal work flow, so this would be a significant breaking change for a large number of users.

**Comment by CharliePoole** [comment]
It's both, I think... The console distributes  the extension as part of the msi and zip distributions. Further, if we decided to drop support of both nunit and vs projects, then the whole IProject thing could go as well. That's possibly unlikely, but I wanted to lay it on the table.

If V4 drops support for NUnit projects, then I'll archive the project. If it doesn't, then I would advocate bringing it into the engine as a "built-in extension" - IMO it's silly to need an extension to run a project type named "NUnit."

Regarding TeamCity's use of nunit projects... It's not a breaking change for them unless they decide to start using V4.

**Comment by ChrisMaddock** [comment]
Hi @CharliePoole,

In my mind, items 2-4 here are outside the scope of the Engine project, and probably decisions for you, as the NUnit project extension maintainer.

Here's my thoughts, specifically to the decision from the Engine project's point of view: 
- While the NUnit project extension remains "stable", I don't see a big enough advantage in removing it from the combined packages, to outweigh the inconvenience to users
- If the extension was to stop functioning, or develop a critical bug which went unfixed, that decision may change. But those issues are within the hands of the extension maintainer. If you decided to go ahead and archive the extension (which I think is perfectly reasonable) - then I think the engine should continue to package the extension until such an issue arises which makes the extension unusable.
- I would prefer we didn't incorporate it into the main engine. I think project formats are a great example of functionality which can sit well in an extension outside the main engine. I think NUnit projects are a piece of functionality who's future is unclear, and bringing that functionality inside the engine will only make it's replacement more difficult.
- If a replacement format were to be developed, that we should definitely consider replacing the default packaged project format with a more modern alternative. But that relies on a person to develop and maintain the new format.

Lastly:

> We stop distributing it with the msi and zip packages. That way, we're under no obligation to test it, which is hard since few of us are TeamCity users.

I think this is more relevant to the TeamCity extension than the NUnit Project extension, no?

**Comment by CharliePoole** [comment]
@ChrisMaddock

In the note to @NikolayPianikov the "it" I was talking about under (1) was the TeamCity extension. Under (2) and (3) I was talking about the NUnit Project Loader extension. Sorry to be so confusing!

To your bullet points...

* (First point) I agree. That's were the idea "freezing" comes in for me.

* (Second point) I agree WRT the current situation. I firmly believe that the responsibility for extensions logically belongs with the engine, no matter who does the work. I think we previously agreed to disagree about this. You think I'm doing it independently and I think I'm doing it as part of the engine project. :smile: 

* (Third point) I agree with this after hearing all the input. In principle, I think it was a mistake to make something called "NUnit" be separate. It's as if you needed to install an extra assembly in word in order to use word documents! But for now we are stuck with this. I think we should remember the point for the future, however.

* I think we should and I think it ought to be part of the engine.

**Comment by ChrisMaddock** [comment]
> I firmly believe that the responsibility for extensions logically belongs with the engine, no matter who does the work. I think we previously agreed to disagree about this. You think I'm doing it independently and I think I'm doing it as part of the engine project. 😄

I agree that we disagree! 😄 

> In principle, I think it was a mistake to make something called "NUnit" be separate.

Agreed. We are where we are!

> I think we should and I think it ought to be part of the engine.

I'd love to see more modern project format available. I'm less sure that this should be part of the engine itself. Project files are a piece of advanced functionality used by a minority of users. They're brilliant functionality for the engine to be able to support, but I still think that should be done through extensibility, rather by adding additional functionality to the engine itself.

What would be the advantage of building this into the engine? Availability? I think including an extension within the extension-packages would be the best way to tackle that, but I do think there that the engine should remain slim itself with regards to different project formats, and users/runner maintainers should be given the choice what to package/include in their own runners.

**Comment by CharliePoole** [comment]
Let's be clear that we are talking about "extensions" added by the user. I say that because the original design of the engine was that everything should be an "extension" or "addin" architecturally, including most of the built-in functionality like running tests. I still talk about it that way sometimes, which is possibly confusing to others.

In that sense, let's look at some "internal" extensions that we currently have, functionality that's available to the user without doing anything special beyond installing the console runner.

1. The NUnit 3 framework Driver
2. The NUnit 3 Result Writer
3. Most Runners
4. Most Services

It would be silly for us to distribute the console runner without the above, no matter what the internal architecture.

I'm just saying it's silly that the only way you can save the parameters for a run is an NUnit project but you can't do that without installing a separate extension.

I totally agree that the __current__ NUnit Project Loader should not be built into the engine, but I'm looking to the future.

So my take on this issue is basically that we need to support __some kind of document__ that allows you picking up where you left off in your work. It needs to be either a new, enhanced format and I'd say it should be builtin the same way that saving test results is built in.

**Comment by ChrisMaddock** [comment]
So essentially a solution to serializing a test package, which is available to all runners?

Yes, ok. I agree that's a good fit for the engine's responsibilities, as they are in my head! Looking at it from that point of view seems different to a user-oriented format, but I guess there's no reason these should be the same thing, and save the extra development effort. 😄

**Comment by CharliePoole** [comment]
Exactly... a native format just as nunit3 is the native result format. As a bit of history, that's what `.nunit` was originally, in NUnit V2. There was always a saveable `.nunit` project, even if you only ran assemblies on the command line.

**Comment by CharliePoole** [comment]
@ChrisMaddock This has turned out to be a dialog! :smiley_cat: 

Anyway, can we move this out of the idea stage?

1. I'm in agreement that the issue title (NUnit projects) is really relevant to the extension, not the engine.
2. There is still the question of what extensions are distributed with the console runner. Stopping the distribution of an extension would probably be a breaking change. Should I create a separate issue for this?
3. Support of "projects" in general is definitely an engine issue. IMO we should resolve precisely what that support is and reflect it in the API of the project service.
4. It seems to me that we retain the option to support an native format within the engine either way. That native format would be new functionality and not a breaking change. I think we should do it but it doesn't have to be in the first 4.x release.

**Comment by ChrisMaddock** [comment]
Hi Charlie,

I think I've covered my thoughts on this above, but personally I don't think there's any change we should make the engine here.

- Distribution, as above, I don't see enough advantage to stopping distributing the extension to outweigh the breaking change. (Unless you, as maintainer, decide to deprecate the extension.)
- I don't see any need for changes to IProject functionality. Is there something you're thinking of here? I think that should be a new issue
- Agreed, any native format should be post-4.0.

**Comment by CharliePoole** [comment]
I am saying I plan to archive the extension in the 4.0 time frame. You could decide whether to keep distributing it or not.

I have no specific ideas about IProjectLoader and IProject functionality but I think we need to review it as a part of re-designing the API. At the very least, we need to make explicit some assumptions about projects - e.g. the fact that they may or may not contain configs and what is the proper behavior if a given project doesn't support configurations but you ask for one. But I agree it's a matter for the API issue and - if we need to make changes - some other new issue we'll create when needed.

**Comment by ChrisMaddock** [comment]
Agreed that would be a separate issue. 

In this case, I think we should continue distributing it up until there's a suitable replacement, and/or the existing package stops working. 

Would you agree? Shall we close this? 🙂
