### ISSUE TITLE
v4: NuGet Package restructure

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#884]
Ref #720.

For v4, we should finally retire the NUnit.Runners package in favour of NUnit.Console. They are the same package with NUnit.Console intended to be the replacement name, however NUnit.Runners is still well used enough that it's been seen as too disruptive to do this previously.

**Comment by CharliePoole** [comment]
Closing this. The NUnit.Runners package has been deprecated for some time but we were still producing new "releases" of it. Each new release simply pointed to the correct package as a dependency. Deprecated packages should not be re-released unless something changes _in that package_. We stopped releasing NUnit.Runners in the 3.13 release.
