### ISSUE TITLE
Cecil exceptions from engine

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#9]
@CharliePoole commented on [Sun Nov 08 2015](https://github.com/nunit/nunit/issues/1009)

The engine can throw exceptions due to errors in Cecil Resolve(). I discovered this when working with the NUnit 3 VS Adapter. The errors are very hard to locate and occur when Cecil cannot resolve the item requested. The code assumes null will be returned rather than an exception being thrown.

We should find every place where we do a Resolve in the engine code and 
1. Catch it and take appropriate action
2. Try to set up the resolver correctly so it doesn't occur.

---

@CharliePoole commented on [Sun Dec 27 2015](https://github.com/nunit/nunit/issues/1009#issuecomment-167425208)

Issue #1144 points to some code where we simply don't check the possible null return at all!

**Comment by ChrisMaddock** [comment]
Having been 'exception free' for the last 4 years, I'm going to close this issue. 😄
