### ISSUE TITLE
Getting this error while running using Nunit 13.1 Could not load file or assembly 'nunit.framework, Version=3.6.0.0, Culture=neutral, keytoken or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit-console#903]

**Comment by gnaneswarreddy** [comment]
I am using Nunit Framework 3.13.1 and Nunit-Console to run the test and i dont have any references and getting the above error

**Comment by CharliePoole** [comment]
The message seems to suggest very strongly that you are actually using the 3.6 version of the framework. Check your package references. Also, you don't state what version of the console you are running, which may be helpful.

**Comment by gnaneswarreddy** [comment]
@CharliePoole I am not using 3.6 but i see in packages i am using 3.13.1 only which i can see in packages.config and nunit-console i am using 3.12.0 when i got that package i can only see 3.6.0 references are there only for Nunit.Extension.NunitProjectloader and Nunit.Extension.NunitV2ResultsWriter

**Comment by gnaneswarreddy** [comment]
@CharliePoole i am able to run it and the error is not getting displayed but the test is not running and saying its passed.Am i missing something?

**Comment by gnaneswarreddy** [comment]
@CharliePoole This is working Thankyou for your help

**Comment by CharliePoole** [comment]
Neither of those extensions reference the nunit framework at all. It's not normal for an extension to reference the framework, since the engine doesn't know what framework is being used by the tests. 

Of course, our own tests of the extensions reference the framework, but that should have nothing to do with your project.
