### ISSUE TITLE
Did nunit-Console runner support .net 5 core ?

### ISSUE THREAD

**Issue by avkadu** [nunit/nunit-console#932]

**Comment by avkadu** [comment]
NUnit.Console-3.12.0 dont have files for .net 5 
![image](https://user-images.githubusercontent.com/32651567/113673635-dffd0180-96d6-11eb-9921-493e7537a24d.png)

**Comment by mikkelbu** [comment]
NUnit.ConsoleRunner.NetCore can perhaps be used (see e.g. https://github.com/nunit/nunit-console/releases/tag/v3.12.0-beta2), but please note that there are some unresolved issues, hence the beta release
https://github.com/nunit/nunit-console/issues?q=is%3Aopen+is%3Aissue+project%3Anunit%2Fnunit-console%2F1

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Thanks Mikkel!
