### ISSUE TITLE
Create a separate assembly to support agents

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#940]
After completing a spike to evaluate the possibility of having a separate `agent.core` assembly, I moved ahead with the idea in the TestCentric engine. This issue is to propose that we do the same thing for NUnit.

Key features of what I did for TestCentric are...

* The `engine` and `agent.core` assemblies are completely separate - neither one knows about the other.
* The `engine.core` assembly contains classes and interfaces needed by both the engine and the agents. In particular, it contains the communications protocols.
* The `agent.core` assembly contains only 13 classes, while `engine.core` is reduced to 26 classes and 5 interfaces. This is important because these are the two assemblies, which must be supported for each agent runtime.
  * Currently, `agent.core` uses a reference to the `metadata` assembly when built for .NET Standard 1.6. The NUnit engine wouldn't need this, of course.
* The core assemblies know nothing about extensibility or about any services - they don't need them - so support is limited to the platforms for which the main engine is built.

The same could be done for the NUnit engine, with a few modifications...
* .NET Standard 1.6 support is not needed (making it easier).
* The engine still supports in-process execution, potentially making it slightly harder until an in-process agent is developed.

**Comment by ChrisMaddock** [comment]
I'm not averse to the idea. Can I ask a few questions?

- What's the key aim here sorry, what advantage does splitting out this assembly give us?
- I assume from how you write this that agents now reference both engine.core and agent.core? Is the idea that agent.core includes files only needed by agents? Why don't we just keep those inside nunit-agent.exe?

> The core assemblies know nothing about extensibility or about any services - they don't need them - so support is limited to the platforms for which the main engine is built.

How does this work for driver extensions? That was the previous reason for including all the extension services in engine.core IIRC, although something I'd hoped we could eventually move away from.

**Comment by CharliePoole** [comment]
In it's current iteration, the GUI engine only knows about the nunit3 driver. However, I'm already discovering the correct driver in the engine and passing it on in the TestPackage as an AssemblyName. It also passes a property with the AssemblyName of the test assembly. The current agent.core uses the second property to find the test assembly but it doesn't yet use the first one for the driver. I decided it was simplest for me to break this functionality first, planning to put it back a different way.

As to your first question, my idea is that folks wanting to write their own drivers _for the same runtimes we already support_ can use agent.core. If new runtimes are invented or if they want to do some thing that works differently from our code, then they would just implement the interfaces themselves. One use I see for this is to write a set of drivers that launch the agent under a debugger. Internally, keeping the code in nunit-agent.exe would work so long as our agents remain a single project with different platforms. I wanted to allow for possibly breaking them out.

**Comment by CharliePoole** [comment]
After running through a couple of testcentric releases with a separate agent.core assembly, I ended up deciding that it made things overly complicated and I have now removed it. I'm closing this issue without action for that reason.
