### ISSUE TITLE
NUnit Console Runner 3.5.0 reports that format nunit2 is unknown

### ISSUE THREAD

**Issue by sergiorykov** [nunit/nunit-console#95]
whereas help says that it's still ok to use it. I need support of nunit2 format for specflow reports.

`NUnit.ConsoleRunner\tools\nunit3-console.exe --result="C:\TestResults.xml";format=nunit2 "c:\project\bin\specs.dll"

**Comment by sergiorykov** [comment]
Sorry. 

Missed support package NUnit.Extension.NUnitV2ResultWriter. 

Excellent responsibility separation!

**Comment by CharliePoole** [comment]
I'm re-opening this as a documentation issue. The help should say that the extension is required.

Glad you like the use of extensions!

**Comment by CharliePoole** [comment]
Should do the same for --teamcity option. Maybe also say something about running v2 tests and loading vs or nunit projects!

**Comment by sergiorykov** [comment]
Thank you for your attention to NUnit and fast response!

Actually there is a bit problem with nuget installation. I wrote about it and about dirty workaround in documentation issue: https://github.com/nunit/nunit-console/issues/93
