### ISSUE TITLE
Investigate why Engine Tests are slow

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#96]
Running the engine tests on my development machine takes 55 seconds. They shouldn't be this slow.

```
Test Run Summary
  Overall result: Warning
  Test Count: 450, Passed: 441, Failed: 0, Inconclusive: 5, Skipped: 4
    Skipped Tests - Ignored: 3, Explicit: 1, Other: 0
  Start time: 2016-10-12 15:27:11Z
    End time: 2016-10-12 15:28:06Z
    Duration: 54.376 seconds
```

**Comment by CharliePoole** [comment]
These are really integration-style tests and start up multiple processes. We should really have our integration tests in a separate assembly, maybe even a different repo.

**Comment by ChrisMaddock** [comment]
I looked into this briefly a while ago, I think the tests are often just more heavy-weight than we'd really like for unit tests.

For v4, I'd like for us to have some better integration tests, and it may be that some of the slowest tests move out of the unit tests into the new assembly.

I'm going to close this, as nobodies picked it up in the last 4 years, and I'm not sure it's a priority at the moment.
