### ISSUE TITLE
NUnit.ConsoleRunner.NetCore .nunit file not supported

### ISSUE THREAD

**Issue by alexmaie** [nunit/nunit-console#962]
Hey Nunit Team,

I have installed the https://www.nuget.org/packages/NUnit.ConsoleRunner.NetCore/ as a dotnet tool. If I try to run the tool with a .nunit file containing all the projects to run but I'm receiving an error that the "File is not supported". This file is working with an older version of the console. 

Not sure if this is an error with the package version of if some additional nugets would need to be installed

Thanks for the help

**Comment by mikkelbu** [comment]
Note that the page https://www.nuget.org/packages/NUnit.ConsoleRunner.NetCore/ says 
>      Any extensions, if needed, may be installed as separate packages.

So you need to install the `NUnit.Extension.NUnitProjectLoader` extension, but whether it will work in .NetCore I don't know. At least #843 indicates that there are some issues with extensions.

**Comment by CharliePoole** [comment]
The NUnitProjectLoader extension will not work in .NET Core AFAIK.

**Comment by alexmaie** [comment]
Hey guys,

Thanks for the previous responses. So basically we have to run each test assembly separately, right?

**Comment by CharliePoole** [comment]
@alexmaie 
Since you use NUnit.ConsoleRunner.NetCore I'd like to ask for your comments on #1045

**Comment by CharliePoole** [comment]
It's not an engine bug because there's no compatible extension. The current NUnit project loader extension only works under .NET Framework.
