### ISSUE TITLE
Remove unused --verbose and --full command line options

### ISSUE THREAD

**Issue by thomaslevesque** [nunit/nunit-console#99]
What is the `--verbose` flag supposed to do? I can't see any difference between running nunit3-console.exe with or without this flag.

(btw, is there a way to print to the console which test is currently executing? that's what I was trying to do with `--verbose`)

**Comment by thomaslevesque** [comment]
I just looked at the code: apparently the `CommandLineOptions.Verbose` property is never used (except to define it in `ConfigureOptions`). The same is true of the `Full` property.

**Comment by ChrisMaddock** [comment]
I think you're looking for `--labels`? I'll leave someone else to comment on`--verbose`

**Comment by thomaslevesque** [comment]
Thanks @ChrisMaddock, this is what I was looking for!

**Comment by CharliePoole** [comment]
Once upon a time, `--verbose` did something. When I removed that code, I thought I would be coming back to add some different verbose output. We'll either kill the option or use it.

The `--full` option was an experimental report of all tests run. We'll either remove or use this one too.

**Comment by ChrisMaddock** [comment]
This is potentially easyfix once a decision is made. 

Can I suggest we remove both unused options, with the view that they could always be re-added, if something is implemented at a later date? @nunit/engine-team - thoughts?

**Comment by rprouse** [comment]
I say remove for now

**Comment by CharliePoole** [comment]
I agree

**Comment by ChrisMaddock** [comment]
Great - I've retitled, and duplicated for NUnitLite.

**Comment by GCichosz** [comment]
I'm on it. How do I update the docs? Directly on wiki, or is there also a specific repository for it?

**Comment by ChrisMaddock** [comment]
Great - thanks! 😄 Just edit the wiki directly - being in the Contributors team should give you permission to do that. Shout up if not! 👍
